<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "<link href='./ff9.css' rel='stylesheet' type='text/css' media='all'/>";
echo "</head><body>";
echo "<center><p class='cell6'>商店简称对照表</p>
<table cellpadding=0 cellspacing=0 class='table_center' bgcolor='#FFFFFF'>  <TR class='cell5'>    <TD>略称</td>  <TD>地点</td>  <TD>Disc</td>  <TD>略称</td>  <TD>地点</td>  <TD>Disc</td>  </TR>
<TR align=middle><TD class='cell2'>村</TD>   <TD>达利村/道具屋</TD>  <TD class=en>1-4</TD><TD class='cell2'>亚</TD>   <TD>亚历山德里亚/武器屋</TD>  <TD class=en>3-4</TD></TR>
<TR align=middle><TD class='cell2'>林</TD>   <TD>林德布尔姆/武器屋</TD>  <TD class=en>1</TD><TD class='cell2'>托</TD>   <TD>托雷诺/骑士家</TD>  <TD class=en>3-4</TD></TR>
<TR align=middle><TD class='cell2'>布</TD>  <TD>布尔美西亚/宝物庫</TD>  <TD class=en>1-4</TD><TD class='cell2'>林</TD>  <TD>林德布尔姆/武器屋</TD>  <TD class=en>3-4</TD></TR>
<TR align=middle><TD class='cell2'>南</TD>  <TD>南门/休憩所</TD>  <TD class=en>2</TD><TD class='cell2'>埃</TD>  <TD>埃斯特·加扎</TD>  <TD class=en>3</TD></TR>
<TR align=middle><TD class='cell2'>托</TD>   <TD>托雷诺/骑士家</TD>  <TD class=en>2</TD><TD class='cell2'>乌</TD>  <TD>乌伊尤维尔</TD>  <TD class=en>3</TD></TR>
<TR align=middle> <TD class='cell2'>克</TD>  <TD>克雷拉镇/水车广场</TD>  <TD class=en>2</TD><TD class='cell2'>沙</TD>  <TD>沙漠皇后</TD>  <TD class=en>3</TD></TR>
 <TR align=middle><TD class='cell2'>林</TD>   <TD>林德布尔姆/武器屋</TD>  <TD class=en>2</TD><TD class='cell2'>地</TD>  <TD>林德布尔姆/地龙之门</TD>  <TD class=en>2</TD></TR>
<TR align=middle><TD class='cell2'>达</TD>  <TD>达格雷欧</TD>  <TD class=en>3</TD> <TD class='cell2'>化</TD>  <TD>化石之路</TD>  <TD class=en>2</TD></TR>
<TR align=middle><TD class='cell2'>伊</TD>  <TD>伊普森古城</TD>  <TD class=en>3</TD><TD class='cell2'>康</TD>  <TD>康德亚·帕特</TD>  <TD class=en>2-3</TD></TR>
<TR align=middle> <TD class='cell2'>布</TD>  <TD>布兰·巴尔</TD>  <TD class=en>3</TD><TD class='cell2'>黒</TD>  <TD>黑魔道士之村/武器屋</TD>  <TD class=en>2-3</TD></TR>
<TR align=middle><TD class='cell2'>达</TD>  <TD>达格雷欧</TD>  <TD class=en>4</TD><TD class='cell2'>玛</TD>  <TD>玛丹·萨里</TD>  <TD class=en>2-4</TD></TR>
<TR align=middle><TD class='cell2'>黒</TD>  <TD>黑魔道士之村/武器屋</TD>  <TD class=en>4</TD><TD class='cell2'>-</TD>  <TD>-------------------</TD><TD class=en>-</TD></TR>
</TABLE>";
echo "
<div class='intro_table'>※表中前后两个“埃”分别为去沙漠女皇前和去过沙漠女皇后去埃斯特·加扎时商店里卖的东西。<br>※<strong>灰色表示Disc4购买不到的武器</strong>，横向表示该武器所在的商店，纵向表示该商店在当时所出售的武器。</div><p class='cell6'><strong>=武器篇=</strong></p><table cellspacing='0' cellpadding='0' class='table_center'><tbody><tr><td class='cell5' rowspan='2'>武器名称</td><td class='cell5' rowspan='2'>价格</td><td class='cell5' colspan='3'>DISC1</td><td class='cell5' colspan='9'>DISC2</td><td class='cell5' colspan='10'>DISC3</td><td class='cell5' colspan='2'>DISC4</td></tr>
<tr><td class='cell5'>村</td><td class='cell5'>林</td><td class='cell5'>波</td><td class='cell5'>南</td><td class='cell5'>托</td><td class='cell5'>克</td><td class='cell5'>林</td><td class='cell5'>地</td><td class='cell5'>巨</td><td class='cell5'>康</td><td class='cell5'>黑</td><td class='cell5'>玛</td><td class='cell5'>亚</td><td class='cell5'>托</td><td class='cell5'>林</td><td class='cell5'>埃</td><td class='cell5'>乌</td><td class='cell5'>沙</td><td class='cell5'>埃</td><td class='cell5'>达</td><td class='cell5'>伊</td><td class='cell5'>布</td><td class='cell5'>达</td><td class='cell5'>黑</td></tr>
<tr><td class='cell2'>小刀</td><td>320</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>碎魔刃</td><td>500</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td></tr>
		 <tr><td class='cell2'>秘银匕首</td><td>950</td><td>-</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>古罗马短剑</td><td>2300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>索林根之刃</td><td><span>6000</span></td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>- </td></tr>
<tr><td class='cell2'>金铜短剑</td><td>17000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>宽刃剑</td><td>330</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>铁剑</td><td>660</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>秘银剑</td><td>1300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>冰之烙印</td><td>3780</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>珊瑚剑</td><td>4000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>钻石剑</td><td>4700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>火舌</td><td>5190</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>符文之剑</td><td>8900</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>守护者</td><td>9340</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>创世之剑</td><td>14000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr><td class='cell8'>标枪</td><td>880</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>秘银长矛</td><td>1100</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>游击矛</td><td>1600</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>寒冰之枪</td><td>2430</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>三叉戟</td><td>3580</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>沉重之枪</td><td>4700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>方尖矛</td><td>6000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>神圣之枪</td><td>11000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>猫爪</td><td>4000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>带毒指套</td><td>5000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>秘银爪</td><td>6500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>巨剪毒牙</td><td>8000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>虎牙</td><td>13500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>复仇者</td><td>16000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>帝王指套</td><td>18000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr><td class='cell8'>空气拍</td><td>400</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>玛蒂娜拍</td><td>750</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>魔法拍</td><td>1350</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>秘银拍</td><td>2250</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>权杖</td><td>260</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>秘银权杖</td><td>560</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>星群权杖</td><td>760</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>治疗权杖</td><td>1770</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>阿修罗权杖</td><td>3180</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>法师权杖</td><td>3990</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td></tr>
<tr><td class='cell2'>魔像之笛</td><td>2700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>拉弥亚之笛</td><td>3800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>精灵横笛</td><td>4500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>哈默尔恩</td><td>5700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>塞壬之笛</td><td>7000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td></tr>
<tr><td class='cell2'>魔道士之杖</td><td>320</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>炎之杖</td><td>1100</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>冰之杖</td><td>980</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>雷之杖</td><td>1200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>橡木杖</td><td>2400</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>柏树枝</td><td>3200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell8'>八角棒</td><td>4500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>魔导师之杖</td><td>6000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td></tr>
<tr><td class='cell2'>餐叉</td><td>1100</td><td>-</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>针刺餐叉</td><td>3100</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>秘银餐叉</td><td>4700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>银餐叉</td><td>7400</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>酒馆餐叉</td><td>10300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class='cell2'>圆月轮</td><td>200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class='cell2'>旭日</td><td>500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td></tr>
</tbody></table>";
echo "
<p class='cell6'><strong><a name='ff9-defend-c'>=防具篇=</a></strong></p><div class='intro_table'>※表中前后两个“埃”分别为去沙漠女皇前和去过沙漠女皇后去埃斯特·加扎时商店里卖的东西。<br />※<strong>灰色表示Disc4购买不到的武器</strong>，横向表示该武器所在的商店，纵向表示该商店在当时所出售的武器。</div><p class='cell6'><b>帽子/头盔</b></p><table cellspacing=0 cellpadding=0 class='table_center'><tr class=cell5><td rowspan='2' width='20%'>防具名称</td><td rowspan='2' width='8%'>价格</td><td colspan='3'>DISC1</td><td colspan='9'>DISC2</td><td colspan='10'>DISC3</td><td colspan='2'>DISC4</td><tr> <td class='cell5'>村</td><td class='cell5'>林</td><td class='cell5'>波</td><td class='cell5'>南</td><td class='cell5'>托</td><td class='cell5'>克</td><td class='cell5'>林</td><td class='cell5'>地</td><td class='cell5'>巨</td><td class='cell5'>康</td><td class='cell5'>黑</td><td class='cell5'>玛</td><td class='cell5'>亚</td><td class='cell5'>托</td><td class='cell5'>林</td><td class='cell5'>埃</td><td class='cell5'>乌</td><td class='cell5'>沙</td><td class='cell5'>埃</td><td class='cell5'>达</td><td class='cell5'>伊</td><td class='cell5'>布</td><td class='cell5'>达</td><td class='cell5'>黑</td></tr>
<tr> <td class=cell2>皮帽</td><td>150</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>羽饰帽子</td><td>200</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>尖帽子</td><td>260</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>头饰</td><td>330</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>三角帽子</td><td>400</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell8>花色丝巾</td><td>500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>魔术师帽子</td><td>600</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr><td class=cell2>拉弥亚头饰 </td><td>800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr><td class=cell2>轿夫帽子</td><td>1000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>缠头带</td><td>1200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>内力头带</td><td>1500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>暗黑帽子</td><td>1800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell8>绿色贝雷帽</td><td>2180</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell8>黑头巾</td><td>2550</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>火红帽子</td><td>3000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>黄金发夹</td><td>3700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td></tr>
<tr><td class=cell2>休普诺之冠</td><td>4400</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class=cell2>闪光魔帽</td><td>5200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class=cell2>精金帽子</td><td>3050</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>盗贼帽子</td><td>7100</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td></tr>
<tr><td class=cell2>祭司帽子</td><td>8300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td></tr>
<tr><td class=cell2>橡胶头盔</td><td>250</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>青铜头盔</td><td>330</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell8>铁盔</td><td>450</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>开面盔 </td><td>600</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>秘银头盔</td><td>1000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>黄金头盔</td><td>1800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>十字盔</td><td>2200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>钻石头盔</td><td>3000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>白金头盔</td><td>4600</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr><td class=cell2>帝王头盔</td><td>7120</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
</table></center><center><p class='cell6'><b>腕轮/护腕</b></p></center><center><table cellspacing=0 cellpadding=0 class='table_center'><tr class=cell5><td rowspan='2' width='20%'>防具名称</td><td rowspan='2' width='8%'>价格</td><td colspan='3'>DISC1</td><td colspan='9'>DISC2</td><td colspan='10'>DISC3</td><td colspan='2'>DISC4</td><tr> <td class='cell5'>村</td><td class='cell5'>林</td><td class='cell5'>波</td><td class='cell5'>南</td><td class='cell5'>托</td><td class='cell5'>克</td><td class='cell5'>林</td><td class='cell5'>地</td><td class='cell5'>巨</td><td class='cell5'>康</td><td class='cell5'>黑</td><td class='cell5'>玛</td><td class='cell5'>亚</td><td class='cell5'>托</td><td class='cell5'>林</td><td class='cell5'>埃</td><td class='cell5'>乌</td><td class='cell5'>沙</td><td class='cell5'>埃</td><td class='cell5'>达</td><td class='cell5'>伊</td><td class='cell5'>布</td><td class='cell5'>达</td><td class='cell5'>黑</td></tr>
<tr><td class=cell2>护腕</td><td>130</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>皮护腕</td><td>200</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>玻璃护臂</td><td>250</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>骨质护腕</td><td>330</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>秘银护臂</td><td>500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>魔法护臂</td><td>1000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>奇美拉护臂</td><td>1200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>唯我护臂</td><td>2000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>恩凯护臂</td><td>3000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>翡翠护臂</td><td>3400</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>龙之护腕</td><td>4800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>力量护腕</td><td>5100</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>青铜护手</td><td>480</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>花纹小盾</td><td>720</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>秘银护手</td><td>980</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>雷神护手</td><td>1200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>钻石护手</td><td>2000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>威尼斯盾</td><td>2800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>守卫护手</td><td>6000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>庇佑护手</td><td>7000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
</table></center><center><p class='cell6'><b>衣服/铠甲</b></p></center><center><table cellspacing=0 cellpadding=0 class='table_center'><tr class=cell5><td rowspan='2' width='20%'>防具名称</td><td rowspan='2' width='8%'>价格</td><td colspan='3'>DISC1</td><td colspan='9'>DISC2</td><td colspan='10'>DISC3</td><td colspan='2'>DISC4</td><tr>	<td class='cell5'>村</td><td class='cell5'>林</td><td class='cell5'>波</td><td class='cell5'>南</td><td class='cell5'>托</td><td class='cell5'>克</td><td class='cell5'>林</td><td class='cell5'>地</td><td class='cell5'>巨</td><td class='cell5'>康</td><td class='cell5'>黑</td><td class='cell5'>玛</td><td class='cell5'>亚</td><td class='cell5'>托</td><td class='cell5'>林</td><td class='cell5'>埃</td><td class='cell5'>乌</td><td class='cell5'>沙</td><td class='cell5'>埃</td><td class='cell5'>达</td><td class='cell5'>伊</td><td class='cell5'>布</td><td class='cell5'>达</td><td class='cell5'>黑</td></tr>
<tr> <td class=cell2>皮衣</td><td>270</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>丝衣</td><td>400</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>皮甲</td><td>530</td><td>-</td><td>○</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>青铜胸甲</td><td>670</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>链子甲</td><td>810</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>秘银背心</td><td>1180</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>精金背心</td><td>1600</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>魔术师之衣</td><td>1850</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>救生背心</td><td>2900</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>轻便锁子甲</td><td>4300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>柔道服</td><td>5000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr><td class=cell2>力量肩带</td><td>7200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>大地之衣</td><td>8700</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>魔人胸甲</td><td>10250</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>密涅瓦胸衣</td><td>12200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>忍衣</td><td>14000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>黑装束</td><td>16300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td></tr>
<tr> <td class=cell2>青铜之铠</td><td>650</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>亚麻布胸铠</td><td>800</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>链铠</td><td>1200</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>秘银之铠</td><td>1830</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>金属板铠</td><td>2320</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>黄金之铠</td><td>2950</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>盾铠</td><td>4300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>恶魔之铠</td><td>5900</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell8>钻石之铠</td><td>8800</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td><td>-</td><td>-</td><td>-</td></tr>
<tr> <td class=cell2>白金之铠</td><td>10500</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>枪骑兵之铠</td><td>12300</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
<tr> <td class=cell2>龙铠</td><td>14000</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>○</td><td>-</td></tr>
</table>
";
echo "</center></body></html>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
