<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "<link href='./ff9_tw.css' rel='stylesheet' type='text/css' media='all'/>";
echo "</head><body>";
echo "<div id='ff9tw' align='center'><a name='ff9_001' />
<table cellspacing='0' cellpadding='0' class='intro'>
    <tbody>
        <tr>
            <td class='ititle' colspan='2'>１.&nbsp;序章<br />
            </td>
        </tr>
        <tr>
            <th width='60'>流程</th>
            <td>开始游戏-&gt;恶梦-&gt;战斗-&gt;诱拐计划</td>
        </tr>
        <tr>
			<th>重要道具</th>
            <td>-</td>
        </tr>
    </tbody>
</table>
<table cellspacing='5' class='tw'>
    <tbody>
        <tr>
            <td>倾听着The&nbsp;place&nbsp;I'll&nbsp;return&nbsp;to&nbsp;some&nbsp;day，<br />
            幻想着我们总有一天将要回到的地方。<br />
            记忆的深处、生命的原点，<br />
            一切都回归到万物之源的水晶&mdash;&mdash;<br />
            <br />
            FINAL&nbsp;FANTASY&nbsp;IX，最终幻想&mdash;&mdash;<br />
            再次演绎了一段悲怆的故事&hellip;&hellip;<br />
            <br />
            <br />
            选择第一项<span class='choose'>NEW&nbsp;GAME</span>开始新游戏。</td>
        </tr>
        <tr>
            <td>风将海浪肆虐地卷起，暴雨疯狂地从天空中倾泻而下，整个海面一片惊涛骇浪的景象。<br />
            然而在这样恶劣的环境下，一艘小船仍在风暴中挣扎着。船是那样得脆弱，小船被巨浪抛到半空，又重重地摔下来，仿佛在戏耍它。<br />
            镜头越来越近，船上两个人的身影也渐渐清晰起来&hellip;&hellip;<br />
            突然，一道闪电划过，亮光瞬间照亮了两人的脸庞。<br />
            <br />
            &ldquo;那少女是我！&rdquo;</td>
        </tr>
        <tr>
            <td>伴随着一声惊叫，<span class='location'>Alexandria</span>王国第17世公主<span class='character'>Garnet</span>从恶梦中惊醒。<br />
            多少次了，一直在做同一个梦，仿佛作为自己的记忆，曾经经历过一样。不过<span class='character'>Garnet</span>已经记不清自己小时候的事了。<br />
            <br />
            窗外阳光明媚，整个<span class='location'>Alexandria</span>王国上空一片和谐美好的景象。远处，一艘剧场艇缓缓下降，朝王宫的方向飞过来，看样子是来做演出的。<br />
            镜头推移，进入剧场艇的内部，一个长有尾巴的少年正从杆子上滑下来，走进一间漆黑的房间。</td>
        </tr>
        <tr>
            <td>&ldquo;好黑啊&hellip;&hellip;&rdquo;那个少年自言自语地说道，&ldquo;看起来这儿还没什么人。&rdquo;<br />
            他点亮一根火柴，从而能勉强看见自己身边的一些地方。<br />
            现在玩家开始控制他。在房间右上方头顶会出现！号，表明发现物品，那是个<span class='item'>Potion</span>；左上方能找到一些钱<span class='item'>47Gil</span>。<br />
            来到屋子中间的桌子前，那儿有一根蜡烛。当走到有事件会发生的地方时，头顶会出现？号，这时只要按确定键进行相关的选择便可以了。<br />
            这里选择第一项&ldquo;<span class='choose'>点亮蜡烛</span>&rdquo;，屋子立刻亮了起来。<br />
            &ldquo;谁在屋里？&rdquo;门外一个声音问道。</td>
        </tr>
        <tr>
            <td>给角色起名字，默认的是他的本名。这个人便是整个故事的男主角&mdash;&mdash;<span class='character'>Zidane</span>。<br />
            &ldquo;是我，<span class='character'>Zidane</span>！&rdquo;<br />
            三个人从门外进来，各自向对方行了个礼&mdash;&mdash;呃，这个应该是他们艇内自定的礼节。<br />
            &ldquo;嘿，你可来晚了一步。&rdquo;红头发的<span class='character'>Blank</span>说。<br />
            &ldquo;对不起，那么老大在哪？&rdquo;<br />
            &ldquo;还没见到他呢。&rdquo;<span class='character'>Cinna</span>习惯性地扬扬手中的锤子。话刚说完，身后的门突然被打开了。一个带着怪物龙盔的人冲了进来，不由分说地向我们发起了进攻。</td>
        </tr>
        <tr>
            <p align='center'><br />
            <td>战斗开始，对手<span class='monster'>Masked&nbsp;Man</span>。这是整个游戏的第一战，是为了让玩家熟悉游戏的战斗系统的，在此可以参看专题部分的《战斗系统详解》一栏。可以从他身上偷到<span class='item'>Potion</span>、<span class='item'>Wrist</span>、<span class='item'>Mage&nbsp;Masher</span>。这一场并不难，即使失败也没有关系。不过胜利的话能看到对手抱着头大叫的样子。<br />
            结束后，<span class='character'>Baku</span>&mdash;&mdash;也就是刚才我们和作战的那个人，<span class='character'>Zidane</span>所说的老大&mdash;&mdash;会带我们去另一间房子开会。<br />
            &ldquo;嘿，你们这班小傻瓜，看起来又有长进了！哈哈哈哈！好吧，我们现在就去开会！&rdquo;<br />
            <font color='#808080'></font></td>
        </tr>
        <tr>
            <td><span class='character'>Baku</span>来到一张放有城堡模型的桌子前：&ldquo;现在说一下计划！<span class='other'>Tantalus</span>，声名狼藉的盗贼团，现在正向<span class='location'>Alexandria</span>王国的方向进发&hellip;&hellip;我们的任务是：把王位的继承人，<span class='character'>Garnet</span>公主，诱拐过来！&rdquo;<br />
            <span class='character'>Cinna</span>继续下去：&ldquo;这里开始，就是我解说了。大家听清楚了！我们的剧场艇预计在<span class='location'>Alexandria</span>靠岸，到时候，我们就把戏服穿上，然后表演<span class='location'>Alexandria</span>最受欢迎的&mdash;&mdash;&lsquo;<span class='other'>I&nbsp;Want&nbsp;to&nbsp;Be&nbsp;Your&nbsp;Canary</span>&rsquo;！可要注意点，<span class='character'>Marcus</span>！你可是做主角的！&rdquo;<br />
            <span class='character'>Marcus</span>：&ldquo;包在我身上！当然啦，诱拐的任务就要交给<span class='character'>Blank</span>和<span class='character'>Zidane</span>了。&rdquo;</td>
        </tr>
        <tr>
            <td>&ldquo;我会用这些小虫虫来分散观众的注意力。&rdquo;<span class='character'>Blank</span>掏出一只来，&ldquo;这些虫子我可受不了&hellip;&hellip;不过，我能行的！所以不用担心啦。到你了，<span class='character'>Zidane</span>！然后怎么办？&rdquo;<br />
            现在有两个选择，第一项是&ldquo;<span class='choose'>到我诱拐</span><span class='character'>Brahne</span><span class='choose'>女王的时候了，是吗？</span>&rdquo;；第二项是&ldquo;<span class='choose'>到我诱拐</span><span class='character'>Garnet</span><span class='choose'>公主的时候了，是吗？</span>&rdquo;正确的当然是第二项，不过如果你连选第一项3遍的话，<span class='character'>Baku</span>便会说：&ldquo;好了，不要再开玩笑了！&rdquo;连续选错到第64遍时，<span class='character'>Ruby</span>便会走进来：&ldquo;<span class='character'>Zidane</span>，你什么时候变成老顽固啦！&rdquo;<br />
            &ldquo;对了！你将要诱拐的是全<span class='location'>Alexandria</span>最漂亮的女孩，<span class='character'>Garnet</span>公主！&rdquo;<span class='character'>Baku</span>赞赏道。</td>
        </tr>
    </tbody>
</table></div><center><font size=4><a href='#ff9_001'>返回1-1</a></font></center><br>";
echo "<div id='ff9tw' align='center'><a name='ff9_002' />
<table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>２.&nbsp;亚历山大广场<br /></td></tr>
<tr><th width=60>流程</th><td>假门票-&gt;偷梯子的人-&gt;钟楼中的莫古<br />-&gt;偷入城堡</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>早晨的阳光倾洒在<span class=location>Alexandria</span>城中的雕像上，街道的路上走来一个奇怪的小男孩，他抬头仰望从头顶飞过的飞空艇，吃惊地看着这巨大的家伙在他身上投下深深的黑影。<br /><br />飞空艇越过外围的居民房屋，径直向城堡飞去。城堡中心，有一块巨大的水晶，在阳光的照射下清晰地射出周围的影像来。整个<span class=location>Alexandria</span>王国一片宏伟壮观的景象。<br />接着，飞空艇飞近城堡，FINAL&nbsp;FANTASY&nbsp;IX的LOGO逐渐显现在屏幕的中央。</td></tr>
<tr><td>镜头回到街道上，刚才的那个小男孩——也就是黑魔道士，正随着人流快步往前走。突然“扑腾”一下，他摔倒在地，手中的票也飞了出去。<br />“你没事吧？”旁边一个小女孩问，看他拍拍身上又站了起来，小女孩拾起地上的票交给他，“拿着！你弄掉的门票！再见！”<br />现在控制这个小黑魔道士，先往下方走，来到一个广场里，广场四圈的左上、上、左下方能找到三张卡片：<span class=card>Sahagin</span>、<span class=card>Lizard&nbsp;Man</span>、<span class=card>Zombie</span>。雕像背后有个<span class=item>Potion</span>。</td></tr>
<tr><td>拿完物品后原路返回，在被撞到的那条街的左侧的两头，能各找到一个<span class=item>Potion</span>。从街的右侧下方一个屋子进入，可以看见物主正在为出席今晚的演出做衣服，在房间内可以找到<span class=item>Potion</span>、<span class=card>Fang</span>和<span class=item>9Gil</span>。<br /><br />继续往前走，在下一个场景可以看见一个导游正带领来自<span class=location>Treno</span>的贵族们往城堡进发。<br /><br />下方两侧的草丛中能找到<span class=item>33Gil</span>和卡片<span class=card>Goblin</span>，对面的旅馆里也能发现<span class=item>Potion</span>、<span class=card>Flan</span>和<span class=item>27Gil</span>。</td></tr>
<tr><td>出来旅馆继续向左走，和左边的站着的人对话他会让你去广场的售票处看下。<br />右边商店的地板上可以找到<span class=item>38Gil</span>。<br />和柜台里的老板对话，便会出现一个对话框，三个选项依次为“<span class=choose>买、卖、取消</span>”。选择“<span class=choose>买、卖</span>”便会进入交易状态，这时控制手指上下移动便是选择交易的物品，按确定键后会出现确认对话框，里面有两个数值：上面是买的数量，按左右键可以1为单位调数量，上下键以10为单位调数量；下面的是需要的总钱数。再按一次确定键便会交易成功。<br />可供选择的物品栏右侧也有三个数值：当前拥有的钱数、所选择物品的拥有数和装备数。</td></tr>
<tr><td>进入下一个场景——广场。<br />注意刚进来时会从下方走过一个河马，和它对话它会得意地告诉你：“哇哈哈，我将我的珍贵的三张卡片藏在了一个安全的地方！”这样在后面某个场景便可调查钟楼上的巨钟，并得到那三张卡：<span class=card>Fang</span>、<span class=card>Goblin</span>、<span class=card>Ironite</span>。需要注意的是这三张卡需要在发生偷梯子事件前去拿，否则就拿不到了。<br />在广场的上方左侧的手推车那里能得到<span class=item>Phoenix&nbsp;Pinion</span>，战斗不能后复活用的道具。<br />另外在合成店和装备店里能找到恢复MP的<span class=item>Ether</span>和<span class=item>Remedy</span>，<span class=item>Remedy</span>可能比较难拿。在合成店的右上方的角落里，需要贴着柜台一点点往右走，稍微走过一点就会走进装备店。</td></tr>
<tr><td>广场左侧有几个小女孩在那跳绳，如果走上去和她们对话的话，你便会见识到FF&nbsp;IX中最ＢＴ的小游戏——跳绳游戏！它要求你在绳子甩过来时按确定键跳过去，连续跳一定的次数便会得到相应的奖励，次数达到一定后绳速还会加快，可以说是相当难。值得一提的是，若此次跳绳数超过50，则在第4篇图文中骑士<span class=character>Steiner</span>找手下的情节时，休息室的莫古会看见<span class=other>Kupo</span>写给它的信。</td></tr>
<tr><td>来到广场中间的售票处发生剧情。和售票员对话，选择第一项“<span class=choose>把门票递给他</span>”。<br />“嗯？这门票有点奇怪的样子……”售票员仔细看看那张票，“哎哟！又是一张假票！这种事情今天总是发生！”<br />“噢……”黑魔道士听完之后失望地叹了口气。<br />“好了好了，不要哭。我知道你现在什么感受。来，我给你这些。要打起精神来呀，唔？”<br />得到卡片<span class=card>Goblin</span>、<span class=card>Fang</span>和<span class=card>Skeleton</span>。<br />“跟<span class=character>Alleyway&nbsp;Jack</span>学一学怎么玩卡片吧。祝你好运，小家伙！”</td></tr>
<tr><td>门票是假的，进不去看演出，黑魔道士只好在广场上徘徊。当走到左下方的巷子里时，他突然又摔倒了。<br /><br />“我钉！”旁边一个人正站在梯子上修招牌，正好这一锤落下的时候黑魔道士摔倒的声音惊了他一下。<br /><br />“嘿！你弄到我钉错了，你这小傻瓜！”那人生气地下来教训了黑魔道士一顿，然后继续上去订，不一会儿就好了。<br />“呼，总算修好了。”，他伸个懒腰，“喔，多么漫长的一天啊。”说完梯子也不拿，就走了。</td></tr>
<tr><td>“嗨，你，过来！你就是那个拿假票的小子，是吧？”一个鼠裔族的小子突然跑进巷子里来，他看起来似乎有什么图谋，“我看见那买票的亲口对你这么说的！”<br />有三个选项，无论承认还是摇头都无所谓，他都会继续问：”“我还是可以让你看到戏的，不过你就要做我的奴隶了！怎么样，你说？”选第一项“<span class=choose>好吧</span>”。“那就最好啦！现在开始第一个任务！你站在那边，看有没有人过来！”鼠裔族跑到巷子的这头，而黑魔道士则跑到那头。“行了没有？”选第一项“<span class=choose>是，行了</span>”。“那就对了！下面就按计划行事！”鼠裔族跑过来扛走梯子。<br />先不要跟上去。待一会儿巷子那头会走进一个人来，迎上去和他对话，注意要快！否则就会被偷走<span class=item>39Gil</span>。“呃...请问您的名字是叫做<span class=character>Alleyway&nbsp;Jack</span>吗？”<br />“呃？你怎么知道我的名字的？”<span class=character>Alleyway&nbsp;Jack</span>奇怪地说，“如果你真的知道的话，那你可能就是想我挑战玩卡片的水平了，是吗？什么，还不知道怎么玩？要我教你？”<br />接下来他会教你如何玩卡片，关于卡片这里就不多说了，具体的请参看专题部分的<a href='cardgame.htm' target=blank>《卡片游戏》</a>。</td></tr>
<tr><td>回到那个巷子，跟着鼠裔族来到下个场景，先不要随他进到屋子里，先往下走，这时可以看见身后一个小女孩从房间里跑出来。进入那个房间便可拿到<span class=item>Eye&nbsp;Drops</span>和<span class=item>3Gil</span>。如果不等小女孩跑出屋的话，那<span class=item>3Gil</span>是无论如何也拿不到的。<br /><br />出屋子来到最下面的河边，和那个小孩对话他会让你帮忙寻找丢失的小猫，可以在最初的那个有雕像的广场找到。<br />完成任务后再回去和他对话，为了表达谢意，他会送给我们一张<span class=card>Bomb</span>卡。</td></tr>
<tr><td>跟着鼠裔族进入钟楼，先在四周找到<span class=item>Potion</span>和<span class=item>Tent</span>，接着再按照他的吩咐爬上钟楼。<br />刚走到楼梯下，一只<span class=other>Moggle</span>突然跳了吓来，险些摔在黑魔道士的身上。<br />“对不起了。我撞上你了！”那只<span class=other>Kupo</span>说道，接着介绍了游戏的存盘系统，也就是和它对话，另外还有送信、记录等功能。<br />接着另外一只<span class=other>Stiltzkin</span>也走了进来，它是个旅行商人，在游戏后期能多次见到它，可以向它买卖物品。关于莫古送信事件，请参阅专题<a href='mog.htm' target=blank>《莫古通信》</a>。<br />这只<span class=other>Kupo</span>有一封信要送到<span class=location>Evil&nbsp;Forest</span>的<span class=other>Monty</span>那儿，漏了这次机会以后就不行了。</td></tr>
<tr><td>继续跟着鼠裔族爬上钟楼，可以看到他很活跃地在屋顶前跳来跳去，而小黑魔道士似乎很胆小，一点一点从木板上走过，有一次还险些摔下去……<br />在屋顶上可以找到一些钱，一共是三处，记号便是白色的圆形物体。<br />“哦，是了！我差点忘记问你了！我到现在还不知道你叫什么名字呢！”鼠裔族问。<br />给角色命名，默认的是<span class=character>Vivi</span>。<br />“那我就叫你<span class=character>Vivi</span>了，好吧？这名字还挺好玩的嘛……”鼠裔族笑了笑，“我叫<span class=character>Puck</span>！很高兴能见到你！”<br />继续走穿过几间屋子的房顶，最终来到一堵城墙边。<br />“过了这堵墙就是城堡里面了！来吧，我们一起进去！”<span class=character>Puck</span>率先爬过城墙去，<span class=character>Vivi</span>紧跟在后面。</td></tr>
</table></center></div><center><font size=4><a href='#ff9_002'>返回1-2</a></font></center><br>";
echo "<a name='ff9_003' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>３.&nbsp;剧场艇演出<br /></td></tr>
<tr><th width=60>流程</th>
<td>晚会开始-&gt;戏剧演出-&gt;比剑游戏<br />-&gt;潜入城堡</td></tr>
<tr><th>重要道具</th>
<td>-</td></tr></table>
<table cellspacing=5 class='tw'><tr>
<td>夜幕悄悄降临在<span class=location>Alexandria</span>城上，两个不同颜色的月亮将夜空装饰得十分幽美。<br />然而吹起的礼乐和点燃升空的焰火却将这沉寂打破，给一直等待的人们带来欢快的气氛。<br />王座上，<span class=character>Brahne</span>女王正陪同<span class=character>Garnet</span>公主观看晚会。随着骑士团团长<span class=character>Steiner</span>把剑一挥晚会正式开始了！丑陋的<span class=character>Brahne</span>女王居然从王座上离开，随着音乐扭动起她那臃肿的身材，躲在贵宾席后的<span class=character>Vivi</span>和<span class=character>Puck</span>也踮起脚尖伸长脖子。<br />然而这一切似乎对<span class=character>Garnet</span>来说都毫无兴趣，她沉闷地把头低着，默默地叹了口气。</td></tr>
<tr><td>“女士们，先生们！”化好妆的盗贼团团长<span class=character>Baku</span>站在即将开演的舞台上向观众们致词，“今晚的演出，讲述的是一个发生在很久很久以前的故事。我们的女主角，<span class=character>Cornelia</span>公主，深深地爱着她的爱人，<span class=character>Marcus</span>。她尝试要从城堡里逃出去，但是却被她的父亲，<span class=character>Leo</span>国王，抓住了。当我们的故事开始的时候，<span class=character>Marcus</span>，刚听到这个消息的<span class=character>Marcus</span>，跟国王交起手来了。<br />“现在，就请我们的<span class=character>Brahne</span>女王陛下，<span class=character>Garnet</span>公主殿下……各位贵族们，还有我们坐在屋顶的看客们，一起来欣赏——<span class=other>Tantalus</span>呈献给大家的——<span class=other>I&nbsp;Want&nbsp;to&nbsp;Be&nbsp;Your&nbsp;Canary</span>！”</td></tr>
<tr><td>场景切换至后台，<span class=character>Cinna</span>，<span class=character>Zidane</span>还有<span class=character>Blank</span>正在背诵台词。<br /><span class=character>Blank</span>：“丧父之痛，丧母之痛啊！<span class=character>Marcus</span>，你连最心爱的人都失去了！”<br /><span class=character>Cinna</span>：“运气已经离我们而去了！我们还怎么活下去？”<br /><span class=character>Zidane</span>：“为了我们的友情……让我们把剑深深地刺入那卑鄙无耻的国王的心脏里去吧！”<br />三人举起剑，冲到舞台上，站在<span class=character>Leo</span>国王的面前。<span class=character>Blank</span>：“我会在背后支持你们的！”<br /><span class=character>Marcus</span>：“请把你的剑收起来！这个奸贼，有我一个人来收拾就行了！”<br /><span class=character>Cinna</span>：“别这样，我的战友！因为，我的兄弟，也是被这奸贼杀死的！”</td></tr>
<tr><td>“在那儿吵闹什么？滚出去，寄生虫们！”<span class=character>Leo</span>国王大发雷霆，“你们竟敢在国王面前露出锋芒！？挡我者死！”<br />和<span class=character>Leo</span>以及两名随从战斗，注意这场战斗是必须胜利的，否则就会GAME&nbsp;OVER。<br />战斗中我方三人都会多处一条无杀伤性的指令，没有实际意义，先将<span class=character>Leo</span>身旁两名随从解决掉再对他进行一定的伤害就能结束战斗。<br />“啊...呃...”<span class=character>Leo</span>国王带着伤逃走了，“你还没有见到我的真功夫，<span class=character>Marcus</span>！”<br />“别想逃！”<span class=character>Zidane</span>从后面追上去，却被<span class=character>Blank</span>挡住去路。<br />“仔细想想，<span class=character>Zidane</span>！要是<span class=character>Schneider</span>王子要迎娶<span class=character>Cornelia</span>公主的话，那样和平就能够降临在王国的上空！”</td></tr>
<tr><td>“一派胡言！如果什么事情都这么轻松的话，那么世界的永远太平可就指日可待了！”显然，<span class=character>Zidane</span>根本不相信这会带来和平。一场剑与剑之间的交锋开始了，两人从台上打到台下，来到贵宾席前。<br />下面是个比剑的小游戏，需依照规定按出<span class=item>↑↓→←□△○×</span>八个键，每当<span class=character>Blank</span>口中喊出一个键时迅速按下，超过一定时间则失败。最后按照按对的次数和按下的快慢获得观众的满意度，不同的满意度获得的奖赏不一样，可以无限次地重新表演。下面是满意度和物品对照表：<div class=excel>1～49－<span class=item>Ether</span><br />50～79－<span class=item>Elixir</span><br />80～99－<span class=item>Silk&nbsp;Shirt</span><br />100－<span class=item>Moonstone</span></div></td></tr>
<tr><td>比剑后选第二项结束小游戏。“哼！晚些再跟你算账！”<span class=character>Blank</span>假装敌不过<span class=character>Zidane</span>向一旁跑去。<br />“别想逃，快回来！”<span class=character>Zidane</span>紧追上去。<br />“啊！”“呃！”一间黑屋子里传来人的惨叫声。<br />画面转亮，我们看见<span class=character>Zidane</span>和<span class=character>Blank</span>正穿着士兵的衣服站在那里，旁边地上躺着两个人，似乎都昏迷不醒。<br />“呵呵呵！衣服换好了没有，<span class=character>Zidane</span>？”<br />“换好了，但这个头盔……”<span class=character>Zidane</span>拿近闻了一下，“好像有点臭……”<br />“我都不知道你在说些什么！？我的头盔简直像是进过了臭水沟一样！”<span class=character>Blank</span>的抱怨还要大，“盔甲太大了……我的背总是痒痒的……靴子全湿了……手套感觉粘粘的……口袋里甚至还有饼干碎……”</td></tr>
<tr><td>“好了好了，我知道了……那包东西你还带在身上吧？”<br />“不用担心！我不会出问题的！”<br />“那就好！首先我们要在<span class=character>Garnet</span>公主的茶杯里放点迷药！”<br />“呵，我已经为我们可爱的公主准备一点特别的东东了！”<br /><br /><span class=character>Blank</span>走到一旁倒下的士兵身旁，“他们睡的可真香！”<br /><span class=character>Blank</span>起身走出房间，<span class=character>Zidane</span>瞧瞧那些士兵，随后走出去。<br /><br /><span class=location>Alexandria&nbsp;Castle</span>几个字显现在屏幕上。一切都即将从这里开始……</td></tr></table>
<font size=4><a href='#ff9_003'>返回1-3</a></font></div>";
echo "<br><a name='ff9_004' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>４.&nbsp;诱拐计划<br /></td></tr>
<tr><th width=60>流程</th><td>邂逅-&gt;集合队员-&gt寻找公主<br />-&gt;空中惊险</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>“据侦察所得……王室成员的位子应该就在这楼梯上面！”<span class=character>Blank</span>告诉<span class=character>Zidane</span>说。<br />“前进！”控制<span class=character>Zidane</span>走上楼梯。刚到第二层，一侧的门突然被打开，一个身穿白魔道士服装的蒙面女孩冲了出来，险些和<span class=character>Zidane</span>撞上。<br />“呃？她穿戴的可够奇怪的……”<span class=character>Zidane</span>心里想。<br />“唔，请问你能让我从这儿过去吗？”女孩支支吾吾地问。<br />这里有两个选项，第一个是“让她过去”，第二个是“仔细看看她的脸”。选哪个都无所谓，但第二个比较符合我们主角<span class=character>Zidane</span>的性格，搞笑的对话也多了一段。<br />“让我看看……”<span class=character>Zidane</span>侧着头端倪起来。<br />“我的脸上有什么不对吗？”女孩问。<br />“呃，没有。你看起来……”<span class=character>Zidane</span>似乎想起什么，“我正想呢，你可能就是我等了许久的人啦。”</td></tr>
<tr><td>“对不起，请问你在等我吗？”女孩疑惑地说。<br />“是的！从我出生那天起我就一直梦见在这儿等你！”<br />“你在笑话我吗？”<br />“没有，当然没有……”<br />“那就好，我要告辞了！”她想离去，却被<span class=character>Zidane</span>拦住。<br />“嘿，再等一下！我们以前见过面是吗？”<br />“不，我不认识你……”<br />“呃……”<span class=character>Zidane</span>绕着她转了一圈，“也许你说的是真的……不过我可不会让一个像你那样漂亮的女孩离开。”<br />“这么说，你不让……”女孩似乎有些着急。这时楼下的<span class=character>Blank</span>走了上来：“嘿，<span class=character>Zidane</span>，进展如何？”<br />趁着<span class=character>Zidane</span>一不注意的时候，女孩立刻冲下楼，把两人撞得原地打转。<br />“刚才谁撞的我！”<span class=character>Blank</span>生气地问。<br />“快起来<span class=character>Blank</span>！刚才那个是公主<span class=character>Garnet</span>！”<span class=character>Zidane</span>从那女孩不谙世事的言行上立刻察觉出不对，随后紧追上去。</td></tr>
<tr><td>镜头转移到城堡入口旁的两个皇家小丑身上，红色的叫<span class=character>Thorn</span>，兰色的叫<span class=character>Zorn</span>。<br />“我们有麻烦了！”<span class=character>Zorn</span>说。<br />“有麻烦了我们！”<span class=character>Thorn</span>说。<br />“这真是可怕！”“我们的头，女王会要了！”<br />“我们得快点！”“得快点我们！”<br /><br />这对小丑特别有意思，言行不是相同就是相对，在随后找女王的路上两人又分别各走错一次路，连指责对方和狡辩都是一模一样的……天，这两人的神经一定不正常。<br />两个小丑最终来到女王所在的阳台上。</td></tr>
<tr><td>“我们要晋见女王！”<br />“女王陛下现在很忙！等会儿再来吧！”骑士团团长说。<br />“有紧急的事情吗？”旁边一位佩剑的女性突然问道，她就是<span class=location>Alexandria</span>有史以来最强大的战士——<span class=character>Beatrix</span>，广场上的雕像就是为她修建的。<br />在得知公主的事情后，<span class=character>Beatrix</span>立刻向女王作了汇报：“女王陛下，看起来<span class=character>Garnet</span>公主把皇家项链一起带走了。”<br />“呃，这样……她究竟在想些什么！？”<span class=character>Brahne</span>女王似乎更加重视那条项链，“<span class=character>Beatrix</span>将军！还有……”<br />给那个骑士团团长起名，他本名是<span class=character>Steiner</span>。<br />“你们立刻去寻找<span class=character>Garnet</span>！”</td></tr>
<tr><td>“骑士团的团员——集合！！！”只听<span class=character>Steiner</span>一声令下，可却没有一个人出来，“呃，人都跑到哪里去了！？”<br />那两名起初被<span class=character>Blank</span>和<span class=character>Zidane</span>打昏的人似乎醒了，跑出来向团长报告：“一切准备妥当，大人！”<br />“其余六个都到哪里去了！？”<span class=character>Steiner</span>跑下楼梯，看到两人都没穿衣服，“什么？你们这些一点用都没有的饭桶！我从女王处接到命令，穿好衣服就跟我去找<span class=character>Garnet</span>公主！”<br />控制<span class=character>Steiner</span>进入那两个骑士走进的房间，会发现二人还在闲聊，将两人赶出去后可以在屋内发现<span class=item>Phoenix&nbsp;Down</span>和一张骑士团名单。<br />现在的任务是先回去找女王要比剑游戏的奖赏，然后找齐8名骑士团队员。当然，不找齐也行，不过就无法获得<span class=item>Elixir</span>。以下是另外6人的位置：</td></tr>
<tr><td>第一个比较难“抓”，因为他是按照你走动的方向而跑的，所以在这个场景多尝试几次吧，那样就能抓着他了。第二个在抓第一个人的右侧房间里吃东西，虽然叫他他也不理，不过总得对一下话。第三个在楼下左侧的图书馆里。第四个在出来王宫的小河前。第五个在河左侧那条路的监狱门口，和MM调侃。第六个便是从监狱里进去，环形楼梯道上，和他对话找齐6个人的话便会获得<span class=item>Elixir</span>。</td></tr>
<tr><td>上到塔顶，<span class=character>Steiner</span>正累得气喘吁吁。<br />“等等，在那边！那是Garnet公主！”<span class=character>Steiner</span>顿时来了精神，“被强盗所追逐的公主不要怕，守护你的骑士来啦！”<br /><br />ＣＧ动画开始。<br />那个蒙面女孩——也就是<span class=character>Garnet</span>逃脱<span class=character>Zidane</span>的追赶爬到塔楼的城墙上，站起身来回头看着<span class=character>Zidane</span>，脸上带有一些似乎调皮的微笑。<br />突然，<span class=character>Garnet</span>纵身一跳，从城墙上跃了下去，<span class=character>Zidane</span>吃了一惊，<span class=character>Steiner</span>更是吓得魂不附体。</td></tr>
<tr><td>然而担心似乎是多余的，落下的<span class=character>Garnet</span>手中牢牢拽着一根绳子，原来她是早就预谋好的……<br /><span class=character>Zidane</span>见状随后牵起另一根绳子追了上去，所幸的是两人有惊无险，都安全落在了一个帐篷上。<br />然而尽忠职守的<span class=character>Steiner</span>却没那么好运。将绳索绑在身上的他却一头撞向了一块木板……<br /><span class=character>Zidane</span>在剧场艇上落下后，四处观望寻找<span class=character>Garnet</span>，没想到<span class=character>Garnet</span>却从天而降，踩在了他的身上。<br />在将乐队都撞得原地打转后<span class=character>Garnet</span>逃进了一间屋子，控制<span class=character>Zidane</span>走进去吧，邂逅才刚刚开始……</td></tr>
</table><font size=4><a href='#ff9_004'>返回1-4</a></font></div>";
echo "<br><a name='ff9_005' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>５.&nbsp;逃离<br /></td></tr>
<tr><th width=60>流程</th><td>表白-&gt;即兴演出-&gt剧烈的爆炸<br />-&gt;脱险逃离</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>“哇，讨厌的！”<span class=character>Garnet</span>又一阵风似的跑进屋里，把一旁站着的<span class=character>Ruby</span>撞得转了好几个圈，坐倒在地，“别跑那么快，知道吗！”<span class=character>Ruby</span>上前看清<span class=character>Garnet</span>是个女孩子，口气放松了些，“你在着什么急呀，亲爱的？至少也应该说声对不起吧？”<br />“真的很抱歉。你都看见的，我现在很忙……”<br />“可是我是在这里准备等会儿出场的呀！”话说到这里，<span class=character>Zidane</span>接着从门外进来，“嘿，<span class=character>Zidane</span>，你看见她怎么撞上我的吗！这个牛崽女的劲儿，比野马还大！”<br />可<span class=character>Zidane</span>似乎没听见：“你让我和她说说吧。”<br />“再说一遍啊，伙计？”<span class=character>Ruby</span>将<span class=character>Zidane</span>逼退一步，显得很不高兴，“你听见我刚才说什么了吗？”<br />两人的争吵似乎没完没了，<span class=character>Garnet</span>当然不会傻站在这儿，立刻一溜烟儿跑下楼。<br />“嘿，<span class=character>Ruby</span>，我们待会儿再说！”<span class=character>Zidane</span>追了下去。</td></tr>
<tr><td>来到最初的那个房间里，<span class=character>Garnet</span>放慢脚步，最终停了下来，<span class=character>Zidane</span>追到她的身后也站住脚步，看着她的背影。<br />“好了，看起来你终于决定不再逃跑了。”<span class=character>Zidane</span>嘴上说着，心理却暗暗地想：喔，看来我们得临时准备一下，但是不管怎么说，我们终于得手了！<br />“你在……你在这条船上工作吗？”<span class=character>Garnet</span>突然转过身来，面向<span class=character>Zidane</span>，见他挠挠头默许，继续说，“正如你们所料，实际上——实际上我就是——”<span class=character>Garnet</span>将头上的袍子掀开，“<span class=character>Garnet&nbsp;Til&nbsp;Alexandros</span>，<span class=location>Alexandria</span>王位的继承人。我有一个请求……”<span class=character>Garnet</span>突然上前握住<span class=character>Zidane</span>的双手，“我希望被诱拐，就是现在。”<br />面对这突如其来的转变，<span class=character>Zidane</span>居然会不知所措：“呃——我不、不是这个意思……”</td></tr>
<tr><td>一阵敲门声打断对话，同时一个声音喊道：“公主，你在哪里？”<span class=character>Garnet</span>听了连忙又把头重新蒙起来：“不好了……他们就是来找我的！”<br />“啊哈……原来是这么一回事……”<span class=character>Zidane</span>拍拍胸脯说，“那好！事情就交给我吧！”接着他又单膝跪下，“就这样了，公主殿下。我会尽最大的努力来诱拐你的！”<br />“你们两个在干什么？快点，这边走！”跑进来的原来是<span class=character>Cinna</span>。见是自己人，<span class=character>Zidane</span>告诉<span class=character>Garnet</span>说不用担心。这时另一扇门突然又响了起来，同时外边传来<span class=character>Steiner</span>的声音：“公主！”等他进来的时候，屋内早就没有了人影。</td></tr>
<tr><td><span class=character>Zidane</span>一行人逃进右边的屋子，可这间屋子只有一扇门。<br />“嘿，<span class=character>Cinna</span>，这可是死胡同！”<span class=character>Zidane</span>叫道。<br />“呵呵，我早知道你会这么说的。芝麻开门！”只见<span class=character>Cinna</span>用脚一踢，桌子下的秘道立刻展现在众人面前。<br />“公主！”门外又传来<span class=character>Steiner</span>的声音，三人连忙跳进秘道里，盖子都顾不上关。<br />“公主一定就在这下面！”<span class=character>Steiner</span>说。“让——让我先上，大人！”随行而来的那名士兵自告奋勇向秘道中跳去，可惜却因身材臃肿卡在地板上。<br /><span class=character>Steiner</span>低头忍了一下，然后跳了起来：“嘿！你知不知道你在做什么！呃，快滚！”他似乎等不急了，转身跑出房间寻找另外的入口。<br />士兵继续挣扎了一阵，等<span class=character>Steiner</span>走远停止住，开始偷笑起来：“嘿嘿，真的上当了……”</td></tr>
<tr><td>画面转回主角们，当他们从秘道跳下来后，<span class=character>Zidane</span>对前面的<span class=character>Garnet</span>说道：“哇，你的体力真好呀，公主。我都快赶不上你了！”<br />“这不算什么。毕竟我也一直坚持训练如何逃出城堡的。”<br />“真是太浪费了。假如你不是公主的话……”<br />“我们可没时间停下来说笑话。快，我们继续走！”<br />在下层转动轮子，分别选第一项“<span class=choose>向左转</span>”和第二项“<span class=choose>向右转</span>”。可以掉下两个宝箱，能够获得<span class=item>Phoenix&nbsp;Down</span>和<span class=item>Phoenix&nbsp;Pinion</span>，不用理会<span class=character>Cinna</span>，反正随后又会给转回去。<br />当我们来到左边的房间，准备继续演出时，<span class=character>Steiner</span>突然从滑杆上滑了下来。</td></tr>
<tr><td>“啊哈！是公主！我，<span class=character>Steiner</span>，是来解救你出去的！”话刚说完，那名随行的骑士也出现并堵住门口。<br />“呵呵，别紧张，公主。我们会把你安全带出去的！”原来这个骑士正是<span class=character>Blank</span>。<span class=character>Steiner</span>气得攻了上来。<br /><br />和<span class=character>Steiner</span>进行战斗，这一场并不算难，攻击他几下他便会使用必杀击破<span class=character>Blank</span>的盔甲，一大群<span class=other>Oglop</span>虫从他身上涌出来，到处乱跳。可以从他那偷得<span class=item>Leather&nbsp;Hat</span>和<span class=item>Silk&nbsp;Shirt</span>。<br />“啊，我最怕<span class=other>Oglop</span>的了！”<span class=character>Cinna、Steiner、Blank</span>吓得四处乱跑，<span class=character>Zidane</span>乘机带着<span class=character>Garnet</span>离开这里。</td></tr>
<tr><td>舞台上，<span class=character>Baku</span>继续演着<span class=character>Leo</span>国王这个角色。<br />“今晚，我终于能够看到我的女儿，<span class=character>Cornelia</span>出嫁的情景了！然后，<span class=character>Schneider</span>王子和他的国家就成为我的囊中物了！”<br />这时国王的两名贴身侍卫，抓住<span class=character>Marcus</span>的手臂走上台，向他报告抓到一名入侵者。<br />“什么，我可怜的<span class=character>Marcus</span>！听着小子：不管你把<span class=character>Cornelia</span>藏得多么紧，不管她是多么的爱你，我都不可以忍受她下嫁给像你这样的穷光蛋！”<span class=character>Leo</span>的声音伴随着一声钟声继续响起，“当钟声敲响三下的时候，你的头将会在斧头之下屈服！”钟声敲响第二遍。<br />画面转到<span class=character>Zidane</span>这边，他们由于<span class=character>Steiner</span>在无法正常演出。最后，大家做出决定一起上台做即兴表演，<span class=character>Steiner</span>也不顾一切冲了上来，结果被传送到台上，傻站在一旁不知所措。</td></tr>
<tr><td>这场即兴演出十分成功，台下掌声不断，连<span class=character>Brahne</span>女王都感动地大哭起来。<br />另外一边，贵宾席前的<span class=character>Vivi</span>和<span class=character>Puck</span>也看得十分投入，可他们站得太显眼，很快就被卫兵发现了。<br /><span class=character>Vivi</span>跑着跑着摔在地上<span class=character>Puck</span>顾不得他自己先逃了，<span class=character>Vivi</span>只好一个人逃上舞台。<br />“别过来……”面对追来的士兵，<span class=character>Vivi</span>想用火魔法吓唬他们，可是放出来的火焰不偏不倚落在了<span class=character>Garnet</span>的身上，点燃了她的袍子。<br />“啊，好烫啊！”<span class=character>Garnet</span>连忙脱掉袍子，但是这样她的真是身份无疑在舞台上彻底暴露了。</td></tr>
<tr><td>“<span class=character>Zidane</span>，时候到了！”<span class=character>Baku</span>吩咐一声，离开了。<br /><span class=character>Zidane</span>按照计划，准备劫持<span class=character>Garnet</span>离开，可是<span class=character>Steiner</span>站在面前，显然，得先过他这一关。<br /><br />和<span class=character>Steiner</span>战斗。<span class=character>Vivi</span>和<span class=character>Garnet</span>会加入我方，他们一个会攻击性的黑魔法，一个会恢复性的白魔法，<span class=character>Garnet</span>的召唤<span class=magic>Summon</span>技能目前不能使用。<br /><span class=character>Steiner</span>有167点HP，旁边的两个士兵攻击一下便会撤退。<br /><br />在舰桥室里，<span class=character>Baku</span>已经调整好引擎，开始启动剧场艇。</td></tr>
<tr><td>ＣＧ动画。<br />女王气急败坏地命令炮手发射铁锚将剧场艇拖住，被铁链锁住的剧场艇在空中摇摆不定。<br />“轰——”的一声，艇的尾翼撞到了一幢建筑上，建筑里的人们惊惶失措，四处逃窜。剧场艇摇晃地更加厉害，撞到了更多的房屋，整个晚会上的人们都吓坏了，现场一片混乱。然而更可怕的在后面，<span class=character>Brahne</span>又疯狂地打开了一扇门，用里面的一尊巨炮放出一个巨大的<span class=monster>Bomb</span>来，歇斯底里地叫着要将剧场艇轰下来。<br />再次和<span class=character>Steiner</span>发生战斗。这场战斗其时不用打，无论胜负一定回合后<span class=monster>Bomb</span>便会引爆自己，所以一直防御就行了。</td></tr>
<tr><td>“轰——”巨大的爆炸声响彻云霄，女王得意地看着剧场艇在<span class=monster>Bomb</span>的自暴下被烟雾所吞没。<br /><br />然而她并没有得意太久，很快剧场艇的前翼就从烟雾中露出，接着整个艇身飞了出来。船头那尊女神像虽已满面黑尘，但却毅然仰望前方，有如某种象征。<br /><br />艇的内部还不时地发出一些小爆炸，大块的部件落了下来。就这样，剧场艇摇摇晃晃地飞出了<span class=location>Alexandria</span>城，在云层中上下挣扎了几下，接着向地面俯冲而去……</td></tr></table><font size=4><a href='#ff9_005'>返回1-5</a></font></div><br>";
echo "<br><a name='ff9_006' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>６.&nbsp;魔之森<br /></td></tr>
<tr><th width=60>流程</th><td>坠落->救火->寻找->救人</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>舰桥中一片混乱，<span class=character>Baku</span>再也控制不住船舵，剧场艇下落的速度越来越快。“我们就要撞上了！”<span class=character>Cinna</span>慌乱地叫喊起来，可这也于事无补。<br /><br />漆黑的夜空中，飞空艇终于经受不住坠落下来，跌跌撞撞地栽进了一片森林中。<br /><br />镜头切远，森林的中央，剧场艇发生了大爆炸，火光冲天，把天空映得通红通红。而伴随着爆炸传出的，还有一声声沉重的叹息。</td></tr>
<tr><td>与此同时，<span class=location>Alexandria</span>的城上。<br />“<span class=character>Garnet</span>……”<span class=character>Brahne</span>女王气狠狠地说，“我从没想到你会干出这种事来。也许你已不是过去那个无助的小女孩了……<span class=character>Zorn</span>！<span class=character>Thorn</span>！”<br />两个小丑分别出现在王座的左右。<br />“我们的小实验成功了没有？”<span class=character>Brahne</span>问。<br />“是的，女王陛下，已经做好战斗准备了。”<span class=character>Zorn</span>回答。<br />“它能够轻易地结束<span class=character>Garnet</span>公主的性命，女王陛下。”<span class=character>Thorn</span>又补上一句。<br />“我不要死的，我要活的！”<span class=character>Brahne</span>暴躁地转过身向两人叫道，“立刻把她给我带回来！”</td></tr>
<tr><td>森林里的一片空地上，被抛出剧场艇的<span class=character>Zidane</span>逐渐清醒过来。他挣扎着从地上爬起来，四周望望后，微微颤颤地向一个小山崖走去。<br />山崖下，已严重毁坏的剧场艇正冒着滚滚浓烟。<br />舰桥中，<span class=character>Baku</span>望着<span class=character>Cinna</span>：“呃……我的背疼得要命，你呢，没事吧？”<br />“我没事，但是飞空艇就有事了。”<span class=character>Cinna</span>还有心思幽默。<br />“能幸运地撞进这片森林里……可真够有意思的……”<br />“老大你说‘有意思’？我可从没听说有人能够从这里活着走出去的。”<br />这时<span class=character>Blank</span>跑进了房间，说道：老大，到处都着火了！看情况快要失控了！”<br />“那就别在这里发牢骚，快点去控制局面！还有，要把伤员给救出来！”吩咐好这边后，<span class=character>Baku</span>继续向<span class=character>Cinna</span>说，“还要把我们的家伙给找回来：武器呀，物品呀，反正能用的就给找回来！要是我们的东西给烤焦了，那就没得救的了！”</td></tr>
<tr><td>飞空艇外，<span class=character>Cinna</span>发愁地看着到处都燃着火苗的飞空艇，<span class=character>Zenero</span>正走出剧场艇，把一个个伤员丢在地上。“那些家伙们究竟在干些什么，整艘船都快要烧光了！”<br />“他们还在找<span class=character>Garnet</span>呢，”<span class=character>Zenero</span>无奈道，“不过哪里都不见她。也许她掉下去了，剧场艇把她压住了也说不定。”<br />“那就最好了。我们先是诱拐她，然后又把她杀死了。我们就是被判一百次绞刑也不够。”<span class=character>Cinna</span>苦笑着说。<br /><br />镜头下移，<span class=character>Zidane</span>跳过沟壑向这边跑来。和<span class=character>Cinna</span>互相问候几句后，树上的<span class=other>Moggle</span>飞下，发生ＡＴＥ事件。</td></tr>
<tr><td>森林内，<span class=character>Vivi</span>和<span class=character>Garnet</span>远远的从路上跑近，在走上一个坡时<span class=character>Vivi</span>滑倒了。<br />“你没事吧？”<span class=character>Garnet</span>上去将他扶起。<br /><span class=character>Vivi</span>站了起来，惧怕地后退了两步，没有回答<span class=character>Garnet</span>，而是问了另一个问题：“它——它又来了吗？”<br /><span class=character>Garnet</span>摇着头望着后面，这时森林中响起轻微的悉嗖的声音，地上突然映出一片黑影，飞快的向<span class=character>Garnet</span>移去……<br />“当心！”随着<span class=character>Vivi</span>的一声叫喊，画面逐渐转黑。<br /><br />剧情回到<span class=character>Zidane</span>这边，左边躺在地上的人身旁有个<span class=item>Phoenix Down</span>，控制他走入右下方的树洞。</td></tr>
<tr><td>走进深处的<span class=location>Evil&nbsp;Forest</span>，这里一片静谧的景象，一只小青蛙悠闲地在小河边来回踱步。然而这宁静的面容并不能掩盖深藏在它那神秘之下的凶险与诡异。<br />这里的场景能碰到的敌人只有两种：<span class=monster>Fang</span>和<span class=monster>Goblin</span>。前者的HP较多，如果之前比剑游戏获得满分拿到<span class=item>Moonstone</span>的话，可以装备上从而获得辅助能力<span class=magic>Beast Killer</span>，如此就可以一下子解决掉<span class=monster>Fang</span>。<br /><br />关于辅助能力请参看专题<a href='s_ability.htm'>《辅助技能》</a>，如何装备等请参看<a href='system.htm'>《系统详解》</a>。另外不推荐游戏初期就疯狂地练级，这样对<a href='guide.htm'>《人物培养》</a>不利。</td></tr>
<tr><td>刚刚走过水洼地带就看到<span class=character>Vivi</span>惊恐地倒退两步一屁股坐在地上，带着颤音说：“她——她有麻烦了……”<br /><span class=character>Zidane</span>往前一看：“……见鬼，那是什么东西？”<br />来不及多想，<span class=character>Zidane</span>冲了上去，和<span class=character>Steiner</span>一同对付囚禁着<span class=character>Garnet</span>的怪物。<br /><br />战斗开始，<span class=character>Zidane</span>因救人心切，首先会进入<span class=other>Trance</span>状态。进入这种状态的队员各项能力都会大幅度提升，有点像我们常说的“暴走”。这样的话<span class=character>Zidane</span>就可以用特殊技能<span class=magic>Free&nbsp;Energy</span>轻松解决对手<span class=monster>Prison Cage</span>。<br /><br />关于<span class=other>Trance</span>方面详细介绍请参看专题<A HREF='trance.htm'>《Trance系统》</A>。</td></tr>
<tr><td>值得一提的是，如果先前与<span class=character>Baku</span>战斗中偷到<span class=item>Mage&nbsp;Masher</span>，在这场战斗中，千万不可使用攻击全体的第2个<span class=other>Trance</span>技<span class=magic>Tidal&nbsp;Flame</span>，否则将误伤公主。战斗中<span class=monster>Prison&nbsp;Cage</span>有时会吸收公主的HP，注意在必要时使用<span class=item>Potion</span>给她回复HP。这家伙是个穷鬼，就不必偷东西了。<br />胜利后怪物会带着<span class=character>Garnet</span>逃走。众人眼睁睁地看着他们离开，却无能为力。<br />“她不见了……我吓得无法施展咒语……那怪物可能会吃了她……”<span class=character>Vivi</span>沮丧地说，都怪自己胆小。然而现在不是自责的时候，因为另一只怪物又突然袭来，像抓住<span class=character>Garnet</span>一样抓住了<span class=character>Vivi</span>，再次发生战斗。</td></tr>
<tr><td>这一场和上一场就不同了，<span class=character>Zidane</span>无法使用<span class=other>Trance</span>技，不过被怪物抓住的<span class=character>Vivi</span>会每回合都用火魔法进行攻击，一次能伤害80～90点HP不等。同样地这次战斗要注意给<span class=character>Vivi</span>恢复。<span class=monster>Prison&nbsp;Cage</span>身上能偷到<span class=item>Leather Wrist</span>和<span class=item>Broadsword</span>。<br />战斗结束，怪物像一滩烂泥一样倒在地上。<br /><span class=character>Vivi</span>站了起来把帽子扶正，显得依然有些惊魂不定：“呼，谢——谢谢……”<br />“你没事吧？”<span class=character>Zidane</span>问道。<br />“是——是的，我想是的。”<span class=character>Vivi</span>刚回答完，那只怪物突然用尽最后的力量喷出一股绿色的毒气，将他和<span class=character>Steiner</span>熏倒，<span class=character>Zidane</span>发现得及时，灵活地闪开了。<br />“公——主！”倒地前<span class=character>Steiner</span>还不忘本职地叫了声。</td></tr></table>
<font size=4><a href='#ff9_006'>返回1-6</a></font></div><br>";
echo "<br><a name='ff9_007' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>７.&nbsp;森林逃亡<br /></td></tr>
<tr><th width=60>流程</th><td>回船->争斗->救人->逃亡</td></tr>
<tr><th>重要道具</th><td>Blank's&nbsp;Medicine<br />Continental&nbsp;Map</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>镜头逐渐亮起，已经回到剧场艇的<span class=character>Vivi</span>躺在床上慢慢转醒，他看见<span class=character>Blank</span>正站在一旁照料着他。<br />“你们这些家伙真幸运。要不是<span class=character>Zidane</span>，你们可都完蛋了。”<span class=character>Blank</span>笑着说对他说，“森林里有些怪物是在其他生物上播种来繁殖后代的，当它们发芽时，会产生剧毒：那时你就去见上帝吧。”<br />“呃，我——我会死吗？”<span class=character>Vivi</span>似乎有点被吓到了。<br />“不，你不会有事的。来，服下这个，它会清除你体内所有的种子。”<span class=character>Blank</span>拿出一支解毒剂来。<br />镜头转到剧场艇二层的楼梯前，<span class=character>Zenero</span>和<span class=character>Benero</span>两人将昏昏沉沉的<span class=character>Steiner</span>推进房间。<br />“好好休息吧，还有服下我给你的药。”<br />被推进房间里的<span class=character>Steiner</span>显得相当落魄，仿佛丢尽了面子。<br />“可恶，我不能就这样呆在这里……公主的性命把握在我手中，他们的头儿能做什么啊！”<span class=character>Steiner</span>摇摇手中的解毒药剂，“这药，真难闻，还有这颜色，显然是毒药！”<br />正当他还忿忿不平地抱怨时，毒性似乎爆发了：“哈……呼……呃，我快死了……上帝救我……”他再也顾不得面子，一口气将那瓶中的液体喝掉，“嘿，还不错……”<br />这会儿他的态度跟刚才相比简直判若两人。</td></tr>
<tr><td>在剧场艇的舰桥上，<span class=character>Zidane</span>正向<span class=character>Baku</span>请求商讨营救公主的事。<br />“别提她了，源于雾中的怪物现在可是四处蔓延！”<span class=character>Baku</span>有点不耐烦地说。<br /><span class=character>Zidane</span>有点激动：“那又怎样？没有我们办不成的事！”<br />“我们首先要考虑伤员问题，还有外面的怪物。我手下人的安全先于公主，你知道的，现在情况太糟了……”<br /><span class=character>Zidane</span>气愤地向地板踢了一脚，见老大还是不肯让步，冲他喊道：“我简直不能相信你要丢下她！你这个胆小鬼！”<br />接下来可以控制<span class=character>Zidane</span>离开了，走之前别忘记拿右下角的<span class=item>Bronze&nbsp;Gloves</span>。看着<span class=character>Zidane</span>离开的背影，<span class=character>Baku</span>的嘴角边露出一丝狡诘的笑容……<br />一出门就有三个ＡＴＥ事件，别忘了按“<span class=choose>Select</span>”查看。</td></tr>
<tr><td>看完ＡＴＥ直接从楼上下来进入右边的房子探望<span class=character>Vivi</span>。<br />看着躺在床上还处在深深自责中的<span class=character>Vivi</span>，<span class=character>Zidane</span>上前安慰了他几句后欲转身离开。临走时<span class=character>Vivi</span>说了声：“谢谢你，<span class=character>Zidane</span>先生。”<br />“第一次听见有人叫我‘先生’，叫我<span class=character>Zidane</span>就好。”<br />“OK……<span class=character>Zidane</span>。”<span class=character>Vivi</span>微笑着说。<br />说完话别急着离开，房间的左上角可以找到物品<span class=item>Ether</span>，从右边的梯子爬上床还能拿到<span class=item>116 Gil</span>。<br />“噫，他一定很沮丧……”走出门后的<span class=character>Zidane</span>回想着刚才安慰<span class=character>Vivi</span>时对他的承诺，“也许我不该做那个保证，连我自己都不知道是否能够找到她。”<br />画面回到<span class=character>Zidane</span>第一次见到<span class=character>Garnet</span>的时候，<span class=character>Zidane</span>的脑海中正浮动着那些模糊而又清晰的景象，他与她谈话时的一颦一笑一喜一怒。</td></tr>
<tr><td>“天……我从未有过如此的感觉……也许是命运使我们走到一起……我自己都无法解释……”这是<span class=character>Zidane</span>内心的真实声音吗？<br />画面回到现实中来。<span class=character>Zidane</span>开始考虑是否去救<span class=character>Garnet</span>。<br />这时出现两个选项：“<span class=choose>去找她</span>”和“<span class=choose>忘了这事</span>”，选哪个都一样，但符合剧情的应该是第一项。“嘿，我在想什么？她很可爱，她在危险之中，这样的理由已经足够了。”<br />“……你在这里啊，”<span class=character>Blank</span>从一旁走进来，“别这么严肃，这回你又想去做什么？”<br />在得知<span class=character>Zidane</span>的想法后，他吃惊地说：“你疯了！天，你都不知道外面有些什么。况且，头儿也不会允许的。”<br />然而<span class=character>Zidane</span>却一意孤行。<br />“噫……你怎么老想着逞英雄？头儿会杀了你的。那你还等什么？去和头儿说吧。”</td></tr>
<tr><td>这个场景的左上可以拿到<span class=item>Wrist</span>。走左边的门出去，场景的下方可以拿到<span class=item>Ether</span>。顺着楼梯下去到货舱，左上角可以找到<span class=item>Rubber Helm</span>。之后就进入右边的门，去找<span class=character>Baku</span>吧。<br />听到<span class=character>Zidane</span>进门的脚步声<span class=character>Baku</span>醒了过来：“啊，啊嚏！等你等的我都要睡着了，见鬼。这么说，你决定离开了？”<br />“是的……我答应过<span class=character>Garnet</span>要诱拐她的。”<span class=character>Zidane</span>回答。<br /><span class=character>Baku</span>笑了：“我不是问你为什么！我也不能责怪你，她实在太漂亮了。我想这个理由就足够了！那么，我希望你做好准备了，由于你破了规矩我要好好揍你一顿！OK，把你的屁股挪到货舱去，那儿的地方更大。”<br /></td></tr>
<tr><td>这个房间的下方可以拿到<span class=item>Potion</span>，准备好之后就出去吧，和外边的<span class=character>Baku</span>对话选择第一个“<span class=choose>准备好了</span>”，开始和<span class=monster>Baku</span>战斗。<br />这家伙并不强，和游戏开始一样，常常跌倒而打不中人，注意点血量即可轻松获胜。在他身上能偷到<span class=item>Hi-Potion</span>和<span class=item>Iron Sword</span>。<br />获胜后发现<span class=character>Blank</span>已经在房间里了。<span class=character>Baku</span>自嘲道：“我真失败……做的好！”他朝<span class=character>Zidane</span>打了一拳，“去找你的公主吧！”说着<span class=character>Baku</span>大笑着走了出去。<br /><span class=character>Zidane</span>在挨了一记后捂着肚子跪倒在地：“呃，只有最后这拳他用了真功夫。”</td></tr>
<tr><td>打完之后也就算脱离组织了，去叫<span class=character>Steiner</span>和<span class=character>Vivi</span>他们一起救公主吧。在找<span class=character>Steiner</span>时当然免不了又来一场口舌之战，最后当然又是以<span class=character>Steiner</span>的委曲求全而告终。<br /><br />当提及<span class=character>Vivi</span>时，<span class=character>Steiner</span>居然一本正经地称呼他为“Vivi大师”，真让人哭笑不得。离开房间前<span class=character>Steiner</span>会和<span class=character>Vivi</span>悄悄提及“<span class=magic>Swd&nbsp;Mag</span>”的事。<br /><br />在<span class=character>Steiner</span>的房间里可以找到<span class=item>Ether</span>。</td></tr>
<tr><td>“你真的要去？”当我们走到剧场艇外舱的时候，<span class=character>Baku</span>靠着墙壁说道，他早已在那里等候多时了。<br />“算了，我可不管你，我来是给你这个的。”<span class=character>Blank</span>交给我们一瓶<span class=item>Blank's&nbsp;Medicine</span>，一起得到的还有<span class=character>Baku</span>的一封信：“不要忘了学习你的技能，离开团伙是你的事，但你最好持续锻炼自己！学会更多的技能会使你更强的。——祝好运，<span class=character>Baku</span>。”<br /><span class=character>Blank</span>身旁的箱子里装的是<span class=item>Leather&nbsp;Hat</span>，说完话就可以走出剧场艇向魔之森深处出发了。<br />艇外的<span class=character>Cinna</span>那里可以购的一些恢复道具。在走入魔之森后发生ＡＴＥ事件。</td></tr>
<tr><td>顺着公主被抓走那条路一直往前跑，一路上的怪物都很简单，只有<span class=monster>Fang</span>和<span class=monster>Goblin</span>。<br />走过两个场景后来到一眼清泉的旁边，这里有只叫<span class=other>Monty</span>的<span class=other>Moggle</span>正在喝水，看见人来了它立刻躲进树洞里去，和他对话可以存盘，另外还可以送出它<span class=other>Kupo</span>写给它的信。泉水处可以恢复HP和MP。<br />要注意的是，这之后的怪物会多出一种叫<span class=monster>Dendrobium</span>的来，它的全体技能附带<span class=magic>Darkness</span>属性，中的队员会大幅降低物理攻击命中率，记得要及时使用<span class=item>Eye&nbsp;Drops</span>解除。<br />这之间有个ＣＧ动画和ＡＴＥ事件：</td></tr>
<tr><td><span class=character>Zidane</span>走进一个山洞，刚进去就看到一个巨大的植物怪挥动着粗壮的枝叶，仿佛很不欢迎他们似的。而就在怪物身后，公主被困在墙上昏迷不醒。还想什么，打就是了。<br /><br />BOSS战：对战怪物为<span class=monster>Plant&nbsp;Brain</span>，很简单的一战。它身上可以偷到<span class=item>Eye&nbsp;Drops</span>和<span class=item>Iron&nbsp;Sword</span>。<br /><br />当我们对其作出一定伤害或过一定回合后，<span class=character>Blank</span>会前来加入，很轻松就可偷光东西，然后开杀吧。正好试试我们<span class=character>Steiner</span>的绝技魔法剑威力如何。</td></tr>
<tr><td>终于怪物被打倒，<span class=character>Steiner</span>抱着公主担心说：“公主，你要坚持下去啊！”<br /><span class=character>Zidane</span>走过去把药给她喝下去。<br /><br />但是情况却不容我们乐观：地上突然陷出一个大洞，大量的怪物开始不断涌出。不得以大家只好向魔之森外面突围。这种怪物是<span class=monster>Plant&nbsp;Spider</span>，如果坚持奔跑的话可以只遇敌一次，切勿站着不动，否则就没完没了了……<br />逃跑过程中发生ＣＧ动画。</td></tr>
</table>
<font size=4><a href='#ff9_007'>返回1-7</a></font></div><br>";
echo "<br><a name='ff9_008' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>８.&nbsp;雾之大陆<br /></td></tr>
<tr><th width=60>流程</th><td>逃出森林->莫古之笛->FAQ-><br />雾的大陆->隐藏的危险</td></tr>
<tr><th>重要道具</th><td>Moogle's Flute</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>“我希望她能早点恢复过来……”<span class=character>Vivi</span>担心地说。<br />一行人终于逃出魔之森，现在正坐在一堆篝火旁，焦急地等待着<span class=character>Garnet</span>快点醒过来。在他们不远处，一个小巧的帐篷被搭建在路旁。<br /><span class=character>Steiner</span>还在一旁责怪<span class=character>Zidane</span>的时候，这时公主已悄悄转醒：“……<span class=character>Steiner</span>……我还活着？是你把我救出来的？”<br /><span class=character>Steiner</span>刚要表彰自己的英勇，<span class=character>Zidane</span>却在一边将事实告诉了<span class=character>Garnet</span>。她听了很感激。<br />“那只猴子没资格受到赞扬！要不是你把公主绑架出来，这一切根本不会发生！”<span class=character>Steiner</span>反驳道。<br />“<span class=character>Steiner</span>……我是自愿离开城堡的，正巧碰上<span class=character>Zidane</span>打算诱拐我是个巧合。”<span class=character>Garnet</span>向他解释说。<br />明白这一切发生的前因后果，<span class=character>Steiner</span>又和<span class=character>Zidane</span>为是尽快离开还是暂时休息争论起来。最后当然是以<span class=character>Steiner</span>尽职尽责地去负责守夜而大家暂时休息告终。</td></tr>
<tr><td>翌日清晨，<span class=character>Zidane</span>走到被石化的森林的前，看着石头般的树藤组成的墙壁，想起为救自己而被困的<span class=character>Blank</span>，不由得感到十分的难过。<br />“谢谢你给的药，我感觉好多了。”<span class=character>Garnet</span>从后面走来，她现在看样子已经完全康复了，“这里是……”<br />“我也很奇怪，当我们打倒那个巨大的植物之后，整个森林都被石化了。”<br />“<span class=character>Vivi</span>告诉我说多亏了你的朋友我们才能脱险，我们必须去救他，我不能……”<br />然而<span class=character>Zidane</span>打断了她的话：“但我们现在什么都做不了，我们会回来救他的，肯定有能救他的方法。现在我们先走吧，根据<span class=character>Blank</span>给我的地图，南方有个洞窟，我们能穿过那个洞窟来避开雾的干扰。”<br />他转身来到<span class=character>Garnet</span>的面前，后者把头低了下去，<span class=character>Zidane</span>问她：“你还好吗？一切都会好起来的的，相信我。”</td></tr>
<tr><td>两人回到营地，<span class=character>Vivi</span>已经起来了，<span class=character>Steiner</span>还在打呼噜。远处，飞来了一只<span class=other>Moggle</span>——<span class=other>Monty</span>。<br /><span class=other>Monty</span>：“你们给我留下了很深的印象，我第一次见有人从魔之森逃出来，你们一定都很强，但不要过于自信， 前面还有更强大的怪物。在你们探索世界前，<span class=other>Mogster</span>将教你们一些东西。”发生ＡＴＥ事件。<br />先回到魔之森这边，<span class=other>Monty</span>送给我们一支<span class=item>Moogle's&nbsp;Flute</span>，之后就可以在大地图上按□来召唤<span class=other>Moguo</span>很方便地休息或者存档了。<br />做完这一切后救上路吧！走之前<span class=character>Zidane</span>一巴掌拍醒了依然站着打着呼噜的<span class=character>Steiner</span>，不明所以的<span class=character>Steiner</span>左右看了半天才反应过来跑着向众人追去。</td></tr>
<tr><td>走出魔之森后来到大地图上，<span class=location>Mist&nbsp;Continent</span>几个字显现在屏幕上。大地图是可以遇敌的，这里的敌人有<span class=monster>Mu</span>、<span class=monster>Python</span>和<span class=monster>Goblin</span>。另外还可以按“<span class=choose>Select</span>”键查看<span class=character>Blank</span>送给我们的地图，地图上的白点表示城镇或洞窟等地方，移动手指指向它们便会出现地名，按“<span class=choose>L1、R1</span>”自动切换地点。<br />先别急着去<span class=location>Ice&nbsp;Cavern</span>，一路向西走，可以到达<span class=location>North&nbsp;Gate</span>。<br />这里靠路右边最上方的栅栏有个缺口，后面有两个宝箱，分别能拿到<span class=item>Eye&nbsp;Drops</span>和<span class=item>Potion</span>，去大门口对话，多说几次后可以买到<span class=item>Potion</span>，看情况补给一下吧。<br />然后动身前往<span class=location>Ice&nbsp;Cavern</span>吧，就在魔之森的南面。</td></tr>
<tr><td>“你听过冰之洞窟吗？”<span class=character>Vivi</span>问<span class=character>Zidane</span>。<br />“当然听过，不就是这里吗？”说着说着，一行人已经到了地方。阵阵的寒气从洞里涌出，洞口的岩层都覆盖上了一层薄冰。这里的ＢＧＭ很好听，敲击乐器模仿出水滴溅到冰上的声音，使人有种身临其境的感觉。<br /><span class=character>Vivi</span>：“我想是这里，我爷爷曾和我谈起过这地方，他说这洞窟能把旅行者带到雾的最高处。”<br />“好极了！<span class=character>Vivi</span>大师的祖父一定是个很有学问的人！逃离雾区之后我们一定要去感谢他！”<span class=character>Steiner</span>恭维说。<br /><span class=character>Vivi</span>低下了头：“我的爷爷曾经教过我许多东西，但是他已经过世了……”<br />“哦……请原谅我的轻率。”<span class=character>Steiner</span>道歉说。<br />“没关系的。”<span class=character>Vivi</span>摇了摇头。<br />“那么，让我们进去吧。”<span class=character>Zidane</span>说。一行人走进洞中，冰封的峭壁上显现出<span class=location>Ice&nbsp;Cavern</span>几个字。接着ＢＧＭ的曲调陡然一转，仿佛暗示着洞里隐藏的危险。</td></tr>
</table>
<font size=4><a href='#ff9_008'>返回1-8</a></font></div><br>";
echo "<br><a name='ff9_009' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>９.&nbsp;冰之洞窟<br /></td></tr>
<tr><th width=60>流程</th><td>冰封莫古->昏迷->黑色华尔兹1号<br />->公主与小刀</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class=tw><tr><td>刚一进入洞窟<span class=character>Garnet</span>立刻就被这冰晶般的世界吸引住了。<br />“哦……多美的地方啊，身临其境的感觉要比从书上读的好多了！”她在一朵兰色的花旁蹲下来，“好美啊……我想知道这是什么花！”<br />“公主，求求你不要碰任何东西！”不识趣的<span class=character>Steiner</span>又来打扰她的兴致。<br />“我们可以走了吗？我都快冻僵了。”<span class=character>Zidane</span>从身后走来，向两人说道。<br /><br />图中的宝箱是<span class=item>Tent</span>，需要从左边的台阶跳上去。</td></tr>
<tr><td>在下一个场景中，调查右边的冰壁，<span class=character>Zidane</span>便会叫<span class=character>Vivi</span>帮忙用用火魔法化开冰层，里面是一个宝箱，装有<span class=item>Ether</span>。之后还有几个像这样的冰壁，可以注意一下。<br /><br />图中<span class=character>Garnet</span>的上方那儿还有一条道路，只不过被挡住看不见而已，从那条路绕过大冰柱便能来到场景左边取得宝箱中的物品<span class=item>Potion</span>。<br /><br />进入下一个场景。</td></tr>
<tr><td>这个场景的右下有两个宝箱，首先拿取台子上面那个，是一瓶<span class=item>Potion</span>。<br />下来后便能烧断那根“天堑冰柱”让其滑落到下面的平台，从而拿到<span class=item>Mage&nbsp;Masher</span>。<br />左上方还有一面大冰壁可以融掉，里面是<span class=item>Elixir</span>，为什么好东西都藏得这么深……<br /><br />下个场景还有最后一面冰壁，烧化后绕个弯就能获得<span class=item>Leather&nbsp;Wrist</span>，而右边还有个<span class=item>Phoenix&nbsp;Down</span>。</td></tr>
<tr><td>下面的场景是个三叉路口，右边那条路正冒着阵阵寒气，还是先走左边吧。<br />这条路通到一个山洞，洞中的台子上居然是个——冰封的莫古！？	<span class=character>Vivi</span>上前念动咒语，火炎轻松地就化解了寒冰。<br />“烫烫！”那只<span class=other>Mois</span>叫着跳起来，然而它发现自己已经摆脱束缚，“哦？我又可以动了！谢谢，Kupo！”<br />这只<span class=other>Mois</span>有封信让你帮它送到<span class=location>Village&nbsp;of&nbsp;Dali</span>的<span class=other>Gumo</span>那儿，别忘了。<br />SAVE之后就可以转回走右上方的那条路了。<br /><br />ＡＴＥ事件<span class=choose>：</span>Mogster教学第2课！<br />和上次一样，还是关于游戏的说明，这次多出了状态效应，元素属性和卡牌游戏三个项目，同样能在专题找到相关解释，不再赘述。</td></tr>
<tr><td>极寒的暴风雪迎面刮来，一行人都被冻得快要失去知觉，走在最后得<span class=character>Vivi</span>慢慢地倒向了一个低谷。<br />“<span class=character>Vivi</span>大师，你没事吧？”<span class=character>Steiner</span>一点点移了过去，他刚想看看下面的<span class=character>Vivi</span>如何时，也冻僵掉了下去。<br />“嘿，铁锈！怎么了？动一下啊！”<span class=character>Zidane</span>跳下去踢了他两下，但是<span class=character>Steiner</span>一点反应也没有。	<span class=character>Zidane</span>无奈，只好上来另想办法，可却发现<span class=character>Garnet</span>也昏迷在地上。<br />“我也想睡了……”<span class=character>Zidane</span>再也坚持不住，软倒在地。<br />屏幕转黑，不知道过了多久，一阵悦耳的铃音传来。<br />“那是什么声音……”<span class=character>Zidane</span>挣扎着爬起来问，“那边有人吗？”他一步步地挪出了洞口。</td></tr>
<tr><td>来到山洞这边，面前是一条被冰冻住的瀑布。瀑布上方站着一个黑魔道士，铃声就是从他那儿发出的<br />“你为什么没睡着？”他奇怪了，“你应该已经死了……”<br />“你就是引起这场暴风雪的人？”<span class=character>Zidane</span>问他。<br />“嘿嘿，正是。”他从上面跳下来，显得很轻松的样子，摇摇手中的铃当，仿佛没把<span class=character>Zidane</span>放在眼里。<br /><br />BOSS战：<br />对手为<span class=monster>Black&nbsp;Waltz&nbsp;No.1</span>和他召唤出来的怪兽<span class=monster>Sealion</span>。</td></tr>
<tr><td>战斗结束后，空中传来一个虚无的声音：“虽然你战胜了1号，但是2号和3号还会来夺回公主的！”<br /><span class=character>Zidane</span>想找出是谁在说话，可是周围一个人都没有。<br />“算了，不管这么多了，回去看看其他人怎么样吧。”<span class=character>Zidane</span>转身离去，镜头上移，冰坡的顶端两个小丑正注视着他的背影。<br />回到刚才的洞中，三人已经醒来。显然他们对刚刚的事仍一无所知，为避免引起不必要的慌乱，<span class=character>Zidane</span>对其他人隐瞒了刚刚所发生的一切。<br />一行人整理完毕继续前行，冰之洞窟的出口就在刚才两个小丑呆的冰坡上。潺潺的溪水从洞外流进，汇集成一道美丽的瀑布。啊，洞外的风景果然怡人，明媚的阳光照耀着碧绿的大地，远处的山丘上漂浮着一朵朵白云。</td></tr>
<tr><td>“那边有个镇，我好象去过的。”<span class=character>Zidane</span>看着远处说。<br />一听有个小镇，<span class=character>Garnet</span>立刻就要动身：“那我们还等什么，快走吧！”<br />“等等，你是个公主！不能就这样去那里，有人在找你，你需要一个新的身份。”<span class=character>Zidane</span>叫住<span class=character>Garnet</span>说。<br /><span class=character>Steiner</span>自然又开始谴责<span class=character>Zidane</span>的想法，两人争论了一番，最后<span class=character>Garnet</span>发表自己的意见。<br />“停下，你们两个……<span class=character>Steiner</span>，我不打算回城堡。我同意<span class=character>Zidane</span>的观点，我需要个新名字……”她捡起刚刚<span class=character>Zidane</span>掉落的匕首，看了看说：“这个叫做‘小刀’……我决定了，我就叫<span class=character>Dagger</span>。”<br />“那适合你吗？”<span class=character>Zidane</span>疑惑地说，“好吧，<span class=character>Dagger</span>，现在我们要注意下说话的方式，试着让它听起来更自然些。”<br />他们一边练习，一边走远了。</td></tr>
</table><font size=4><a href='#ff9_009'>返回1-9</a></font></div><br>";
echo "<br><a name='ff9_010' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>１０.&nbsp;达利村<br /><br /></td></tr>
<tr><th width=60>流程</th><td>旅店->劫持->王女->入口</td></tr>
<tr><th>重要道具</th><td>Aries</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>宁静的达利村坐落在<span class=location>Nolrich&nbsp;Heights</span>上，四周除了一座小山之外，其它什么也没有。<br />我们主人公的旅行延伸到这片世外桃源的土地上。先去拜访旁边那座<span class=location>Observatory&nbsp;Mountain</span>脚下的小屋。</span><br />“啊，我的咖啡闻起来真香啊！”屋内的老人手里举着一杯热气腾腾的咖啡，回身对你夸赞说。<br />房间左侧的天花板上吊着一艘迷你飞空艇，当你走进时你的头顶上会出现！号并发现了它。<br />“请问，这个为了纪念第15艘剧场艇的模型，是不是还在继续出售？”<span class=character>Zidane</span>问那老人。<br />“我是在<span class=location>Treno</span>的拍卖会上买得的，不过我现在还有些钱，我真正想要的只是一些稀有的咖啡豆而已。如果你能给我带来一些稀有的咖啡豆，我就把它送给你。”<br />“真的？”<span class=character>Zidane</span>惊喜道。<br />“我从不说谎。让我想想……”老人思考了一下，“我想尝尝<span class=item>Burman</span>、<span class=item>Kirman</span>和<span class=item>Moccha</span>三种咖啡。如果你把它们都找到了，带回来给我。”</td></tr>
<tr><td>离开物见山，让我们走入村庄去看一看。<br />达利村的环境果然静谧之极，几只白鸽安静地落在地上，即使是人走近了也不会惊飞。<br />“哇，好大的风车！”<span class=character>Vivi</span>望着村中的风车显得很兴奋。然而现在可不是观光的时候。<br />“<span class=character>Vivi</span>，旅店在这边！”<span class=character>Zidane</span>说，“让我们先休息一下再说吧，我们还得决定下一步怎么走。”<br />一行人走进旅店后，旁边跑出两个孩子来。<br />“嘿，你看见了吗？”“当然！”两个人小声说着，接着跑开了。屏幕上出现<span class=location>Village&nbsp;of&nbsp;Dali</span>几个字。</td></tr>
<tr><td>“喂，在工作时间睡觉？”<span class=character>Zidane</span>敲敲桌子。趴在柜台前的宿屋老板抬起头来，睁开那睡眼朦胧的双眼。<br />“噢，对……不起。”老板还想说什么，可却突然打住了，他正盯向<span class=character>Zidane</span>的身后看着什么。<br />“嘿，我知道她很可爱，可你这样盯着人家也太不礼貌了。”<span class=character>Zidane</span>回头看看<span class=character>Dagger</span>说。<br />“哦，我不是在看那个年轻姑娘。我只是……”老板解释道，可话刚说到一半又转到别处去了，“房间在那边。请随便用，就像在家里一样。”<br /><span class=character>Dagger</span>还想问她要住在哪里，可<span class=character>Zidane</span>告诉她这里是乡下旅店，没有单间的。<span class=character>Dagger</span>无奈，只好也走进屋里。</td></tr>
<tr><td>“在睡之前告诉我一件事，”<span class=character>Zidane</span>走进屋内问道，“你为什么要离开城堡，<span class=character>Dagger</span>？”<br /><span class=character>Dagger</span>欲言又止，最终才说出她是想逃往邻国<span class=location>Lindblum</span>。然而为什么这么做她却没有告诉<span class=character>Zidane</span>。“我知道了，不管怎样我都会把你送到<span class=location>Lindblum</span>的。”<br />“够了！公主，你不能相信一个贼的话！”身边的<span class=character>Steiner</span>再也忍不住了，“他可能会把你带到更危险的地方，就像魔之森那样！我求求你公主，和我回城堡吧！”“我知道在魔之森没把事情弄好，但我现在脑中没有疑惑。我会用生命保护<span class=character>Dagger</span>的。”<br />“荒谬！我才是保护公主的人，”<span class=character>Steiner</span>打断他的话，“现在是，将来也是，永远都是！”<br />当两人还在争吵时，一旁的<span class=character>Vivi</span>早已忍不住袭来的倦意，躺在床上睡着了……<br />夜间<span class=character>Zidane</span>隐约听到了<span class=character>Dagger</span>在唱歌。早上起来时发现大家都不见了，于是<span class=character>Zidane</span>向外走去。这时发生三个ＡＴＥ。房间两侧能找到<span class=item>Potion</span>和<span class=item>Antidote</span>，外屋的莫古有封信要送给它。</td></tr>
<tr><td><span class=character>Zidane</span>走出房间，一直向上走，<span class=character>Vivi</span>正在前面的角落里不知干什么。和他聊了几句无关紧要的话后，<span class=character>Zidane</span>说：“OK，那么我们得决定接下来应该做什么。我准备去找<span class=character>Dagger</span>和铁锈。你不介意一起在旅店碰头吧？”<br />“好吧，我一会儿去。”<br />“那么，你在看什么？”<br />“没什么，我一直能听见‘咕，咕’的声音。”<br />“那是陆行鸟发出的声音……”<br /><span class=character>Zidane</span>走后，<span class=character>Vivi</span>一个人呆在那想看看什么是陆行鸟。突然，一个人迅速地从后面将他抱住，然后飞快地逃走了。<br />刚走不远的<span class=character>Zidane</span>对这一切丝毫没有察觉。<br />“嗯？不管<span class=character>Steiner</span>了。我想知道<span class=character>Dagger</span>现在在哪里。”<br />再次发生ＡＴＥ。</td></tr>
<tr><td>现在可以自由控制<span class=character>Zidane</span>，在村子里的杂货店进行一下补给吧。不要忘了风车的房间上方有个重要道具：星宫<span class=item>Aries</span>，收集齐13个星宫可以在<span class=location>Treno</span>那里兑换物品。具体的13星宫位置请看<a href=http://www.squarecn.com/ff/zhuanti/FF9/secretevent.htm#11>《十三星宫》</a>。另外在宿屋对面的车轮旁能捡到<span class=item>120Gil</span>。<br /><br />值得一提的是，风车上的宝箱、下面屋子右上方的门、开门的<span class=item>Mayor's&nbsp;Key</span>和村长的屋子，都要等到Disk3的卡片大赛时才能开启，而且仅有一次机会，不要忘记。<br />切换场景后会再次发生ＡＴＥ。</span></td></tr>
<tr><td>控制<span class=character>Zidane</span>也走入那间商店，<span class=character>Dagger</span>正在一旁看着什么。<br />“你发烧了还是怎么了，你的脸都红了？”<span class=character>Zidane</span>问她。<br />“没——没什么。”<br />“你的举动好奇怪……噢，我知道了！你在改变说话的方式！<span class=choose>你做的真不赖</span>！”<br />“谢谢！我在演戏时做的不错吧，是吗？”她显得很高兴。<br />“<span class=choose>你当然知道如何作假了</span>！”<span class=character>Zidane</span>可真会哄人，继续谈了一会儿后，他叫<span class=character>Dagger</span>先回旅店去。<br />“谢谢，我很高兴！”临走之前<span class=character>Dagger</span>向店员行了个礼。<br />“她可真是个怪人……”<span class=character>Eve</span>莫名其妙地说。</td></tr>
<tr><td>离开商店后<span class=character>Zidane</span>伸了个懒腰：“我现在该去叫<span class=character>Steiner</span>回旅店了。”走到宿屋房间外的窗子前，可以调查看到屋内的<span class=character>Dagger</span>一个人在那练习说话。<br />“并且把‘我对此表示抱歉’改成‘对不起’，‘我对此表示感谢’改成‘谢谢’……”<br />找了一圈没找到铁锈先生，<span class=character>Zidane</span>也回到宿屋内。<br />继续和<span class=character>Dagger</span>说了一阵子的话，听她讲述平常的王宫生活，可仍然没有等到<span class=character>Vivi</span>和<span class=character>Steiner</span>。<br />“我有个穿过南大门的好计划，很简单的！他们的目标只是你一个人，所以我们只要掩护好你就可以了。”<span class=character>Zidane</span>往后翻了个跟头，“忘了那铁锈吧，一切看我的！”<br />发生ＡＴＥ事件。</td></tr>
<tr><td>画面转回<span class=character>Zidane</span>这边，他们已经聊了很长时间，可还是没等到那两人。<span class=character>Zidane</span>有些担心，于是决定出去寻找<span class=character>Vivi</span>。<br />在<span class=character>Vivi</span>刚才呆的地方，<span class=character>Zidane</span>听见了隐隐约约的哭声。<br />“是<span class=character>Vivi</span>吗？”<span class=character>Zidane</span>发现声音是从地下一根管子里传出来的。通过管子和下面的人一说话，发现果然是的。<br />“……他们叫我呆在这儿的。”<span class=character>Vivi</span>抽泣着说。<br />“不要急，我们就弄你出来不要乱动啊，OK？”<span class=character>Zidane</span>起身四处望了望，“这村庄怎么了？附近应该有到地下的路，让我们找找吧。”<br />可是通往地下的路究竟藏在哪里呢？<span class=character>Zidane</span>盯着转动的风车，脑海中突然涌现出一个地方……</td></tr>
</table><font size=4><a href='#ff9_010'>返回1-10</a></font></div><br>";
echo "<br><a name='ff9_011' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>１１.&nbsp;隐藏在地下的秘密<br /></td></tr>
<tr><th width=60>流程</th><td>发现秘道->孵化黑魔道士的蛋-><br />黑色华尔兹2号->起飞</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class=tw><tr><td>还记得那间风车小屋吗，早先有个人一直靠在一个圆形的仓盖旁，这时已经不见了。走进去调查那个仓盖，<span class=character>Zidane</span>发现那果然是一个秘道……<br />地下的凉风吹到脸上挺舒服的，不过<span class=character>Zidane</span>可没有时间享受这些。在第一个场景的下方有<span class=item>156Gil</span>。<br />“这不就是……就是一个地下储藏室吗？”<span class=character>Zidane</span>走到一间房子附近，上边有只陆行鸟在圈里叫呀叫的。<br />突然，<span class=character>Zidane</span>听见屋子里传出说话声，他连忙叫<span class=character>Dagger</span>不要出声，自己悄悄走上前去。<br />“为什么它会动……你肯定‘它’是村长的兄弟找到的？”一个男人问道。</td></tr>
<tr><td>“我想他们调解过了，他的兄弟现在是我们的成员。”另一个听起来很年轻的声音说。<br />“过去他不是一直站在那个老女人一边吗？”先前那个人继续问，似乎还很不放心。<br />“哦，那么放弃农场的事呢？他说过他的目的仅是和村长作对。可是谁管这些，我们需要的只是更多的人干活。嘿，让我们把这个家伙放到箱子里去。”<br />“我想城堡里的那些家伙会照顾好‘它’的。”<br />“城堡？”<span class=character>Dagger</span>听到这心里不由得咯噔一下。<br />这时房子里的两人押着一个黑魔道士走了出来，那居然是——<span class=character>Vivi</span>！<span class=character>Zidane</span>看见他们要带走他，刚想上前阻止，却被<span class=character>Dagger</span>给拉到一旁。</td></tr>
<tr><td>“你干什么！？”<span class=character>Zidane</span>不高兴地说。<br />“你看见那个棚子边上的大桶了吗？”我在城堡见过和它一样的纹章，这个地方一定和亚历山大有什么关系，我必须知道究竟！所以，我求你了，不要惹上任何麻烦……”<br />面对<span class=character>Dagger</span>的请求，<span class=character>Zidane</span>只好答应。<br />小屋内有个<span class=item>Potion</span>，对面有个<span class=item>Eye&nbsp;Drops</span>。在下一个场景，高处有两个宝箱，其中一个可以从旁边的箱子跳上去拿，另一个被吊着，拉下那个滑轮就行了。两个各装着<span class=item>Ether</span>和<span class=item>Potion</span>。左侧的木桶里藏着一只莫古<span class=other>Kumop</span>，它会求你把信送到<span class=location>Lindblum</span>的<span class=other>Mogki</span>那儿。<br />下一个场景还有两个箱子：<span class=item>Iron&nbsp;Helm</span>和<span class=item>Leather&nbsp;Wrist</span>。</td></tr>
<tr><td>来到一个机器轰鸣的房间，在那里<span class=character>Dagger</span>听到有人哭。<br />“<span class=character>Vivi</span>？”<span class=character>Zidane</span>发现哭声是从一个箱子发出来的，确认是他后，“等下再说吧，我就弄你出来！”<br />画面转黑，<span class=character>Vivi</span>从箱子里被救出来。<br />“在你离开后，几个人绑架了我并带到这里，”<span class=character>Vivi</span>低着头说，他们让我呆着，我很害怕，我不知道该做什么……他们问我‘你为什么出去了’，然后又说‘货船还没有来’。我不知道他们在说什么，所以什么都没讲。之后他们又说，‘把它放到今天的那趟船去吧’。”<br />“听着，Vivi。下次遇到这种事你该做点什么，你应尝试尖叫什么的，”<span class=character>Zidane</span>教导他说，“比如……‘放开我，你们这些人渣’，它可以吓倒对手并鼓起你的勇气。”</td></tr>
<tr><td>汇合后继续前行，上方门的旁边有<span class=item>95Gil</span>。<br />右边有个古怪的机器，它似乎在不断地“造蛋”。<br />“那是……蛋吗？这台机器是在……制造蛋？”<span class=character>Zidane</span>奇道，“这不是雾的引擎，可是却有雾从里面出来……”<br />调查门并选择“打开”会发生强制战斗，对手是3个<span class=monster>Ghost</span>，并不难解决。<br />门内还能发现许多机器，看起来是给外边的那台机器输送雾的能源的，而那些蛋究竟是做什么的呢？<br />三个宝箱里各是<span class=item>Phoenix&nbsp;Down</span>、<span class=item>Potion</span>和<span class=item>Phoenix&nbsp;Pinion</span>。</td></tr>
<tr><td>顺着机器的传送带，我们进入下一个场景。这里一个陆行鸟正在一个筒内奔跑着，从而带动传送带前进。<span class=character>Zidane</span>从蛋内能听到一些声音，仿佛就要孵化了……<br />“啊～这是什么！？”<span class=character>Vivi</span>在前面突然叫起来。<span class=character>Zidane</span>追了上去，不禁也惊呆了。<br />那是黑魔道士，一个个蛋全部孵化成了黑魔道士。虽然“它们”和<span class=character>Vivi</span>有一些不同，但还是一眼就能认出来的。<br />“这是什么？他们是木偶吗……”<span class=character>Vivi</span>既惊恐又疑惑。<br /><span class=character>Dagger</span>还在想这幕后的主使是否与自己的母亲相关，<span class=character>Zidane</span>发现身后有人来了，他连忙带着两人躲进了传送带尽头的圆管里。结果三人全被装进了开始<span class=character>Vivi</span>被困的那种木箱里，顺着传送带继续往前运去……</td></tr>
<tr><td>画面转到<span class=location>Observatory&nbsp;Mountain</span>山顶，<span class=character>Steiner</span>正向那位老人打听飞空艇什么时候起飞，而老人根本没有理他。<br />下山跟着老人进屋，没想到他却主动打招呼：“咖啡的香味使我感觉轻松多了，要来一杯吗？”<br />“哦，谢谢你了。”<span class=character>Steiner</span>将咖啡喝掉，“我不是来这里喝咖啡的！告诉我货船什么时候到达，否则亚历山大皇室将没收这快地方！”<br />“你是个没有创造力的询问者。”显然，老人在质疑他的问话方式和态度，而<span class=character>Steiner</span>却像个傻瓜一样继续我行我素。最后，老人扔下一句“他们应该在装货了”，<span class=character>Steiner</span>连忙朝村子的方向赶去。</td></tr>
<tr><td>远远地，<span class=character>Steiner</span>看见飞空艇旁的地面上有什么东西出来。画面转近，原来是两个人用陆行鸟载着一个圆筒，旁边已经堆了许多了。从两人的对话中，可以得知他们也不知道这是在做什么，只是有钱赚何乐而不为呢？接着两人看到凶神恶煞的<span class=character>Steiner</span>跑过来，连忙躲进地下仓库。<br />“这个桶，里面会是什么呢!？”<span class=character>Steiner</span>沉思道，这时他看见桶突然晃了一下，“我看见桶动了一下？让我再看看。”<br />出现两个选项，一个是“<span class=choose>用剑戳一下</span>”，一个是“<span class=choose>再仔细观察一下</span>”。没什么区别，因为马上<span class=character>Zidane</span>等三人就会从桶里跳出来，但选择第一项比较符合铁锈大哥的鲁莽性格，同时也能看到他吓得滑稽的场面。</td></tr>
<tr><td>正当<span class=character>Steiner</span>骗众人说这艘飞空艇是开往<span class=location>Lindblum</span>时，一个黑魔道士迅速地从远处飞来。他飞快地靠近飞空艇，接着如瞬间转移一般出现在我们面前。<br />“公主，女王在城堡等你！”<span class=monster>Black&nbsp;Waltz&nbsp;No.2</span>面无表情地说，“你就是那个打败1号的？我是2号！我的力量、魔法和速度远胜于1号，抵抗是徒劳的！”<br /><span class=character>Dagger</span>当然不会答应他：“不，我不要回城堡！”<br />“跟我走，不然你们会后悔的！”<br /><br />BOSS战，我方4对1，人数占上风。</td></tr>
<tr><td>战术提示：<br />在这一战中，<span class=monster>Black&nbsp;Waltz&nbsp;No.2</span>是不会向<span class=character>Dagger</span>进攻的，这也为我们提供了很大的便利。还有，注意<span class=character>Vivi</span>不要乱用魔法攻击，因为对方受到黑魔法伤害后会用相同的魔法进行反击，因此最好在<span class=character>Zidane</span>偷完东西之前一直蓄力，让<span class=character>Steiner</span>用魔法剑去打它，<span class=character>Dagger</span>用白魔法恢复。<br />可从它身上偷到<span class=item>Steepled&nbsp;Hat</span>和<span class=item>Leather&nbsp;Plate</span>，HP是1030。<br />战斗结束后谈论下目前的行程，即将出现的对话框可以选择“<span class=choose>到旅店休息</span>”或者“<span class=choose>现在就出发</span>”，选前一项的话可以回去休整一下再来飞空艇。</td></tr>
<tr><td>铁锈自告奋勇地到飞空艇上去问是否能搭个便车，<span class=character>Zidane</span>随后让<span class=character>Dagger</span>不用顾虑那么多直接乘上去。虽然他早已知道<span class=character>Steiner</span>撒谎说这是开往<span class=location>Lindblum</span>的，但他告诉<span class=character>Dagger</span>不用担心，他自有办法。<br />临上前<span class=character>Zidane</span>会发现<span class=character>Vivi</span>一直在为黑魔道士的事默默难过，他会问<span class=character>Zidane</span>“我像他们吗”，选择第二项“<span class=choose>他们仅是人偶而已</span>”安慰一下他吧。<br />搭上飞空艇驶向蓝天吧，可以看见飞空艇起航的精美ＣＧ，还有FF&nbsp;IX中经典的Kuso场面：爬在梯子下面的<span class=character>Zidane</span>不知是不是故意地摸了一下<span class=character>Dagger</span>的屁股……<br />“喔，好柔软……”<span class=character>Zidane</span>邪恶地说。</td></tr>
</table><font size=4><a href='#ff9_011'>返回1-11</a></font></div><br>";
echo "<br><a name='ff9_012' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>１２.&nbsp;空中激战<br /></td></tr>
<tr><th width=60>流程</th><td>转航-&gt;激战-&gt;Vivi的愤怒<br />-&gt;摆脱追击</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class=tw><tr><td>爬上飞空艇的船尾，<span class=character>Zidane</span>开始为刚刚的行为辩解：“好了好了，我刚才不是故意的。”<br />“请你不要在说了，”<span class=character>Dagger</span>转向<span class=character>Vivi</span>，“我们进去吧。”说着，她拉着<span class=character>Vivi</span>进入了船舱，却把<span class=character>Zidane</span>关在了门外。<br />“看来她依然不是很相信我。”<span class=character>Zidane</span>这样想。突然，<span class=character>Dagger</span>又跑了出来，很焦急地把<span class=character>Zidane</span>拉进去。<br />船舱内，村子里制造出来的那些黑魔道士正操作着飞船的航行。<span class=character>Vivi</span>正在尝试和他们沟通，但不管如何努力这些黑魔道士就是不说一句话，甚至好象没看到他一样。最后的无功而返让<span class=character>Vivi</span>十分沮丧。<br />“<span class=character>Vivi</span>，我要上去一会儿，在它到达城堡之前我要掉转船头，”<span class=character>Zidane</span>又对<span class=character>Dagger</span>说，“照看好他，OK？”<span class=character>Zidane</span>顺着尽头的楼梯爬到甲板上。</td></tr>
<tr><td>“我做了什么…我无法相信公主没来飞空艇就起飞了！我要怎么和<span class=character>Brahne</span>女皇交代呢？”甲板上，<span class=character>Steiner</span>正在那哭天喊地。<br />“你在干什么呢，怎么没等我们就让飞空艇起飞了？”<span class=character>Zidane</span>走到他身后说。<br />“那是因为，这里的人员……”，<span class=character>Steiner</span>突然意识到什么，立刻跳了起来，“什么，你……公主在哪！”<br />在得知公主也在艇上后<span class=character>Steiner</span>仿佛变了个人似的：“这船是返回亚历山大的，你将会因诱拐公主而被吊死！趁现在好好享受自由吧！”他大声宣布着。<br /><span class=character>Zidane</span>没有理会他，独自向驾驶室走去，只留下<span class=character>Steiner</span>一人在那里。不多时，飞空艇突然震动了一下。</td></tr>
<tr><td>画面回到驾驶室，<span class=character>Zidane</span>正在操作飞空艇，一旁的黑魔道士默默地看着他。<br />“你，你，你！”<span class=character>Steiner</span>跑进来，气地直跳脚，但又一时想不出话来诅咒他。<br />“怎么了，你的喉咙被卡住了？”<span class=character>Zidane</span>拿他开心道。<br />“你这白痴，把船开回去！”<span class=character>Steiner</span>上前想抓住他，但每次都被躲开了。几个黑魔道士围了过来。<br />“嘿，我想我们使他们不安了。”<span class=character>Zidane</span>说。<br />“但是之前他们一直都没有反应的啊，是你引起的这麻烦，”<span class=character>Steiner</span>开始向他们解释：“很抱歉，等我把这白痴关起来就转回原来的方向。”<br />黑魔道士们似乎没听见，全部向船头走去。<br />“出什么问题了？”<span class=character>Steiner</span>奇怪道。</td></tr>
<tr><td>船头，<span class=character>Vivi</span>和<span class=character>Dagger</span>正在谈着什么。刚才那个ＣＧ里的黑魔道士突然从天而降，扬手一个闪电球击倒了<span class=character>Vivi</span>。<br />“<span class=character>Vivi</span>！”<span class=character>Dagger</span>跑上前去：“你没事吧？”<br />“原来2号是被你打败的啊，但是你还不配和我抗衡！”那人狂妄地叫嚣说，“公主，在我干掉这些家伙之前你最好乖乖地呆着。”<br />飞空艇上的黑魔道士都走了过来，挡在<span class=character>Vivi</span>的前面。<br />“你们算是保护他吗？愚蠢，你们这些无意识的人偶！你们能做什么啊？”那个黑魔道士叫道，“闪开！你们胆敢和一名黑魔道士较量？”<br />双方发生激烈的混战，那个家伙的魔力明显高出一筹。</td></tr>
<tr><td>“太——太残忍了！”<span class=character>Steiner</span>悲痛地说道。<br />“啊啊啊……”<span class=character>Vivi</span>突然大叫着冲了出去。<br />“<span class=character>Vivi</span>大师，我来帮你！”<span class=character>Steiner</span>也跟了出去。<span class=character>Zidane</span>嘱咐<span class=character>Dagger</span>驾驶好飞空艇后也随后追出。<br />船头，三人和<span class=character>Black Waltz No.3</span>对峙着。<br />“为什么？他们不是你朋友嘛？”<span class=character>Vivi</span>激动地问。<br />“朋友？我看起来像那些愚钝的黑魔道士吗？”<span class=character>Black&nbsp;Waltz&nbsp;No.3</span>露出很古怪的笑容，“不要担心，更多的他们正在被制造。”<br />BOSS战：<br />敌人为<span class=monster>Black&nbsp;Waltz&nbsp;No.3</span>。</td></tr>
<tr><td>战术提示：<br />由于同伴的逝去，另得<span class=character>Vivi</span>异常愤怒。一直被以为是“人偶”的那些黑魔道士在关键时刻保护了他，这让他更坚信这一点：他们是有生命、有思想、有感情的！<br />战斗开始<span class=character>Vivi</span>直接进入<span class=other>Trance</span>状态，这样他每回合便能用魔法攻击2次。这次的魔法攻击不会遭到反击了，放心地狂轰乱炸吧。不过这家伙才1128点HP，要偷东西的还是悠着点吧。<br />在他身上可以偷到<span class=item>Steepled&nbsp;Hat</span>、<span class=item>Linen&nbsp;Cuirass</span>和<span class=item>Silver&nbsp;Gloves</span>。<br />当<span class=monster>Black&nbsp;Waltz&nbsp;3</span>在受到物理攻击后，会进入飞行状态，用2回合全体雷魔法后降下来。这时再用纯物理攻击他是无效的，使用技能攻击吧。</td></tr>
<tr><td>战斗结束后，<span class=monster>Black&nbsp;Waltz&nbsp;No.3</span>丢下一句：“你们这些混蛋……我就是为了杀戮而存在的！”然后飞走了。<br />看着周围的景物，<span class=character>Zidane</span>想：“我看见南大门了…她还是决定去那！”这么想着他向驾驶室走去。<span class=character>Vivi</span>却还在那里看着甲板边挂着的死去同伴的帽子。<br /><br />另一边，<span class=monster>Black&nbsp;Waltz&nbsp;3</span>飞空艇上的2个皇家小丑发现战败了的<span class=character>Black&nbsp;Waltz&nbsp;3</span>向他们飞来，连忙跳出飞空艇。<br />“我只为杀戮而存在……”<span class=monster>Black&nbsp;Waltz&nbsp;3</span>回来后只是这样反复地念着，明显已经失去控制。</td></tr>
<tr><td>画面回到飞空艇上的驾驶室，<span class=character>Dagger</span>掌着舵。<br />“看到南大门了嘛？”<span class=character>Zidane</span>走近来，“那是专为飞空艇设计的巨大通道，可是人为驾驶通过比较困难，要小心一点。而且我们没有获得许可，他们也不会让我们过去。但是这里的防备很松懈，一切都会顺利的，<span class=character>Dagger</span>船长！”<br />“收到！”<span class=character>Dagger</span>顺着他的语气俏皮地说。<br />“我们必须回去！那个黑魔法师正坐着一艘飞船朝我们冲过来！”<span class=character>Steiner</span>突然冲进来，跳着叫喊说，“他可能会撞上我们的！”<br /><span class=character>Zidane</span>听后跑出去看了一眼：“<span class=character>Dagger</span>，锈铁说的没错，他正朝我们冲过来！但我们没办法甩掉它的。我们要在门关上之前把它关在外面，这是唯一的机会！”</td></tr>
<tr><td>逃脱追击之后，飞空艇在雾之大陆上空静静地飞着，附近不时有别的飞空艇慢慢经过。景色是那么得优美，仿佛刚才什么都没有发生过一样。<br />远处，<span class=location>Lindblum</span>正离我们越来越近。<span class=location>Lindblum</span>——这个工业化的大型城市，具有世界上一流的飞空艇设计水平。在飞进城堡的时候我们就能见识到它的雄伟景观，空中穿梭如云的飞艇更是让人感到壮丽之极。<br />镜头越拉越远，巨大的<span class=location>Lindblum</span>在阳光下泛着金色的光辉，一派繁荣的景象。然而此时飞空艇上的<span class=character>Vivi</span>却怎么也高兴不起来。“我和那些黑魔道士……是一样的吗？”他的心中一直缠绕着这个问题。</td></tr>
</table><font size=4><a href='#ff9_012'>返回1-12</a></font></div><br>";
echo "<br><a name='ff9_013' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>１３.&nbsp;巨大城<br /></td></tr>
<tr><th width=60>流程</th><td>大公-&gt;旧识-&gt;参观-&gt;歌声</td></tr>
<tr><th>重要道具</th><td>Kupo&nbsp;Nut<br />Autograph<br />Moogle&nbsp;Suit</td></tr>
</table><table cellspacing=5 class=tw><tr><td>雄伟壮观的<span class=location>Lindblum</span>城内部也毫不逊色，庄严的BGM更是营造出一种尊威的气氛。<br />“在内部建造的船坞！真是太令人惊奇了……即使是女皇陛下的红玫瑰号也能容纳得下！”<span class=character>Steiner</span>一下飞空艇就开始叫，一点骑士的风度都没有。<br />对面走来三个<span class=location>Lindblum</span>的守卫，在<span class=character>Dagger</span>自报家门之后，他们却以怀疑的目光注视着她：<br />“别开玩笑了，哪个皇室家族会让公主独自坐这么简陋的飞船啊。看看你带来的人！”<br />“你胆敢指责公主在说谎？公主是在非常情况下才不得不来这里的！”<span class=character>Steiner</span>气得直跳。<br />“那么向我证明你们是皇室成员吧！”<br />“好吧。”说着<span class=character>Dagger</span>走上前去，把胸前的什么东西给那守卫看了一下。“这是……<span class=item>Falcon&nbsp;Claw</span>！不，有点不一样。”他转头对另一个卫兵说，“快去请<span class=character>Minister&nbsp;Artania</span>大臣来！”</td></tr>
<tr><td>“要不是你那肮脏的白痴样子,他们才不会怀疑我们呢！”<br />“嘿，我可不是那个只会扯着嗓子并穿着肮脏的锈盔甲的蠢货！”<span class=character>Zidane</span>对<span class=character>Steiner</span>的嘲笑毫不留情。<br />当他们还在争吵时，大臣<span class=character>Artania</span>已经到了。<br />“见到你很高兴，公主请跟我走，大公正在等你。”原来<span class=character>Artania</span>认识她，这下好办了。跟随<span class=character>Artania</span>进入一个升降电梯，在乘坐电梯期间<span class=character>Artania</span>为我们介绍了整个<span class=location>Lindblum</span>的情况：它分为哪些区，电梯各通往哪个层。<br />很快地，我们来到最上层的皇宫和议会厅，这里一般是进不来的，然而有<span class=character>Artania</span>领路，自然畅通无阻。<br />进入议会厅后，<span class=character>Dagger</span>礼貌地向王座上行了一个礼。而等她直起身来时，却发现上面根本没有人。</td></tr>
<tr><td>突然，一个古怪而熟悉的声音响了起来，王座背后，一只<span class=other>Oglop</span>探出半个脑袋来。接着，“它”一跳一跳地向<span class=character>Dagger</span>蹦去。<br />“<span class=other>Oglop</span>！”不知是为了凸显自己保护公主的决心，还是上次被捉弄怕了，<span class=character>Steiner</span>上前一拳将“它”击了回去。<br />其余人也都走进来，见到这样一只<span class=other>Oglop</span>都觉得惊讶无比，最后还是<span class=character>Dagger</span>首先认了出来：<br />“我记得那撇小胡子。真的是你吗，<span class=character>Cid</span>舅舅？”<br />“是的，好啊各位&lt;叽咕&gt;我就是<span class=character>Cid&nbsp;Fabool</span>，<span class=location>Lindblum</span>的大公。”<span class=character>Cid</span>自我介绍后向<span class=character>Dagger</span>说道，“和我的<span class=item>Falcon&nbsp;Claw</span>很相似啊，很高兴我又见到了你，<span class=character>Garnet</span>，你真正&lt;叽咕&gt;成长为一位优秀的姑娘了。可我……”</td></tr>
<tr><td>“请允许我解释。”一旁的<span class=character>Artania</span>接着说道，“大约六个月前，有个人潜入城堡并攻击了正在睡梦中的大公。很不幸，我们来迟了一步……大公被变成了一只<span class=other>Oglop</span>，他的妻子<span class=character>Hilda</span>夫人被绑架了……”<br /><br />原来是怎么一回事，明白这些后<span class=character>Dagger</span>想和<span class=character>Cid</span>谈谈关于她母亲的事，<span class=character>Cid</span>从王座上跳下来：<br />“这正是我想要的。但我想最好放到明天再说，大家为什么不先去休息一下？”<br />“午餐时间到了，请跟我来。”<span class=character>Artania</span>再次为我们领路。</td></tr>
<tr><td>画面转黑，时间已是下午，<span class=character>Zidane</span>一人在城里闲逛。他走进一家酒店，和老板很熟悉地打了招呼。<br />“如果不介意的话，你挡着人家的路了？”一位女服务生举着盘子在一旁说道。<br />“哇！”<span class=character>Zidane</span>又开始发挥他的本色，和那MM调侃起来。<br />“喂，长猴子尾巴的，你影响到其他客人了。”柜台边一个穿红衣服的女性不满地说道。<br />“怎么……你也有条尾巴，长耗子脸的。”<span class=character>Zidane</span>回敬。<br />“耗子脸……等我喝完后，就来踢你的屁屁。”她站起身来，却没有过来踢他，“好久不见了，<span class=character>Zidane</span>。”<br />“嘿，怎么回事！？等等……”<br />“你忘了我的名字？”<br />“不，我当然记得。”<span class=character>Zidane</span>说道。在故意说错了几个名字后，<span class=character>Zidane</span>终于叫出了她的真名：“你还好吗，<span class=character>Freya</span>？多久没见面了？”<br />“大概3年了吧。”<span class=character>Freya</span>感慨道。<br />“找到什么关于你男朋友的事了吗？”“没有。”<br />“那么……你来Lindblum有什么打算？”<br />“除了狩猎祭还能有什么？这是个检验我技能的好机会。”<br />他们就这样聊了一下午。</td></tr>
<tr><td>深夜，<span class=character>Cid</span>走进议会厅，<span class=character>Dagger</span>跟在他后面。<br />“那么皇后怎么样了，她还和以前一样健康吗？”<span class=character>Cid</span>问。<br />“是的，可是自从父亲去世后，母亲的举动变得很奇怪。”<span class=character>Dagger</span>向<span class=character>Cid</span>大公说，她发现有可疑人物出现在城堡，因为怕自己的母亲有什么可怕的计划，她才打算乘<span class=location>Lindblum</span>的剧场艇偷偷过来，却没想到正好却有人来诱拐她……<br />“是我干的，是我命令<span class=other>Tantalus</span>诱拐你的。”<span class=character>Cid</span>说，看着<span class=character>Dagger</span>的惊讶表情，他笑了，“我曾答应过你父亲，不管发生了什么事，我都要保护你。亚历山大的动乱已经有一段时间了，但如果我们直接行动的话，可能会爆发战争。因此，我向<span class=character>Baku</span>求助。演戏是进出亚历山大最好的掩护，没人会怀疑到这背后是<span class=location>Lindblum</span>做的。”<br /><span class=character>Dagger</span>随后担心地提起在达利村看到的黑魔道士人偶，<span class=character>Cid</span>说：“我们不会让这事发生的，即使她有一个军队的黑魔道士。只要我们的飞船舰队在，她是无法前进半步的。”<br />在这之后，<span class=character>Cid</span>带着<span class=character>Dagger</span>参观了飞船码头，并告诉她：6个月前这里曾研制出最新的飞空艇——<span class=other>Hilda&nbsp;Garde&nbsp;1</span>，它不需要雾作动力就能飞行。然而有一天，<span class=character>Cid</span>在酒馆遇到一位可爱的女士……结果<span class=character>Hilda</span>将他变成了一只<span class=other>Oglop</span>虫，并乘坐<span class=other>Hilda&nbsp;Garde&nbsp;1</span>离开了。<br />“这真是个讽刺……直到现在她还没有回来……我又致力于研究2号，但进程一直不如人意。变成跳跳虫后我的思维和往常不同了……”<span class=character>Cid</span>的语气显得很低沉而悲哀。</td></tr>
<tr><td>第二天早上<span class=character>Zidane</span>在旅店里醒来。<br />“早上好，”<span class=character>Vivi</span>推门走进来，“<span class=location>Lindblum</span>可真是个繁华的地方啊，我从未见过着么多的人。”<br />“<span class=location>Lindblum</span>总是这样，这里的人们来自世界各地。我甚至都记不起来我第一次为什么来这里，我只知道在这里，我和<span class=other>Tantalus</span>的弟兄们在一起。”<br />“他们仍住在这里吗？”<br />“恩，我们的本部在剧场区，我现在就去那里，你来吗？”<br />“不用了，我想去城里逛逛。”<span class=character>Vivi</span>走出房间。<br />接下来浏览一下整个城市吧，有很多物品和ＡＴＥ都在等你。旅店里的莫古还有一封<span class=character>Ruby</span>给<span class=character>Zidane</span>的信。</td></tr>
<tr><td><span class=location>Lindblum</span>简介：<br />拥有先进的飞空艇设计和驾驶水平及经验的<span class=location>Lindblum</span>王国可是说是整个雾之大陆上最强大的国家之一了。FF系列里飞空艇的老牌代表<span class=character>Cid</span>就是这个国家的大公，也就等于领袖。<br /><span class=location>Lindblum</span>共分为四部分：剧场区、工业区、商业区和城堡。一架小型的飞空艇连通它们，我们可以乘坐它来往于各个地方。</td></tr>
<tr><td>整个商业区相当繁荣，武器装备合成物品店都能买到许多好东西。旅馆里能找到<span class=item>163Gil</span>，广场正中的房子里有<span class=item>Hi-Potion</span>和<span class=item>Echo&nbsp;Screen</span>，合成店里有<span class=item>Silver Gloves</span>。<br />商业区的最下方能出城，想练练级为接下来的狩猎大会作准备还是必需的。<br />在武器店，可以看到墙上挂着的一把大剑，并听到<span class=character>Zidane</span>说出一句很有争议的话：“我记得见过一个头发像钉子一样的家伙就用这种样子的剑。”<br />而“头发像钉子一样的家伙”究竟是不是指FF&nbsp;VII的男主角<span class=character>Cloud</span>，那就不得而知了。</td></tr>
<tr><td>工厂区没什么事发生，入口附近有<span class=item>Leather&nbsp;Wrist</span>，酒吧旁边有<span class=item>Bronze&nbsp;Vest</span>，尽头房间内能有<span class=card>Mimic</span>和<span class=item>Steepled&nbsp;Hat</span>。<br />来到剧场街，先发生一个ＡＴＥ。车站外面的街的下面有127Gil，右下角的画家的房子里有Ore。<br />进入一个钟楼之中，会发生一个ＡＴＥ，之后就能横扫里面的物品了：<span class=item>68Gil</span>、<span class=item>97Gil</span>、<span class=item>282Gil</span>、<span class=item>Mini-Burmecia</span>。<br />走出来再有一个ＡＴＥ，经过最下面的楼梯，可以看到许多人在等一位明星。之后那位明星会钻进一个莫古的大外套内逃出来，追着他到画家的房子里，和他对话便能获得<span class=item>Autograph</span>，还能找到<span class=item>Moogle&nbsp;Suit</span>。</td></tr>
<tr><td>完成一切之后，乘飞空艇来到<span class=location>Lindblum</span>城堡中。在宾客房里，<span class=character>Zidane</span>看见<span class=character>Steiner</span>一个人在那儿。<br />“公主不见了，她应该呆在这的！”<span class=character>Steiner</span>带着哭腔说。<br />“或许她只是出去散散步而已。”<span class=character>Zidane</span>毫不在意地说。<br />然而<span class=character>Steiner</span>却依然多余地担心，罗嗦了半天后，他一人跑去寻找<span class=character>Dagger</span>。<br />房间里有两个宝箱：<span class=item>Glass Armlet</span>和<span class=item>Ether</span>。<br />墙边的莫古<span class=other>Mogki</span>有一封信给他，并且他还会让你把另一封信送给<span class=location>Burmecia</span>的<span class=other>Atla</span>。<br />之后走出宾客房，在走廊上<span class=character>Zidane</span>听见<span class=character>Dagger</span>的歌声从楼上传下来。然而想乘电梯的话必须先经过授权。</td></tr>
<tr><td>究竟怎样才能获得授权呢？<span class=character>Zidane</span>想着这个问题往回走，在宾客房的外面，有一个正在打瞌睡的卫兵。<br />“嘿，快醒醒！”<span class=character>Zidane</span>大声将他叫醒，“我刚才看见个可疑的家伙！”<br />“什么！？哪、哪里！”那个士兵迷迷糊糊地说。<br />“楼上，跟我来。”<span class=character>Zidane</span>将他引进宾客房，只听里面传出一阵拳打脚踢的声音，之后那个卫兵——哦不，是<span class=character>Zidane</span>穿着卫兵的衣服走了出来。<br />“太简单了。”<span class=character>Zidane</span>神奇地走上电梯，来到最上层。<br />这里就是当初会见<span class=character>Cid</span>的地方，不过现在进不去，左转绕过一个蒸汽室去楼顶。</td></tr>
<tr><td>“唱得真不错啊！”<span class=character>Zidane</span>走上前来。<br />“你怎么上来的？这里是禁区。”<br />“呵呵，我就是靠这个生存的。”<span class=character>Zidane</span>有些洋洋得意。<br />“哦对了，你是<span class=other>Tantalus</span>中的一员，这对你来说一定很容易……”<span class=character>Dagger</span>在说这番话的时候语气好奇怪，不过<span class=character>Zidane</span>并没有注意到。<br />“哇，多美的景色……”<span class=character>Zidane</span>看着远处赞道，“嘿，那儿有个望远镜，我们去看看吧！”<br />透过望远镜，可以看到许多我们还没去过的地方。<span class=character>Zidane</span>不停地向<span class=character>Dagger</span>介绍远处的美景，然而她似乎并不热心。<br />“给我看看。”<span class=character>Dagger</span>站到望远镜前，心里却一直在想：<br />“我给大家带来了这么多麻烦……<span class=character>Cid</span>舅舅知道这一切……那就是为什么他让<span class=other>Tantalus</span>带我离开亚历山大的原因……无论怎样努力，我总是落后一步……我好无助啊……”<br />这或许就是我们常说的处在无助中的少女情怀。</td></tr>
</table><font size=4><a href='#ff9_013'>返回1-13</a></font></div><br>";
echo "<br><a name='ff9_014' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>１４.&nbsp;狩猎大会<br /></td></tr>
<tr><th width=60>流程</th><td>比赛-&gt;称号-&gt;救援-&gt;宴会</td></tr>
<tr><th>重要道具</th><td>Master&nbsp;Hunter</td></tr>
</table><table cellspacing=5 class=tw><tr><td>“怎么了？”<span class=character>Zidane</span>似乎发觉了<span class=character>Dagger</span>有些不对劲儿。<br />“<span class=character>Zidane</span>……”<span class=character>Dagger</span>低声说道，“你为什么帮助我来到这里，来到<span class=location>Lindblum</span>……”<br />“我就是想要帮助你，就这么简单，”<span class=character>Zidane</span>很轻松地告诉她，“头儿不同意我的意见，所以最后我退伙了。”<br />“嗯……你们当初是打算怎样诱拐我的？”<br />“我门准备给你服用催眠药，然后诱拐你。”<br />“我想你不需要它了，因为我已经到这里了。嘿，给我一点的话你不介意吧？”之后<span class=character>Dagger</span>又加上一句，“我最近睡不着觉。”<br /><span class=character>Zidane</span>将催眠药交给她，随后又提起了那歌声：“呃……那首歌就是你在达利村唱的吗？那究竟是首什么歌？”<br />“我不知道，我甚至不记得我在哪里学会的。每当我感到悲伤或者孤独的时候就会想唱起它。不知是什么原因，它安慰我并使我不再感到孤独。”<br />“我想它是首神秘的歌，让我再听一遍吧。”<span class=character>Zidane</span>说。<br />动听的旋律再次飘向天空，飘向每一个角落。</td></tr>
<tr><td>画面转到其余几个人，他们在各自为自己的事情忙碌着。<br />“嘿，<span class=character>Dagger</span>，这样如何：我明天如果在狩猎大赛上获得第一，你和我约会怎么样？”<span class=character>Zidane</span>突然跳上台阶说。<br />“那和我有什么关系啊？”<br />“求求你了……”<span class=character>Zidane</span>倒会耍赖。<br />“……好吧。”得到这个回答的<span class=character>Zidane</span>欢天喜地地走了。<br />画面转到另一处场景，一些士兵站在一辆锁住的车子前，他们正谈论着什么节日。从他们口中能听出似乎这个节日似乎有点可怕，每年都有不少人断送性命。这难道就是狩猎大会？突然，锁住的车门被撞了开来，一群野兽冲了出来，士兵们连忙去疏散人群。<br />在另一扇很大的门前，一只巨型的野兽不断地用它那尖利的牙齿撞击门柱，守卫将它放了出来。<br />“今年的‘特典’太完美了，没人能阻止它。”守卫叫道，“去吧，<span class=monster>Zaghnol</span>！”</td></tr>
<tr><td><span class=character>Zidane</span>回到宾客房，发现大家已经等在那里了。<br />“好吧，我们开始吧。”一个守卫向我们说道，他介绍了有关狩猎大赛的条规说明：即12分钟内杀的怪物最多的人，将获得狩猎大师的称号并得到相应的奖赏。<br /><span class=character>Zidane</span>说自己的奖赏希望是钱，<span class=character>Freya</span>要附加能力的物品，<span class=character>Vivi</span>则想得到一张卡片。<br />“OK！”守卫重复了一遍我们的要求，确认无误后说，“活动马上就开始了，你们都从不同的地方出发。<span class=character>Zidane</span>将在剧场街开始，<span class=character>Freya</span>在工业区，<span class=character>Vivi</span>在商业区。”<br />说明一切后，众人纷纷走出房间。控制<span class=character>Zidane</span>前往剧场街吧，狩猎大会就要开始了！</td></tr>
<tr><td>在一处城墙上，可以看到<span class=character>Dagger</span>和<span class=character>Steiner</span>在为<span class=character>Vivi</span>加油。<br /><span class=character>Zidane</span>来到剧场街，狩猎大会倒计时正式开始。这一战无论谁获胜，剧情都是不变的，只是得到的奖品不同而已。狩猎时左上方的数字即倒计时时间，右下角是你目前取得的分数，正上方的字则是谁目前分数排第一。<br />建议先在剧场街和工业区里狩猎，在大约还剩4分钟时，去商业区的最深处，这里将会遇到那只<span class=monster>Zaghnol</span>，它是取得狩猎大会冠军的重要因素。如果想要<span class=character>Zidane</span>赢的话，在与<span class=character>Freya</span>并肩作战时KO了她就行了，反过来就能让<span class=character>Freya</span>获胜。想让<span class=character>Vivi</span>赢就两个人都自杀……</td></tr>
<tr><td>注：狩猎不同怪物获得的分数和最后得到的奖品一览：<div class=excel><span class=monster>Mu</span>－12pts<br /><span class=monster>Trick&nbsp;Sparrow</span>－13pts<br /><span class=monster>Fang</span>－19pts<br /><span class=monster>Zaghnol</span>－80pts<br /><br /><span class=character>Zidane</span>－<span class=item>5000Gil</span><br /><span class=character>Vivi</span>－<span class=card>Theater&nbsp;Ship</span><br /><span class=character>Freya</span>－<span class=item>Coral&nbsp;Ring</span></div></td></tr>
<tr><td>结束后<span class=character>Cid</span>大公为我们颁发奖品。正在这时，一名重伤的<span class=location>Burmecia</span>士兵从外面挣扎着走进来。<br />“请原谅我的擅自打扰……我带来了紧急消息，从我们的国王那里……”他说话已上气不接下气，看样快要不行了。<br />“<span class=location>Burmecia</span>的国王？”<span class=character>Cid</span>暗想不妙，“快继续说。”<br />“我们的国家正被未知的军队侵略，我们几乎顶不住了，请立即增援！敌军看起来像一群戴着尖帽子法师……”<br />“国王和我是故交，我们会立即增援的。”听完<span class=character>Cid</span>所说的话，士兵如负重释般出了口气，再也坚持不住倒在地上。<br />“他已经去了……能坚持这么久已经是奇迹了，我无法相信发生的这一切……”<span class=character>Freya</span>悲伤地说，从外貌上看似乎她和那个士兵是同一族的人。</td></tr>
<tr><td><span class=character>Cid</span>坐回王座，大家围绕在他身旁商量对策。<br />“我们别无选择，撤回驻守边疆的第四巡逻队。”<span class=character>Cid</span>说道，可是这样做的话就会失去对亚历山大的防卫。然而事关紧急，也没有别的办法了。<br />“尖顶帽……可能是黑魔道士，就像<span class=character>Vivi</span>那样？”<span class=character>Freya</span>疑惑地说道。<br />“难道是母亲！”<span class=character>Dagger</span>简直不敢相信这个想法。<br />“我必须走了，我不能坐等增援。”<span class=character>Freya</span>说道，<span class=character>Zidane</span>和<span class=character>Vivi</span>都表示要帮她。<span class=character>Dagger</span>也想去阻止母亲，<span class=character>Zidane</span>拒绝了：“你还没有意识到将来会有多么危险，你可能会被杀的！现在还不是说服你母亲的时候……”<br />“现在不是争论的时候。”<span class=character>Cid</span>停止了两人的争论，<span class=character>Freya</span>继续说：“他说的没错，我们必须立即前往<span class=location>Burmecia</span>，您能打开龙之门吗？”她问<span class=character>Cid</span>。<br />步行去<span class=location>Burmecia</span>从那个门出发是最好的选择，<span class=character>Cid</span>立刻同意了：“在等待大门打开前&lt;叽咕&gt;我们先用餐吧。”</td></tr>
<tr><td>在餐桌上，一行人开始埋头大吃，<span class=character>Dagger</span>则表现得很古怪。不一会儿，<span class=character>Vivi</span>首先感觉不对劲儿：<br />“哦，我太饱了，我现在很困……”他趴在桌旁睡着了。<br /><span class=character>Cid</span>、<span class=character>Freya</span>随后也同样地倒在了一边。<br />“<span class=character>Dagger</span>……？”<span class=character>Zidane</span>晃了几下，看到她默默地站在一旁，仿佛明白了什么，挣扎几下后最终瘫倒在地。<br />“我怎么这么大意！呃，我感觉不对劲……原谅我，公主，我应该先试试有没有毒的……”<span class=character>Steiner</span>哭着说。<br />“不可能，你的盘里没下药。”<span class=character>Dagger</span>一句话立刻让<span class=character>Steiner</span>“活”了过来，“那不是毒，仅是<span class=character>Zidane</span>给我的安眠药。相信我，这不是我原计划的，我必须自己做出决定……别无选择，<span class=character>Cid</span>舅舅不会让我离开城堡的……”她轻轻走到<span class=character>Zidane</span>身边和他告别，“原谅我，<span class=character>Zidane</span>……”</td></tr>
<tr><td>当<span class=character>Zidane</span>等人醒来时，<span class=character>Dagger</span>和<span class=character>Steiner</span>早已不在了，没办法，我们现在只能继续前行。<br />乘电梯来到最底层，坐左边的那辆车来到地龙之门</span>。<br /><br />门口有个商人可以买道具，还有个莫古<span class=other>Moonte</span>，它可以收到来自<span class=other>Stiltzkin</span>的信。<br />出去后我们再次来到雾之大陆上，一切仍显得那么平静。但是这背后，究竟隐藏着什么样的危险？还有<span class=character>Dagger</span>，她为何要那样做？<br /><span class=character>Zidane</span>无时无刻不在被各种各样的事情所困扰着。</td></tr>
</table><font size=4><a href='#ff9_014'>返回1-14</a></font></div><br>";
echo "<br><a name='ff9_015' />
<div id='ff9tw' align='center'><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>１５.&nbsp;新的伙伴<br /></td></tr>
<tr><th width=60>流程</th><td>Quina加入-&gt;陆行鸟挖宝</td></tr>
<tr><th>重要道具</th><td>Moccha&nbsp;Coffee</td></tr>
</table><table class=tw cellspacing=5><tr><td>离开地龙之门，再次来到雾之大陆。一路北上，走不远可以看到一片沼泽——<span class=location>Qu's&nbsp;Marsh</span>。进去后会发现这里就是那莫古教学的ＡＴＥ发生地点。<br />在深处的一片沼泽旁，有一个奇怪的人正在那里念叨着好饿。去上面的水塘旁边抓一只青蛙过来再和她说话。那人会问<span class=character>Zidane</span>要青蛙，在给她命名为<span class=character>Quina</span>后把青蛙交给她。这时<span class=character>Quina</span>的师傅<span class=character>Quale</span>出现把众人带进了沼泽中的房子里。<br />“吃的艺术不仅仅在于捕捉青蛙，”<span class=character>Quale</span>这样<span class=character></span>说着，“世界是很大的，有许多许多食物，你应该出去见识见识，尝尝其他食物。”<span class=character>Quale</span>转向<span class=character>Zidane</span>：“旅行者，带上<span class=character>Quina</span>去了解世界吧！”<br />出现选项，建议选择第一项，这样我方便满足4人了。<br />“为什么不呢？”<span class=character>Zidane</span>摊开手做了个很潇洒的动作。</td></tr>
<tr><td>“怎么了？”临走时<span class=character>Zidane</span>发现<span class=character>Vivi</span>有些异样。<br />“恩…那个人长得很像我的爷爷。”<span class=character>Vivi</span>说，“也许他知道我爷爷的事，我要和他谈谈，<span class=character>Zidane</span>。”<br />两人转头又进入了屋内。<br />“恩，你认识一个叫<span class=character>Quan</span>的人吗？”<span class=character>Vivi</span>问。<br />“不，我不认识那个老顽固，”<span class=character>Quale</span>先是一楞但马上否认掉了，但还是说漏了嘴。<br />“<span class=character>Quan</span>爷爷是有点奇怪，可是……你怎么知道的？”<span class=character>Vivi</span>顿了顿接着说道：“<span class=character>Quan</span>爷爷看起来和你很像……”<br />“当然，我们是一个部落的。”<span class=character>Quale</span>忍不住回答了一句，但马上又不说话了。<br />“你真的不认识他吗？”<span class=character>Zidane</span>显然看出他在说谎。<br />“不！我不认识这个Quan！”<span class=character>Quale</span>仿佛有些生气了。<br />“真的嘛？”<span class=character>Zidane</span>的口气有点嘲讽，“那真糟糕……我们走吧，<span class=character>Vivi</span>。”两人离开了房间。</td></tr>
<tr><td>提示:<br />1.有<span class=character>Quina</span>在队伍里时去沼泽里可以抓青蛙，抓到一定数量会获得各种物品和装备，要记得不时去沼泽里看看。不过不要抓光了，记得留一雌一雄让他繁殖，还有金色青蛙也不要捕捉。<br />辨认方法：看青蛙身上的黑线，雄的比较明显，雌的则基本看不见。<br />2.<span class=character>Quina</span>的青魔法技能是靠吞食怪物获得的，战斗中把怪物打至少于1/4的血后使用<span class=magic>Eat</span>能力既可。这里可以吃到的魔法有：<span class=magic>Aqua&nbsp;Breath</span>，<span class=magic>Frog&nbsp;Drop</span>，<span class=magic>Mighty&nbsp;Guard</span>，<span class=magic>Vanish</span>，<span class=magic>Pumpkin&nbsp;Head</span>，<span class=magic>Limit&nbsp;Glove</span>，<span class=magic>Angel's&nbsp;Snack</span>，<span class=magic>Mustard&nbsp;Bomb</span></span>从商业区下面出去后在森林里吃<span class=monster>Bomb</span>，如果愿意回来这里也能顺便吃到<span class=magic>Lv3&nbsp;Def-Less</span>)。<br />更具体的东西请查阅专题<a href=./ff9_magic2.php>《青魔法》</a>。</td></tr>
<tr><td>出沼泽后一路往东，过一座桥就可以看到路行鸟森林了。这里的相关内容请查看专题<a href=chocobo.htm>《陆行鸟挖宝》</a>。<br /><br />森林的东北方向是<span class=location>South&nbsp;Gate</span>这里最前大门的右边可以找到一个<span class=item>Ether</span>，进来的右边顶头可以到第一个咖啡<span class=item>Moccha&nbsp;Coffee</span>。旁边的泉水可以帮助恢复HP和MP。都拿完了后就向<span class=location>Gizamaluke's&nbsp;Grotto</span>进发吧。</td></tr>
<tr><td>提示:<br />如果这里把路行鸟森林第一次的藏宝图都挖到了的话，就可以挖出藏宝图<span class=item>streamside</span>和<span class=item>between&nbsp;moutains</span>了。</td></tr>
</table><font size=4><a href='#ff9_015'>返回1-15</a></font></div><br>";
echo "<br><a name='ff9_016' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>１６.&nbsp;陷落的通道<br /></td></tr>
<tr><th width=60>流程</th><td>黑魔道士-&gt;遇见小丑-&gt;<br />救助莫古-&gt;离开洞窟</td></tr>
<tr><th>重要道具</th><td>Protection&nbsp;Bell<br />Holy&nbsp;Bell</td></tr>
</table><table class=tw cellspacing=5><tr><td>“不……”在<span class=location>Gizamaluke's Grotto</span>的洞口，<span class=character>Freya</span>发现地上躺着两名士兵。他们才刚死去不久。“快醒醒！起来啊！见鬼！说话啊！”可是无论<span class=character>Freya</span>如何叫喊，他们都不会再站起来了。<br />“哦，天啊……”<span class=character>Zidane</span>走上前来，不禁低呼。<br />“那些黑魔道士！”<span class=character>Freya</span>的目光中充满着愤怒，“他们究竟是谁！”<br />“没什么，你并没做任何事。”<span class=character>Zidane</span>看到<span class=character>Vivi</span>低下头来，安慰他说。<br />“<span class=character>Vivi</span>，他们不是你……”<span class=character>Freya</span>也意识到刚才的话有些过激，她向众人说道，“国王可能有危险，我们快走！”<br />一行人跑入洞窟，而<span class=character>Zidane</span>突然在后面自言自语道：“我敢打赌<span class=character>Dagger</span>没有来过这里……”</td></tr>
<tr><td>山洞的右边有一个躺着的士兵，他交给你一个<span class=item>Protection&nbsp;Bell</span>后就死了。拿起铃铛在门前摇动，门就会开而铃铛则变成碎片。在那人身上还可以拿到一个。<br />进去后碰到两个小丑，不过他们好象把你给淡忘了，打败他们招来的2个黑魔道士后两人惊慌逃走。继续往里走会有一个黑魔道士，干掉他可以获得一个开门的铃铛。然后上台阶开左边的门。进来后拐角的地方可以拿到<span class=item>Bronze&nbsp;Vest</span>，和路尽头的士兵说话又可以拿到一个铃铛，返回下楼梯开最右边的门。<br />来到一个新的场景，要绕一圈才能下去，在圆环路的1点钟方向和7点钟方向分别可以拿到<span class=item>Mythril&nbsp;Gloves</span>和<span class=item>Magus&nbsp;Hat</span>。这里会遇到一种新的怪物：<span class=monster>Lamia</span>，如果之前没有吃到<span class=magic>Lv3&nbsp;Def-Less</span>这里也可以从它身上吃到，另外此怪还是比较强的，小心应付。</td></tr>
<tr><td>绕过一圈来到一个大钟旁，一只莫古正在那里焦急地喊着他的伴侣。<br />“没想到在这里遇到莫古，发生什么了？”<span class=character>Zidane</span>等人走过来问道。<br />“我的老公，他在这个铃铛里困住了！”<span class=character>Mogmi</span>哭泣着，“我们才在这里完婚，然后有几个小丑攻击我们！我好害怕！”。它边说边走近众人，接着它发现了<span class=character>Vivi</span>身上的<span class=item>Kupo&nbsp;Nut</span>。<br />出现选项是否给它果实，选第一项给它。<br />拿到果实的<span class=character>Mogmi</span>高兴地跑去告诉它的伴侣有果实，结果只见那钟震动了两下就给那只莫古从里面掀开了。两只莫古在道了谢后离开了。<br />“好疯狂的一对儿！”<span class=character>Zidane</span>感叹道。</td></tr>
<tr><td>钟内可以拿到一个铃铛，不过它只能开右边的门。进来后发现刚才的两只莫古就住在这里。<span class=character>Mogmi</span>再次向你表示了感谢。记得和<span class=character>Mogta</span>说话时选第一个它会很高兴。这里可以存档和休息恢复，因为接下来是要打BOSS了。<br />离开时<span class=character>Mogta</span>会叫住你，给你一个铃铛<span class=item>Holy&nbsp;Bell</span>，出去进左边的门吧。<br /><div class=excel>提示：<br />1.上边的树藤可以爬上去，不过还是不要上的好，外面会碰到60级的龙。这个树藤是为了方便以后再拿到<span class=item>Kupo Nut</span>来和莫古换东西而设的。<br />2.刚刚有个场景上台阶后的中间的门没开嘛，那门就是通到莫古这个场景的近路，区别只是走中间的不好顺路拿那两个道具了。</div></td></tr>
<tr><td>进门后碰到一个奄奄一息的士兵，<span class=character>Freya</span>跑了上去：“你还好吗？”<br />“<span class=character>Freya</span>……小心……<span class=monster>Gizamaluke</span>已经疯了，它被某些奇怪的意志操纵着……”话音刚落，一只怪物从管道跳进了他们旁边的深水池里。<br />BOSS战：<br />对战怪物为<span class=monster>Gizamaluke</span>，它比较擅长水属性魔法攻击，弱点是雷，其它没什么需要注意的，想轻松点就扔个<span class=item>Tent</span>，等它中了状态后就任君宰割了。从他身上可以偷到<span class=item>Ice&nbsp;Staff</span>、<span class=item>Magus Hat</span>和<span class=item>Elixir</span>。<br />击败BOSS后，我们总算通过了这个洞窟，然而从情势上看，我们来得似乎晚了一步……</td></tr>
</table><font size=4><a href='#ff9_016'>返回1-16</a></font></div><br>";
echo "<br><a name='ff9_017' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tbody><tr><td class=ititle colspan=2>１７.&nbsp;分道扬镳<br /></td></tr>
<tr><th width=60>流程</th><td>闯过关口-&gt;乘上火车<br />	北大门-&gt;模糊的记忆</td></tr>
<tr><th>重要道具</th><td>Gate&nbsp;Pass</td></tr>
</tbody></table><table class=tw cellspacing=5><tbody><tr><td>故事情节叙述到<span class=character>Dagger</span>这一边。<br />南大门前站着两个守卫，<span class=character>Steiner</span>扛着一个大包裹出现在画面里。他想穿过大门，但被守卫拦住了。<br />“给我停下，”守卫问道，“你是来干什么的？我要检查你的行李，照章办事，你是知道的。”<br />“见鬼，我必须要做些什么！”<span class=character>Steiner</span>把包裹放在一边，不安地想着。<br />“警方正在搜寻一个女孩及一名中年男子，”守卫继续说道，“那个女孩据说很像<span class=character>Garnet</span>公主。”<br />“恩，这是什么！？”检查包裹的守卫插话道，“那些是……腐烂的东西！它们是毒药吗！？”<br />“腐烂？我可没带任何已经烂了的东西……”<span class=character>Steiner</span>努力装出一脸惊讶的表情。<br />“哦！这是<span class=location>Lindblum</span>的特产，我不敢相信你竟带了这么多！”<br />“它是我的最爱！没有它们我可活不下去。”<br />“恩，喜欢它的人都这么说。”从话语可以听出他似乎也很喜欢那种特产，“你可以通过了。”守卫让开了道路。</td></tr>
<tr><td>为了让公主有能出来的空间需要把右边的两个人劝说离开。先和那个女的谈话选第一项，她就会离开。然后去左边和工人说话，再来和右边下面的男人说话选择第一项，这样附近便没人了。<br />这个场景的左下角可以拿到<span class=item>Multina&nbsp;Racket</span>，车上的宝箱现在还拿不到。先往右上走去。<br />刚刚靠近门口却被守卫叫住了，<span class=character>Steiner</span>吃了一惊，原来是好心的守卫要给他<span class=item>Gate&nbsp;Pass</span>。之后走进过道里。<span class=character>Steiner</span>放下包裹站在通道口把风。这里公主换衣服时会出现个很短暂的选项，分别是“<span class=choose>继续把风</span>”和“<span class=choose>去巡查另一边</span>”，快速选择第二项的话能见到公主受惊的话语。</td></tr>
<tr><td>来到下一个场景，那里有一个莫古。<br /><br />“那辆蒸汽火车会载我们到山顶去。”<span class=character>Dagger</span>说，“我们就快到了，亚历山大就在山后面，不是嘛？我成功了，没依靠<span class=character>Zidane</span>的帮助！”<br />“你从不需要他的帮助，公主。”<span class=character>Steiner</span>对那小子一直都很有意见。<br /><br />这里右边的售票员那里可以补充下药品，左边的箱子里是<span class=item>Potion</span>.下面的<span class=other>Grimo</span>它会让你送信去给<span class=other>Nazna</span>，准备完了就去上车吧。</td></tr>
<tr><td>上车后<span class=character>Dagger</span>找个位置坐下，<span class=character>Steiner</span>则站在一旁。<br />“可以理解，我们从<span class=location>Lindblum</span>开始的一路上非常辛苦，”<span class=character>Steiner</span>又开始赞美公主，“但是你的白魔法帮助我战胜了这么多怪物，是你的坚韧让我们闯过了陆行鸟森林那些怪物的阻挠。最后，你又成功的骗过南大门守卫，我全身心地被你的智慧和勇气所折服了，公主！”<br />“请你不要再叫我那个了……”<br /><span class=character>Steiner</span>抱歉地说：“请原谅我，我只是习惯了……”<br />“没什么，在<span class=character>Zidane</span>教我如何这样说话的时候我也犯了许多错误。”说起<span class=character>Zidane</span>，<span class=character>Dagger</span>的脸上浮现出微笑。<br />“那个乡巴佬太没礼貌了！”一听到<span class=character>Zidane</span>的名字<span class=character>Steiner</span>立刻激动起来，“虽然……他是有一些鬼点子，但是他和你说话的方式太令人难以接受了！我说的是实话！”</td></tr>
<tr><td>画面转回<span class=character>Zidane</span>这边，水池边那个士兵说了句“保护<span class=location>Burmecia</span>”后就垂下了头。<br />“我绝对会保护<span class=location>Burmecia</span>的！”<span class=character>Freya</span>沉痛地说道，接着带头向通道外跑去。<br /><br />出门后不要急着去<span class=location>Burmecia</span>，先往北来到北大门。<br />“烟火的味道，还有血的气息！”<span class=character>Freya</span>皱着鼻子，“门的那一边肯定发生了一场很激烈的战斗……”<br />“一些东西闻起来很不好的样子，我有不好的预感！”<span class=character>Quina</span>跑进来到处闻着味道，“还是花闻起来香！你们来闻闻花！”</td></tr>
<tr><td>“无论什么事，只要是喜欢的，<span class=character>Quina</span>她都会去做。我真应该向她学习学习。”<span class=character>Freya</span>感叹着说。<br />“我不认为她是有意识地去做的。”<span class=character>Zidane</span>说。<br />“如果我能够做我喜欢的事的话，我就不会……”<span class=character>Freya</span>又想起了他的男友，离别让她一直处在痛苦之中。<br />“<span class=character>Zidane</span>，这些花尝起来很好吃！”<span class=character>Quina</span>在一旁叫着。<br />“明白我的意思了吗？”<span class=character>Zidane</span>看着<span class=character>Quina</span>笑了笑。<br />“但是我仍然……”<span class=character>Freya</span>显得有些难过，“算了，让我们走吧！<span class=location>Burmecia</span>就在前面！”<br /><br />这个场景的宝箱里可以拿到<span class=item>Hi-Potion</span>和<span class=item>Tent</span>。</td></tr>
<tr><td>这里的大地图上靠近西北的方向可以遇到一种怪<span class=monster>Nymph</span>，从它身上可以吃到青魔法<span class=magic>Night</span>。<br /><br />在更西北角的海边可以看到有路行鸟的脚印，如果之前有挖到路行鸟地图碎片可以在这里翻开<span class=item>healing&nbsp;shore</span>，从而让路行鸟获得行走浅滩的能力。<br /><br />要做的都做完了就向<span class=location>Burmecia</span>进发吧。就在北大门的西北方向一点。一个被雨笼罩的城市。</td></tr>
<tr><td>“这就是<span class=character>Freya</span>的家乡了……”<span class=character>Zidane</span>望着那残破的大门，有种失落的感觉，“你们在做什么？快过来。”<br />“已经有5年了……我离开这儿也已很久了……”<span class=character>Freya</span>走到门前单膝跪了下来，“没有一晚我不梦到家乡的，我实在不敢相信我现在就在这儿……5年前我还只是个自私的孩子，时间让我成为了一名龙骑士，现在再次为我的国家<span class=location>Burmecia</span>效力！”<br />“我们会尽全力帮你的！”众人鼓励说，“让我们走吧。”<br />一行人跑进城市的街道，屏幕上渐渐出现青之王都的地名。<br />“我还可以为我的国家做些什么？”<span class=character>Freya</span>呆呆地看着残破的街道，“已经没有时间了。”她站起身来。</td></tr>
</tbody></table><font size=4><a href='#ff9_017'>返回1-17</a></font></div><br>";
echo "<br><a name='ff9_018' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>１８.&nbsp;青之王都<br /></td></tr>
<tr><th width=60>流程</th><td>小丑-&gt;故人-&gt;秘议<br />-&gt;女将军-&gt;神秘男子</td></tr>
<tr><th>重要道具</th><td>Cancer</td></tr>
</table><table class=tw cellspacing=5><tr><td>沥沥的雨水无情地滴落在这片宁静的土地上，然而它现在已经不再平静了。血和水混在一起四处流淌，路边到处歪倒着一具具死尸。<br /><br />在我们踏入<span class=location>Burmecia</span>的第一个场景中，有一台翻倒的车子。在它下边仔细找找，可以获得一个重要的星宫道具——<span class=item>Cancer</span>。</td></tr>
<tr><td>“又是他们！真是固执啊他们！”<span class=character>Zorn</span>、<span class=character>Thorn</span>两人出现在上方的窗台前，显然很不欢迎我们的出现，“黑魔道士们！”<br />一声令下，两名黑魔道士跳了下来，和他们发生战斗。<br /><br />胜利之后两个小丑扔下一句“女将军会为此惩罚你们的！她在发怒的时候可是很吓人的！”就离开了。<br /><br />我们当然不以为意，先走左边的门拿两个宝箱<span class=item>Soft</span>、<span class=item>Potion</span>，然后出来上楼梯走有方的门。</td></tr>
<tr><td>这个场景的1楼楼梯处有个<span class=item>Soft</span>，2楼尽头的宝箱是个假的。如果你靠近它便会发生强制战斗，对手便是那个装作宝箱的怪物<span class=monster>Mimic</span>，它会召来一个同党<span class=monster>Magic&nbsp;Vice</span>，<span class=monster>Magic&nbsp;Vice</span>它的拿手好戏便是偷了你的钱后开溜，小心着点。它可以学到青魔法<span class=magic>Magic&nbsp;Hammer</span>。<br />随后进入下一个场景，其中有一扇门，现在是推不开的，没办法，继续往前走。</td></tr>
<tr><td>看到楼梯这边的宝箱了吗，不要急着往前跑，要按住或松开取消键一点一点走过去，这样楼板便不会塌。<br />取得<span class=item>Germinas&nbsp;Boots</span>之后就跑过那楼梯吧，这样才能让楼板落到下一层，铺开道路。如果先跑过来拿箱子的话，楼板落下后便无法过来了……<br /><br />返回最初见到小丑的那个地方重新走左边的门，经过刚铺好的楼梯来到2层，门旁的宝箱还是那个冒牌怪物<span class=monster>Mimic</span>。</td></tr>
<tr><td>门内的房间便是刚才那两个小丑所在的地方，走进窗台选第一项翻到旁边的房子里，一旁倒在地上的士兵坚持着说完最后一句话：“去拿铃铛……在床后面，还有，去皇宫……保护国王，请快点去……”<br /><br />走到床后，在图中所示的位置调查得到<span class=item>Protection&nbsp;Bell</span> 。<br />之后原路返回，来到起初那个推不动的门前，使用这个铃铛便能进去了。<br /></td></tr>
<tr><td>走到一个很长的楼梯通道内，<span class=character>Vivi</span>很担心即将发生的事会对他有什么影响，也许结果就是证明他不是人类……<br />“你是谁！”上边跑下来一个带着家眷的鼠裔族士兵，他充满敌意地望着我们，“你是和那些黑魔道士一起的么！”<br />“不，不是的……”<span class=character>Zidane</span>连忙解释。<br />“你说慌！你身后明明有个黑魔道士在那！”<br />对方越说越僵，眼看就要动手，幸好<span class=character>Freya</span>上来替众人解围，她和那个士兵认识。互相说明情况后，士兵继续带领家眷逃走了，我们则往上走。</td></tr>
<tr><td>来到一个院子内，先进下面一层的门救一个险些被雕像砸着的鼠裔族男子，<span class=character>Zidane</span>劝说他们去<span class=location>Lindblum</span>避难，他们答应了。在以后的剧情中也确实遇到了他们。<br />之后从上面一层左边的门进入，门口两个宝箱是<span class=item>Tent</span>和<span class=item>Phoenix&nbsp;Down</span>。右边尽头的宝箱是……冒牌货……<br />继续前行到一个广场，左边的门内能拿到<span class=character>Freya</span>的专用武器<span class=item>Mythril&nbsp;Spear</span>。右边门内的箱子里放着<span class=item>Lighting&nbsp;Staff</span>。那里还有两只莫古，<span class=other>Atla</span>不仅可以存盘休息寄信，还能从它那买得一些物品。<br /><span class=other>Stiltzkin</span>则可以固定地卖给你一些道具。<br />走出广场，来到一处巨大的雕像前，它已经破碎不堪了，而且堵住前进的去路。</td></tr>
<tr><td>“呃，这很糟糕……”<span class=character>Zidane</span>抱歉地说，“<span class=character>Freya</span>，这样看来，我不认为国王成功逃脱了……”<br /><span class=character>Freya</span>没有说话，此时有三个选项，任意选没有关系，但最后必须选择第二项“<span class=choose>让她单独呆着</span>”。<br />“！！！”<span class=character>Freya</span>似乎发现什么，她纵声一跃跳过雕像直接进入皇宫，“皇宫里有人！你们在等什么，快上来！”<br />“你说的容易……”<span class=character>Zidane</span>感叹着龙骑士的惊人跳跃力，慢慢顺着雕像往上跳，他对<span class=character>Vivi</span>说：“上来。”<br />“呃...好的。”<span class=character>Vivi</span>刚跳上最底层，摔到了。<br />“哦，天啊。我先上来了，试着自己找条路上来，我会在上边等你的。”<br />“等我在皇宫吃完后再后你会合！”<span class=character>Quina</span>说。<br /><span class=character>Zidane</span>最终追上<span class=character>Freya</span>，他们隐藏在石像后面，发现女王和一名女性正站在那儿，那个人就是传说中的亚历山大最强战士——<span class=character>Beatrix</span>女将军。</td></tr>
<tr><td>再次回到现实中，这时一名白发神秘男子走进我们的视线。<br />“我发现这些雨很有诗意。”他这样说道，“雨滴就像在赞美我们的胜利……”<br />“你的黑魔道士让这场征战变得非常简单<span class=character>Kuja</span>。”女王赞美地说，“我现在只关心<span class=location>Burmecia</span>的国王在哪，我们必须照顾好他，以防止这些大老鼠叛乱。<span class=character>Beatrix</span>，为何这么长时间还没好？”<br />“你在浪费你的时间。”	<span class=character>Kuja</span>说道，“当遇到地震时，老鼠们常常会寻找新家。他们现在很可能退到沙漠之树那儿了……所以你看，已经太迟了。国王已经翘起尾巴遛了。”<br /><span class=character>Kuja</span>所说的沙漠之树就是指<span class=location>Cleyra</span>，被风沙魔法包围守护着的幻想之城。<br />“听起来我们遇到麻烦了。”<span class=character>Zidane</span>皱眉道。<br />“那个阴险的人，到底是谁？”<span class=character>Freya</span>问。<br />“不知道，我也没见过。”<span class=character>Zidane</span>刚说完，一个<span class=location>Burmecia</span>士兵冲了上来，准备向女王动手，然而旁边的<span class=character>Beatrix</span>只说出了自己的名字，就把对方镇住了。<br />见情势不妙，<span class=character>Zidane</span>等三人连忙跳了出来，BOSS战。</td></tr>
<tr><td>战术提示：<br />“你必须先对付我们！”<span class=character>Freya</span>转头向那名士兵说道，“我们会处理这儿的，你快去找国王，用你的生命去保护他！”<br />“……谢谢你，Freya。”士兵愣了一下，随即跑开。<br />“哈哈哈……我从未这样被羞辱过。”<span class=character>Beatrix</span>冷酷地笑了起来，“我曾一次单手杀死一百个勇士……对我来说，你们两个还不如一条小虫。”<br />和女将军对战，从BGM就可以听出她的实力有多强大，我方压抑地完全不能出手。这一战主要就是要坚持住，直到她最后使出一招将我方HP全部减为1的绝招，战斗才会以失败告终，如果中途我方被击败，则会GAME&nbsp;OVER……<br />她的身上可以偷到<span class=item>Phoenix&nbsp;Down</span>、<span class=item>Chain&nbsp;Plate</span>、<span class=item>Mythril&nbsp;Sword</span>。应该说，所有对手中女将军是最难偷的一个，很有挑战，试试自己的运气吧。</td></tr>
<tr><td>“多么可笑的弱小，还有谁可以面对我呢？”<span class=character>Beatrix</span>冷笑着看着倒在地上的我们。<br />“走吧，<span class=character>Beatrix</span>。我们必须准备进攻<span class=location>Cleyra</span>。”女王吩咐道，她们随后就离开了，只剩<span class=character>Kuja</span>一人。<br />ＣＧ动画。<br />脚步逼近，<span class=character>Kuja</span>走近我们，眼里露出一种轻蔑的神色。<br />“现在，这儿还有什么？另一只老鼠，还有……”他望向<span class=character>Zidane</span>，似乎有某种神秘联系在他们之间，“嗯，这个家伙可能会造成问题……”<br /><span class=character>Kuja</span>潇洒地转过身，乘上一只银龙飞走了，只剩下倒在地上的四人。<span class=character>Freya</span>无力地抬了下手，可一切都已徒劳了，她失去了伙伴、朋友、国家和自己的爱人，所有所有……</td></tr>
</table><font size=4><a href='#ff9_018'>返回1-18</a></font></div><br>";

//echo "<br><a name='ff9_012' />
//<font size=4><a href='#ff9_012'>返回1-12</a></font></div><br>";
echo "</body></html>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
