<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='font-size: 22px; color: #800000;'>Final</span><span style='color: #800000; font-size: 22px;'> Fantasy IV ( FF4, iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 2-3 爭奪暗之水晶</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納城'><span style='color: #000080; text-decoration: underline;'>艾布拉納城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納城 1F'>
<span style='color: #000080; text-decoration: underline;'>艾布拉納城 1F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納城 2F - 大殿'><span style='color: #000080; text-decoration: underline;'>艾布拉納城 2F &#8211; 大殿</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納城 西塔'><span style='color: #000080; text-decoration: underline;'>艾布拉納城 西塔</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納城 東塔'><span style='color: #000080; text-decoration: underline;'>艾布拉納城 東塔</span>
</a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納城 地下通道'><span style='color: #000080; text-decoration: underline;'>艾布拉納城 地下通道</span></a></span></span><br /> (02) <span style='text-decoration: underline; color: #000080;'><a href='#艾布拉納洞窟'>
<span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟</span></a></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納洞窟 B1'>
<span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟 B1</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>酒神之酒 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納鎮'><span style='color: #000080; text-decoration: underline;'>艾布拉納鎮</span>
</a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納洞窟 密道 1 - 1'><span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟 密道 1 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.4 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納洞窟 密道 2 - 1'><span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟 密道 2 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#艾布拉納洞窟 密道 1 - 2'><span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟 密道 1 &#8211; 2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>赫耳墨斯之靴 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.6 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#艾布拉納洞窟 密道 2 - 2'><span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟 密道 2 &#8211; 2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>替身人偶 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>艾吉加入隊伍</span>
<br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔'><span style='color: #000080; text-decoration: underline;'>巴別塔</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B1'>
<span style='color: #000080; text-decoration: underline;'>巴別塔 B1</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>爆彈碎片 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B2'><span style='color: #000080; text-decoration: underline;'>巴別塔 B2</span></a></span>
</span> ( 地圖獎勵：<span style='color: #800000;'>爆彈右臂 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B3 - 1'><span style='color: #000080; text-decoration: underline;'>巴別塔 B3 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>3.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B4 - 1'><span style='color: #000080; text-decoration: underline;'>巴別塔 B4 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#巴別塔 B3 - 2'><span style='color: #000080; text-decoration: underline;'>巴別塔 B3 &#8211; 2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>紅色獠牙</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B4 - 2'><span style='color: #000080; text-decoration: underline;'>巴別塔 B4 &#8211; 2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>特級恢復藥 x3</span> )<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B5'><span style='color: #000080; text-decoration: underline;'>巴別塔 B5</span></a></span></span> ( 地圖獎勵：聖靈藥 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>遇敵：艾布拉納王、艾布拉納王妃 ( 自動結束 )<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>艾吉學會「水遁」與「雷迅」技能</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：盧比坎特<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B6'>
<span style='color: #000080; text-decoration: underline;'>巴別塔 B6</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.9 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B7'>
<span style='color: #000080; text-decoration: underline;'>巴別塔 B7</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>聖靈藥</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.10 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B8'><span style='color: #000080; text-decoration: underline;'>巴別塔 B8</span></a></span>
</span> ( 地圖獎勵：<span style='color: #800000;'>以太 x2</span> )<br /> (04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城'><span style='color: #000080; text-decoration: underline;'>矮人城</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; <span style='color: #ff0000;'>取</span><span style='color: #ff0000;'>得「露卡的項鍊」</span>( 可開啟封印洞窟入口 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='color: #ff0000;'>
獵</span><span style='color: #ff0000;'>隼號增加飛越岩漿功能</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.3 &#8211; 取得傳繼能力道具：<span style='color: #800000;'>調查</span> ( 以及<span style='color: #800000;'>改造、絕地反擊</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城本次取得條件說明'><span style='color: #000080; text-decoration: underline;'>本次取得條件說明</span></a></span></span><br /> 
(05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#風精靈洞窟'><span style='color: #000080; text-decoration: underline;'>風精靈洞窟</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#風精靈洞窟 B1 - 1'>
<span style='color: #000080; text-decoration: underline;'>風精靈洞窟 第一階段</span></a></span></span> ( B1-1 ~ B3-1 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#風精靈洞窟 B2 - 2'><span style='color: #000080; text-decoration: underline;'>風精靈洞窟 第二階段</span></a></span></span> 
( B2-2 ~ 密室 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#風精靈洞窟 B2 - 3'><span style='color: #000080; text-decoration: underline;'>風精靈洞窟 第三階段</span></a></span></span> ( B2-3 ~ B3-3 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>地圖獎勵：B1 ~ B3 
<span style='color: #800000;'>銀蘋果 x3</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.4 &#8211; <span style='color: #ff0000;'>於洞窟盡頭房間內發現楊</span><br /> (06) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸洞窟'><span style='color: #000080; text-decoration: underline;'>幻獸洞窟</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#幻獸洞窟 B1'><span style='color: #000080; text-decoration: underline;'>幻獸洞窟 B1</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>蘇摩之滴</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸洞窟 B2'><span style='color: #000080; text-decoration: underline;'>幻
獸洞窟 B2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>蘇摩之滴</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸洞窟 B3'><span style='color: #000080; text-decoration: underline;'>幻獸洞窟 B3</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>蘇摩之
滴</span> )<br /> (07) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸鎮'><span style='color: #000080; text-decoration: underline;'>幻獸鎮</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸鎮 地圖1'>
<span style='color: #000080; text-decoration: underline;'>幻獸鎮 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸鎮 地圖2'><span style='color: #000080; text-decoration: underline;'>幻獸鎮 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>7.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#幻獸圖書館'><span style='color: #000080; text-decoration: underline;'>幻獸圖書館</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：阿修羅 <span style='color: #ff0000;'>( 取得召喚魔法：阿修羅 )</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：利維亞桑 <span style='color: #ff0000;'>( 取得召喚魔法：利維亞桑 )</span><br /> (08) 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟'><span style='color: #000080; text-decoration: underline;'>封印洞窟</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟 B1'><span style='color: #000080; text-decoration: underline;'>封印洞窟 B1</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>大地之鼓 x3</span> )<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟 B2'><span style='color: #000080; text-decoration: underline;'>封印洞窟 B2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>紅色獠牙 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.3 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟 B3 上層'><span style='color: #000080; text-decoration: underline;'>封印洞窟 B3 上層</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>藍色獠牙 x3</span> )
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟 B3 下層'><span style='color: #000080; text-decoration: underline;'>封印洞窟 B3 下層</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>藍色獠牙 x2</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
8.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟 B4'><span style='color: #000080; text-decoration: underline;'>封印洞窟 B4</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>白色獠牙 x3</span> )
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#封印洞窟 B5'><span style='color: #000080; text-decoration: underline;'>封印洞窟 B5</span></a></span>
</span> ( 地圖獎勵：<span style='color: #800000;'>終極聖靈藥</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>在水晶之間取得「暗之水晶」</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>
BOSS 戰：惡魔牆<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.7 &#8211; <span style='color: #ff0000;'>凱因離隊</span><br /> (09) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回矮人城'><span style='color: #000080; text-decoration: underline;'>返回矮人城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
9.1 &#8211; <span style='color: #ff0000;'>找矮人王對話</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>9.2 &#8211; 西德將獵隼號加裝鑽頭功能，即可返回地面</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='艾布拉納城'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;' data-mce-mark='1'>艾布拉納城</span><br /> 乘著飛空艇來到地圖西南方的大島嶼上</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span></p>
<p><span style='color: #ff0000;'>1/16 Update: </span>( 補充提醒 – 隱藏召喚獸道具：<span style='color: #800000;'>蛇雞獸</span> )</p>
<p>先補充一下，在艾布拉納城所在的這座大島週邊地圖，可以遇到一種叫「樓陀羅幼雛」的怪物，身上帶有莉迪亞專用的隱藏召喚獸道具：蛇雞獸，剛來到這裡的話不妨試試，或是後期再回來慢慢刷也可以，詳情請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>
<a href='./ff4_hiding_summoning_spells.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 隱藏召喚獸</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-008.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 在島上的右下方，有一座顏色昏暗的城堡，叫做艾布拉納城。這裡有很多的暗道及寶箱 ( 有的會遇敵 )，沒有 BOSS 也沒有強敵 ( 如果你是現在才來的話 )，讓我們把這裡的寶箱先搜刮乾淨吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來第一段路先直走進去 1F 地圖</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-003.png' width='486' height='326' /><br /> <a name='艾布拉納城 1F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納城 1F</span><br /> 這裡的右上方房間有一個寶箱 ( <span style='color: #800000;'>高級恢復藥</span> )，需要從房間的左下暗道通過<br /> 拿完再繼續往上進到 2F</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-004.png' width='486' height='326' /><br /> <a name='艾布拉納城 2F - 大殿'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納城 2F &#8211; 大殿</span><br /> 在 2F 這裡查看地圖會發現 5 個寶箱，但是沒有通道可進去，往前繼續走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來大殿後，先到王座上調查，可以取得一個「<span style='color: #800000;'>忍者經藏</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著往左右兩側各有一個暗道，通往剛剛 2F 的寶箱房間<br /> 左側：<span style='color: #800000;'>獨角獸之角、鬧鐘   </span>右側：<span style='color: #800000;'>金針、小屋、少女之吻</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 然後就回到一開始的外部區域，先走左邊，下樓後往上前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 走到底會進入西塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-009.png' width='486' height='326' /><br /> <a name='艾布拉納城 西塔'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納城 西塔</span><br /> 在西塔的 1F 左右各有一個寶箱，這裡只有右側有暗道能進入<br /> 寶箱：<span style='color: #800000;'>沉睡之劍</span> ( 打開會遇敵：堅鋼巨像、骷髏戰士 x2 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 繼續往前走來到西塔的 2F，右側的兩個寶箱需要從右下暗道繞進去<br /> 寶箱：<span style='color: #800000;'>失語箭、10000 元</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 然後到上方的罐子處，可以發現一個「<span style='color: #800000;'>酒神之酒</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著到左下角落，可以直接往下走，到剛剛 1F 左側的寶箱房間</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進去後竟然是從房間的下面走出來，感覺好詭異XDDDDD<br /> 寶箱：<span style='color: #800000;'>爆彈之魂</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完後就回到外部，換從右邊下去，再往上前往東塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-015.png' width='486' height='326' /><br /> <a name='艾布拉納城 東塔'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納城 東塔</span><br /> 在東塔的 1F 左右也是各一個寶箱，目前只有左側的上方有暗道能繞進去<br /> 左側寶箱：<span style='color: #800000;'>長須豹之須</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 要繼續往上走之前，右上角的花瓶會找到一個「<span style='color: #800000;'>忍者經藏</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 來到 2F 後，入口在左邊 ( 這門設計得也太靠邊了吧&#8230;.XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這裡一共有 4 個寶箱，先拿左邊與中間的兩個，再從右上的暗道繞下來<br /> 寶箱：<span style='color: #800000;'>高級恢復藥 x2、緊急出口、嗜血槍</span> ( 遇敵：拉米亞、長須豹 x2 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完後走回來在上面的罐子會發現一個「<span style='color: #800000;'>赫耳墨斯之靴</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 最後從右邊寶箱上方地面的破洞進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 會下來到剛剛 1F 右側的寶箱 ( <span style='color: #800000;'>銀沙漏</span> )，貼著兩側牆壁走是可以過去拿的<br /> 拿完之後，就往地上的破洞繼續進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-022.png' width='486' height='326' /><br /> <a name='艾布拉納城 地下通道'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納城 地下通道</span><br /> 一下來是個地下通道，先別急著往前，第一個蠟燭就會發現一個「<span style='color: #800000;'>忍者經藏</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著繼續走有三個寶箱，先拿左邊兩個，最後拿右邊的 ( 打開會遇敵 )<br /> 寶箱：<span style='color: #800000;'>以太 x2、銀蘋果</span> ( 遇敵：狂暴食人魔 x3，HP 6812 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完就直接走到底，上了樓梯就會離開這裡，回到大地圖上<br /> 這邊的寶箱就全部拿完了 ( 應該吧XDDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/01-eblan_castle-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='艾布拉納洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納洞窟</span><br /> 在同一個大島的左下角，利用企業號的拖吊功能，吊起氣墊船放在岸邊，接著離開飛空艇，乘坐氣墊船就能來到艾布拉納洞窟 ( 洞窟前能剛好停下氣墊船 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-001.png' width='486' height='326' /><br /> <a name='艾布拉納洞窟 B1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納洞窟 B1</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 地圖獎勵：<span style='color: #800000;'>酒神之酒 x3</span><br /> 取得寶箱：<span style='color: #800000;'>吸血鬼之牙、手裡劍、萬能藥</span><br /> 右上的兩個寶箱均要經過暗道，可參考下面地圖，都拿完就往出口 2 進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-002.png' width='486' height='326' /><br /> <a name='艾布拉納鎮'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納鎮</span><br /> 沒想到在洞窟內竟然有個小鎮&#8230;. ( 感覺有點怪異XD )<br /> 由右至左是：旅店道具店<strong>(3)</strong>、武器防具店<strong>(4)</strong>、洞窟密道入口<strong>(5)</strong>、醫務室<strong>(6)</strong></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在旅店的櫃檯左邊，可以找到一個「<span style='color: #800000;'>忍者經藏</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 醫務室門口的罐子：<span style='color: #800000;'>恢復藥</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 最裡面的壁爐也有一個：<span style='color: #800000;'>恢復藥</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這裡的武器防具看起來都不錯，只是有的之前在巴別塔也有取得一些，如果有需要的話可以準備一下。在此處收集情報後發現這裡是個忍者之國，國家的王子為了保護人民，正從密道要前往巴別塔。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 都準備好就前往密道入口吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-007.png' width='486' height='326' /><br /> <a name='艾布拉納洞窟 密道 1 - 1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納洞窟 密道 1 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>以太、高級恢復藥</span> ( 密道中 )、<span style='color: #800000;'>帳篷</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這裡寶箱超級多XDDDDD，但是你剛進來密道 1 的時候，暫時只能先取得三個寶箱，中間那一個需要走密道進入，拿完後就往出口 7 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-008.png' width='486' height='326' /><br /> <a name='艾布拉納洞窟 密道 2 - 1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納洞窟 密道 2 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>爆彈之魂</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 進來到密道 2，只能先取得最上面的一個寶箱，然後就繼續往下面的出口 8 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-009.png' width='486' height='326' /><br /> <a name='艾布拉納洞窟 密道 1 - 2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納洞窟 密道 1 &#8211; 2</span><br /> 地圖獎勵：<span style='color: #800000;'>赫耳墨斯之靴 x3</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥 x2、小屋、聖靈藥 x2</span> ( 密道中 )<span style='color: #800000;'>、蜘蛛絲、不死鳥之尾 x2、銀沙漏</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 再回到密道 1，上面的寶箱旁邊有暗道，可以繞進去取得另外兩個寶箱，這一段共可以取得 9 個寶箱 ( 有夠多XDDDDD )，拿完繼續往右上角的出口 9 進入 ( 取得地圖獎勵 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-010.png' width='486' height='326' /><br /> <a name='艾布拉納洞窟 密道 2 - 2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>艾布拉納洞窟 密道 2 &#8211; 2</span><br /> 取得寶箱：<span style='color: #800000;'>手裡劍、金針</span><br /> <strong style='line-height: 1.5em;'><span style='color: #ff0000;'>2013/4/7 Update:</span></strong></p>
<p><strong><span style='color: #ff0000;'>( 全地圖 100% 特別注意，很多人最後才發現是這裡沒走完 )</span></strong></p>";
echo "<p><span style='color: #ffffff;'>-</span></p>
<p>這個密道 2 的地圖，很容易會漏掉而在之後未能取得遊戲全地圖 100% 的成就獎勵「<span style='color: #800000;'>寶物獵手</span>」，要特別注意。原因是在<span style='color: #ff0000;'><strong>出入口</strong> <strong>7、8、9 的位置</strong>，<strong>剛進來這裡的時候要「往回走一點點」</strong></span>，否則會沒有走完全部，離開這裡的時候，<strong><span style='color: #ff0000;'>請一定要確認密道 2 有 100% 都走完！</span></strong></p>
<p><span style='color: #ffffff;'><strong>-</strong></span></p>
<p><strong><span style='color: #ff0000;'><span style='color: #0000ff;'>( 最後打完 BOSS 戰，要離開時務必確認有得到地圖獎勵：<span style='color: #800000;'>替身人偶 x3</span> ，這樣就能確認一定有走完這裡的 100% 地圖了 )</span></span></strong></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>第二次來到密道 2，先拿左上的兩個寶箱，然後進入右側的出口 10</p>
<p>( 上面提到的出入口 7、8、9 的位置，剛進來這裡的時候要記得「<span style='color: #ff0000;'>往回走一點點</span>」)</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 裡面有一個儲存點，右側有密道可以取得一個寶箱，打開會遇敵<br /> 取得寶箱：<span style='color: #800000;'>嗜血劍</span> ( 遇敵：堅鋼巨像 x2 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 寶箱前面有個奇怪的石碑，無法調查也沒反應，有人知道這是啥嗎XD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 回到密道 2 繼續往前走，上面的密道可以取得剛剛還未拿到的寶箱<br /> 地圖獎勵：<span style='color: #800000;'>替身人偶 x3</span><br /> 取得寶箱：<span style='color: #800000;'>特級以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 盡頭會遇到盧比坎特與艾布拉納的王子艾吉，也是我們最終五人的最後一員！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 隨後艾吉與盧比坎特進入戰鬥 ( 會自動進行與結束 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 戰鬥結束後，<span style='color: #ff0000;'>艾吉加入隊伍</span> ( 從對話中就能知道這傢伙很沒禮貌XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 繼續往前走就會直接進入巴別塔的 B1，如果不需要準備就前進，若想準備一下也回去休息，或是利用剛剛的儲存點幫艾吉練一下等級&#8230;. ( 35 級實在有點低&#8230;請站後排謝謝 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/02-eblan_cave-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴別塔'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔</span><br /> 從艾布拉納洞窟走出來後，便會直接進入巴別塔外部的走道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 往前走個幾步後，艾吉會施展「穿牆術」，進入巴別塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-002.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>重要提醒：</span></p>
<p>巴別塔 ( 地上部份 ) 也屬於一次性的地圖，走過就沒了，所以<span style='color: #ff0000;'>請特別注意「地圖完成度 100%」及「怪物圖鑑收集」</span>，地圖完成度會關係著最後是否能取得重要的技能道具「<span style='color: #800000;'>寶物獵手</span>」。在塔中有一些寶箱的周圍地圖很容易被忽略掉，因為常常拿了寶箱人就走掉了，結果地圖沒繞完整。<span style='color: #ff0000;'>請確認你在每一個樓層都有拿到地圖獎勵再離開</span>，否則後續若發現沒有拿到「寶物獵手」會很失望，要一個一個去各迷宮找，而巴別塔又不見的情況下&#8230;.只能下一輪繼續了。( 別忘了隨時按下畫面右上角的「地圖」來確認完成的百分比 )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>這是我們第二次來到巴別塔，<span style='color: #ff0000;'>會完成之前沒有走完的 B7 ~ B8 地圖</span>，取得兩次的地圖獎勵。</p>
<p>( 而怪物圖鑑的收集後續會再整理，反正第一輪是無法完成怪物圖鑑 100% 的，就不用太擔心 )<br /> <a name='巴別塔 B1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B1</span><br /> 地圖獎勵：<span style='color: #800000;'>爆彈碎片 x5</span><br /> 取得寶箱：<span style='color: #800000;'>獨角獸之角、銀沙漏</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ff0000;'>1/16 Update:</span> ( 補充提醒 – 隱藏召喚獸道具：<span style='color: #800000;'>爆彈怪</span> )</p>
<p>在這一次來到巴別塔後，可能會在塔中遇到一種怪物：治癒爆彈怪。他身上帶有極低機率掉落的隱藏召喚獸道具 ( 莉迪亞專用的 )：爆彈怪，有要收集全四種隱藏召喚獸的可以在此努力一下，如果打不到的話，後期在月面地表也可以找另一個去打，請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_hiding_summoning_spells.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 隱藏召喚獸</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-004.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> B1 只有單線，拿完兩個寶箱後就往出口 2 進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-003.png' width='486' height='326' /><br /> <a name='巴別塔 B2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B2</span><br /> 地圖獎勵：<span style='color: #800000;'>爆彈右臂 x3</span><br /> 取得寶箱：<span style='color: #800000;'>屠魔斧</span> ( 遇敵：狂暴食人魔 x3 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 中間的寶箱會遇敵，但是一般的雜兵，繼續往出口 3 前進<br /> ( 屠魔斧對巨人有效，是好東西，可讓塞西爾裝備 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-004.png' width='486' height='326' /><br /> <a name='巴別塔 B3 - 1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B3 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>莉莉絲之吻</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一小段只有一個寶箱，拿完後就繼續往出口 4 前進 ( 未走完的地圖後續會走到 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-005.png' width='486' height='326' /><br /> <a name='巴別塔 B4 - 1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B4 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>阿修羅</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 到 B4 路上會取得一個寶箱，再往出口 5 繼續前進 ( 未走完的地圖後續會走到 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-006.png' width='486' height='326' /><br /> <a name='巴別塔 B3 - 2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B3 &#8211; 2</span><br /> 地圖獎勵：<span style='color: #800000;'>紅色獠牙</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一段沒有寶箱，完成 B3 地圖後，出口 6 是儲存點，恢復一下繼續往出口 7 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-007.png' width='486' height='326' /><br /> <a name='巴別塔 B4 - 2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B4 &#8211; 2</span><br /> 地圖獎勵：<span style='color: #800000;'>特級恢復藥 x3</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一段也沒有寶箱，但會完成 B4 地圖，往上面的出口 8 繼續前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-008.png' width='486' height='326' /><br /> <a name='巴別塔 B5'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B5</span><br /> 取得寶箱：<span style='color: #800000;'>10000 元</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 拿完左側寶箱後，走中間的路就會接連進入事件與 BOSS 戰，要做好準備</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 建議事項：<br /> 1. 盡量避免裝備冰屬性武器，例如<span style='color: #800000;'>玄冰槍、冰印劍</span>等等，我是都裝備斧頭類<br /> 2. 而除了武器之外，其他像是鎧甲、頭盔類就建議用冰屬性，可以減少火魔法傷害<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 往前走遇到了艾布拉納王及王妃 ( 艾吉的父母 )，但是兩人似乎已經不是普通的人類，講沒幾句竟然開戰了&#8230;&#8230; ( 自動攻擊即可，他們的攻擊都是普通的火炎而已 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 事件：後來艾布拉納王與王妃恢復了意識，語重心長地離開了，緊接著盧比坎特出現，憤怒的艾吉爆發 <del>成為超級塞亞人</del> 後<span style='color: #ff0000;'>學會了「水遁」和「雷迅」</span>！<br /> ( 接著便會進入 BOSS 戰 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰：<span style='color: #0000ff;' data-mce-mark='1'>盧比坎特</span><br /> HP：<span style='color: #0000ff;' data-mce-mark='1'>25500</span>，弱點：<span style='color: #ff0000;'><span data-mce-mark='1'>冰</span> <span data-mce-mark='1'>( 披風蓋起時 )</span></span><br /> 攻擊：烈炎 ( 全體 )、<span style='color: #ff0000;' data-mce-mark='1'>火焰流 ( 全體傷害約 700~800 )</span><br /> 備註：<span style='color: #ff0000;' data-mce-mark='1'>披風蓋起時會有吸收冰屬性要注意</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 開戰前 BOSS 會幫大家恢復全部 HP/MP &#8230;.人超好XDDDD<br /> 2. BOSS 的披風若受到召喚攻擊，會對自己使用冰魔法，若剛好是打開的就會自損XD<br /> 3. BOSS 本身受到物理攻擊時會反擊 ( 全體烈炎 )，若有冰屬性裝備應該還好<br /> 4. 只要注意「火焰流」全體攻擊傷害較大，如果等級夠的話其實不怕<br /> 5. 其他狀況下 BOSS 幾乎不太會主動攻擊，就等待披風開啟即可<br /> 6. 等披風開啟就立即切換到莉迪亞召喚「希瓦」攻擊，傷害約 6000~6500<br /> 7. 其他輔助的像對 BOSS 放蜘蛛絲，對己方丟加速或赫耳墨斯之靴階可<br /> 8. 若是有人掛點可以對 BOSS 丟個火系魔法，還會幫我們復活&#8230;XDDDDD<br /> 9. 總結，這是一場挺搞笑的 BOSS 戰<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 結束後繼續走 ( 出口 9 ) 之前，記得左右繞一下把 B5 的地圖走完 100%<br /> 地圖獎勵：<span style='color: #800000;'>聖靈藥</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來發現是水晶之間，正高興地要往前拿水晶時&#8230;.掉了下去！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-014.png' width='486' height='326' /><br /> <a name='巴別塔 B6'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B6</span><br /> 掉落後的位置就是 B6，這裡只有一個出口 10，繼續前進吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-015.png' width='486' height='326' /><br /> <a name='巴別塔 B7'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B7</span><br /> 地圖獎勵：<span style='color: #800000;'>聖靈藥</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這裡就是上一次到這裡未走完的 B7，沒有寶箱，往上面出口 11 繼續走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-016.png' width='486' height='326' /><br /> <a name='巴別塔 B8'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴別塔 B8</span><br /> 地圖獎勵：<span style='color: #800000;'>以太 x2</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 右側盡頭有一個寶箱，拿完後再往左進入出口 12</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 出來後發現了一部新型飛空艇，艾吉將它命名為「<span style='color: #0000ff;'>獵隼號</span>」XDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著便可以控制飛空艇，先往東南方飛回去矮人城吧！( 這算偷東西嗎XDDDD )<br /> ( 注意目前這台「獵隼號」只能飛行在一般的地面上，無法穿越地上的岩漿 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/03-the_tower_of_babil-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='矮人城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>矮人城</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 回到矮人城後，先直接前往大殿找矮人王對話，會取得<span style='color: #ff0000;' data-mce-mark='1'>「露卡的項鍊」</span>，這是用來開啟封印洞窟入口的必要物品</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-002-1.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 繼續來到 B1 的醫務室會發現西德在床上<br /> ( 從左側旅店的右上角入口下來後，第一間就是醫務室 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 和西德對話後，說明了現在飛空艇的狀況，西德馬上帶著幾個矮人，東敲敲西打打的，幫獵隼號調整為可以自由地在地底飛行了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著眾人就在西德的床下發現了一封信，原來西德留下的禮物<br /> 然後取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>調查 </span>( 以及<span style='color: #800000;' data-mce-mark='1'>改造、絕地反擊</span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-004.png' width='486' height='326' /><br /> <a name='矮人城本次取得條件說明'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>本次取得條件說明：</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>1. 調查：</span>敵方全體狀態顯示 ( HP/MP、弱點、吸收等 )</strong><br /> 取得條件：巴別塔通過後，回到矮人城與西德對話，在飛空艇改造後取得<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>2. 改造：</span>在戰鬥中改變武器屬性</strong><br /> 取得條件：曾對西德使用過一個傳繼能力道具後，和「調查」一起取得<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>3. 絕地反擊：</span>瀕死時攻擊力加倍</strong><br /> 取得條件：曾對西德使用過兩個傳繼能力道具後，和「調查」一起取得</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在此階段得到的調查、改造也許比較不實用，但「<span style='color: #800000;'>絕地反擊</span>」可就是一個很不錯的技能了，我這裡是推薦給凱因使用，因為凱因可以跳躍攻擊，如果在瀕死狀況下跳躍，除了可以不受攻擊外，也能造成更大傷害！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 另外在艾吉加入隊伍後，我也把<span style='color: #800000;'>吟唱、調查</span>給了艾吉。原因是艾吉在隊伍中比較屬於輔助的功能，行動速度又夠快，無論是唱歌、丟恢復系道具、調查方面都會有很好的輔助效果，推薦可參考。( 當然各位也可自行發揮 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接下來我們可以繼續在地底的地圖逛，往最西北方的洞窟去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/04-castle_of_dwarves-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 提醒事項：<br /> 1. 接下來我們可以先去風精靈洞窟，迷宮內地面佈滿了會損血的液體 ( 強酸？)<br /> 2. 那裡的雜兵幾乎都會各式各樣的狀態攻擊，你想得到的幾乎都有&#8230;&#8230;<br /> 3. 會中沉默、蛙變、失明、中毒、縮小、失血，建議多準備一些恢復道具或解藥<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='風精靈洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>風精靈洞窟</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 風精靈洞窟位在地底世界的西北方角落</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 為什麼我一走進有就有點看到「少年 Pi 的奇幻旅程」的感覺？這裡好像那座食人島啊！而且更巧的是走一走也會失血這樣XDDDDD ( 注意地上的綠色液狀會損血 )，而且這是一個非常煩人的洞窟&#8230;&#8230;</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 那地上會損血的液體有解嗎？當然有，<span style='color: #ff0000;'>請使用羅莎的白魔法「浮空」</span>，進入洞窟後，對全體使用一次，之後在相同地圖只要沒陣亡都能保持飄浮狀態，即可不需擔心地面會損血了。<span style='color: #ff0000;'>( 但進入下一個地圖就要重新施加一次浮空魔法 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-004-1.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 以下的地圖請注意，<span style='color: #0000ff;'>藍色區域就是當前你所在的區域</span>，依照我的順序來走，未在藍色區域內的之後都會走到，不用擔心，只要往我標示的數字方向去即可。<br /> ( 這裡的地圖畫超久&#8230;.畫到快瘋了XDDDDDD )<br /> <a name='風精靈洞窟 B1 - 1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>風精靈洞窟 B1 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>天使之箭、怪獸圖鑑</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 第一段路只能拿到 2 個寶箱，右上在暗道內的目前還拿不到，往出口 2 走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>風精靈洞窟 B2 &#8211; 1</span><br /> 先往左側的出口 3</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>風精靈洞窟 B3 &#8211; 1</span><br /> 取得寶箱 ( B3 )：<span style='color: #800000;'>高級恢復藥、少女之吻、妖精棒</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 拿完寶箱走右側有暗道過去，前往出口 4，下面被一堆寶箱擋住的路是過不去的，不用在這裡嘗試了，等一下可以走到</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-006.png' width='486' height='326' /><br /> <a name='風精靈洞窟 B2 - 2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>風精靈洞窟 B2 &#8211; 2</span><br /> 取得寶箱 ( B2 )：<span style='color: #800000;'>萬能藥、爆彈之魂、3000 元、2000 元、緊急出口、少女之吻、以太</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 這一段路中途的地面全是強酸，會持續損血<span style='color: #ff0000;'>請注意要記得保持浮空</span>，走到盡頭後附近的地上會有一個洞 ( 出口 5 )，可以通到 B3 的右側地圖</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在盡頭處先拿完寶箱，回頭看在附近地上有個洞，就進去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>風精靈洞窟 B3 &#8211; 2</span><br /> 這一段路沒有寶箱，往上走到底的左側有一個暗道，就是通往剛剛一排寶箱擋住的下半部，那邊有一個傳送點 ( 出口 6 )，會通往風精靈洞窟的密室</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 盡頭的傳送點，繼續前進吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'> 風精靈洞窟 密室</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 取得寶箱：<span style='color: #800000;'>紅色獠牙</span> ( 遇敵：夢魔 x4 )、<span style='color: #800000;'>圓月輪</span> ( 遇敵：魔界花、瑪門樹精 x2 )<br /> <span style='color: #800000;'>白色獠牙</span> ( 遇敵：夢魔 x4 )、<span style='color: #800000;'>復仇者</span> ( 遇敵：魔界花 x2 )<br /> <span style='color: #800000;'>美杜莎之箭</span> ( 遇敵：地底蜈蚣 x2 )、<span style='color: #800000;'>藍色獠牙</span> ( 遇敵：夢魔 x4 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 來到一處有 6 個寶箱的小區域，每個寶箱打開都要遇敵&#8230;.超煩的啊XDDDDD<br /> 雖然武器是都不錯，但是每場打下來真的很煩&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 打完之後右側是出口 7，會離開這裡，對，就是要再走一次洞窟&#8230;. ( 煩死了XDDD )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 如果恢復道具不夠了，建議回去矮人城買一下，因為還沒走完咧…<br /> 儲存後再次進入這個變態的洞窟XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-013.png' width='486' height='326' /><br /> <a name='風精靈洞窟 B2 - 3'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>風精靈洞窟 B2 &#8211; 3</span><br /> 再次來到 B2 ( 請參考前面 B1 的路 )，這次請走下面的出口 8</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>風精靈洞窟 B1 &#8211; 2</span><br /> 取得寶箱：<span style='color: #800000;'>精靈之弓、1000 元、小屋</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 出來後有一個儲存點，先走右側暗道拿寶箱，再拿左側寶箱，再進入左下的出口 9</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>風精靈洞窟 B2 &#8211; 4</span><br /> 地圖獎勵 ( B1 )：<span style='color: #800000;'>銀蘋果</span>、地圖獎勵 ( B2 )：<span style='color: #800000;'>銀蘋果</span><br /> 取得寶箱 ( B1 )：<span style='color: #800000;'>北極之風、金蘋果、蘇摩之滴、以太、高級恢復藥</span><br /> 取得寶箱：<span style='color: #800000;'>封魔之刃</span> ( 遇敵：諂媚女巫、諂媚青蛙 x5 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一段可以先走中間的出口 10，會回到 B1 取得 5 個寶箱，並取得 B1 的地圖獎勵，接著再回來走上面暗道取得寶箱 ( 會遇敵 )，最後進入出口 11</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-016-1.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>風精靈洞窟 B3 &#8211; 3</span><br /> 地圖獎勵：<span style='color: #800000;'>銀蘋果</span><br /> 取得寶箱 ( B3 )：<span style='color: #800000;'>聖靈藥</span><br /> 取得寶箱 ( 風精靈家中 )：<span style='color: #800000;'>波動之杖、菊一文字</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 往右下的盡頭走 ( 出口 12 ) 是風精靈的家</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 左側床上會看見楊昏迷不醒，叫他也沒反應。<span style='color: #ff0000;'>( 請確定有對著楊調查過 )</span></p>
<p>後續要等回到地面後，再去法布爾城找楊的妻子拿「<span style='color: #800000;'>愛的平底鍋</span>」回來敲醒他，並會取得傳繼能力道具及召喚魔法。( 抱歉要下篇再說明了，這一篇的篇幅已經太長了XDDDDD )</p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 左側有兩個寶箱，拿完直接往 2F 一直往上走就能離開洞窟 ( 終於走完了&#8230;.. )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/05-sylph_cave-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='幻獸洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸洞窟</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/img_8691.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 幻獸洞窟的位置在地底世界的西南方一個小島上</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/img_8696.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 如果你是照我的進度先去過了風精靈洞窟，再來到這裡的話，除了地面岩漿一樣會耗損 HP 之外，這裡的雜兵會讓你覺得異常輕鬆，因為沒什麼雜兵會放變態的狀態魔法&#8230;..整個就是爽很多啊！<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ff0000;'>和風精靈洞窟一樣，可以使用白魔法「浮空」的狀態來避免地面的岩漿不斷耗損 HP，也別忘了在地圖切換時要再重新加狀態。</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 幻獸洞窟內並沒有儲存點，要通過洞窟後到達幻獸鎮才有儲存點，所以記得還是要在洞窟外先儲存一下，或是準備一些恢復道具備用。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 雜兵的部份就第一個要注意的是這個怪物 ( 名字忘了記，後補 ) 的「地震」全體攻擊，傷害高達 1000 以上！不過&#8230;..如果你還維持著浮空狀態就不用擔心了XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/06-eudemons_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 第二個可能會遇到的是「雷龍」，不過它的「閃電」攻擊傷害不高，大約 500 左右而已，只是他會掉落「<span style='color: #800000;'>黃金髮飾</span>」( 減輕雷屬性攻擊，女性專用 )，機率蠻高的，我遇到兩次都有掉落 ( 黃金髮飾也可以賣不少錢XDDDD )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>另外，雷龍身上帶有「<span style='color: #800000;'>藍色尾巴</span>」，屬於極低機率掉落的珍稀物品，後期可到地面世界的精金洞窟去交換「<span style='color: #800000;'>洋蔥之盾</span>」( 防禦 9 體力+LV/3 防禦力+LV/11，除狂暴外全異常狀態防禦 )，等級不錯的話建議可以在這裡花點時間試試，也許運氣突然就來了XDDDD ( 後期還是可以再回來幻獸洞窟 B2、B3 這裡用<span style='color: #800000;'>報警器</span>叫出雷龍繼續打 )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>( 詳細可參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_weapons.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 尾巴與強力裝備收集</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/06-eudemons_cave-004.png' width='486' height='326' /><br /> <a name='幻獸洞窟 B1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸洞窟 B1</span><br /> 地圖獎勵：<span style='color: #800000;'>蘇摩之滴</span><br /> 取得寶箱：<span style='color: #800000;'>不死鳥之尾、高級恢復藥、以太</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 在右上的小區域左側有暗道 <span style='color: #ff0000;'>( 暗道中也是會損血，記得保持浮空狀態 )</span>，通往左上的區域，把寶箱搜刮完，地圖都走遍後就往左側出口 2 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/06-eudemons_cave-005.png' width='486' height='326' /><br /> <a name='幻獸洞窟 B2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸洞窟 B2</span><br /> 地圖獎勵：<span style='color: #800000;'>蘇摩之滴</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥、小屋</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> B2 的路線很單純，拿完上下兩個寶箱就繼續往出口 3 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/06-eudemons_cave-006.png' width='486' height='326' /><br /> <a name='幻獸洞窟 B3'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸洞窟 B3</span><br /> 地圖獎勵：<span style='color: #800000;'>蘇摩之滴</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥、淬毒斧、菊一文字、不死鳥之尾、怪獸圖鑑</span><br /> <span style='color: #800000;'>守護者</span> ( 遇敵：小惡魔、惡魔騎士 x2 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> B3 的暗道路線還挺長的，有的雖然是捷徑但會漏走到地圖，所以要留意一下地圖的完成度，往最後的出口 4 ( 傳送點 ) 前進，可以傳送到幻獸鎮</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/06-eudemons_cave-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 前往幻獸鎮的傳送點</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/06-eudemons_cave-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='幻獸鎮'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸鎮</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 幻獸鎮這裡也算是一般的城鎮，一樣有旅店、道具店、武器店、防具店等等，可以到處逛一下找人對話搜集情報。<br /> <a name='幻獸鎮 地圖1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>幻獸鎮 地圖1</span><br /> 取得寶箱：<span style='color: #800000;'>以太、怪獸圖鑑、鼠尾巴、6000 元、5000 元</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 傳送到幻獸鎮後，第一個地點就有很多的寶箱，傳送點 5 可以前往第二層地圖，傳送點 6 是是前往另一個有寶箱的房間以及返回地底的傳送點，所以拿完寶箱先往 5 去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #ffffff; text-decoration: underline;'><a href='#top'><span style='color: #ffffff; text-decoration: underline;'> </span></a></span></span><br /> <a name='幻獸鎮 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸鎮 地圖2</span><br /> 來到第二層後，這裡也有各種商店，建議都可以看一下，所賣的物品都不錯，在旅店左側的房間有兩個寶箱與儲存點 ( 旅店住宿費 1200 &#8230;. 黑店 &#8230;.. )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在旅店內的道具店有賣以太了！也有平常買不到的道具，不過以太一個要價 10000 元是怎麼回事&#8230;&#8230;.如果你身懷巨款的話不妨多買一些備用XDDDD<br /> ( 我只買了 3 個以太，加上 10 個赫爾墨斯之靴這樣&#8230;..好窮酸啊XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 旅店左側的房間，有兩個寶箱 ( <span style='color: #800000;'>怪獸圖鑑、不死鳥之尾</span> )，還有一個儲存點，在這裡搭小屋休息就好了，誰要住旅店啊XDDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 寶箱拿完先去跟旁邊的人對話，他會告訴你關於協助找 8 個幻獸小孩的事，也會告訴你有個小孩在綠洲，因為想喝那邊的水&#8230;..</p>
<p>( 8 個幻獸小孩位置可以先參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span> ，後續會另有專題截圖說明 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 出房間前儲存一下，到中間的幻獸圖書館去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-006.png' width='486' height='326' /><br /> <a name='幻獸圖書館'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>幻獸圖書館</span><br /> 在圖書館的書架上有關於召喚獸的一些介紹，逛一圈之後就往左側樓梯下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 來到最下層後，會遇到幻獸王 ( 利維亞桑 ) 與阿修羅 ( 幻獸王之妻 )，先找右邊的阿修羅對話，會發生 BOSS 戰，打完再找幻獸王對話，一樣是 BOSS 戰</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>阿修羅</span><br /> HP：<span style='color: #0000ff;'>20001</span><br /> 備註：<span style='color: #ff0000;'>吸收雷、冰、風、水、火屬性</span> ( 也吃太好了吧XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 阿修羅比較特別的是她會一直幫自己丟康療來回復，並且受到攻擊就會反擊<br /> 2. 沒什麼特別的攻擊，但是反擊的物理攻擊傷害頗高要小心<br /> 3. 先給她減速，並且幫莉迪亞加速，丟個施毒給她試試 ( 沒中就算了 )<br /> 4. 既然她會自己丟回復，那讓羅莎給她吃一個反射魔法就&#8230;變成幫我們回復XD<br /> 5. 她會吸收很多屬性，所以我選擇用莉迪亞召喚「霧龍」攻擊 ( 傷害 4500 左右 )<br /> 6. 羅莎除了看時機回復之外，如果已學到「神聖」也可以攻擊<br /> 7. 另外三人其實要幹嘛都可以&#8230;.單純防御也可以，要快一點的話就一起砍吧！<br /> 8. 基本上這是一場很有母愛的 BOSS 戰XDDDDDD<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>利維亞桑</span><br /> HP：<span style='color: #0000ff;'>30001</span>，弱點：<span style='color: #ff0000;'>雷</span><br /> 攻擊：<span style='color: #ff0000;'>大海嘯 ( 全體水屬性攻擊，傷害約 1000~1200 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. BOSS 一開始就會放一次大海嘯，全體傷害很高要小心<br /> 2. 接著羅莎回復，艾吉唱速度之歌或是恢復之歌 ( 如果有裝吟唱的話 )<br /> 3. 塞西爾丟蜘蛛絲讓 BOSS 減速，莉迪亞召喚拉姆攻擊 BOSS 弱點<br /> 4. 凱因跳躍攻擊大約可有 4000~5000 傷害 ( 我是裝備淬毒斧 )<br /> 5. 莉迪亞的召喚拉姆約有 6000~7000 的傷害，加上凱因跳躍很快就能結束<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 打敗兩個 BOSS 後 ( 第一場打完如果 MP 不太夠可以回去儲存點回復 )，<span style='color: #ff0000;'>莉迪亞可以取得「阿修羅」及「利維亞桑」兩個召喚魔法</span></p>
<p>( 拿完此兩個召喚魔法後，隨時可以返回巴隆城找 <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_part_3_1.php#巴隆城' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>奧丁</span></a></span></span> 對戰，順便偷傳繼能力道具：<span style='color: #800000;'>暗黑</span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完召喚魔法後，先從傳送點 5 返回第一層地圖</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 再從傳送點 6 前往另一個寶箱房間 <span style='color: #ff0000;'>( 這個長得比較不像傳送點，要留意 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 先往上去取得 4 個寶箱：<span style='color: #800000;'>與一之弓、與一之箭、特級以太、聖靈藥</span><br /> 下面的傳送點就可以直接返回地底世界地圖上 ( 幻獸洞窟的洞口 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 離開了幻獸鎮回到地圖後，如果想要再次前往，只要再進入幻獸洞窟，門口會多了一個幻獸鎮的居民，和他對話就可以馬上進入幻獸鎮，很方便喔！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/07-town_of_eudemons-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='封印洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接下來我們就可以繼續前往劇情的主線，封印洞窟。位置在地圖的南方中間偏左，就在幻獸洞窟的右下方不遠處，裡面終於沒有會失血的地面了XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <strong>說明1：</strong><br /> 這裡的雜兵要小心這個「智化奇美拉」的「冰焰」攻擊 ( 全體 )，傷害約有 800~1000 左右，一次遇到兩隻被連放兩次冰焰就會有點慘&#8230;..XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <strong>說明2：</strong><br /> 這裡只要是有門的出入口都會有敵人 ( 狂暴之門 ) 擋路，打敗後才能進入，但每個門只要打敗一次即可重覆進入。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 遇敵：狂暴之門<br /> 攻擊：<span style='color: #ff0000;'>九次元之門 ( 即死攻擊 )</span><br /> 備註：他就只有這一百零一種攻擊而已，而且是單體，所以不用太擔心，在發動前幹掉他就沒事了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <strong>說明3：</strong><br /> 這裡有低機率可以遇到<span style='color: #ff0000;'>「黃龍」</span>，需注意「天雷」的全體攻擊 ( 傷害約 1000 )，另外黃龍身上有四種道具掉落都很不錯，依機率高到低分別是：<span style='color: #800000;'>藍色獠牙、報警器、銀蘋果、黃色尾巴</span>，需要收集物品或是怪獸圖鑑的人可以自行安排</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來到入口後，門口調查需使用矮人王給的<span style='color: #ff0000;'>「露卡的項鍊」</span>開啟大門</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-006.png' width='486' height='326' /><br /> <a name='封印洞窟 B1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟 B1</span><br /> 地圖獎勵：<span style='color: #800000;'>大地之鼓 x3</span><br /> 取得寶箱：<span style='color: #800000;'>怪獸圖鑑、虎徹、以太</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 取得下面的寶箱後，先往右下的出口 2，開門後會先遇敵 ( 狂暴之門 )，打敗進入後可以取得另外兩個寶箱，然後再繼續往左上的出口 3 前進<br /> (<span style='color: #0000ff;'> 藍線處</span>為繩索，接近後會自動攀爬前進 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進入出口 3 後是一小段地圖，有兩個寶箱與另外三個出口 ( 4、5、6 )，上面的 4 和 5 都是空房間，可以打打門怪&#8230;..然後就往右下的出口 6 進入 B2<br /> 寶箱：<span style='color: #800000;'>高級恢復藥、以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-008.png' width='486' height='326' /><br /> <a name='封印洞窟 B2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟 B2</span><br /> 地圖獎勵：<span style='color: #800000;'>紅色獠牙 x3</span><br /> 取得寶箱：<span style='color: #800000;'>怪獸圖鑑、不死鳥之尾、光之劍、光之幕簾、風魔手裡劍、聖靈藥</span><br /> <span style='color: #800000;'>虎徹、黑頭巾</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> B2 的出入口更多，當然&#8230;..每個門一樣還是有門怪要打XDDDD<br /> 各出口如下面說明，逛完之後繼續往出口 13 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 出口 7：空房間<br /> 出口 8：寶箱 ( <span style='color: #800000;'>光之劍</span> )<br /> 出口 9：寶箱 x3 ( <span style='color: #800000;'>光之幕簾、風魔手裡劍、聖靈藥</span> )<br /> 出口 10：空房間<br /> 出口 11：<span style='color: #ff0000;'>儲存點</span><br /> 出口 12：寶箱 x2 ( <span style='color: #800000;'>虎徹、黑頭巾</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著是另一個小房間，取得寶箱 ( <span style='color: #800000;'>以太</span> )，繼續往出口 14 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 下一段路先拿寶箱 ( <span style='color: #800000;'>高級恢復藥、不死鳥之尾</span> )，左側的 15 是空房間，繼續往下面的 16 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-011.png' width='486' height='326' /><br /> <a name='封印洞窟 B3 上層'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟 B3 上層</span><br /> 地圖獎勵：<span style='color: #800000;'>藍色獠牙 x3</span><br /> 取得寶箱：<span style='color: #800000;'>靜寂之鐘</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 拿完右側寶箱，繞完地圖後，可以從中間繩索 ( 藍線 ) 通往 B3 下層<br /> ( 右下角的出口 17 是空房間，但還是有門怪 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-012.png' width='486' height='326' /><br /> <a name='封印洞窟 B3 下層'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟 B3 下層</span><br /> 地圖獎勵：<span style='color: #800000;'>藍色獠牙 x2</span><br /> 取得寶箱：<span style='color: #800000;'>特級以太、特級恢復藥</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 下來後先往右側出口 18 拿寶箱，再往左側出口 19 進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著是一個儲存點，繼續往出口 20 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-014.png' width='486' height='326' /><br /> <a name='封印洞窟 B4'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟 B4</span><br /> 地圖獎勵：<span style='color: #800000;'>白色獠牙 x3</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這裡沒有寶箱，前方左右兩條繩索無法攀爬到底，繞完地圖後就直接往出口 21 去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-015.png' width='486' height='326' /><br /> <a name='封印洞窟 B5'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>封印洞窟 B5</span><br /> 地圖獎勵：<span style='color: #800000;'>終極聖靈藥</span></p>
<p><span style='color: #ff0000;'>補充說明：</span>這個地圖獎勵「終極聖靈藥」<span style='color: #ff0000;'>全遊戲中能正常取得的就只有這一個 </span>( 還想要的話只能從第二輪後的 <span style='text-decoration: underline; color: #0000ff;'><a href='./ff4_hiding_boss.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>隱藏 BOSS 原初巴別巨人</span></a></span><span style='color: #0000ff;'> </span>身上用偷的&#8230;.. )，可以一次完全恢復全員的 HP/MP，但因為只有一個太珍貴了，我想應該沒人會去用它，不過提供一個好處讓大家知道一下，這個終極聖靈藥可以拿去商店賣錢，一個可賣 <span style='color: #ff0000;'><strong>$325000</strong></span>！讓你瞬間變暴發戶&#8230;.XDDDDDDD<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一段地圖也沒有寶箱，繞完後就往出口 22 進入就是水晶之間了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 到了水晶之間往前調查<span style='color: #ff0000;'>取得「暗之水晶」</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 一走出水晶之間，正準備要離開時，突然發現背後有怪物接近了！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>惡魔牆</span><br /> HP：<span style='color: #0000ff;'>99999</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 開戰後 BOSS 會持續朝我方逼進，馬上給 BOSS 放減速 ( 或丟蜘蛛絲 )<br /> 2. 讓三個物理攻擊主力使用狂暴及加速 ( 或酒神之酒、赫耳墨斯之靴 )<br /> 3. 莉迪亞使用召喚魔法進攻，或是高級魔法 ( 如核爆，若有的話 )<br /> 4. 當 BOSS 被魔法攻擊會以徐徐石化來反擊，要立即用金針解除 ( 或其他方式 )<br /> 5. 由於 BOSS 的血蠻厚的，可以要耗上一段時間，硬砍打爆他<br /> 6. 一旦讓 BOSS 接近後會越來越麻煩<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span></p>
<p><span style='color: #ff0000;'>BOSS 戰結束後的重要提醒：</span></p>
<p>接下來要原路走回封印洞窟的入口，請務必記得，<span style='color: #ff0000;'>要回到 B1 入口前將凱因的裝備全部卸下！</span>尤其是玩第二輪的朋友們，如果你讓凱因穿著強力的精金鎧、洋蔥裝備、拿了洋蔥之劍離開，那等最後凱因再次歸隊時&#8230;..你辛辛苦苦在第一輪刷尾巴換的裝備就跟著不見了&#8230;..這樣太悲劇了，請記得扒光凱因啊XDDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>如果真的不小心忘了拆凱因的裝備，可以在劇情進行時按下 Home 鍵，並在多工列完全退出遊戲，再重新開啟遊戲選擇繼續，就能回到劇情之前的最後一個位置，即可補救了。</p>
<p><span style='color: #ffffff;'>-</span><br /> 打敗後要一路往回走到封印洞窟的入口&#8230;&#8230; ( 洞窟內無法傳送&#8230;. )，突然間高貝扎的聲音又出現，結果凱因竟然搶走了暗之水晶，頭也不回的走了！<span style='color: #ff0000;'>( 凱因離隊 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 看來主角們沒有取得水晶的命XDDDDD，沒辦法了，還是再回去矮人城一趟吧！<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='返回矮人城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;'>返回矮人城</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 回到矮人城大殿報告不好的消息 ( 矮人王 OS：這群人怎麼這麼不可靠啊&#8230;. )，矮人王說了關於密西迪亞的傳說，要我們趕緊前往密西迪亞，但是&#8230;.怎麼回去？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這時候西德便出現了，<span style='color: #ff0000;'>幫獵隼號裝上了鑽頭，可以在地面與地底來去自如了！</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著就可以搭乘飛空艇，往地底世界的最東北方去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在這裡會發現一個突起點，飛到上面出現「！」時，再點一下螢幕就能返回地面世界了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 回到地面的位置一樣是在阿加爾特旁。接下來在地面上的世界我們還有不少支線需要去完成它們，但是這一篇的篇幅已經太長&#8230;..下篇繼續吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-3/08-the_sealed_cave-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 
<span style='color: #0000ff;'><strong><span data-mce-mark='1'>FF4 Part 2-3 後記：</span></strong></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一篇在風精靈洞窟和幻獸洞窟的攻略的攻略編寫上花了非常多的時間，因為要找出最適合的行進順序，才能用最快速度通過洞窟，相信大家看著攻略走一定是輕鬆沒有負擔的，一下子就走完了&#8230;&#8230;<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 我比較注重攻略的完整度與進度是否順暢，如果等待比較久的話先說聲抱歉，也感謝很多高手幫忙回覆解答一些網友的疑問。( 只是進度跑太快的朋友如果錯過了什麼，就會比較遺憾一點就是了&#8230;. )</p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<p>FF4 Part 2-3 爭奪暗之水晶 ( 完 )</p></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
