<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy IV ( FF4, iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 1-1 開端．巴隆王的陰謀</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#飛空艇'><span style='color: #000080; text-decoration: underline;'>飛空艇</span></a></span></span><br /> (02) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#巴隆城'><span style='color: #000080; text-decoration: underline;'>巴隆城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; 取得「爆彈戒指」</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城 1F'><span style='color: #000080; text-decoration: underline;'>巴隆城 1F</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城 西塔 2F'><span style='color: #000080; text-decoration: underline;'>巴隆城 西塔 2F</span></a></span></span></p>
<p>(03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆鎮'><span style='color: #000080; text-decoration: underline;'>巴隆鎮</span></a></span></span><br /> (04) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#迷霧洞窟'><span style='color: #000080; text-decoration: underline;'>迷霧洞窟
</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; BOSS 戰：霧龍<br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#迷霧村'><span style='color: #000080; text-decoration: underline;'>迷霧村</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; 發現莉迪亞<br /> (06) 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#凱波'><span style='color: #000080; text-decoration: underline;'>凱波</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.1 &#8211; 
<span style='color: #ff0000;'>莉迪亞加入隊伍</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.2 &#8211; 取得第一個傳繼道具「<span style='color: #800000;'>自動恢復藥</span>」<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.3 &#8211; 發現羅莎<br /> 
(07) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下水脈'><span style='color: #000080; text-decoration: underline;'>地下水脈</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>7.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下水脈 B1 南口'><span style='color: #000080; text-decoration: underline;'>地下水脈 B1 南口</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>
眼藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>泰拉加入隊伍</span>
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下水脈 B2 南側'><span style='color: #000080; text-decoration: underline;'>地下水脈 B2 南側</span></a>
</span></span> ( 地圖獎勵：<span style='color: #800000;'>解毒藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>第一個儲存點<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.3 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#地下水脈 B3'><span style='color: #000080; text-decoration: underline;'>地下水脈 B3</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>帳篷 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;
&#8211;</span>7.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下水脈 B2 北側'><span style='color: #000080; text-decoration: underline;'>地下水脈 B2 北側</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>不死鳥之尾 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.5 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#地下水脈 B1 北口'><span style='color: #000080; text-decoration: underline;'>地下水脈 B1 北口</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>以太</span> )<br /> (08) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下湖'><span style='color: #000080; text-decoration: underline;'>地下湖
</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下湖 B2'><span style='color: #000080; text-decoration: underline;'>地下湖 B2
</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>恢復藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#地下湖 B1'>
<span style='color: #000080; text-decoration: underline;'>地下湖 B1</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>宙斯之怒 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：八足巨妖</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='飛空艇'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>飛空艇</span><br /> <span style='color: #ffffff;'>-</span><br /> 劇情一開始便在飛空艇上，塞西爾率領著一群小兵，氣氛有點詭橘。原來是因為剛剛奉命做了一些違背良心的事，大伙正天人交戰中&#8230;..</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/01-airship-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 突然之間出現了敵人 ( 遇敵：浮游之眼 x2 )，簡單解決</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/01-airship-002.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 緊接著飛空艇群來到了「巴隆城」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/01-airship-003.png' alt='' width='486' height='326' /><br /> <a name='巴隆城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>巴隆城</span><br /> <span style='color: #ffffff;'>-</span><br /> 塞西爾因質疑巴隆王搶奪水之水晶的用意，被解除了隊長職務。國王交給了塞西爾一個「爆彈戒指」，並要他與龍騎士團長「凱因」一同去執行任務</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第一個地點的內部空間就已經一堆通道了，一不小心還真可能會迷路，記得以前第一次玩的時候連這裡也迷路好久啊XDDDDDDD。不過這也就是為什麼我要寫攻略的原因啊&#8230;..( 菸<br /> <span style='color: #ffffff;'>-</span><br /> 可以行動之後，先往右走吧！</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-002.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡會看到凱因在面壁思過 ( 誤 )，先找他對話</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 兩人會開始回憶過去的故事</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-004.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就開始與城內的人對話收集情報，我也可以省一點攻略的說明 ( 喂 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-005.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就往下到 1F 去</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-006.png' alt='' width='486' height='326' /><br /> <a name='巴隆城 1F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 1F</span><br /> <span style='color: #ffffff;'>-</span><br /> 左右兩側往下的樓梯是黑魔法與白魔法研究室，可以去對話一下，回來後往右走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-007.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右邊有個人會告訴你，按下左邊牆上開關，會開啟一個門，裡面有寶物</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-008.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 調查左邊開關後即可進入，裡面有三個寶箱：<span style='color: #800000;'>480 元、以太、帳篷</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-009.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完寶箱就往左邊走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-010.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底從後面的階梯上去</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-011.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到一個小台階，繼續走下去</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-012.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一下來會遇到第三位主角：白魔法師「羅莎」<br /> ( 去房間是想幹嘛&#8230;XDDDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-013.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 對話結束後就繼續往下走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-014.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出來之後左邊的門是前往巴隆城的地牢，裡面關著三個密西迪亞的魔法師，可以去找他們對話一下，但是良心會受到譴責&#8230;.不想去就往上直走即可</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-015.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著路上遇到會「西德」( 好光鮮亮麗的西德XDDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-016.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 前面有兩個房間，右邊是一堆沮喪的赤翼隊員，還有人在酗酒XDDDD<br /> 不過我們要去的是正前方的房間</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-017.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後遇到一隻可以改名的兔子叫「命名威」，但是&#8230;&#8230;</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-018.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 現在改名應該會失敗，根本不能改名嘛XDDDD</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-019.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 不管了，不能改名就算了，繼續往左上樓梯去吧！</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-020.png' alt='' width='486' height='326' /><br /> <a name='巴隆城 西塔 2F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 西塔 2F</span><br /> <span style='color: #ffffff;'>-</span><br /> 經過這裡會有個女子告訴你房間準備好了，上去休息吧！</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-021.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 原來這裡就是塞西爾自己的房間，調查床舖後休息吧！</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-022.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 劇情：夜間，羅莎依約前來，詢問了密西迪亞發生的事情&#8230;..</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-023.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 隔日，塞西爾與凱因會合後，為了尊嚴與洞悉巴隆王的居心，踏上了冒險的旅程<br /> <span style='color: #ff0000;'>( 此時響起了 Final Fantasy 的經典主題曲，好感人又好激動啊！！！)</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-024.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到地圖上後，終於可以存檔囉！前面就是下一個地點：巴隆鎮</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/02-castle_baron-025.png' alt='' width='486' height='326' /><br /> <a name='巴隆鎮'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆鎮</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>1/16 Update:</span> ( 補充提醒 &#8211; 隱藏召喚獸道具：<span style='color: #800000;'>哥布林、蛇雞獸</span> )</p>
<p>遊戲初期在巴隆鎮週邊，有兩個怪物可以留意一下，哥布林與俯衝鷹。這兩個敵人身上帶有隱藏召喚獸 ( 召喚魔法，莉迪亞專用 )，掉落機率是最低的第 4 檔，非常難到手，如果有時間不妨試一試，或是後期再回來這裡慢慢刷也可以，請參考：<span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_hiding_summoning_spells.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 隱藏召喚獸</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>哥布林</span> ( 低機率掉落道具「哥布林」)</p>
<p><img class='alignnone' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-001.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>俯衝鷹</span> ( 低機率掉落道具「蛇雞獸」)</p>
<p><img class='alignnone' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-006.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 繼續看巴隆鎮。這裡除了和鎮上的人對話之外，可以先在旅店右邊的草堆發現一個「<span style='color: #800000;'>恢復藥</span>」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-002.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著進入旅店後，櫃檯前面的罈子也有一個「<span style='color: #800000;'>恢復藥</span>」，拿完就上旅店的二樓去</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上來看到有個放寶箱的房間，但沒有門，調查牆上的開關可以打開通道</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-004.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 三個寶箱分別是：<span style='color: #800000;'>小人麵包、帳篷、眼藥</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-005.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著到鎮上最右上角有個女子，會跳舞給你看XDDDD</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-006.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 我是在玩成人遊戲嗎 ( 羞 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-007.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 看完跳舞就走下水池，延著水道往下走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-008.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在水路的盡頭是一個水池，中間靠左會發現一個「<span style='color: #800000;'>帳篷</span>」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-009.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再往右下移動一點，會發現一個「<span style='color: #800000;'>銅沙漏</span>」，然後就可以往回走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-010.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回來後到最右邊靠圍牆的草叢上，會發現一個「<span style='color: #800000;'>眼藥</span>」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-011.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/25 Update:</span> ( 感謝網友<span style='color: #0000ff;'> vvttgogo</span> 提供資料，還有三個道具 )</p>
<p>接著往最右上角的入口出去</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-017.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>再繞過上面圍牆的角落往左邊走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-018.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>過來後在牆的缺口處，會發現一個「<span style='color: #800000;'>不死鳥之尾</span>」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-019.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>然後在空地上的花叢間，會發現一個「<span style='color: #800000;'>金針</span>」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-020.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>";
echo "<p><span style='color: #ffffff;'>-</span></p>
<p>再從牆邊搜尋，會找到另一個「<span style='color: #800000;'>不死鳥之尾</span>」，然後就回到鎮上</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-021.png' alt='' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>在河道左邊是羅莎的家，在左邊的罐子有一個「<span style='color: #800000;'>恢復藥</span>」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-012.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 後面一點的牛車 (?) 上也有一個「<span style='color: #800000;'>恢復藥</span>」( 隱藏的物品也太多了吧XDDDDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-013.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再來到中間靠左的房子 ( 羅莎的家左邊 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-014.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 裡面牆上的開關可以開啟一道門，後面是個傳送點，但目前無法使用；往樓梯下去則是訓練室，跟訓練室的所有人對話後會有 Game Center ( iOS 平台專屬的遊戲中心 ) 的「成就」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-015.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 有關 FF4 在各城鎮村落中可取得的道具，我會盡量照上面的方式，附上截圖列出，但如果都很好找到的話，我可能就會用文字敘述的方式列出而已，有需要的才會補上截圖，不然 FF4 的隱藏道具看起來也是很多啊！截圖會截不完XDDDDDD</p>
<p><span style='color: #ffffff;'> -</span><br /> 在巴隆鎮這裡沒什麼特別的事，記得保持一個好習慣，跟每個地點的所有人都要對話，才能取得最完整的情報，這裡有羅莎的家 ( 中間靠右 ) 和西德的家 ( 最左上方 )，記得都要進去對話一下。而這邊你也會發現還有商店是未開放的，代表之後還會回來這裡。<br /> 
<span style='color: #ffffff;'>-</span><br /> 目前兩位主角塞西爾與凱因的初始等級是 LV 10，而兩個人雖然裝備都是齊全的，但建議還是在附近練練級，差不多提升個 2 級到 LV 12 左右，利用鎮上的旅店進行恢復，離開前也別忘了補充一些恢復道具。都準備好了之後就可以前往下一個地點。( 建議把戰鬥速度調快一點，不然真的有點慢，我是調最快的「1」XD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/03-baron-016.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='迷霧洞窟'></a><br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>迷霧洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 在巴隆城的北方，唯一的一個洞窟，稍微走一下路就會看到了</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來又遇到命名威，這次改叫「地形威」了，
還送你一張「<span style='color: #ff0000;'>魔法白地圖</span>」<br /> 用途是如果你有走遍單一區域地圖的話就會給予獎勵，後續你就會明白了</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-002.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>重要提醒：</span></p>
<p>第一輪遊戲從現在開始，每到一個新的迷宮都會有地圖完成度 100% 的獎勵，<span style='color: #ff0000;'>請務必隨時按下畫面右上角的「地圖」確認完成的百分比</span>，沒有走完該處地圖的話務必要繞完取得地圖獎勵，因為全地圖 100% 可以在最後取得重要的技能道具「<span style='color: #800000;'>寶物獵手
</span>」，這對於後期收集尾巴與強力武器非常重要，後續也有單一次出現的地圖，我也會再次提醒，各位請確實多留意一下地圖完成度 100%。要是有某個地圖沒走完 100%，後續無法查詢哪一個地圖沒走完整，要一個一個找&#8230;..會很麻煩的XD</p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個洞窟路線很短，一開始單線前進，這裡會先經過一個寶箱 ( <span style='color: #800000;'>恢復藥</span> )<br /> ( 中途會聽到神祕的聲音 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過第二個寶箱 ( <span style='color: #800000;'>眼藥</span> )，拿完往下繼續走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-004.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：下樓梯往左 ( 寶箱：<span style='color: #800000;'>帳篷</span> ) &gt; 右下 ( 主線 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-005.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後一個寶箱 ( <span style='color: #800000;'>恢復藥</span> )，再往前就會遇到 BOSS 戰</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-006.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 神祕的聲音要我們回去，問我們是否沒有回去的意思，選「是」迎來 BOSS 戰</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-007.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>霧龍
</span><br /> HP：<span style='color: #0000ff;'>約 800</span> ( 沒仔細算 )<br /> 技能：<span style='color: #ff0000;'>變成霧狀時攻擊無效 ( 且會用冷霧反擊，傷害約 90 )</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/04-mist_cave-008.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 塞西爾可以加暗黑後直接砍即
可，傷害大約有 60 左右<br /> 2. 凱因就用跳躍，但要抓好時機，否則下來時如果是霧狀就會被反擊<br /> 3. 並不難的一戰，BOSS 大概 2 回合變成一次霧狀，留意回復<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 備註：當你離開前應該會出現「走遍迷霧洞窟」
的訊息，獎勵是「<span style='color: #800000;'>5 個恢復藥</span>」<br /> 如果沒出現就回頭繞一下，或是<span style='color: #ff0000;'>按下「地圖」確認還沒走過的地方</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>離隊人員提醒：</span></p>
<p>等一下進了迷霧村之後會直接進入劇情，<span style='color: #ff0000;'>過完劇情凱因就會離隊，</span><span style='color: #ff0000;'>進村前請務必脫下他的裝備</span>，尤其是第二輪開始的朋友們，如果你給凱因穿上了<span style='color: #800000;'>精金鎧</span>、<span style='color: #800000;'>洋蔥系列裝備
</span>，千萬要卸下來啊！不然等下次凱因歸隊就悲劇了&#8230;&#8230;XD<br /> <a name='迷霧村'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>迷霧村</span><br /> <span style='color: #ffffff;'>-</span><br /> 出了洞窟後<span style='color: #ff0000;'>往右</span>繼續走就會來到迷霧村</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/05-the_town_of_mist-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就是一段劇情：原來爆彈戒指是為了要把這裡趕盡殺絕&#8230;.</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/05-the_town_of_mist-002.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 兩人發現了一個少女，並決定帶走她 ( 原來剛剛的霧龍是&#8230;. )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/05-the_town_of_mist-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 後來少女不依，還使出「大地之怒」( 女人果然不能惹&#8230;. )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/05-the_town_of_mist-004.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 醒來了後只剩下塞西爾一個人，繼續往前走，看到沙漠後就往東一直走，會經過一個綠洲之村，就是我們的下一個地點：凱波</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/05-the_town_of_mist-005.png' alt='' width='486' height='326' /><br /> <a name='凱波'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>凱波</span><br /> <span style='color: #ffffff;'>-</span><br /> 凱波就在這片沙漠的右側位置</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 塞西爾一進來就帶著女孩去開房間&#8230;..櫃檯還不收費XDDDDDD</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-002.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 突然之間巴隆的將軍出現，要求交出女孩，這當然不行，只好開戰！</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇敵：<span style='color: #0000ff;'>將軍、巴隆兵 x3</span></p>
<p><span style='color: #ff0000;'>提醒：如果要收集怪物圖鑑，必須先把「將軍」打死，再打小兵</span></p>
<p>( 如果將軍是逃走的，則怪物圖鑑資料會顯示「？」，將無法完成這一名的怪物資料 )<br /> 備註：如果沒有想收集怪物圖鑑，就把前面三個小兵打完後，將軍就會直接逃跑了</p>
<p>詳請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_enemies_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 怪物圖鑑收集</span></a></span></span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-004.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 結束後，女孩感到被救了一命，於是<del> 以身相許</del> 召喚士「莉迪亞」加入了隊伍</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-005.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 村內雖然也有商店，但是現在的錢&#8230;..好少啊XDDDDDD</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-006.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在村子內繞一下吧，和所有人都對話後，就前往最東北方的這間房子</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-007.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來會先看到地形威，結果他又變「無業遊民 生命威」( 這什麼梗XD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-008.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 現在可以找他查看怪物圖鑑，但資料當然還不多就是了</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-009.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往前走竟然發現了羅莎！並取得傳繼能力道具「<span style='color: #800000;'>自動恢復藥</span>」<br /> ( 離開時那隻兔子會說明這是啥 )</p>
<p>&nbsp;</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-010.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 結果羅莎還是持續發著高燒，無法清醒，詢問了旁邊的長者，告訴我們需找到一個幻之寶石「沙漠之光」，而這塊寶石要前往「蟻獅洞窟」&#8230;&#8230;</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-011.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 傳繼能力道具在「關鍵道具」選單中，可選擇你要使用的角色 ( 只能用一位 )<br /> <span style='color: #ff0000;'>12/24 Update: 強烈建議現在先不要使用掉這個自動恢復藥，留著後續會有用的</span></p>
<p>( 傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span> )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/06-kaipo-012.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡逛完了之後，準備好就可以離開凱波，往東北方走，去「地下水脈」</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='地下水脈'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下水脈</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 提醒一下，目前莉迪亞的等級太低，HP 也超低，
路上隨便遇個敵就有一半機會掛掉，尤其是遇到這種「小人魔術師」，有時還會一次出現四個，被丟個魔法攻擊應該就趴了。除了記得讓莉迪亞站後排之外，其他就要自求多福了，我是覺得一直掛就乾脆別救算了，不然現在不死鳥之尾這麼稀少怎麼夠用，或者撐到學會「復活魔法」為止也行，再不行就逃跑XDDDD</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-002.png' alt='' width='486' height='326' /><br /> <a name='地下水脈 B1 南口'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>地下水脈 B1 南口</span><br /> <span style='color: #ffffff;'>-</span><br /> 一開始就是一個叉路<br /> 叉路：上 ( 寶箱：<span style='color: #800000;'>少女之吻、恢復藥</span> ) &gt; 左 ( 主線 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：下 ( 寶箱：<span style='color: #800000;'>帳篷</span> ) &gt; 上 ( 主線 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-004.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著遇到了<span style='color: #ff0000;'>賢者
泰拉，對話後加入了隊伍</span>，終於有人可以幫忙了，不然好慘XD<br /> ( 泰拉加入後，可善用<span style='color: #0000ff;'>雷屬性魔法</span>對敵人全體，大部份都具有此弱點 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-005.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後眼前的叉路先往右走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-006.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下一個叉路繼續往右走<br /> ( 往上雖然是死路，但是別忘了走遍地圖會有獎勵，所以&#8230;.好掙扎啊XD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-007.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著這個區域往上走是空的 ( 但還是得走一下XD )，就接著往下走水路</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-008.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來水路後會遇到一個叉路，先往左邊走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-009.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到一個大瀑布，最左邊有暗道可以進入</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-010.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後往前走，可取得三個寶箱：<span style='color: #800000;'>特級以太、特級恢復藥、不死鳥之尾</span><br /> 然後再回到剛剛水路上的叉路</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-011.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到叉路後就接著繞到上面來</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-012.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭走上來有一個寶箱：<span style='color: #800000;'>以太</span><br /> 然後就可以往回走到剛剛遇到泰拉的叉路，然後就往上繼續走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-013.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到下一段路前會取得走遍地圖獎勵：<span style='color: #800000;'>眼藥 x5</span><br /> ( 可以先給恢復藥或不死鳥之尾嗎，比較需要XDDDDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-014.png' alt='' width='486' height='326' /><br /> <a name='地下水脈 B2 南側'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下水脈 B2 南側</span><br /> <span style='color: #ffffff;'>-</span><br /> 一開始單線前進，下來到水路繼續走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-015.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：往左上直走到底 ( 寶箱：<span style='color: #800000;'>恢復藥</span> ) &gt; 下 ( 主線，石頭兩側往下均可 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-016.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後從這個樓梯上去</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-017.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 (<span style='color: #800000;'> 以太</span> )，繼續往下前進</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-018.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著通過一個入口，就會看見遊戲中的第一個室內儲存點<br /> ( 可以睡覺了&#8230;.感動&#8230;T.T )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-019.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 自動睡一覺後，醒來就繼續往前走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-020.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會再經過一個寶箱 ( <span style='color: #800000;'>玄冰棒</span> )，繼續往下走</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-021.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下了樓梯應該就會出現地圖獎勵：<span style='color: #800000;'>解毒藥 x5</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-022.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往下走到底又是水路，左邊是死路，往右邊才是主線<br /> ( 截圖上的數字是提醒你死路還是要走一下XDDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-023.png' alt='' width='486' height='326' /><br /> <a name='地下水脈 B3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下水脈 B3</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：右下 ( 寶箱：<span style='color: #800000;'>580 元、爆彈碎片</span> ) &gt; 左 ( 主線 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-024.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續單線就會到下一段路 ( 地圖獎勵：<span style='color: #800000;'>帳篷 x3</span> )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-025.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 補充一下，如果沒拿到地圖獎勵，記得回去沒走過的路再繞一次<br /> 像我就是繞回去又走一次才出現 <span style='color: #ff0000;'>( 記得按「地圖」確認沒走過的地方 )</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-026.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在迷宮中若按下地圖，也會顯示你走過的地方，右
下角會有目前該區域的完成度<br /> ( 在這個畫面一樣是可以繼續走的，只是畫面會重疊，但至少可以得知目前位置 )<br /> <span style='color: #ff0000;'>( 截圖的數字 1 代表入口，數字 2 代表出口 )</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-027.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 剛到一個新的區域就會像這樣，一片霧茫茫&#8230;.繼續往前走吧！<br /> ( 這是在玩即時戰略嗎XDDDDD，星海爭霸？)</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-028.png' alt='' width='486' height='326' /><br /> <a name='地下水脈 B2 北側'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>地下水脈 B2 北側</span><br /> <span style='color: #ffffff;'>-</span><br /> 這個區域有兩個寶箱，比較麻煩的是第一個寶箱左邊的暗道，分別可以繞到右半邊以及下面的入口，暗道中需要摸黑前進，建議這個區域像這樣看著地圖比較好走<br /> ( 截圖裡暗道的路線是最後憑記憶去畫出來的，如果方向不太準請多包涵&#8230;. )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-029.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這一段開始會有很討厭的敵人，會放蛙變不停地讓
你變青蛙，或是變回來，如果少女之吻不夠用的話，就&#8230;..祈禱他會繼續放魔法幫你變回來XDDDD，但是打敗他們也是有機會掉少女之吻的 ( 不然莉迪亞升到 13 級也能學會蛙變 )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-030.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出口前的寶箱：<span style='color: #800000;'>恢復藥</span>，左邊就是暗道</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-031.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過暗道，繞到右半部的盡頭寶箱：羽飾帽子，拿完就可以往回到出口去了<br /> ( 暗道的路線有點曲折&#8230;.剛剛上面那張圖我已盡量畫出路線了，有錯請包涵XD )<br /> ( 地圖獎勵：<span style='color: #800000;'>不死鳥之尾 x3</span> )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-032.png' alt='' width='486' height='326' /><br /> <a name='地下水脈 B1 北口'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下水脈 B1 北口</span><br /> <span style='color: #ffffff;'>-</span><br /> 上來 B1 後，先到左邊拿一個寶箱 ( <span style='color: #800000;'>以太</span> )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-033.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就看地圖吧！( 看著地圖走，這樣寫攻略好像方便多了XDDDD )<br /> 1 是入口，2 是出口，其餘三個寶箱：<span style='color: #800000;'>宙斯之怒、暗影劍、銅沙漏</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-034.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>以太</span> ( 到底是誰發明這種獎勵方式的啦XDDDDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-035.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出去後會回到地圖上，泰拉在出口前還會提醒要休息一下</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/07-waterway-036.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>";
echo "<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='地下湖'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下湖</span><br /> <span style='color: #ffffff;'>-</span><br /> 前面就是下一個地點了，進去前別忘了恢復 + 儲存</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-001.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後就一路往下直走，會出現選項，當然選「是」</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-002.png' alt='' width='486' height='326' /><br /> <a name='地下湖 B2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下湖 B2</span><br /> <span style='color: #ffffff;'>-</span><br /> 地圖參考 ( 之後都會用類似這樣的方式，再提醒一次：1 是入口，2 是出口 )<br /> 取得寶箱：<span style='color: #800000;'>冥王頭盔、冥王護手</span> ( 一邊看地圖一邊前進真的很方便XDDD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-003.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>恢復藥 x5</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-004.png' alt='' width='486' height='326' /><br /> <a name='地下湖 B1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>地下湖 B1</span><br /> <span style='color: #ffffff;'>-</span><br /> 地圖參考 ( 取得寶箱：<span style='color: #800000;'>冥王鎧、赫耳墨斯之靴</span> )<br /> ( 赫耳墨斯之靴在 FFD 可是神物啊！但是在 FF4 是道具來的&#8230;加速用XD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-005.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>宙斯之怒 x3</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-006.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後在水池深處看見兩支章魚觸腳在搖來搖去，往前靠近就會進入 BOSS 戰！</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-007.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>八足巨妖</span><br /> HP：<span style='color: #0000ff;'>( 後續補上 )</span><br /> 攻擊：物理攻擊傷害約 30~70<br /> 弱點：<span style='color: #ff0000;'>雷、暗黑</span></p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-008.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 開戰後塞西爾馬上先用暗黑提升攻擊力，之後的攻擊可有 400 以上的傷害<br /> 2. 泰拉就針對 BOSS 另一弱點放雷魔法，傷害有 250 左右<br /> 3. 莉迪亞與泰拉兩人都可以丟「宙斯之怒」，目前應該有 4 個，全扔了吧XD<br /> 4. 中途若 HP 過低一定要記得回復，最好是讓泰拉放「救療」一次回滿<br /> 5. 如果不幸全掛了&#8230;.就大絕吧XDDD ( Home 鍵離開遊戲，重啟選繼續 )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗 BOSS 後繼續往前走就能離開這裡，回到地圖上</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-009.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到地圖上後，繼續往前走就會看到「達姆希安城」( 還看到赤翼隊出現&#8230; )<br /> ( 到達後會有 Game Center 的成就喔！下篇待續XD )</p>
<p><img class='alignnone' src='./ff4_images/ff4_part_1-1/08-underground_lake-010.png' alt='' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>FF4 Part 1-1 開端．巴隆王的陰謀 ( 完 )</div></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
