<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy IV ( FF4, iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 1-2 法布爾城水晶失守</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#達姆希安城'><span style='color: #000080; text-decoration: underline;'>達姆希安城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#達姆希安城 牢房'>
<span style='color: #000080; text-decoration: underline;'>達姆希安城 牢房</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#達姆希安城 牢房 B1'><span style='color: #000080; text-decoration: underline;'>達姆希安城 牢房 B1</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#達姆希安城 3F'><span style='color: #000080; text-decoration: underline;'>達姆希安城 3F</span></a></span></span>
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>吉爾伯特加入隊伍</span> <span style='color: #ff0000;'>( 泰拉離隊 )</span><br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B1 - 1'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 B1 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B2 - 1'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 B2 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.3 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B1 - 2'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 B1 &#8211; 2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>2.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B1 - 3'>
<span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 B1 &#8211; 3</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>恢復藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B2 - 2'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 
B2 &#8211; 2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B2 - 3'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 B2 &#8211; 3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.7 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅洞窟 B2 - 4'><span style='color: #000080; text-decoration: underline;'>蟻獅洞窟 B2 &#8211; 4</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>不死鳥之尾 x3
</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#蟻獅巢'><span style='color: #000080; text-decoration: underline;'>蟻獅巢</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：蟻獅<span style='color: #ffffff;'> </span>(<span style='color: #ffffff;'> </span>取得「<span style='color: #800000;'>沙漠之光</span>」)<br /> (03) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#凱波'><span style='color: #000080; text-decoration: underline;'>凱波</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='color: #ff0000;'>羅莎加入隊伍</span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; 取得傳繼能力道具：<span style='color: #800000;'>道具知識</span><br /> (04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#霍布斯山'><span style='color: #000080; text-decoration: underline;'>霍布斯山</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#霍布斯山 西口'><span style='color: #000080; text-decoration: underline;'>霍布斯山 西口</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x3</span> )<br />
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>莉迪亞習得魔法「火炎」<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#霍布斯山 第 5 階段'><span style='color: #000080; text-decoration: underline;'>霍布斯山 第 5 階段</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#霍布斯山 山頂'><span style='color: #000080; text-decoration: underline;'>霍布斯山 山頂</span></a></span></span>
<span style='color: #ffffff;'> </span><span style='color: #ff0000;'>( 楊加入隊伍 )</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#霍布斯山 東口'>
<span style='color: #000080; text-decoration: underline;'>霍布斯山 東口</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>爆彈之魂 x3</span> )<br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城'>
<span style='color: #000080; text-decoration: underline;'>法布爾城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 1F'>
<span style='color: #000080; text-decoration: underline;'>法布爾城 1F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 2F'><span style='color: #000080; text-decoration: underline;'>法布爾城 2F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;
&#8212;&#8211;</span>5.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 外部'><span style='color: #000080; text-decoration: underline;'>法布爾城 外部</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>5.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 東塔 2F'><span style='color: #000080; text-decoration: underline;'>法布爾城 東塔 2F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.5 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 東塔 3F'><span style='color: #000080; text-decoration: underline;'>法布爾城 東塔 3F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 西塔 1F'>
<span style='color: #000080; text-decoration: underline;'>法布爾城 西塔 1F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.7 &#8211; 城內六連戰<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.8 &#8211; 凱因、高貝扎現身，水晶失守，
羅莎遭到挾持<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.9 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法布爾城 大殿'><span style='color: #000080; text-decoration: underline;'>法布爾城 大殿</span>
</a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得「<span style='color: #800000;'>奪命之刃</span>」、傳繼能力道具「<span style='color: #800000;'>反擊</span>」</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='達姆希安城'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>達姆希安城</span><br /> 出了地下湖後，前方就會來到達姆希安城</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後先不要進去，先往右走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 延著城牆的邊緣，一直往後走，不小心走出去了就重走就好，路蠻寬的</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到最後面會發現一個入口，直接進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-004.png' width='486' height='326' /><br /> <a name='達姆希安城 牢房'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>達姆希安城 牢房</span><br /> 進來發現是一個牢房，裡面有個垂死的人講著寶物的事，對話完就消失了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著走到最右邊的牆上有個開關，調查後右側會開啟通道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進入通道一路往左邊走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到第二間會找到一個寶箱 ( <span style='color: #800000;'>能量弓</span> )，接著往左下角繼續穿牆過去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後一間是兩個寶箱：<span style='color: #800000;'>紅寶石戒指、羽飾帽子</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到原本走道之後，往左走到底，這裡往下會有暗道可以進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-010.png' width='486' height='326' /><br /> <a name='達姆希安城 牢房 B1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>達姆希安城 牢房 B1</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 一下來就看到六個寶箱，拿完之後先別離開<br /> 寶箱：<span style='color: #800000;'>恢復藥、以太、解毒藥、不死鳥之尾、眼藥、金針</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著到右上的角落，會發現「<span style='color: #800000;'>鐵箭</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右下角也有，這裡是「<span style='color: #800000;'>聖箭</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後則是左下角的「<span style='color: #800000;'>聖靈藥</span>」，拿完就可以回到城門口進去了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進城之前，
<span style='color: #ff0000;'>記得把泰拉的裝備卸下，因為他等一下就會先離開了</span>，泰拉身上有一件「<span style='color: #800000;'>大地之衣</span>」，拆給莉迪亞裝備剛剛好XDDDDD <span style='color: #ff0000;'>( 泰拉之後還會再歸隊一次 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進城後發現門口倒了幾個士兵奄奄一息，快進去看看吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡也是，感覺發生了很可怕的事情，繼續往上走吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過 2F 會發現一個寶箱 ( <span style='color: #800000;'>帳篷</span> )，繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-018.png' width='486' height='326' /><br /> <a name='達姆希安城 3F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>達姆希安城 3F</span><br /> <span style='color: #ffffff;'>-</span><br /> 到了 3F 會發現前面躺著一個人，可以先不管他，先往左右兩側去看看</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左側下面角落的罐子可以<span style='color: #ff0000;'>恢復 HP、復活、復原異常狀態</span>！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右側同樣位置的罐子則是可以<span style='color: #ff0000;'>恢復 MP</span>！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 發現這兩個罐子後，其實是一個很好練級的
機會，因為可以免費恢復，如果覺得自己目前的等級太低的話，建議可以走回去「地下湖」打章魚 BOSS 的地方，去打鱷魚，一次會有三隻，經驗值 400 多，用冰結魔法就可以一次解決，若將其中兩人自殺，一次的經驗值會有 1314。<br /> <span style='color: #ffffff;'>-</span><br /> MP 不夠用了就回來這裡恢復 ( 如果
你是要練單人就不要恢復 HP，不然會復活 )，再繼續回地下湖去練級，FF4 難度不低，覺得過程很辛苦的話，不妨利用這個機會練一下。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續我們的劇情吧！往前走去調查躺在地上的女子</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 原來她就是泰拉的女兒安娜！同時還出現一個陌生的吟遊詩人吉爾伯特</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後泰拉與吟遊詩人進入了戰鬥 ( 泰拉有點抓狂&#8230;.. )<br /> ( 戰鬥是自動的，不需控制，但對話有點久XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 劇情：安娜解釋了事情的經過，但是&#8230;.終究還是離開了人世… ( 淚<br /> ( 有語音真的很感動啊！)</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>接著吟遊詩人「吉爾伯特」說明了關於蟻獅洞窟的事，也加入了隊伍</span></p>
<p>( 同時泰拉第一次離隊，後續會再次加入 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後會得到一艘氣墊船，就從達姆希安城的右下方，往東方直走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/01-castle_damcyan-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='蟻獅洞窟'></a><br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>蟻獅洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 從達姆希安城往東，過了淺灘後，就會發現一個洞窟<br /> ( 按畫面右下角就可以下船 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-001.png' width='486' height='326' /><br /> <a name='蟻獅洞窟 B1 - 1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B1 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>蜘蛛絲、金針、帳篷、恢復藥 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡稍微說明一下，我在地圖上的出入口
所標的數字，不同地圖的相同數字表示是連接兩張地圖的出入口，數字的大小則表示建議的行走順序這樣。<br /> <span style='color: #ffffff;'>-</span><br /> 在 B1 拿完上述 6 個寶箱就先從 2 走出去，這時候還沒有取得地圖獎勵<br /> <a name='蟻獅洞窟 B2 - 1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B2 &#8211; 1</span><br /> 取得寶箱：<span style='color: #800000;'>恢復藥、蜘蛛絲、南極之風、玄冰棒、暗影劍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完 5 個寶箱後，先從 3 回到 B1 去<br /> <a name='蟻獅洞窟 B1 - 2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B1 &#8211; 2</span><br /> 從 3 進來後接著繼續往 4 進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-004.png' width='486' height='326' /><br /> <a name='蟻獅洞窟 B1 - 3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B1 &#8211; 3</span><br /> 取得寶箱：<span style='color: #800000;'>不死鳥之尾、緊急出口、以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡還有一個儲存點，可以搭帳篷恢復一下</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這邊會得到 B1 的地圖獎勵：<span style='color: #800000;'>恢復藥 x5</span>，然後就回到 B2 去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-007.png' width='486' height='326' /><br /> <a name='蟻獅洞窟 B2 - 2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B2 &#8211; 2</span><br /> 回到 B2 後，就從 B2 右邊的 5 進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-008.png' width='486' height='326' /><br /> <a name='蟻獅洞窟 B2 - 3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B2 &#8211; 3</span><br /> 取得寶箱：<span style='color: #800000;'>拉米亞豎琴</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-009.png' width='486' height='326' /><br /> <a name='蟻獅洞窟 B2 - 4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>蟻獅洞窟 B2 &#8211; 4</span><br /> 再次回到 B2 後，就往 6 前進，會進到蟻獅的巢穴</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> B2 的地圖獎勵：<span style='color: #800000;'>不死鳥之尾 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-011.png' width='486' height='326' /><br /> <a name='蟻獅巢'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>蟻獅巢</span><br /> 進來蟻獅巢後就一路往下直走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了盡頭就會遇到 BOSS，吉爾伯特還以為 BOSS 是溫馴的&#8230;= =</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>蟻獅</span><br /> HP：( 後續補上 )，弱點：<span style='color: #ff0000;'>冰</span><br /> 攻擊：<span style='color: #ff0000;'>反擊之角 ( 單體傷害約 130~150 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 讓莉迪亞針對 BOSS 的弱點用「冰結」魔法攻擊<br /> 2. 塞西爾放暗黑後直接物理攻擊，吉爾伯特就唱恢復之歌<br /> 3. BOSS 變紅色眼睛時，遇到魔法攻擊會自動反擊，傷害還好，注意回復即可</p>
<p>4. 承上，白色眼睛時會對物理攻擊反擊</p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>打敗後取得「沙漠之光」</span>，該回去凱波救羅莎了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到地圖上後 ( 懶得走可以用道具「緊急出口」傳送出去 )，直接坐氣墊船繞到凱波去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <strong>題外話1：</strong><br /> 這
個蟻獅洞窟我這樣用地圖的方式來說明，不知道有沒有比較清楚？剛好 FF4 提供了這麼方便的功能，讓我們可以一邊看著地圖一邊走，所以除非有很不明顯的暗道，或是較複雜的路段，之後的迷宮我盡量會用此方式來說明，不過若是心血來潮可能還是會照之前的方式一步一步的標出來。<br /> <span style='color: #ffffff;'>
-</span><br /> <strong>題外話2：</strong><br /> 突然發現如果<span style='color: #ff0000;'>畫面中要換人來走路，只要點一下主角就可以了耶XD</span>，不小心點到的時候發現的 ( 我是不是神經太大條XDDDD )，例如你在畫面中點一下塞西爾，就會切換到下一位莉迪亞，再點一下又切到吉爾伯特這樣。不過我還是習慣看塞西爾走路。</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/02-the_antlion_cave-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 難怪我一直找不到怎麼讓隊伍第一個人顯示在地圖上，原來不是用我習慣的方式來換 ( 通常是排在第一個即可 )，是要點一下來換XDDDDD<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline; color: #0000ff;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span><br /> <a name='凱波'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>凱波</span><br /> <span style='color: #ffffff;'>-</span></p>";
echo "<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-001.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 坐上氣墊船後，往地圖左邊走，經過達姆希安城，再延著海岸繞下來，到了沙漠往右走就會到達凱波 ( 地圖一樣可以開著邊走邊看，好方便XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進後就直接回到最右上方靠牆的屋子</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到羅莎的床邊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會跳出道具視窗，就拉到最下面，選擇「<span style='color: #800000;'>沙漠之光</span>」<br /> ( 明明就可以直接使用就好，為什麼還要玩家選擇啊，難道會選解毒藥之類的嗎XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 羅莎醒來後，說明了目前的局勢，我們似乎需前往霍布斯山</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 羅莎畢竟還是希望陪在塞西爾身邊，於是<span style='color: #ff0000;'>羅莎也加入了隊伍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇敵：晚上吉爾伯特在屋外遇到了魚人的襲擊，安娜的靈魂現身，一段感人的打氣加油！( 魚人大約需要 3~4 回合就能打敗 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 劇情：安娜的靈魂向吉爾伯特做了最後的道別與鼓勵，終究還是永遠地離開了，接下來的日子裡，吉爾伯特會開始振作起來嗎？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/24 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>Ethan Lin</span> 補充 )</p>
<p>在吉爾伯特打完魚人之後，接著要離開凱波之前，到村子的北方，大約是旅店的後面</p>
<p>( 下圖<span style='color: #ff0000;'>紅圈</span>的位置 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-010-2.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>在兩棵椰子樹的中間，會有發光點，可以取得第二個傳繼能力道具：<span style='color: #800000;'>道具知識</span></p>
<p><span style='color: #ff0000;'>這是第二個傳繼能力道具，一樣建議先留著勿用掉，目前你應該有留著兩個了</span></p>
<p>( 傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-010-1.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 最後確認一下需不需要補充道具，可以去旅店內的道具店買。至於武器店與防具店目前沒什麼好買的，都準備好之後，就可以離開凱波，再次搭上氣墊船，前往下一個地點：霍布斯山</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/03-kaipo-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='霍布斯山'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>霍布斯山</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>1/16 Update:</span> ( 補充提醒 &#8211; 隱藏召喚獸道具：<span style='color: #800000;'>蛇雞獸</span> )</p>
<p>在霍布斯山有一個怪物「蛇雞獸」身上會掉落同名的隱藏召喚魔法道具「蛇雞獸」，是莉迪亞專屬的技能道具，極低機率掉落，詳情可參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_hiding_summoning_spells.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 隱藏召喚獸</span></a></span></span>，建議可花點時間試試看，如果都沒掉，建議後期帶著寶物獵手技能再回來慢慢刷</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-007.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 坐氣墊船走原路，繞回蟻獅洞窟的右上方就是霍布斯山</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來見到了巨大的冰塊，羅莎溫柔地要莉迪亞試著用「火炎」，但是莉迪亞因為之前不好的經驗而不願嘗試&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後在眾人的鼓勵下，還是成功打開了入口，<span style='color: #ff0000;'>莉迪亞也學會了火炎魔法</span><br /> ( 原來是因為這樣所以不能用火魔法啊&#8230;.Orz )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-004.png' width='486' height='326' /><br /> <a name='霍布斯山 西口'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>霍布斯山 西口</span><br /> 第一段路沒有寶箱，將地圖繞完一遍後，先往上圖的 2 入口前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-006.png' width='486' height='326' /><br /> <a name='霍布斯山 第 5 階段'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>霍布斯山 第 5 階段</span><br /> 取得寶箱：<span style='color: #800000;'>帳篷、恢復藥、山彥草、960 元</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡有儲存點，儲存一下接著就可以往回走，從上一張地圖的 3 進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-008.png' width='486' height='326' /><br /> <a name='霍布斯山 山頂'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>霍布斯山 山頂</span><br /> 取得寶箱：<span style='color: #800000;'>聖箭</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到山上會遇到一名武僧 ( 楊 ) 正在與魔物們戰鬥</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著需要控制武僧進行戰鬥 ( 用<span style='color: #ff0000;'>踢擊</span>或是直接攻擊即可 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰 &#8211; 第一階段：<br /> <span style='color: #0000ff;'>爆彈怪宗母</span> ( 啥怪名字XDDDD )<br /> 弱點：<span style='color: #ff0000;'>冰、暗黑</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰 &#8211; 第二階段：</p>
<p><span style='color: #0000ff;'>爆彈怪 x6</span><br /> 在一段攻擊後 BOSS 會開始準備爆發，分裂成六個小爆彈怪，在爆發的時候會造成全體傷害，HP 較低的可能會倒下&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. <span style='color: #ff0000;'>楊直接用踢擊效果很好</span>，塞西爾用暗黑，或是直接砍傷害都不錯<br /> 2. 莉迪亞以冰結進攻，吉爾伯特唱恢復之歌 ( 倒下就算了XDDD )<br /> 3. 羅莎的 HP 也不高，所以應該也會倒下<br /> 4. 分裂後的六個爆彈怪就很好解決了，沒什麼難度<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗 BOSS 後，<span style='color: #ff0000;'>楊也加入了隊伍</span> ( 很好，隊伍越來越強大了XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就繼續前進吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-015.png' width='486' height='326' /><br /> <a name='霍布斯山 東口'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>霍布斯山 東口</span><br /> 這裡沒有寶箱，直接一路往出口 2 前進就會離開這座山</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>爆彈之魂 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下了山之後就延著陸地往東一直走，要走一段不算短的路</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/04-mt_hops-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='法布爾城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>法布爾城</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 從霍布斯山下來後一路往東走，法布爾城的位置就在右側的大陸上</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-002.png' width='486' height='326' /><br /> <a name='法布爾城 1F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>法布爾城 1F</span><br /> 進來第一個大廳後，左側 <strong>( 1 )</strong> 是旅店與道具店，右側 <strong>( 2 )</strong> 是武器防具店</p>
<p>( <span style='color: #ff0000;'>2/15 update:</span> 感謝網友<span style='color: #0000ff;'> 路邊草</span> 提供，等一下會到東塔 3F 裡國王的床是可以免費休息的 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在旅店中兔子又變成了「記者 錄影威」XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這次很不錯喔，可以讓你重溫之前經過的劇情！( 而且主要都是有配音的過場 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器防具店有賣不錯的裝備，如果錢夠的話建議整裝一下<br /> ( <span style='color: #ff0000;'>建議至少買個閃雷爪給楊裝備上</span>，等一下的戰鬥會有不錯的效果 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 都逛完之後就繼續前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-007.png' width='486' height='326' /><br /> <a name='法布爾城 2F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>法布爾城 2F</span><br /> 從樓上來後先不要往前，先往下方的入口出去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-008.png' width='486' height='326' /><br /> <a name='法布爾城 外部'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>法布爾城 外部</span><br /> 這裡左右分別有東塔與西塔，我們先往右邊的東塔去 <strong>( 1 )</strong></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-009.png' width='486' height='326' /><br /> <a name='法布爾城 東塔 2F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>法布爾城 東塔 2F</span><br /> 往上來到 2F，有個背影看起來不錯的女子，如果你請她跳舞的話&#8230;.<br /> ( 請三思而後行XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在 2F 的右上角的花瓶處面朝右，會發現一個「<span style='color: #800000;'>酒神之酒</span>」，然後繼續往 3F 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-011.png' width='486' height='326' /><br /> <a name='法布爾城 東塔 3F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>法布爾城 東塔 3F</span><br /> 在 3F 的床旁邊有一個寶箱 ( <span style='color: #800000;'>帳篷</span> )，原來這裡是陛下的臥室啊&#8230;.</p>
<p>( <span style='color: #ff0000;'>2/15 update:</span> 感謝網友 <span style='color: #0000ff;'>路邊草</span> 提供，國王的床是可以免費休息的 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完就可以下去，接著往左邊的西塔去 <strong>( 2 )</strong></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-013.png' width='486' height='326' /><br /> <a name='法布爾城 西塔 1F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>法布爾城 西塔 1F</span><br /> 進到 1F 的左邊就有三個寶箱：<span style='color: #800000;'>爆彈碎片、南極之風、恢復藥</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/27 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>Romberg</span> 提供資訊，西塔 1F 右側還有一個<span style='color: #800000;'>宙斯之怒</span> )</p>
<p>在三個寶箱的右側，有一盞蠟燭，可以得到一個「<span style='color: #800000;'>宙斯之怒</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-015-1.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>上去到 3F 會遇到楊的老婆，上去打個招呼吧！</p>
<p><span style='color: #ff0000;'>( 後期我們會需要再回來找她的，請記住楊的妻子在法布爾城的西塔 3F )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 拿完就可以回去內部的 2F 繼續前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著會進入劇情，遇到法布爾王說明原委後，決定要在此協助法布爾城迎戰！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後羅莎與莉迪亞會留在城內，其餘三人會到城門口，緊接著便是六連戰 ( 敵人有重覆 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第一戰、第三戰、第六戰：<span style='color: #0000ff;'>上校、巴隆海軍 x2</span><br /> ( 先把後面的上校打死後，小兵會陷入混亂 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第二戰、第五戰：<span style='color: #0000ff;'>萊西、毛怪哥布林、魚人</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第四戰：<span style='color: #0000ff;'>石像鬼</span> <span style='color: #ff0000;'>( 小心一開始的龍捲風攻擊，效果是單體瀕死 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後眾人退到了水晶之間，凱因竟然出現了，而且指名要與塞西爾對戰！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進入了一場摯友之間充滿無奈的戰鬥&#8230;. ( 三回合後會結束 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 劇情：當凱因要下最後一擊時，羅莎與莉迪亞出現了，喝止了凱因，但緊接著高貝扎也出現了，看來凱因是被高貝扎操縱的啊！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 隨後凱因取走了水晶，高貝扎綁走了羅莎，在一旁的莉迪亞救起了大家，討論一番後決定先稍做休息，並準備去救出羅莎，接著就往下先回到大殿中</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-029.png' width='486' height='326' /><br /> <a name='法布爾城 大殿'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>法布爾城 大殿</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>12/27 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>Romberg</span> 提供資訊，大殿裡還有一個「<span style='color: #800000;'>赫耳墨斯之靴</span>」 )</p>
<p>下來大殿後，先到左側的罐子，可以取得一個「<span style='color: #800000;'>赫耳墨斯之靴</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-030-1.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>接著在大殿的右上角有一個暗道，通往右邊的寶箱</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-030.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 取得寶箱：<span style='color: #800000;'>蜘蛛絲、惡魔之盾、以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就回到 1F 左側的旅店，前往左邊櫃檯就會自動休息</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 隔天大家出現在東塔 3F，國王準備了船隻，並送了一把「<span style='color: #800000;'>奪命之刃</span>」給塞西爾<br /> ( 奪命之刃：攻擊 30 一定機率秒殺敵人 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開前可以回去旅店/道具店看有沒有什麼要補充的，準備好了之後就出城。等一下要上船，這時候可以先將除了塞西爾之外的所有人裝備都卸下了，航行的途中會有事件發生，最後會只剩塞西爾一人。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>重要提醒 (一)：</span></p>
<p><span style='color: #ff0000;'>上船之前，卸下所有人的裝備是很重要的 ( 塞西爾除外 )，尤其如果你是玩第二輪遊戲，角色身上穿了第一輪繼承的精金鎧、洋蔥裝備之類，這些人離隊之後再回來時，是不會帶著你的裝備回來的，請特別注意！</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>重要提醒 (二)：</span></p>
<p><span style='color: #ff0000;'>如果你是第二輪遊戲，這是吉爾伯特最後待在隊伍中的機會，可以給他使用兩個傳繼能力道具</span>，後續再遇到他時，就能多取得兩個傳繼能力道具。通常第一輪時，不會留道具給他使用，而是建議在最終戰之前留下「<span style='color: #800000;'>精神波、消明</span>」這兩個給第二輪的吉爾伯特使用。( 如果你是玩第一輪，就不用管這個提醒 )</p>
<p>詳情可以參考：<span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_ability_items_list.php#道具取得攻略簡表' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 前往右上方的海岸邊，國王準備的船就在那裡</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上船前楊的老婆會拿出一個傳繼能力道具「<span style='color: #800000;'>反擊</span>」給我們，這是第三個，這個倒是建議可以給塞西爾用掉，在戰鬥時受到物理攻擊時會自動反擊，很好用的一個能力！<span style='color: #0000ff;'>( 用了之後要設定到戰鬥指令中 )</span></p>
<p>( 傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在往巴隆航行的途中，眾人遇到了傳說中的幻獸「利維亞桑」襲擊！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 醒來後又只剩塞西爾獨自一人&#8230;..接下來該怎麼做呢？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-2/05-castle_fabul-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p>FF4 Part 1-2 法布爾城水晶失守 ( 完 )</p></font></center>
";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
