<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy IV ( FF4, iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 3-1 初探月世界</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#各地支線與物品取得'><span style='color: #000080; text-decoration: underline;'>各地支線與物品取得</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#艾布拉納洞窟'><span style='color: #000080; text-decoration: underline;'>艾布拉納洞窟</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得傳繼能力道具：<span style='color: #800000;'>火焰流</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#試煉之山'><span style='color: #000080; text-decoration: underline;'>試煉之山</span></a></span></span> ( 遇到第一個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#精金洞窟'><span style='color: #000080; text-decoration: underline;'>精金洞窟</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>「<span style='color: #800000;'>鼠尾巴</span>」交換取得「<span style='color: #800000;'>精金</span>」<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.4 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#法布爾城'><span style='color: #000080; text-decoration: underline;'>法布爾城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>找楊的妻子取得「愛的平底鍋」</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.5 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#凱波'><span style='color: #000080; text-decoration: underline;'>凱波</span></a></span></span> ( 遇到第二個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#迷霧村'><span style='color: #000080; text-decoration: underline;'>
迷霧村</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得傳繼能力道具：<span style='color: #800000;'>MP + 50%</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#陸行鳥村'><span style='color: #000080; text-decoration: underline;'>陸行鳥村
</span></a></span></span> ( 遇到第三個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城'><span style='color: #000080; text-decoration: underline;'>巴隆城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：奧丁
<span style='color: #ff0000;'> ( 偷取傳繼能力道具：<span style='color: #800000;'>暗黑</span> )</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>習得召喚魔法「奧丁」</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.9 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回地底世界'>
<span style='color: #000080; text-decoration: underline;'>返回地底世界</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>1.9.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#矮人城'><span style='color: #000080; text-decoration: underline;'>矮人城</span></a></span></span> ( 遇到第四個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>1.9.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#鐵匠可可羅的家'><span style='color: #000080; text-decoration: underline;'>鐵匠可可羅的家</span></a>
</span></span> ( 遇到第五個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;-</span>交出「精金、傳說之劍」<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>1.9.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#特美拉'><span style='color: #000080; text-decoration: underline;'>特美拉
</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>1.9.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#風精靈洞窟'><span style='color: #000080; text-decoration: underline;'>風精靈洞窟</span></a></span></span> ( 遇到第六個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;
&#8212;&#8212;-</span><span style='color: #ff0000;'>習得召喚魔法「風精靈」</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;-</span>取得傳繼能力道具：<span style='color: #800000;'>凝氣</span> ( 以及<span style='color: #800000;'>踢擊、忍耐</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>1.9.5 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#風精靈洞窟本次取得條件說明'><span style='color: #000080; text-decoration: underline;'>本次取得條件說明</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.10 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回法布爾城'><span style='color: #000080; text-decoration: underline;'>返回法布爾城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;&#8211;</span>
歸還「愛的平底鍋」，取得「<span style='color: #800000;'>菜刀</span>」<br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#密西迪亞'><span style='color: #000080; text-decoration: underline;'>密西迪亞</span></a></span></span>
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; <span style='color: #ff0000;'>取得魔導船</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回地底 - 鐵匠可可羅的家'><span style='color: #000080; text-decoration: underline;'>返回地底 &#8211; 鐵匠可可羅的家</span></a></span></span> ( 取得「<span style='color: #ff0000;'><span style='color: #800000;'>王者之劍</span></span>」)</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.3 &#8211; 前往月球<br /> (03) <span style='color: #000080;'><a href='#哼鳴威一族的住所'><span style='text-decoration: underline; color: #000080;'><span style='text-decoration: underline;'><span style='text-decoration: underline;'>哼鳴威一族的住所</span></span></span></a></span> ( 遇到第七個幻獸小孩 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; 取得傳繼能力道具：<span style='color: #800000;'>經驗獵手</span></p>
<p>(04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#月之地下通道'><span style='color: #000080; text-decoration: underline;'>月之地下通道</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
4.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#月之地下通道 西'><span style='color: #000080; text-decoration: underline;'>月之地下通道 西</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#月之地下通道 東'><span style='color: #000080; text-decoration: underline;'>月之地下通道 東</span></a></span></span><br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#月民之館'><span style='color: #000080; text-decoration: underline;'>月民之館</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; <span style='color: #ff0000;'>福索雅加入隊伍</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; 返回地球</p>
<p>(06) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人'><span style='color: #000080; text-decoration: underline;'>巴別巨人</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人 巨人口'>
<span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人口</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#巴別巨人 巨人頸'><span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人頸</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>特級恢復藥 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人 巨人胸'>
<span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人胸</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>萬能藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人 巨人腹'><span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人腹
</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>特級以太</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人 巨人內部通道'><span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人內部通道</span></a></span></span> 
( 地圖獎勵：<span style='color: #800000;'>聖靈藥</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人 巨人內部樓梯間'><span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人內部樓梯間</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：四天王聯合戰<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別巨人 巨人控制裝置'><span style='color: #000080; text-decoration: underline;'>巴別巨人 巨人控制裝置</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：控制系統、攻擊系統、防禦系統<br /> (07) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回巴隆城'><span style='color: #000080; text-decoration: underline;'>返回巴隆城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.1 &#8211; 取得傳繼能力道具：<span style='color: #800000;'>HP + 50%</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='各地支線與物品取得'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>各地支線與物品取得</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到地面世界後，我們就可以先到各地去取得一些重要的物品，拿齊了之後再回到地底去，完成現階段的支線事件，最後再前往密西迪亞進行劇情的主線。<br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ff0000;'>請注意：以下的事件都是在前往密西迪亞取得「魔導船」之前去的，如果你先去取得了魔導船，就無法取得楊的傳繼能力道具與之後楊的妻子給的菜刀。</span><br /> <span style='color: #ffffff;'>-</span><br /> 建議可以照以下我所安排的路線順序，大概會剛好順路繞一圈地圖，
不用上上下下跑來跑去，一站接著一站去走就可以取得所有物品並觸發事件。<br /> <a name='艾布拉納洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>艾布拉納洞窟</span><br /> 剛上來地面後，第一站我們就前往位於地圖左下角的艾布拉納洞窟</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 氣墊船目前應該停在洞窟門口，無法過去，記得先去換成企業號，把氣墊船吊回旁邊的陸地上，再換乘氣墊船到洞窟去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進到洞窟後，通過 B1 地圖，直接走到內部的艾布拉納鎮，往密道入口進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著必須通過密道 1 與密道 2 的地圖，到達盡頭處 ( <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_part_2_3.php#艾布拉納洞窟' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>艾布拉納洞窟地圖</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡可以發現一個傳繼能力道具：<span style='color: #800000;'>火焰流</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-005.png' width='486' height='326' /><br /> <a name='試煉之山'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>試煉之山</span><br /> 接下來繼續使用企業號，吊起你的氣墊船帶著，先前往地圖東南方的試煉之山</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 你要用獵隼號來也可以，但是後續還要回去帶氣墊船會很麻煩&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上了試煉之山後，一路走到山頂 ( <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_part_1_3.php#試煉之山' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>試煉之山地圖</span></a></span></span> )，到右側的儲存點附近</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡會發現第一個幻獸小孩，莉迪亞會請他趕快回幻獸鎮</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-009.png' width='486' height='326' /><br /> <a name='精金洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>精金洞窟</span><br /> 接著繼續帶著氣墊船，到地圖東側中間一個小島位置 ( 在祕銀村南側 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 先在祕銀村把氣墊船放下，然後換乘氣墊船往東南方前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會來到一個更小的島，上面有個洞窟就是精金洞窟</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後往上走到底，會遇見兩個小人，找站在台階上的對話</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 對話後會跳出道具選擇，選擇「<span style='color: #800000;'>鼠尾巴</span>」( 在 <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_part_2_3.php#幻獸鎮%20地圖1' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>幻獸洞窟 > 幻獸鎮寶箱</span></a></span></span> 中取得的 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著便能<span style='color: #ff0000;'>取得「精金」</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開精金洞窟後，可以把氣墊船丟在這裡，直接北上前往法布爾城</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-016.png' width='486' height='326' /><br /> <a name='法布爾城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>法布爾城</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 從 2F 的下面出口來到外部，然後前往左側的西塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往上走到西塔 3F 找楊的妻子，楊的妻子得知了訊息後，會交出一個「愛的平底鍋」要我們再回去把楊敲醒</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開法布爾城後，接著前往地圖中間，沙漠中央的凱波村</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-020.png' width='486' height='326' /><br /> <a name='凱波'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>凱波</span><br /> 沙漠中無法停放飛空艇，所以要停在沙漠左側的邊緣陸地，再走過來即可</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後到旅店左上角水池邊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡會發現第二個幻獸小孩，喝著綠洲之水呢&#8230;.過太爽&#8230;.XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開凱波，繼續往左側的迷霧村前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-024.png' width='486' height='326' /><br /> <a name='迷霧村'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>迷霧村</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後到左上角的房子內</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就會發現一個傳繼能力道具：<span style='color: #800000;'>MP + 50%</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-027.png' width='486' height='326' /><br /> <a name='陸行鳥村'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>陸行鳥村</span><br /> 接著要往地圖西北方的陸行鳥村</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 別忘了陸行鳥村旁邊都是森林，要將飛空艇停在南側的特羅亞城，再走路北上</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了陸行鳥村要做什麼呢？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到村內的中上方位置</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會找到第三個幻獸小孩，也跑得真遠啊&#8230;&#8230;</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 以上的物品事件都取得之後，接下來就前往我們熟悉的巴隆城去。上面的事件中目前為止應該取得了四樣物品：<span style='color: #800000;'>火焰流、精金、愛的平底鍋、MP + 50%</span>，並且你已經找到了三個幻獸小孩。</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-033.png' width='486' height='326' /><br /> <a name='巴隆城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城</span><br /> 進去前可以先補滿你的 HP/MP，可以到巴隆鎮睡覺、用小屋，或是回去巴隆城內西塔樓上塞西爾的房間睡覺 ( 我很懶的&#8230;..用小屋就好了 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進到巴隆城內部往右邊出去 ( 大家應該走到很熟了吧XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出來外部後往東塔前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進了東塔往下走兩層到 B2，盡頭會再次遇到巴隆王，原來他被賦與了幻獸的力量，為了幫助我們，必須先測試我們的能耐&#8230;..接著就進入 BOSS 戰！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>奧丁</span><br /> HP：<span style='color: #0000ff;'>40001</span><br /> 攻擊：物理攻擊 ( 單體約 1200~1400 )、斬鐵劍 ( 全體非死即重傷 )<br /> 備註：<span style='color: #ff0000;'>奧丁身上有傳繼能力道具「暗黑」，請務必偷到手</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-038.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 開戰後奧丁會先有零星的物理攻擊，但速度不快，先丟個減速或蜘蛛絲給他<br /> 2. 然後讓艾吉偷盜，可以取得傳繼能力道具：<span style='color: #800000;'>暗黑</span> ( 很好偷 )<br />
3. 接下來<span style='color: #ff0000;'>優先幫全員做加速動作</span> ( 魔法或是<span style='color: #800000;'>赫耳墨斯之靴</span> )，然後放護盾<br /> 4. 如果你有使用吟唱技能 ( 我是給艾吉 )，也有學到英雄之歌，就唱這首吧！<br /> 5. 莉迪亞召喚<span style='color: #ff0000;'>利維亞桑</span>攻擊，約有 6000~8000 傷害<br /> 6. 塞西爾直接攻擊即可，羅莎除了幫忙回復外，如果有神聖魔法也可一起攻擊<br /> 7. 幾回合後奧丁會開始高舉右手，準備要殺出非死即
傷的斬鐵劍&#8230;.<br /> 8. 以上動作應可以在奧丁使出斬鐵劍之前將他打趴 ( 如果等級夠的話 )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗奧丁後，莉迪亞會<span style='color: #ff0000;'>習得召喚魔法「奧丁」</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='返回地底世界'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>返回地底世界</span><br /> 地面上的事件與物品取得都完成後，就回去換成獵隼號，往地圖南方的阿加爾特前進，我們先返回地底世界去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-040.png' width='486' height='326' /><br /> <a name='矮人城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>矮人城</span><br /> 回到地底世界後，我們先前往矮人城</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-041.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到 1F 往右側走來到武器防具店，從兩個櫃檯中間入口進去酒吧</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-042.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在酒吧櫃檯右邊會找到第四個幻獸小孩 ( 喝得爛醉是怎樣&#8230;..XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-043.png' width='486' height='326' /><br /> <a name='鐵匠可可羅的家'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>鐵匠可可羅的家</span><br /> 接著我們繼續往南飛，到地圖東南方角落附近</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-044.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在山壁邊緣會發現一間房子，這裡是鐵匠可可羅的家</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-045.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進後在門口的水井旁會先遇到第五個幻獸小孩</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-046.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在 1F 內部左下角會發現一個「<span style='color: #800000;'>萬能藥</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-047.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後從右側通道上去 2F</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-048.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 2F 的書架上會有一個「<span style='color: #800000;'>蘇摩之滴</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-049.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就把 2F 床上睡很爽的可可羅叫醒吧&#8230;&#8230;</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-050.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 對話後會出現道具選擇，選了「<span style='color: #800000;'>精金</span>」後，會再<span style='color: #ff0000;'>交出「傳說之劍」給他</span></p>
<p><span style='color: #ff0000;'>1/20 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>阿給</span> 提供情報 )</p>
<p><span style='color: #ff0000;'>如果你之前已把「傳說之劍」賣掉了也沒關係，事件還是可以順利進行的</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-051.png' width='486' height='326' /><br /> <a name='特美拉'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>特美拉</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-052.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著往左飛，在地底世界的南方邊界中央位置，有一個小村落叫特美拉<br /> ( 也在封印洞窟的東南方，距離很近 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-053.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後照例可以先把鎮上的物品搜刮一下 ( 數字說明在下方 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-054.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 1. 道具店左側牆邊：<span style='color: #800000;'>爆彈之魂</span><br /> 2. 東北方角落的木桶：<span style='color: #800000;'>不死鳥之尾</span><br /> 3. 旅店內部右側的床頭櫃 ( 右邊的 )：
<span style='color: #800000;'>大地之鼓</span><br /> 4. 左上角房子內部：<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; 寶箱：<span style='color: #800000;'>宙斯之怒、爆彈碎片、特級以太、2000 元</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>4.2 &#8211; 木箱：<span style='color: #800000;'>怪獸圖鑑</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.3 &#8211; 罐子：<span style='color: #800000;'>南極之風</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡商店的商品都很不錯，建議可以幫主角們換換裝備，像是黃金髮飾、或是鑽石類的防具等等，我也在這裡買了一些XD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-055.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器店和防具店中間是有暗道互通的，不過好像沒什麼意義XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-056.png' width='486' height='326' /><br /> <a name='風精靈洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>風精靈洞窟</span><br /> 最後我們往地圖最西北方的風精靈洞窟去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-057.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 別忘了進去前先<span style='color: #ff0000;'>對全體使用「浮空」魔法</span>，以防止地面會損血 ( 切換地圖要再施法一次 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-058.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一路來到最下層的 B3，到風精靈的屋子內去找楊 ( 風精靈洞窟地圖 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-059.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 當然要選擇「<span style='color: #800000;'>愛的平底鍋</span>」把他敲醒！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-060.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著風精靈會表示要協助戰鬥，<span style='color: #ff0000;'>莉迪亞習得召喚魔法「風精靈」</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-061.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後楊會交出傳繼能力道具：<span style='color: #800000;'>凝氣</span> ( 以及<span style='color: #800000;'>踢擊、忍耐</span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-062.png' width='486' height='326' /><br /> <a name='風精靈洞窟本次取得條件說明'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span>
<br /> <span style='color: #0000ff;'>本次取得條件說明：</span><br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>1. 凝氣：</span>戰鬥中使用為蓄力效果，最多可連續使用三次</strong><br /> 取得條件：在巴別塔之戰離開前楊離隊後，到風精靈洞窟找到楊對話沒反應，回到地面上的法布爾城，到西塔 3F 找楊的妻子，取得愛的平底鍋，再回到風精靈洞窟把楊敲醒後取得。<br /> <span style='color: #ffffff;'>-</span><br /> 
<strong><span style='color: #800000;'>2. 踢擊：</span>對敵人全體攻擊，但傷害會降低 25%</strong><br /> 取得條件：在楊離隊前對楊使用過一個傳繼能力道具後，與凝氣一起取得<br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>3. 忍耐：</span>戰鬥時使用該回合防御力提升 75%</strong><br /> 取得條件：在楊離隊前對楊使用過兩個傳繼能力道具後，與凝氣一起取得</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著繼續從右側樓梯往 2F 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-063.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在 2F 左側會發現第六個幻獸小孩 ( 想必他不是會飛就是會浮空&#8230;.XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-064.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後繼續往上走就可以直接回到地底世界了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-065.png' width='486' height='326' /><br /> <a name='返回法布爾城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>返回法布爾城</span><br /> 接著我們就再次回到地面世界，也再一次前往法布爾城</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-066.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到西塔 3F，將愛的平底鍋交還給楊的妻子，會取得「<span style='color: #800000;'>菜刀</span>」<br /> ( 菜刀是最強的投擲武器，但是我試了一下好像只能丟一次&#8230;.XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-067.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 以上的支線事件都完成後，就可以繼續劇情主線，前往南方的密西迪亞</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/01-sub-event-068.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='密西迪亞'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>密西迪亞</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就會進入劇情事件，前往祈福之塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在長老的幫助下，密西迪亞附近的海域升起了一艘巨型船艦：<span style='color: #ff0000;'>魔導船</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開密西迪亞就會看到黑色的魔導船停在旁邊，真的是好巨大啊XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 此時響起的音樂是 <span style='color: #0000ff;'>The Big Whale</span> <span style='color: #0000ff;'>( Magical Ship，魔導船 )</span>，是我在 FF4 OST 裡面最喜歡的一首音樂，憾動人心的旋律充滿了勇
氣與希望，聽著音樂會讓人彷彿擁有了十足的勇氣，象徵即將踏上月世界的主角們，具備著無比的信心！<br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>Final Fantasy IV DS：Magical Ship</span> ( 聽聽看振奮一下吧！)</strong><br /> <span style='color: #ffffff;'> -</span><br /> 魔導船的操作點有兩個，一個在最上方的綠色方塊，可以在原地圖飛行</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 另一個就是船上的水晶，可以用來往返月球與地球</p>
<p>( 下船就從左側樓梯下去即可 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-006.png' width='486' height='326' /><br /> <a name='返回地底 - 鐵匠可可羅的家'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>返回地底 &#8211; 鐵匠可可羅的家</span><br /> 取得魔導船後，要上月球之前的第一件事，就是先搭乘獵隼號返回地底</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再一次回到地底後往東南方，去鐵匠可可羅的家</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後直接找壁爐前的可可羅對話，<span style='color: #ff0000;'>取得「王者之劍」</span></p>";
echo "<p><span style='color: #ff0000;'>1/20 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>阿給</span> 提供情報 )</p>
<p><span style='color: #ff0000;'>如果你之前並沒有交出傳說之劍 ( 已賣掉的話 )，這時候還是可以獲得王者之劍的</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完王者之劍後，就能返回地面，我們終於可以準備出發去月球了&#8230;.<br /> ( 出發前的事情也太多XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/02-mysidia-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='哼鳴威一族的住所'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #0000ff;'>哼鳴威一族的住所</span><br /> ( 也有翻譯成海明威、哼哼威，隨便啦&#8230;.XDDDD )<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>1/16 Update: </span>( 補充提醒 – 隱藏召喚獸道具：<span style='color: #800000;'>爆彈怪</span> )</p>
<p>在月球地表上，可以遇到一種怪物「暗黑榴彈怪」，身上帶有極低機率掉落的隱藏召喚獸道具：爆彈怪 ( 莉迪亞專用技能道具 )，如果有要收集的人要注意，因為另一種會掉落的「治癒爆彈怪」只在巴別塔出現，後期已無法進入巴別塔，所以只剩下這個怪物會掉落，要收集就慢慢刷吧XD</p>
<p>詳情可參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_hiding_summoning_spells.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 隱藏召喚獸</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-005.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 一上來到月球後，可以先前往地圖南方的哼鳴威一族住所</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/03-hummingway_home-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡剛好可以停下魔導船 ( 真的是好大一架XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/03-hummingway_home-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就可以先去右上角位置</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/03-hummingway_home-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡可以取得一個傳繼能力道具：<span style='color: #800000;'>經驗獵手</span> ( 經驗值提升 30% )<br /> ( 我一樣給了主角塞西爾，貫穿全劇情的第一男主角嘛XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/03-hummingway_home-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在右邊的其中一隻兔子有賣高級道具，連聖靈藥都有，也有賣<span style='color: #ff0000;'>報警器</span>，後期如果需要收集一些怪物掉落的道具，報警器是很需要的 ( <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_weapons.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 尾巴與強力裝備收集</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/03-hummingway_home-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著來到左上的小房間，可以找到第七個幻獸小孩<br /> ( 剩下一個在幻獸神洞窟，建議現在先別去，等凱因歸隊後再說 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/03-hummingway_home-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='月之地下通道'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>月之地下通道</span><br /> <span style='color: #ffffff;'>-</span><br /> 在月球上的敵人一個比一個還強大，有的物理防御很高 ( 例如各種膠質怪 )，需用魔法攻擊，打起來是比地面上的敵人要難打很多，等級要升也是很快&#8230;.XDDD<br /> ( 開自動會砍很久，有些小兵不如用召喚魔法利維亞桑通常可以一次解決&#8230;XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 月球上的地點沒幾個，接下來我們前往地圖西側有兩個洞窟<br /> ( 地圖東側一個圓形區域內的洞窟是幻獸神巴哈姆特的家，現在先別去惹他&#8230; )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在下面入口旁的高台上停放好魔導船，走下來進入，就是月之地下通道的入口</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-003.png' width='486' height='326' /><br /> <a name='月之地下通道 西'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>月之地下通道 西</span><br /> 地圖獎勵：<span style='color: #800000;'>報警器 x3</span><br /> 取得寶箱：<span style='color: #800000;'>星之沙、月之幕簾、金蘋果</span> ( 遇敵：真核細胞、原核細胞 x2 )<br /> <span style='color: #ffffff;'>-</span><br /> 這裡很單純，路線也很短，拿完寶箱就可以往出口前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走出洞窟回到地圖上，要往右下方前進，可以進到東側通道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-005.png' width='486' height='326' /><br /> <a name='月之地下通道 東'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>月之地下通道 東</span><br /> 地圖獎勵：<span style='color: #800000;'>報警器 x3</span><br /> <span style='color: #ffffff;'>-</span><br /> 東側通道的位置</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡的路線更短，連寶箱都沒有，走完就能賺 3 個報警器真不錯&#8230;.XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出了通道後就往左側繼續前進，會到達另一個入口，即是月民之館</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/04-moon_under_path-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='月民之館'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>月民之館</span><br /> 通過月之地下通道西、東之後，就可以來到月民之館入口</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/05-moon_house-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進入後往前直走，會進入事件：福索雅的出現<br /> ( 原來福索雅是塞西爾的大伯&#8230;..這有一點連續劇的劇情，塞西爾表示：_____ )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/05-moon_house-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 福索雅提到了巴別巨人，且我們須回去艾布拉納旁的巴別塔<br /> 對話完後<span style='color: #ff0000;'>福索雅加入隊伍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/05-moon_house-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>提醒事項：</span><br /> 在福索雅加入後，下一步將返回地球去巴別巨人內部打四天王，且<span style='color: #ff0000;'>打完後福索雅就會離隊</span>，這會關係到後續取得的 3 個重要的傳繼能力道具 ( <span style='color: #800000;'>精神波、不死鳥、魔法全體化</span>等 )，所以照例是要先對福索雅使用兩個傳繼能力道具。<br /> <span style='color: #ffffff;'>-</span><br /> 我把<span style='color: #800000;'>改造</span>和<span style='color: #800000;'>火焰流</span>丟給了這位老頭，各位也可以自行安排</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/05-moon_house-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在月民之館 1F 的兩側盡頭分別可以回復 HP/狀態 ( 左 )，以及回復 MP ( 右 )，有需要的話可以多加利用，不妨在這附近練練級再回去地球&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/05-moon_house-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來就原路走回魔導船，返回地球去！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/05-moon_house-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴別巨人'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人</span><br /> 一返回地球就發現了巴別巨人已經誕生</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著過去的好友一一出現 ( 連雙胞胎也復活了XD )，福索雅指示進入巨人的口！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>提醒事項 (一)：</span><br /> 這裡的敵人強度也是很高，隨便一個射線就是 <span style='color: #ff0000;'>1300~1800</span> 的傷害，就連普通的物理攻擊也是很囂張，真的要小心一點&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-003.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>提醒事項 (二)：</span></p>
<p>巴別巨人也是屬於一次性的地圖，走過就沒了，所以<span style='color: #ff0000;'>請特別注意「地圖完成度 100%」及「怪物圖鑑收集」</span>，地圖完成度會關係著最後是否能取得重要的技能道具「<span style='color: #800000;'>寶物獵手</span>」。有一些寶箱的周圍地圖很容易被忽略掉，因為常常拿了寶箱人就走掉了，結果地圖沒繞完整。<span style='color: #ff0000;'>請確認你在每一個樓層都有拿到地圖獎勵再離開</span>，否則後續若發現沒有拿到「寶物獵手」會很失望，要一個一個去各迷宮找，而巴別巨人又不見的情況下&#8230;.只能下一輪繼續了。</p>
<p>( 而怪物圖鑑的收集後續會再整理，反正第一輪是無法完成怪物圖鑑 100% 的，就不用太擔心 )</p>
<p><span style='color: #ff0000;'>( 請隨時按下畫面右上角的「地圖」確認完成的百分比 )</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>如果第一輪遊戲走完最後的迷宮「月面地下溪谷」後，沒有自動取得「寶物獵手」，而你又找不到是哪裡的迷宮沒有走完全的話，可以在第二輪遊戲中繼續走完，仍會取得「寶物獵手」。在第二輪遊戲中已走過的地圖是不用重繞的，會繼承你已完成的百分比。<br /> <a name='巴別巨人 巨人口'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人口</span><br /> 第一段沒有什麼，直接往入口 1 進去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>提醒事項：</span><br /> 巴別巨人內的迷宮也是<span style='color: #ff0000;'>一次性的出現，如果沒有走完 100% 後續就消失了</span> ( 要第二輪才能再通過 )，另外如
果要收集怪物圖鑑的也是要留意自行安排。( 如果福索雅一直趴下&#8230;.看要不要考慮別救了XDDD )<br /> <a name='巴別巨人 巨人頸'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人頸</span><br /> 地圖獎勵：<span style='color: #800000;'>特級恢復藥 x3</span><br /> <span style='color: #ffffff;'>-</span><br /> 這一小段也有地圖獎勵，真輕鬆&#8230;..繼續往出口 2 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-005.png' width='486' height='326' /><br /> <a name='巴別巨人 巨人胸'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人胸</span><br /> 地圖獎勵：<span style='color: #800000;'>萬能藥 x5</span><br /> 取得寶箱：<span style='color: #800000;'>風魔手裡劍、高級恢復藥、以太、與一之箭、報警器</span><br /> <span style='color: #ffffff;'>-</span><br /> 這一段取得五個寶箱後就繼續往出口 3 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-006.png' width='486' height='326' /><br /> <a name='巴別巨人 巨人腹'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人腹</span><br /> 地圖獎勵：<span style='color: #800000;'>特級以太</span><br /> 取得寶箱：<span style='color: #800000;'>蘇摩之滴、銀蘋果</span><br /> <span style='color: #ffffff;'>-</span><br /> 這一段也是很簡單，繼續往出口 4 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-007.png' width='486' height='326' /><br /> <a name='巴別巨人 巨人內部通道'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人內部通道</span><br /> 地圖獎勵：<span style='color: #800000;'>聖靈藥</span><br /> 取得寶箱：<span style='color: #800000;'>聖靈藥</span><br /> <span style='color: #ffffff;'>-</span><br /> 最後一段有儲存點，旁邊還有一個兔子威，儲存/恢復後繼續前進出口 5</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 兔子威是賣道具的，有手裡劍、小屋和三種魔法攻擊道具</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-009.png' width='486' height='326' /><br /> <a name='巴別巨人 巨人內部樓梯間'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人內部樓梯間</span><br /> <span style='color: #ffffff;'>-</span><br /> 繼續往前就會進入 BOSS 戰了，四天王聯合之戰！<br /> ( 看起來是聯合，結果是一個一個上場XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 四天王 BOSS 戰：<span style='color: #0000ff;'>斯卡米留尼</span><br /> HP：25000，弱點：<span style='color: #ff0000;'>火 / 回復系道具、回復魔法</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 四天王 BOSS 戰：<span style='color: #0000ff;'>凱納槽</span><br /> HP：25000，弱點：<span style='color: #ff0000;'>冰、雷</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 四天王 BOSS 戰：<span style='color: #0000ff;'>巴爾巴希莉亞</span><br /> HP：25000，弱點：<span style='color: #ff0000;'>聖、毒</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 四天王 BOSS 戰：<span style='color: #0000ff;'>盧比坎特</span><br /> HP：25000，弱點：<span style='color: #ff0000;'>冰 ( 披風打開時 )</span><br /> 備註：<span style='color: #ff0000;'>披風合起時會吸收冰屬性</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 四個天王的 HP 是連貫的，合計共 10 萬，打法和弱點與之前相同<br /> 2. 除第一個之外基本上後面三位由<span style='color: #ff0000;'>莉迪亞的召喚魔法為主力攻擊</span><br /> 3. 
第一戰 <span style='color: #0000ff;'>斯卡米留尼 </span>可以用羅莎的<span style='color: #ff0000;'>康療</span>或<span style='color: #ff0000;'>愈療</span>來打他即可解決<br /> 4. 第二戰 <span style='color: #0000ff;'>凱納槽 </span>一樣在集中水源時以召喚「拉姆」攻擊，躲進殼內時用冰或雷魔法<br /> 5. 第三戰 <span style='color: #0000ff;'>巴爾巴希莉亞 </span>要注意大旋風的瀕死攻擊，莉迪亞可召喚利維亞桑<br /> 6. 第四戰 <span style='color: #0000ff;'>盧比坎特 </span>的<span style='color: #ff0000;'>火焰流</span>攻擊很強，務必注意回復<br /> 7. 盧比坎特的披風收起時會吸收冰魔法要注意<br /> 8. 
在披風打開時以召喚希瓦來攻擊，很快就能結束<br /> 9. 稍微計算一下每個天王快趴下時，傷害會延續到下一位，可好好利用<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打完後就繼續往前進吧！還有一戰要打 ( 不放心的話可以走回頭儲存一下 )<br /> <span style='color: #ff0000;'>( 補充：建議將塞西爾與艾吉的武器換成無屬性的武器 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-015.png' width='486' height='326' /><br /> <a name='巴別巨人 巨人控制裝置'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴別巨人 巨人控制裝置</span><br /> 最後遇到了巴別巨人的控制系統，緊接著又進入 BOSS 戰</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>攻擊系統 ( 左 )、控制系統 ( 中 )、防禦系統 ( 右 )</span><br /> HP：<span style='color: #0000ff;'>攻擊 12000、控制 25000、防禦 10000</span><br /> 弱點：控制 / 攻擊：<span style='color: #ff0000;'>雷</span>，防禦：<span style='color: #ff0000;'>土 ( 並會吸收其他所有屬性 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 攻擊建議順序：<span style='color: #ff0000;'>攻擊系統 ( 左 ) > 控制系統 ( 中 ) > 防禦系統 ( 右 )</span><br /> 2. 開戰後第一優先丟他們全體減速 ( 務必在控制系統對自己放反射前
就丟 )<br /> 3. 然後莉迪亞先召喚拉姆打全體，接著其他人主打攻擊系統<br /> 4. 下一個打中間的控制系統，可召喚利維亞桑 ( 真好用 )，防禦會吸收別管他<br /> 5. 剩下右邊的防禦系統後，因為所有屬性都會被吸收，所以直接砍就好<br /> 6. 防禦系統會一直幫控制系統恢復，但每次約 800 多而已，不用擔心<br /> 7. 最後就狂砍剩下的防禦系統，或是用無屬性的魔法攻擊即可，他不會反擊<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打完後高貝扎出現，福索雅說出了高貝扎與塞西爾的身世之謎&#8230;..<br /> 結果高貝扎竟然是塞西爾的親哥哥&#8230;.. ( 果然是八點檔無誤 )<br /> <span style='color: #ffffff;'>-</span><br /> 接著就是一連串的劇情與回憶，要控制小高貝扎去外面水池邊找父親，再回來屋子裡發現倒下的母親，繼續劇情</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 終於最後福索雅與高貝扎自行前往月球 <span style='color: #ff0000;'>( 福索雅離隊 )</span>，巴別巨人倒下，眾人正在商討如何從這裡逃離時，<span style='color: #ff0000;'>凱因再次出現並加入隊伍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這一段劇情有點長&#8230;..中間還有小羅莎、小塞西爾、小凱因XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了魔導船中可以行動時，第一次只能強制往前調查水晶前往月球<br /> ( 因為羅莎與莉迪亞一開始被塞西爾趕走&#8230;.. )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了月球後，羅莎與莉迪亞再次出現，這次就能正常行動了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/06-babil_giant-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='返回巴隆城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>返回巴隆城</span><br /> 又到了月球後，先別急著走，再次啟動你的魔導船，回到地球的巴隆城吧！<br /> ( 船都快比城還大了XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/07-back_to_baron-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進到 1F 後往左側走出去外部</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/07-back_to_baron-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了西塔附近進入右邊的門</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/07-back_to_baron-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往右側的樓梯可以前往 2F 的中央露台</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/07-back_to_baron-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡會出現一個士兵，對話後可取得傳繼能力道具：<span style='color: #800000;'>HP + 50%</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/07-back_to_baron-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來就可以再次回到月球，繼續探索我們最後的冒險區域了！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_3-1/07-back_to_baron-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>- </span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<p>FF4 Part 3-1 初探月世界 ( 完 )</p></font></center>
";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
