<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='font-size: 22px; color: #800000;'>Final Fantasy IV ( FF4, iOS )</span></p>
<p><span style='font-size: 22px; color: #800000;'>Walkthrough, Graphic Guide</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>Part 2-2 前進地底巴別塔</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#露營威'><span style='color: #000080; text-decoration: underline;'>露營威 > 聆聽威 > 多情威</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆鎮'>
<span style='color: #000080; text-decoration: underline;'>巴隆鎮</span></a></span></span> ( 露營威 > <strong>聆聽威</strong> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#特羅亞鎮'><span style='color: #000080; text-decoration: underline;'>特羅亞鎮</span></a></span></span> ( 聆聽威 > <strong>
多情威</strong> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>酒吧櫃檯對話 &#8211; 開啟胖陸行鳥點唱機功能<br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#祕銀村'><span style='color: #000080; text-decoration: underline;'>祕銀村</span></a></span></span><br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#阿加爾特'><span style='color: #000080; text-decoration: underline;'>阿加爾特</span></a></span></span>
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; 多情威 > <strong>布丁威</strong> ( 要求提供<span style='color: #800000;'>彩虹布丁</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; <span style='color: #ff0000;'>調查水井出現地底入口</span><br /> (04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城'>
<span style='color: #000080; text-decoration: underline;'>矮人城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; BOSS 戰：卡爾克布莉娜 ( 二種型態 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; BOSS 戰：高貝扎<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.3 &#8211; <span style='color: #ff0000;'>莉迪亞加入隊伍</span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.4 &#8211; 取得傳繼能力道具：<span style='color: #800000;'>誘敵</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城 東塔'><span style='color: #000080; text-decoration: underline;'>矮人城 東塔</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城 西塔'><span style='color: #000080; text-decoration: underline;'>矮人城 西塔</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城 B1'><span style='color: #000080; text-decoration: underline;'>矮人城 B1</span></a></span></span><br />
 <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城 B2'><span style='color: #000080; text-decoration: underline;'>矮人城 B2</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.9 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人基地'><span style='color: #000080; text-decoration: underline;'>矮人基地</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.10 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#矮人城 開發室'><span style='color: #000080; text-decoration: underline;'>矮人城 開發室</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;-</span>取得「<span style='color: #800000;'>成人讀物</span>」，與開發室所有人員完成對話</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;-</span>取得傳繼能力道具：<span style='color: #800000;'>後列斬</span><br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔'><span style='color: #000080; text-decoration: underline;'>巴別塔</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B13'><span style='color: #000080; text-decoration: underline;'>巴別塔 B13</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>南極之風 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B12'><span style='color: #000080; text-decoration: underline;'>巴別塔 B12</span></a></span></span> ( 地圖獎勵：
<span style='color: #800000;'>北極之風 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B11'><span style='color: #000080; text-decoration: underline;'>巴別塔 B11</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>白色獠牙</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#巴別塔 B10'><span style='color: #000080; text-decoration: underline;'>巴別塔 B10</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B9'><span style='color: #000080; text-decoration: underline;'>
巴別塔 B9</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>萬能藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B8'><span style='color: #000080; text-decoration: underline;'>巴別塔 B8</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>5.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴別塔 B7'><span style='color: #000080; text-decoration: underline;'>巴別塔 B7</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#巴別塔 B6'><span style='color: #000080; text-decoration: underline;'>巴別塔 B6</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰 &#8211; 第一回合：盧格、巴爾納伯<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰 &#8211; 第二回合：盧格<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.9 &#8211; <span style='color: #ff0000;'>取得「盧格的鑰匙」</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.10 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回巴別塔 B9'>
<span style='color: #000080; text-decoration: underline;'>返回巴別塔 B9</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;-</span>遇敵：哥布林隊長 x3<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.11 &#8211; <span style='color: #ff0000;'>楊獨自留下犧牲 ( 離隊 )</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.12 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回巴別塔 B13'><span style='color: #000080; text-decoration: underline;'>返回巴別塔 B13</span></a></span></span></p>
<p>(06) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城'><span style='color: #000080; text-decoration: underline;'>巴隆城</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.1 &#8211; <span style='color: #ff0000;'>與西德徒弟對話，企業號加入「拖吊」功能</span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.2 &#8211; 前往霍布斯山旁吊起氣墊船</p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='露營威'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>露營威 > 聆聽威 > 多情威</span><br /> <span style='color: #ffffff;'>-</span><br /> 在打敗了佐特塔的巴爾巴希莉亞後，我們可以先在地圖上逛逛。關於常常不期而遇的那隻紅衣兔子，到底還想要變成什麼呢？<br /> <span style='color: #ffffff;'>-</span><br /> 寫於命名威的流程，在主線劇情中是以穿插的方式，加入攻略中，主要就是該時期你可以遇到的情況下，我就會盡量都寫清楚這樣。</p>
<p>( 關於命名威的全事件流程，請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_hummingway_events.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 命名威全事件流程</span></a></span></span> )<br /> <a name='巴隆鎮'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴隆鎮</span><br /> 接下來我們可以先再次回到遊戲開始的巴隆鎮</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/01-baron-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/01-baron-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 到鎮上的武器防具店裡去找他</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/01-baron-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 結果這次變成了「聆聽威」了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/01-baron-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 原來聆聽威的功能就是讓我們重溫過去遊戲中聽到音樂喔！好讚！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/01-baron-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> FF 的音樂真的都非常好聽，我們真的要很感謝植松伸夫老師，做了這麼多令人永遠難忘的 FF 系列音樂，每次聽到都會好感動，畫面都出來了&#8230;.<br /> <a name='特羅亞鎮'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>特羅亞鎮</span><br /> 再來往左上角飛，到特羅亞鎮去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 逛著逛著，走到了旅店的後方路上</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡又遇到他了，變成了「多情威」，原來最近在把妹XDDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後居然還要我們去酒吧裡面幫他把妹XDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 沒辦法，該幫的忙還是要幫，來到酒吧找這位櫃檯妹妹聊幾句好了&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 多情威出現後，便告訴我們之後可以找胖陸行鳥當點唱機囉！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/02-troia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 命名威的支線先寫到這裡，後線當然還有，不過有的也需要一些時間與特定的道具 ( 例如 <span style='color: #800000;'>彩虹布丁</span> )，所以屆時還會再繼續說明的。( 請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_hummingway_events.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 命名威全事件流程</span></a></span></span> )<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='祕銀村'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>祕銀村</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 祕銀村在地圖的東側，有一長串列島的左邊，一個小島嶼上<br /> ( 遊戲中的翻譯有些地方寫成迷霧村了… 差很多 = = )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 先到地圖右下角的水井，可以找到一個「<span style='color: #800000;'>少女之吻</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著是右上角的房子右側，在木桶前面地上有一個「<span style='color: #800000;'>祕銀杖</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 防具店右下方地面：<span style='color: #800000;'>祕銀匕首</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器店左側草堆上：<span style='color: #800000;'>5000 元</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後是地圖左下角的位置：<span style='color: #800000;'>減肥食品</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完這些道具之後，可以逛一下這裡的武器與防具店，全部都是祕銀製品，價錢是還好，只是好像並沒有特別好的，我只買了一個祕銀護手</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 村子裡的人都是小人、青蛙或豬，一一對話後就會發現沒什麼重要的情報，旅店也好貴 ( $500/次 )，逛完之後就可以離開，前往劇情的主線：阿加爾特</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/03-the_village_of_mithril-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='阿加爾特'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>阿加爾特</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 阿加爾特位於地圖南部的中間一座島上，若從巴隆城一路往南飛就會看到</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡的路繞來繞去的，建議在手機上看著地圖，再對照我的數字標示比較好找</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 1. 中央那口井外圍的左上角草堆上：<span style='color: #800000;'>恢復藥</span><br /> 2. 再往下走一點點的草叢處：<span style='color: #800000;'>不死鳥之尾</span><br /> 3. 左側中央的直條平台，往下的盡頭：<span style='color: #800000;'>高級恢復藥</span><br /> 4. 左上角的水池右上方草叢：<span style='color: #800000;'>小屋</span><br /> 5. 中央房子左側，在柵欄與草叢中間：<span style='color: #800000;'>大地之鼓</span><br /> 6. 中央房子門口的小草堆：<span style='color: #800000;'>南極之風</span><br /> ( 如果你是照我進度，應該會看到那隻兔子在中間房子門口XDDDD )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來就找這隻兔子吧！結果他又變成了純情的「布丁威」XDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 布丁威要我們幫忙找一個東西叫做「<span style='color: #800000;'>彩虹布丁</span>」，找到後再拿來給他&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 彩虹布丁是從各種顏色的「膠質怪」( 就是長得像布丁一樣的軟軟的那個就是了 ) 身上會掉落，但是極難得手，一般怪物身上會有四種掉落物品，依照機率區分稱為第一檔至第四檔，彩虹布丁一般是屬於第三或第四檔
才會掉落，機率極低&#8230;..<br /> <span style='color: #ffffff;'>-</span><br /> 現階段會遇到的膠質怪不多，如果你時間很多的話，不妨先去「蟻獅洞窟 B2」試試看手氣，那裡會經常出現黃色膠質怪&#8230;. ( 我打了將近 100 次都沒掉XDDDD ) 後期比較建議的是粉紅色的布丁公主，屬於第三檔掉落。( 詳情請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_hummingway_events.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 命名威全事件流程</span></a></span></span> )</p>
<p><span style='color: #ffffff;'>-</span><br /> 由於現階段要打出彩紅布丁實在太花時間，所以我們先繼續進行主線的攻略，後續再回來進行這件事情。另外，在布丁威站的房子裡面還有一個<span style='color: #800000;'>不死鳥之尾</span>，不過現在進不去，也是之後再回來拿就好。( 其實不拿好像也沒差XDDDD )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 道具拿完，武器、防具店也都逛完之後，就到地圖中間的那口井去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ff0000;'>重要提醒：</span></p>
<p><span style='color: #ff0000;'>下一個離隊的人是西德</span>，如果你還沒對他使用過傳繼能力道具的，現在還來得及，建議的部份可以看上一篇。<br /> <span style='color: #ffffff;'>-</span><br /> 調查水井後出現道具選擇，就選「<span style='color: #800000;'>岩漿石</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 之後岩漿石被西德丟到了井中，引起了火山噴發，村子旁邊出現了一個大洞！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著就回到飛空艇，往大洞口飛去出現「！」後，點一下畫面就能進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/04-agart-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>( 要進入之前建議還是先存檔一下，因為暫時回不來地面上 )</span><br /> <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='矮人城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>矮人城</span><br /> <span style='color: #ffffff;'>-</span><br /> 進入地底後，往左下走就會看到一座城：矮人城</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>- </span><br /> <span style='color: #ffffff;'>-</span><br /> 來到 1F 後，先往左側入口進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後是旅店與道具店，在櫃檯的左側可以找到「<span style='color: #800000;'>5000 元</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 這邊的道具店也有賣「<span style='color: #800000;'>怪獸圖鑑</span>」，建議先買一些 ( 大概 10 個差不多 )，後續 BOSS 戰會用到，調查屬性弱點時使用。( 白魔法的偵測也可以，且因為西德會離隊，要有備無患 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 要繼續回大廳往前走之前，先提醒一下：<br /> 1. 等一下進去找矮人王時，對話之後將進行連續兩場 BOSS 戰 <span style='color: #ffffff;'>( 沒有休息時間 )</span><br /> <span style='color: #ff0000;'>2.</span> <span style='color: #ff0000;'>BOSS 戰之前西德就會先離隊</span> <span style='color: #ff0000;'>( 別忘了卸下西德身上的所有裝備 )</span></p>
<p><span style='color: #ff0000;'>( 第一輪的朋友，還沒對西德使用過傳繼能力道具的話，現在還有最後機會 )</span><br /> 3. 第一戰不難打，麻煩的是第二戰的高貝扎，塞西爾的等級與 HP 量很重要<br /> 4. 我大約隊伍平均 38 級時來這裡，打了三次還是打不過<br /> 5. 倒不是因為高貝扎攻擊太強，是因為只剩塞西爾加上後續會出現的莉迪亞<br /> 6. 羅莎、楊、凱因都需要在戰鬥中從死亡狀態手動復活才能繼續應戰<br /> 7. 往往救起來馬上就又趴了 ( 高貝扎的攻擊都是全體攻擊&#8230;. )<br /> <span style='color: #ffffff;'>-</span><br /> 以上是等一下會面臨的情況，斟酌一下目前的隊伍狀態，有信心就上吧！準備好就回到 1F 大廳，往上走就會發生劇情及兩場 BOSS 戰！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ff0000;'>與矮人王談話之間，西德便會離隊</span> ( 回去修理飛空艇 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 後來發現有人在偷聽談話，眾人趕到王座後的水晶之間，發現了幾個很討厭人偶，原來是高貝扎派來的，準備好應戰吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰 &#8211; 第一階段：<span style='color: #0000ff;'>卡爾克 x3、布莉娜 x3</span><br /> HP：<span style='color: #0000ff;'>卡爾克 ( 後排 ) 1500、布莉娜 ( 前排 ) 500</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 這六個人偶有兩種打法，如果你想增加怪獸圖鑑收集率，<span style='color: #ff0000;'>先將兩種人偶各打死一個，再留下任意一種人偶，就會合體成大人偶，這樣就能收到三種怪物，不會在怪物圖鑑上出現問號「？」</span></p>
<p>( 詳請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_enemies_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 怪物圖鑑收集</span></a></span></span> )<br /> 2. 剩下單一顏色的人偶會融合成大型人偶 ( 卡爾克布莉娜 )<br /> 3. 如果想省事點，就一次打前排，一次打後排，最後剩下前後排各一個時，再一次解決掉，就不會出現融合的情況 ( 只要剩其中一種會融合 )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰 &#8211; 第二階段：<span style='color: #0000ff;'>卡爾克布莉娜</span><br /> HP：<span style='color: #0000ff;'>9315</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 1. 物理攻擊一樣會被反擊，羅莎趴掉的機會很高&#8230;.<br /> 2. <span style='color: #ff0000;'>讓楊用凝氣三次後進攻</span>，傷害約有 2500~2600 左右<br /> 3. 塞西爾協助回復與解除混亂狀態 ( 如果有人中的話 )<br /> 4. 凱因持續跳躍攻擊即可 ( 注意：下來之後還是有可能會被反擊 )<br /> 5. 楊出手約 2~3 次即可打敗 BOSS<br /> 6. 若時間拖太久 BOSS 會再次分裂成剛剛的六個小人偶，又要重來一次&#8230;.<br /> 7. 打完會馬上接下一場，盡可能讓塞西爾補滿 HP 應戰 ( 其他沒差 )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 隨後高貝扎出現，進入第二場戰鬥！( 不給休息的啊XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 打沒幾下高貝扎就會用麻痹攻擊，並召喚出黑龍，接著就趴了三個剩下塞西爾</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著神祕的霧龍出現！擊退了黑龍，也給了高貝扎不小的傷害，是誰做的？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 原來是莉迪亞！( 長大了？變正妹XDDDD )<br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>高貝扎</span><br /> HP：<span style='color: #0000ff;'>9999</span><br /> 攻擊：<span style='color: #ff0000;'>震雷、冰凍、烈炎、生物 ( 都是對全體&#8230;. )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 剛開始可以行動時，<span style='color: #ff0000;'>凱因看準時機跳躍，「有機會」可以躲過一死</span><br /> 2. 莉迪亞出現後，我們的攻擊主力就是她身上的「召喚」能力<br /> 3. 由於高貝扎會切換護罩，所以必須用「<span style='color: #800000;'>怪獸圖鑑</span>」調查弱點 ( 或用偵測魔法 )<br /> 4. 確認當下的弱點後，立即讓莉迪
亞召喚對應的幻獸<br /> 5. 例如：<span style='color: #0000ff;'>希瓦 ( 冰 )、拉姆 ( 雷 )、伊弗利特 ( 火 )</span><br /> 6. 開戰後塞西爾趕緊先丟一個「<span style='color: #ffffff;'><span style='color: #ffffff;'><span style='color: #ffffff;'><span style='color: #800000;'>蜘蛛絲</span></span></span></span>」讓 BOSS 減速，<span style='color: #ff0000;'>接著先復活羅莎</span><br /> 7. 還未調查到弱點前，莉迪亞可以先碰碰運氣，我打了三次都是先召喚希瓦<br /> 8. 接著塞西爾優先使用「赫爾墨斯之靴」幫自己或是莉迪亞加速<br /> 9. 若羅莎復活後有機會行動，第一優先補全體 HP，第二加速，第三復活其他人<br /> 10. 還有多餘出手機會的話，羅莎可以幫全體補上魔盾減少傷害<br /> 11. <span style='color: #ff0000;'>整場就是在復活、補血、調查弱點、召喚攻擊中渡過就是了&#8230;..</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 打敗後<span style='color: #ff0000;'>莉迪亞加入隊伍 </span>( 原來她跑去幻獸界了啊，還長真快XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 畫面切跳回王座間，矮人王交給我們一個傳繼能力道具：<span style='color: #800000;'>誘敵</span><br /> ( 這根本就是為了塞西爾設計的技能道具，什麼都沒有就血最多XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 聽完矮人王的建議後，我們知道了下一個地點是：巴別塔。<br /> 先來看一下好久不見的莉迪亞狀態如何？30 級&#8230;.HP 600 出頭…這算啥XD<br /> 花點時間幫她練練級吧！這太嬌弱了啦XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 可以行動之後，讓我們先搜刮一下這裡的寶箱，回到 1F 先往右上去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 上來後是武器店與防具店，雖然有不錯的武器與防具，但建議等我們拿完寶箱後再來看要買啥比較好。這裡的兩側各有一個入口，<span style='color: #0000ff;'>買完裝備後就先走右邊過去</span><br /> <span style='color: #ff0000;'>( 兩個櫃檯中間的入口是酒吧，可以通往開發室，等拿完寶箱再說 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-018.png' width='486' height='326' /><br /> <a name='矮人城 東塔'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>矮人城 東塔</span><br /> 這裡有一個寶箱：<span style='color: #800000;'>矮人之斧</span>，拿完繼續從中間上去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 2F 地上都是罐子，要從下面繞到左邊中間的罐子，有一個「<span style='color: #800000;'>酒神之酒</span>」<br /> 拿完後繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 3F 有四個寶箱，牆壁之間都有通道可以過去，拿完後就回到 1F<br /> 寶箱：<span style='color: #800000;'>以太、銀沙漏、聖靈藥、力量護臂</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到 1F 之後走中間下面的入口出去矮人城的外部</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 出來後往下繞到左邊的西塔去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-023.png' width='486' height='326' /><br /> <a name='矮人城 西塔'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>矮人城 西塔</span><br /> 1F 什麼都沒有，左下角是回到旅店，繼續從中間上樓</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 2F 也都是罐子，在右下方罐子有一個「<span style='color: #800000;'>酒神之酒</span>」，繼續上樓</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 3F 有點複雜，要走牆壁中的通道，有點難解釋，看截圖的標線吧！( 這裡畫好久&#8230;.. )<br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥、黑帶裝、以太、聖靈藥</span><br /> <span style='color: #ff0000;'>( 拿完就回去 1F，並從左下角的樓梯回到旅店 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到旅店後，從右上角的樓梯下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-027.png' width='486' height='326' /><br /> <a name='矮人城 B1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>矮人城 B1</span><br /> B1 有四個區域，由左至右：醫務室<strong>(1)</strong>、B2 入口<strong>(2)</strong>、胖陸行鳥房間<strong>(3)</strong>，最右側<strong>(4)</strong>則有很多罐子，可以找到<span style='color: #800000;'>三個基薩爾野菜</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #800000;'>基薩爾野菜</span>的位置如下圖</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 拿完之後回到左邊第二個區域，和矮人對話後可以進去他背後的門</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-030.png' width='486' height='326' /><br /> <a name='矮人城 B2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>矮人城 B2</span><br /> 下來 B2 後，先走過去拿三個寶箱：<span style='color: #800000;'>小屋 x3</span>，接著往最左下角下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-031.png' width='486' height='326' /><br /> <a name='矮人基地'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>矮人基地</span><br /> 最後這個區域的中間位置有一個「<span style='color: #800000;'>爆彈碎片</span>」( <span style='color: #ffffff;'><span style='color: #ff0000;'>紅圈處</span> </span>)，左側小區域中有個<span style='color: #0000ff;'><strong>回復壺</strong></span> ( <span style='color: #0000ff;'>藍</span><span style='color: #0000ff;'>圈處 </span>) 而最左下角的出口會到地圖上，前往巴別塔就要從這個出口</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-032.png' width='486' height='326' /><br /> <a name='矮人城 開發室'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'><span style='color: #0000ff;'>矮人城 開發室</span> </span>( 取得傳繼能力道具：<span style='color: #800000;'>後列斬</span> )<br /> 寶物都拿完後，就回到<span style='color: #ff0000;'><strong>武器防具店</strong></span>吧！往兩個櫃檯中間的入口進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後是酒吧，在右下角有個暗道往右走，可以通往開發室 ( 裡面是工作人員 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 到了開發室後，繞過來右側的入口下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 下面是休息室，在陸行鳥後面的書架上，會發現一個「<span style='color: #800000;'>成人讀物</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ff0000;'>接著開始和所有開發室的人對話</span>，就從休息室這裡開始吧！<br /> ( 旁邊這個黃衣服的怪物對話會進入戰鬥，應該會全滅，但不會有事的XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到樓上再和所有人 <span style='color: #ff0000;'>( 大人、小人、怪物、動物都算 )</span> 對話一次</p>
<p>有的只跟你講幾句話，有的則會發生戰鬥 ( 還有一個是走廊上突然遇敵 )<br /> 注意一共有四個區域：<span style='color: #0000ff;'>左吧台區<strong>(1)</strong>、走廊上<strong>(2)</strong>、中房間<strong>(3)</strong>、右房間<strong>(4)</strong></span></p>
<p><span style='color: #ff0000;'>1/2 Update：左邊的吧台區附近有一個小人坐在那，這很容易漏掉，要仔細看</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-038.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 全部都對話完畢後<span style='color: #ff0000;'> ( iOS 版的 Game Center 會出現成就完成的訊息 )</span><br /> 再次回到樓下休息室，黃衣怪的左邊就會出現光點，取得傳繼能力道具：<span style='color: #800000;'>後列斬</span>！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 這個後列斬是個好東西，<span style='color: #0000ff;'>建議給塞西爾使用</span>，因為他防御性最好，站後排還能保持傷害輸出簡直完美，這樣現階段就能讓凱因與楊站前排，塞西爾與兩位女性都站後排</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-040.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 取得道具<span style='color: #800000;'>後列斬</span>之後，就可以準備出發了。回到剛剛 B2 再往下的矮人基地，從最左下角離開。( 如果需要在附近練等級的話，可多利用 <span style='color: #0000ff;'>藍圈處 </span>的回復壺 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/05-castle_of_dwarves-041.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 在前往巴別塔之後，<span style='color: #ff0000;'>接著下來離隊的人會是楊</span>，其中關係到後續會取得的傳繼能力道具<br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>1. 凝氣：</span>戰鬥中使用時效果為累積力量 ( 物理攻擊力 )，最多可使用三次</strong><br /> 取得條件：主線劇情 ( 精靈洞窟 ) 過後會直接取得<br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>2. 踢擊：</span>攻擊全體化，但傷害會降低為 25%</strong><br /> 取得條件：對楊使用過一個傳繼能力道具後，與「凝氣」一起獲得<br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>3. 忍耐：</span>使用後該回合防御力提升 75%</strong><br /> 取得條件：對楊使用過兩個傳繼能力道具後，與「凝氣」一起獲得<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>我的建議是：</span></p>
<p>如果你的傳繼能力道具是足夠的，建議給楊使用兩個道具，因為「<span style='color: #800000;'>忍耐</span>」這個能力在第二輪打隱藏 BOSS 的時候還蠻有用的 ( 後來是給塞西爾使用，打隱藏 BOSS 時搭配誘敵，效果很好 )。若是第一輪你只給楊使用了一個傳繼道具，那麼在第二輪的時候只要再補一個給他即可。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>有網友補充測試證明，第一輪給過傳繼能力道具之後，第二輪不需要再給同樣數量的道具，即可取得該角色完整的三個傳繼能力道具。例如第一輪你給過雙胞胎一共三個技能進具，後來取得了連續詠唱等能力；到了第二輪就算你什麼都沒給雙胞胎使用，後面還是可以取得連續詠唱的！</span>( 但我自己還沒試，要等第三輪來試XD )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 順帶一提，我還把「<span style='color: #800000;'>裝哭</span>」給了莉迪亞，而「<span style='color: #800000;'>逞強</span>」還在考慮中，反正我覺得自己是註定要玩第二輪、第三輪了，也許這一輪我還是會把「逞強」丟給莉迪亞，不過未決定之後，還是先留著吧！</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴別塔'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔</span><br /> <span style='color: #ffffff;'>-</span><br /> 從矮人城地下的基地出來後，一路要往左上方前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 走到快要接近巴別塔入口時，會看到矮人的戰車，繼續往前進戰車會掩護我們</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 前面就是巴別塔入口了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>重要提醒：</span></p>
<p>巴別塔屬於一次性地圖，因為地圖完成度關係到最後可否取得「<span style='color: #800000;'>寶物獵手</span>」這個重要的技能道具，所以在此請確認 B13 ~ B9 的地圖都要完成 100%，而 B8 ~ B7 因為要等第二次來巴別塔才能完全走完 100%，所以<span style='color: #ff0000;'>這次一定會走不完 B8 ~ B7 是不用擔心的</span>。另外巴別塔地下的怪物若您要收集怪物圖鑑也記得都要遇上，否則也要等下一輪了再來。( 只在這裡出現的怪物後續會在補充說明 )</p>
<p>( 收集怪物資料請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_enemies_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 怪物圖鑑收集</span></a></span></span> )<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 這裡的敵人有不少具備火屬性，應避免使用火屬性武器，以免攻擊老是被吸收。另外要特別注意這個敵人，當你一次遇到三隻狂放烈焰的時候&#8230;.能回復就趕快回復，很容易就會有人趴下去了XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-004.png' width='486' height='326' /><br /> <a name='巴別塔 B13'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B13</span><br /> <span style='color: #ffffff;'>-</span><br /> 地圖獎勵：<span style='color: #800000;'>南極之風 x5</span><br /> 取得寶箱：<span style='color: #800000;'>緊急出口、高級恢復藥、以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 拿完寶箱後，往出口 2 繼續前進<br /> <a name='巴別塔 B12'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B12</span><br /> <span style='color: #ffffff;'>-</span><br /> 先走最下面的 3 ( 寶箱 )，接著走右側的 4 ( 寶箱 )，最後走中間的出口 5<br /> 地圖獎勵：<span style='color: #800000;'>北極之風 x3</span><br /> 取得寶箱：<span style='color: #800000;'>綠色貝雷帽、玄冰槍</span> ( 遇敵：監視眼 )、<span style='color: #800000;'>冰印劍</span> ( 遇敵：監視眼 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 寶箱遇敵：<span style='color: #0000ff;'>監視眼</span><br /> 這傢伙會呼叫雜兵來跟你打，不過其實都不難<span style='color: #ff0000;'> ( 收集怪物圖鑑的話要注意，只有這裡有 )</span><br /> ( 兩個寶箱的武器剛好給塞西爾與凱因裝備上，很好用！)</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-007.png' width='486' height='326' /><br /> <a name='巴別塔 B11'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B11</span><br /> <span style='color: #ffffff;'>-</span><br /> 先取得寶箱，接著先走下面右邊的出口 6 ( 寶箱 )，再回來走出口 7</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 地圖獎勵：<span style='color: #800000;'>白色獠牙</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥、不死鳥之尾、貓爪、殺手弓</span> ( B10 )、<span style='color: #800000;'>南極之風</span> ( B10 )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 如果你有遇到這顆蛋，也可以先不要攻擊他，等他變成怪物後再攻擊</p>
<p><span style='color: #ff0000;'>1/16 Update: </span></p>
<p><span style='color: #ff0000;'>但是如果你要收集怪物圖鑑，那就必須將這顆蛋直接砍爆，資料才不會出現「？」</span></p>
<p><span style='color: #ff0000;'>( 怪物圖鑑資料中會有名稱，但點進去看都是？？？時，是不算完成收集的 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 這顆蛋也有機會變成<span style='color: #ff0000;'>綠龍</span>，要小心綠龍的天雷攻擊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-010.png' width='486' height='326' /><br /> <a name='巴別塔 B10'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B10</span><br /> <span style='color: #ffffff;'>-</span><br /> 左側的 8 是儲存點，繞到右側後，9 是遇敵寶箱 ( <span style='color: #800000;'>寒冰鎧</span> )，10 是空房間，接著到右上的 11 是遇敵寶箱 ( <span style='color: #800000;'>寒冰盾</span> )，最後往左上角的出口 12 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x5</span><br /> 取得寶箱：<span style='color: #800000;'>寒冰鎧 </span>( 遇敵：監視眼 )、<span style='color: #800000;'>寒冰盾</span> ( 遇敵：監視眼 )<br /> <span style='color: #ffffff;'>-</span><br /> 10 的空房間看起來有點怪怪，不過我在裡面頂多遇到奇美拉而已，有人遇到特別一點的怪物嗎？也可以分享一下XDDDD<br /> <a name='巴別塔 B9'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B9</span><br /> <span style='color: #ffffff;'>-</span><br /> 先拿入口旁邊的寶箱，中間 13 的門目前是上鎖的，繞完往右拿寶箱並進入出口 14</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 地圖獎勵：<span style='color: #800000;'>萬能藥 x5</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥、北極之風</span><br /> <a name='巴別塔 B8'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B8</span><br /> <span style='color: #ffffff;'>-</span><br /> 到了 B8 往左邊的 15 前進會到 B7，目前 B8 與 B7 尚無法全部走完，後續會先到 B6 發生 BOSS 戰，等下一次再回到巴別塔時就能走完</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-013.png' width='486' height='326' /><br /> <a name='巴別塔 B7'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B7</span><br /> <span style='color: #ffffff;'>-</span><br /> 右側的 16 是儲存點，進去儲存後，往左下拿寶箱，接著就進入右下出口 17</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 取得寶箱：<span style='color: #800000;'>特級以太</span><br /> <a name='巴別塔 B6'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴別塔 B6</span><br /> <span style='color: #ffffff;'>-</span><br /> 來到 B6 走到中間往上之後，就會進入事件與 BOSS 戰</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 準備事項：<br /> 1. 塞西爾能力裝備<span style='color: #800000;'>誘敵、後列斬、保護</span> ( 當然是要保護一下莉迪亞，血太薄了XD )<br /> 2. 裝備的部份我是裝光之盾，其他沒有特別要提醒的<br /> 3. 塞西爾的誘敵看情況使用，如果你等級較高一些應該不用也沒差</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰 &#8211; 第一回合：<span style='color: #0000ff;'>盧格、巴爾納伯</span><br /> HP：<span style='color: #0000ff;'>盧格 6000、巴爾納伯 9000</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略注意：</p>
<p>提醒：這一場如果要完整收集怪物圖鑑需要<span style='color: #ff0000;'>「第二輪」遊戲才能完成</span>，因為共有三種：盧格、巴爾納伯以及合體機器人，<span style='color: #800000;'>第一輪來這裡可以先打死巴爾納伯，再打死盧格，第二輪來這裡打死巴爾納伯後，別急著打死盧格，過一下他會變成合體機器人，再打死他即可完成三個怪物圖鑑收集。</span>如果先打死盧格，則巴爾納伯隨後會「自爆」，這樣在怪物圖鑑中只有名字，其他都是「？」無法完成收集要注意。</p>
<p>( 圖鑑收集可參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_enemies_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 怪物圖鑑收集</span></a></span></span> )</p>
<p><span style='color: #ffffff;'>-</span><br /> 1. 先用雷屬性魔法攻擊巴爾納伯，或是直接砍<br /> 2. 如果先攻擊盧格的話，巴爾納伯會自爆 ( 傷害高達 5000，會有人趴下 )<br /> 3. 這場不難打，建議還是好好的先打完巴爾納伯再攻擊盧格<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰 &#8211; 第二回合：<span style='color: #0000ff;'>盧格 ( 變身後 )</span><br /> HP：<span style='color: #ff0000;'>12000</span>，弱點：<span style='color: #ff0000;'>雷、回復</span><br /> 技能：反轉瓦斯 ( 傷害值與回復值交換，會重覆交換要注意 )、火焰放射</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'><strong>技術型攻略：</strong></span><br /> 1. 盧格的反轉瓦斯很單純就是交換傷害值與回復值的計算<br /> 2. 每次反轉瓦斯出現時，就會交換一次，其實只要記好目前的狀況為何即可<br /> 3. 例如第一次使用後，可以讓羅莎用「康療 or 愈療」攻擊他，傷害甚至達 9999<br /> 4. 承上，交換後就要「<span style='color: #ff0000;'>自砍同伴</span>」來補血 ( 讓塞西爾砍的話可以補好多XD )<br /> 5. 或者可以讓莉迪亞用「冰火雷」的全體魔法來幫大家補血<br /> 6. 途中又再遇到
反轉時，就會變回正常狀況，只要留意目前的情況即可<br /> 7. 正常情況下的盧格弱點是雷，可用莉迪亞召喚「拉姆」給予高傷害<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'><strong>偷懶型攻略：</strong></span><br /> 1. 一開始被反轉時，就讓兩個人各丟出一個聖靈藥，傷害 9999 x2，搞定<br /> 2. 聖靈藥很珍貴，但是如果你想偷懶，就這麼做吧&#8230;.<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 大家認為我用哪一種打法呢？當然是第一種，這樣才有真正的攻略精神。而且通常 3~4 回合左右就可以打敗他了，只要注意當前傷害值與回復值的順序即可。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 打敗盧格後，會<span style='color: #ff0000;'>取得「盧格的鑰匙」</span>，可以用來打開剛剛 B9 上鎖的門</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 前面是一個傳送裝置，但目前無法使用，我們往回走吧！另外順便提醒，打完 BOSS 會先離開巴別塔，<span style='color: #ff0000;'>這時候楊會離隊！別忘了卸下楊身上的所有裝備，</span><span style='color: #ff0000;'>並且如有傳繼能力道具要使用現在還有最後的機會可以做決定！</span>( 請參考前面矮人城最後一段的建議事項 )</p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-020.png' width='486' height='326' /><br /> <a name='返回巴別塔 B9'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>返回巴別塔 B9</span><br /> 回到 B9 後，就往中間原本上鎖的門走去 <span style='color: #ff0000;'>( 使用盧格的鑰匙開啟 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 進入後會遇敵：<span style='color: #0000ff;'>哥布林隊長 x3</span> ( 小雜兵XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 劇情：哥布林啟動了巨炮，楊決定獨自留下，把眾人趕出了房間，又有人要準備犧牲了&#8230;&#8230;.這劇情真的是賺人熱淚啊&#8230;. ( 感動 ing )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 結果門就這樣損壞了，沒辦法救楊，只好往回走下去，一直要走回 B13 啊&#8230;..<br /> ( 走來走去的好煩人，又不能傳送，這裡有沒有電梯啊XDDDDDD )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>1/10 Update:</span> 感謝網友 <span style='color: #0000ff;'>leo</span> 提供離開無法傳送的迷宮方法</p>
<p>補充說明：莉迪亞若有學到 <span style='color: #ff0000;'><span style='color: #800000;'>異次元</span> </span>魔法，可以使用後返回上一層迷宮</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-024.png' width='486' height='326' /><br /> <a name='返回巴別塔 B13'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>返回巴別塔 B13</span><br /> 事件：千辛萬地回到 B13 後，高貝扎的聲音又出現了，還來一招過河拆橋XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 逃出來後，西德駕著飛空艇趕了過來，但是飛空艇到了赤翼隊的追擊，西德決定跳下飛空艇，丟炸彈封住地面的洞口，又要犧牲一個&#8230;&#8230; ( 再次流淚 ing )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 飛空艇回到地面上後，趕緊往北回到巴隆城去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴隆城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巴隆城</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到巴隆城後，到大廳往右走，到東側的外部去 ( 還記得怎麼走吧？)</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 走出來後會在外面遇到西德的徒弟，找他們對話</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著他們會協助將<span style='color: #ff0000;'>企業號增加「拖吊」的功能</span>，就能運送之前用過的氣墊船</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 事件過後會自動離開巴隆城，乘上飛空艇，現在就往西北方向去</p>
<p>我們的氣墊船就停在霍布斯山旁邊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 把飛空艇飛在氣墊船的上方，按下右下角的「吊起」即可裝載起來</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 裝上後就往西南方的大型島嶼前進，那裡將是我們的下一個目的地</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-2/06-the_tower_of_babil-034.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<p>FF4 Part 2-2 前進地底巴別塔 ( 完 )</p></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
