<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;' data-mce-mark='1'>Final Fantasy IV ( FF4, iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;' data-mce-mark='1'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;' data-mce-mark='1'> </span></p>
<p><span style='color: #800000; font-size: 22px;' data-mce-mark='1'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;' data-mce-mark='1'> </span></p>
<p><span style='color: #800000; font-size: 22px;' data-mce-mark='1'>Part 2-1 佐特塔擊破</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p>(01) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#密西迪亞'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>密西迪亞</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>1.1 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#密西迪亞 祈福之間'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>密西迪亞 祈福之間</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>1.2 &#8211; 取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>合力詠唱 x2</span> ( 以及<span style='color: #800000;' data-mce-mark='1'>連續詠唱、裝哭、逞強</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>1.3 &#8211; 
<span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#密西迪亞本次取得條件說明'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>本次取得條件說明</span></a></span></span><br /> (02) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>
<a href='#迷霧村'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>迷霧村</span></a></span></span><br /> (03) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#陸行鳥之
森'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>陸行鳥之森</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>3.1 &#8211; 錄影威轉變為「露營威」<br /> (04) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#特羅亞城'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城</span></a></span></span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>4.1 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#特羅亞城 1F - 1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城 1F &#8211; 1</span></a></span></span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#特羅亞城 B1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城 B1</span></a></span></span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>4.3 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#特羅亞城 1F - 2'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城 1F &#8211; 2</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>
&#8212;&#8212;&#8211;</span>4.4 &#8211; 遇見吉爾伯特，<span style='color: #ff0000;' data-mce-mark='1'>取得「私語草」</span><br /> (05) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#特羅亞鎮'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞鎮</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>5.1 &#8211; 可於酒吧用 10 萬元購得會員證 ( 沒錢就算了… )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>5.2 &#8211; 取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>金幣獵手</span><br /> (06) 
<span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#陸行鳥村'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>陸行鳥村</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='color: #ff0000;' data-mce-mark='1'>找到黑陸行鳥</span><br /> 
(07) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#磁力洞窟'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>7.1 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#磁力洞窟 B1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟 B1</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>以太</span> )<br /> 
<span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>7.2 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#磁力洞窟 B2'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟 B2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>吸血鬼之牙 x3
</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>7.3 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#磁力洞窟 B3'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟 B3</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>
靜寂之鐘</span> ) ( 第一個儲存點 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>7.4 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#磁力洞窟 B4'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟 B4</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>特級以太</span> ) ( 第二個儲存點 )</p>
<p><span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>7.5 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#磁力洞窟 水晶之間'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟 水晶之間</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>
&#8212;&#8212;&#8212;&#8212;&#8211;</span>BOSS 戰 &#8211; 第一回合：暗黑精靈<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8212;&#8212;&#8211;</span>BOSS 戰 &#8211; 第二回合：暗黑精靈<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8212;&#8212;&#8211;</span>BOSS 戰 &#8211; 第三回合：暗龍<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>7.5 &#8211; 
<span style='color: #ff0000;' data-mce-mark='1'>取得土之水晶</span><br /> (08) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#返回特羅亞城'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>返回特羅亞城</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>8.1 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>
<a href='#返回特羅亞城 2F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城 2F</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>8.2 &#8211; 醫務室找吉爾伯特對話<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>8.3 &#8211; 取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>歌唱</span> ( 以及<span style='color: #800000;' data-mce-mark='1'>隱身、醫藥</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>
8.4 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#特羅亞城本次取得條件說明'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>本次取得條件說明</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>8.5 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#返回特羅亞城 B1'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城 B1</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>8.6 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#返回特羅亞城 B2'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>特羅亞城 B2</span></a></span></span> ( 取得 <span style='color: #800000;' data-mce-mark='1'>18 個寶箱</span> )<br /> (09) 
<span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.1 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 1F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 1F</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>宙斯之怒 x5</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.2 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 2F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 2F</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>眾神之怒 x3</span> 
)<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.3 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 3F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 3F</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>藍色獠牙
</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.4 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 4F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 4F</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>聖靈藥
</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.5 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 5F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 5F</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>銅沙漏
x3</span> ) ( 儲存點 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：梅加斯三姊妹 ( 多格、馬格、拉格 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.6 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 6F'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 6F</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>
&#8212;&#8212;&#8211;</span>9.7 &#8211; 高貝扎撤退、<span style='color: #ff0000;'>泰拉犧牲 ( 離隊 )</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.8 &#8211; 取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>回憶</span> ( 以及<span style='color: #800000;' data-mce-mark='1'>快速詠唱、誓死抵抗</span> )<br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;
</span>9.9 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔本次取得條件說明'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>本次取得條件說明</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.10 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#佐特塔 7F'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>佐特塔 7F</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>9.11 &#8211; <span style='color: #ff0000;' data-mce-mark='1'>凱因、羅莎加入隊伍</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：巴爾巴希莉亞<br /> (10) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#巴隆城'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>巴隆城</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>10.1 &#8211; <span style='color: #ff0000;' data-mce-mark='1'>取得岩漿石</span><br /> (11) <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>
<a href='#返回磁力洞窟'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>返回磁力洞窟</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8211;</span>11.1 &#8211; <span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #000080; text-decoration: underline;' data-mce-mark='1'><a href='#返回磁力洞窟 水晶之間'>
<span style='color: #000080; text-decoration: underline;' data-mce-mark='1'>磁力洞窟 水晶之間</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>龍捲風</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='密西迪亞'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #0000ff;' data-mce-mark='1'>密西迪亞</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在打完凱納槽，取得了飛空艇之後，我們變得自由多了！這時候其實可以先用飛空艇把整張地圖繞一下，清除還沒有探索過的迷霧區，讓地圖看起來更清楚一些。下一個地點原
本應該是特羅亞城，但是我們可以先去幾個地方，取得重要的物品與一些零散的道具等等，地點是<span style='color: #0000ff;' data-mce-mark='1'>密西迪亞、迷霧村</span>與<span style='color: #0000ff;' data-mce-mark='1'>陸行鳥森林</span>。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span>
<br /> 另外提醒一下，有了飛空艇之後，如果你之前忘記去拿傳繼能力道具，例如在凱波的「<span style='color: #800000;' data-mce-mark='1'>道具知識</span>」、試煉之山的「<span style='color: #800000;' data-mce-mark='1'>詛咒</span>」等等，現在都可以再飛回去拿。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ff0000;'>1/16 補充說明：</span></p>
<p><span style='color: #ff0000;'>您也可以從巴隆鎮中間房子裡的「魔鬼之路」直接傳送到密西迪亞來。</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 還記得密西迪亞的位置嗎？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 一進去就直接到中間的祈福之館，然後往之前長老站的位置後方階梯上去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來後在原本放水晶的位置左側有個門進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-004.png' width='486' height='326' /><br /> <a name='密西迪亞 祈福之間'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>密西迪亞 祈福之間</span><br /> 上來這個地方稱為「祈福之間」，繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 上來發現長老與兩個魔法師在看風景 ( 誤 )，去找長老對話</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 長老說，帕羅姆與普羅姆把希望寄託在主角們身上了<br /> 於是一次取得了共計 5 個傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>連續詠唱、裝哭、逞強、合力詠唱 x2</span>！</p>
<p>( 正常情況下是「<span style='color: #800000;' data-mce-mark='1'>合力詠唱 x2</span>」)</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 一口氣取得五個如下，看來<span style='color: #800000;' data-mce-mark='1'>連續詠唱</span>真的挺吸引人的啊&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/01-mysidia-008.png' width='486' height='326' /><br /> <a name='密西迪亞本次取得條件說明'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>本次取得條件說明：</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>1. 連續詠唱：</span>連續發動兩次魔法</strong><br /> 
取得條件：在帕羅姆與普羅姆在巴隆城最後石化前 ( 等同離隊 )，對兩人使用了共計三個傳繼能力道具，之前有建議過 ( 其實是後來補上的XD )，給帕羅姆吃「詛咒」，普羅姆吃「自動補給、道具知識」，這樣就吃了三個了。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 在這樣的條件下，現在就可以取得「連續詠唱」這個能力。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>2. 裝哭</span>：敵方單體物理防御力下降 50%</strong><br /> 取得條件：在帕羅姆與普羅姆在巴隆城最後石化前 ( 等同離隊 )，對普羅姆使用了一個
傳繼能力道具，在此取得。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>3. 逞強</span>：戰鬥中智力加倍 ( 提升 100% )</strong><br /> 取得條件：在帕羅姆與普羅姆在巴隆城最後石化前 ( 等同離隊 )，對帕羅姆使用了一個傳繼
能力道具，在此取得。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>4. 合力詠唱 x2</span>：效果為兩位同伴一起發動強力魔法 ( 根據使用的角色組合 )</strong><br /> 取得條件：在巴隆城的雙胞胎石化劇情之後，在此取得。
<br /> ( 該道具的效果我還沒試，故尚未能幫大家說明與建議 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 由上面的說明可以知道，除了第 4 項的兩個「合力詠唱」為必定取得外，<span style='color: #800000;' data-mce-mark='1'>前面三個都必須要對雙胞胎使用過傳繼能力道具才能獲得！這根本就是玩弄人嘛&#8230;..</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 一開始沒多久在凱波村遇到生病的羅莎時，我們取得了第一個傳繼能力道具「自動恢復藥」( 在道具欄位裡叫「自動補給」)，但當時誰知道
要留下來啊&#8230;.通常都會給主角或是莉迪亞給吃了吧！？甚至後來取得的「道具知識、詛咒、反擊」，也很少有人會好好的留下來給雙胞胎吃的，除非看過攻略，有痛過這樣&#8230;&#8230;<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 不瞞大家，我調了記錄從遇到生病羅莎的點重新玩了，花了我不少時間&#8230;.不過看著自己的攻略走，一下子就到雙胞胎石化的劇情了，頂多又多花了一些練級的時間而已，如果你還是覺得很不甘心「連續詠唱」沒取得，那&#8230;..不妨下定決心，重新來過，這個道具算是很值得的。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 但是我在前面也有說過，盡情享受 FF 劇情的美好也是我們玩 FF 的主要原因，有時間就重玩，沒時間也不用太煩惱
，就只是個遊戲…XD<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 後續還會有類似的條件式取得的傳繼能力道具，我會再提前說明與建議，抱歉這次因為我也是第一次玩，沒注意到提醒大家先別使用 ( 後來有補上前面的文章內了 )，如果跟著我之前未更新的攻略到了這裡沒取得的話，跟大家說聲抱歉！<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 當然，等我這次好好的通關，攻略寫完之後，我也一定會製作一份完整的傳繼能力道具的取得條件列表，讓大家更清楚來龍去脈。( 所有的傳繼能力道具不非玩一輪就能拿齊的，要拿齊恐怕要第二輪、第三輪&#8230;.好變態的 FF4….XDDD )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>1/6 Update:</span><span style='color: #ff0000;'> 傳繼能力道具列表及攻略流程已完成</span></p>
<p>請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完上述傳繼道具之後，就可以離開密西迪亞，前往另一個地點：迷霧村<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline; color: #0000ff;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span><br /> <a name='迷霧村'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>迷霧村</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 還記得迷霧村嗎？就是一開始塞西爾與凱因帶著爆彈戒指去，遇到莉迪亞的村子，後來一直沒有機會再去，現在有了飛空艇就可以回去看看有什麼道具可以拿，雖然迷霧村已經殘破不堪，但是該拿的還是要拿XDDDDDD<span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 迷霧村在巴隆城的北方，地圖中間偏左的位置</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-002.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 首先到走到地圖的右上角</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 水池右側的草堆上，會發現一個「<span style='color: #800000;' data-mce-mark='1'>爆彈碎片</span>」( 之前爆炸留下的嗎XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 再來到地圖的右下角，草叢中是有暗道可以過去的</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來這一小塊區域會發現另外兩個「<span style='color: #800000;' data-mce-mark='1'>爆彈碎片</span>」( 紅圈處 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著到旅店左上方的屋子去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 牆邊的壁爐是可以進去的，進去後碰到壁就往右 ( 稍偏右下的方向 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 暗道中必須完全摸黑前進 ( 沒地圖可看 )，路徑大約是：<span style='color: #0000ff;' data-mce-mark='1'>右下 > 右上一小段 > 右下</span><br /> ( 看下面截圖路線就很清楚了 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著會到一個小房間有兩個寶箱：<span style='color: #800000;' data-mce-mark='1'>黃金髮飾、布衣</span>，右下角還有一個暗道繼續走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 暗道的路徑一樣會卡一下，大約是：<span style='color: #0000ff;' data-mce-mark='1'>左下 > 左上一小段 > 左下</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 盡頭也是兩個寶箱：<span style='color: #800000;' data-mce-mark='1'>變化棒、紅寶石戒指</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在迷霧村的武器店與防具店中，總共只有賣三樣東西：<span style='color: #800000;' data-mce-mark='1'>長鞭、舞者匕首、詩人短袍</span><br /> ( 沒什麼用處&#8230;&#8230; )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/02-mist-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完物品之後，我們先前往迷霧村北方海面上的一個小島，在那邊有一個小小的陸行鳥之森，去找一下那隻搞笑的兔子XDDDD<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='陸行鳥之森'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>陸行鳥之森</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/03-chocobo_forest-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 迷霧村的北方海面上，有一個很小的小島，上面有一個圓型的陸行鳥之森</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/03-chocobo_forest-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這裡會找到「錄影威」，結果他現在迷上了露營，成了旅行者「<span style='color: #0000ff;' data-mce-mark='1'>露營威</span>」XD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/03-chocobo_forest-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 他會提醒你劇情錄影的部份可以找陸行鳥之森的朋友看 ( 就是胖陸行鳥 )，並且會問你是否願意賣給他帳篷？<span style='color: #ff0000;' data-mce-mark='1'>絕對不要賣他！因為他會用區區 300 元買掉你所有的帳篷，這是詐騙，是詐騙，是詐騙啊啊啊啊！！！</span>( 激動不爽中XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/03-chocobo_forest-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這裡也提醒一下不知道的朋友，白色陸行鳥是可以恢復 MP 的喔！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/03-chocobo_forest-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 另外也要補充一下，錄影威之前在<span style='color: #0000ff;' data-mce-mark='1'>試煉之山的南方</span>應該就能遇到，如果你當時已經遇過他了，也向你問過帳篷的事了，現在這裡應該不會遇到。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 找完了「露營威」後，我們就可以繼續前往我們的主線：特羅亞城。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='特羅亞城'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞城</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 在特羅亞城前面有一小塊地面剛好可以讓飛空艇著陸 ( 旁邊是特羅亞鎮 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 特羅亞城在西北大陸上，在下圖紅圈的位置</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 城內的人幾乎全是女性，記得去對話收集一下情報</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-003.png' width='486' height='326' /><br /> <a name='特羅亞城 1F - 1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞城 1F &#8211; 1</span><br /> 到了 1F 大廳後，先往右下角方向進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 走出來後再往左側的門進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來後左邊的樓梯下去目前沒東西可拿，所以先從右邊的樓梯下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-006.png' width='486' height='326' /><br /> <a name='特羅亞城 B1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞城 B1</span><br /> 下來後一共有 8 個寶箱：<span style='color: #800000;' data-mce-mark='1'>帳篷 x2、高級恢復藥 x2、以太 x2、紅寶石戒指 x2</span><br /> 拿完後回到樓上</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著從中間的入口下去</p>";
echo "<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在右下角有一個壺，可以取得一個「<span style='color: #800000;' data-mce-mark='1'>酒神之酒</span>」，拿完就可以回到 1F 大廳</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-009.png' width='486' height='326' /><br /> <a name='特羅亞城 1F - 2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞城 1F &#8211; 2</span><br /> 回來 1F 大廳後就改走左下角出去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 出來後一樣有個入口，直接進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在這裡發現了吉爾伯特，看來似乎非常虛弱地在養傷中</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 吉爾伯特詢問了眾人的近況後，<span style='color: #ff0000;' data-mce-mark='1'>拿出了「私語草」給我們</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 回到 1F 大廳繼續往內走，會有 8 個神官大人，可以去對話了解更多情報</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/04-castle_troia-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 從特羅亞城的情報中，我們得知必須前往東北方向的磁力洞窟去，而且據說金屬製的裝備在洞窟中會行動困難。不過我們現在還有可以先去一下旁邊的特羅亞鎮。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='特羅亞鎮'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞鎮</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在這裡除了收集情報之外，當然也是為了來補給，並且拿一些道具。首先到防具店的右邊草叢，可以發現一個「<span style='color: #800000;' data-mce-mark='1'>帳篷</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 再來是防具店的後方草叢 ( 要從上面的橋繞過來 )，有一個「<span style='color: #800000;' data-mce-mark='1'>高級恢復藥</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著是武器店左上方的小花，有另一個「<span style='color: #800000;' data-mce-mark='1'>高級恢復藥</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在旅店的右側有個地方可以走下水，下去後往左走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 一路往上走到水路的盡頭，會發現一個「<span style='color: #800000;' data-mce-mark='1'>不死鳥之尾</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完後往回走，在不遠處有另一個階梯可以上去，來到地圖的左上方</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在左上角這個區域的地上，一共有 4 個物品可以撿<br /> 共計可取得：<span style='color: #800000;' data-mce-mark='1'>以太、特級以太、1000 元、替身人偶</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著逛到鎮的最右上角有一間屋子</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 裡面是黑陸行鳥養殖園，在書櫃右邊有個開關，調查後會有通道可以去 B1</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 到了 B1 就看到一堆人和兩隻黑陸行鳥，右邊有個暗道可以繞到後門裡面，和柵欄內的人對話，在這裡可以了解一下關於黑陸行鳥的使用方式，因為我們後續會去的磁力洞窟就需要黑陸行鳥帶我們才能抵達</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著可以到旅店左上方的房子去逛一下，那裡是特羅亞的酒吧</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 酒吧的 1F、2F 都可以去對話一下。這邊也特別提一下門口的這兩個人，右上的會跟你要「會員證」，而門口左邊的就有賣<span style='color: #800000;' data-mce-mark='1'>會員證</span> ( 和<span style='color: #800000;' data-mce-mark='1'>基薩爾野菜</span>等等 )，<span style='color: #ff0000;' data-mce-mark='1'>但是一個 10 萬元&#8230;.</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 如果你正好有 10 萬元 ( 建議本篇打完再來，你應該就會有錢了，後續在特羅亞城還有 55000 元可以拿 )，就買下會員證後，對右上角的人使用會員證，後面就會開啟一個通道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-1.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 延著暗道繞下來往右前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-2.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 再往樓梯的入口下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-3.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這裡是帝王酒吧，向櫃檯的人對話就會進入一場表演&#8230;.XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-4.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span></p>
<p>果然塞西爾也是喜歡這一味的 ( 羅莎表示：________ )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-5.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 表演完後，走向舞台後方的通道 ( 又是暗道 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-6.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 一直往右會到另一個小房間，裡面就能取得傳繼能力道具「<span style='color: #800000;' data-mce-mark='1'>金幣獵手</span>」，效果是戰鬥時獲得金錢會提升 30% <span style='color: #0000ff;' data-mce-mark='1'>( 我後來給塞西爾裝上了，FF4 全程的主角嘛&#8230;. )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-014-7.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 逛完特羅亞鎮，補充完所需道具後，我們就可以起身前往在北方的陸行鳥村，<span style='color: #ff0000;' data-mce-mark='1'>注意必須「走路」去</span>，因為那邊飛空艇無法著陸 ( 周圍都是森林 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/05-troia-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='陸行鳥村'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>陸行鳥村</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/06-chocobo_village-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在入口左側不遠處有一個類似坐墊處 (?)，可以召喚出胖陸行鳥 ( 用基薩爾野菜 )，現在胖陸行鳥已經可以提供之前的劇場觀看了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/06-chocobo_village-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在找黑陸行鳥之前，我們先來找一下這邊地上散落的三個基薩爾野菜吧！<br /> 請到地圖上的這三個點找，會找到<span style='color: #800000;' data-mce-mark='1'>三個基薩爾野菜</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/06-chocobo_village-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 然後就可以找一隻黑色陸行鳥出發了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/06-chocobo_village-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 飛起來之後，就直接往右飛，前往磁力洞窟</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/06-chocobo_village-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='磁力洞窟'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 到了洞口就可以降下 ( 黑陸行鳥只能在森林降落，而返程時只要騎上就會自動飛回陸行鳥村 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 磁力洞窟的位置就在陸行鳥村往東，特羅亞城的東北方</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br />
<span style='color: #0000ff;' data-mce-mark='1'>建議事項：</span><br /> 1. 這裡無法使用金屬製裝備<span style='color: #ff0000;' data-mce-mark='1'> ( 戰鬥時會呈現麻痹無法行動狀態 )</span><br /> 2. 除了塞西爾請勿裝備劍與盾之外 ( 空手 )，其餘三人應該都有不影響的裝備<br /> 3. 行進時遇敵的主力攻擊為楊與西德，泰拉最好省點 MP 打 BOSS<br /> 4. 可以的話楊建議雙手各裝備一個爪，對小兵主要用「踢擊」<br /> 5. 隊列的部份塞西爾與泰拉站後排，若要用自
動建議選擇「防御」<br /> 6. 如果真的快不行了&#8230;.就逃走吧！再不然傳送離開洞窟，再去補充一下重走<br /> 7. 別忘了塞西爾也能用白魔法幫忙回覆，至少 MP 較多一點點XDDDD<br /> 8. 洞窟內的敵人經驗值都很高，升級會很快，西德與楊的攻擊力也會越強<br /> <a name='磁力洞窟 B1'></a><br /> 
<span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟 B1</span><br /> 取得寶箱：<span style='color: #800000;' data-mce-mark='1'>高級恢復藥、獨角獸之角</span><br /> ( 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>以太</span> ) 第一段地圖只有單一出口，直接往 2 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-003.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>1/16 Update:</span> ( 補充提醒 – 隱藏召喚獸道具：<span style='color: #800000;'>奪心魔</span> )</p>
<p>在磁力洞窟裡面有一個怪物要注意一下：奪心魔。他身上帶有同名的隱藏召喚獸道具「奪心魔」( 極低機率掉落 )，後期有了報警器之後，可以到這裡的 B3/B4 隨傳隨到，建議現在有遇到的話可以多試幾次，沒掉落的話建議後期再帶著寶物獵手回來刷，詳情可參考：<span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_hiding_summoning_spells.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 隱藏召喚獸</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_secret_summoning/01-secret_summoning-009.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a name='磁力洞窟 B2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟 B2</span><br /> 到了 B2 路上會先經過一個寶箱 ( <span style='color: #800000;' data-mce-mark='1'>以太</span> )，接著先往 3 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 裡面還有兩個寶箱：<span style='color: #800000;' data-mce-mark='1'>2000 元、以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>吸血鬼之牙 x3</span>，接著往 4 繼續前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-006.png' width='486' height='326' /><br /> <a name='磁力洞窟 B3'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟 B3</span><br /> 到了 B3 後先往旁邊的 5 進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 裡面有一個<span style='color: #ff0000;' data-mce-mark='1'>儲存點</span> ( 歡呼！)，趕緊回復 / 儲存一下吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 出來後接著往下面的 6 進去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這裡是三個寶箱：<span style='color: #800000;' data-mce-mark='1'>高級恢復藥、蜘蛛絲、銅沙漏</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>靜寂之鐘 x3</span>，接著繼續往左上角的 7 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 然後會經過一個小區域，並且有一個寶箱：<span style='color: #800000;' data-mce-mark='1'>妖精爪</span>，繼續往左邊的 8 前進<br /> <span style='color: #ff0000;' data-mce-mark='1'>( 妖精爪可以給楊裝備，一定機率使敵人混亂 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-012.png' width='486' height='326' /><br /> <a name='磁力洞窟 B4'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟 B4</span><br /> 先往右上角的 9 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 裡面是第二個<span style='color: #ff0000;' data-mce-mark='1'>儲存點</span>，可以恢復與儲存</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 再來往左上角先取得寶箱 ( <span style='color: #800000;' data-mce-mark='1'>緊急出口</span> )，最後進入 10 就會遇到 BOSS 了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>特級以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-015.png' width='486' height='326' /><br /> <a name='磁力洞窟 水晶之間'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟 水晶之間</span><br /> 一進來就看到 BOSS 蹲在那裡了，接下來要連打三回合！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰 &#8211; 第一回合：<span style='color: #0000ff;' data-mce-mark='1'>暗黑精靈</span><br /> 備註：第一戰無法獲勝，<span style='color: #ff0000;' data-mce-mark='1'>在 BOSS 使用烈炎後會全滅，自動進入第二階段</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 危急之中，吉爾伯特忍著傷彈奏了音樂，經由私語草傳到了戰鬥現場</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在吉爾伯特的琴聲下，可以控制磁力了，<span style='color: #ff0000;' data-mce-mark='1'>裝備好劍與盾再向前第二回合</span><br /> ( HP / MP 會自動回滿 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰 &#8211; 第二回合：<span style='color: #0000ff;' data-mce-mark='1'>暗黑精靈</span><br /> HP：<span style='color: #0000ff;' data-mce-mark='1'>27780</span>，弱點：<span style='color: #ff0000;' data-mce-mark='1'>火、聖</span><br /> 技能：<span style='color: #0000ff;' data-mce-mark='1'>烈炎 or 震雷 ( 傷害約 500~700 )、生物 ( 持續失血 )</span><br /> 攻略：泰拉用「爆炎」、塞西爾用「救療」協助回復全體，楊與西德持續攻擊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰 &#8211; 第三回合：<span style='color: #0000ff;' data-mce-mark='1'>暗龍</span><br /> HP：<span style='color: #0000ff;' data-mce-mark='1'>7854</span>，弱點：<span style='color: #ff0000;' data-mce-mark='1'>火、聖</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 塞西爾丟以太 ( 最好是特級以太 ) 幫泰拉回復 MP<br /> 2. 泰拉繼續用「爆炎」，因 BOSS 的 HP 剩不多，約 2 次即可解決<br /> 3. 中途如果楊與西德還沒躺平，一樣持續攻擊<br /> 4. 塞西爾有空的話再用「救療」回復全體 ( 已躺平的人建議不用救了 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 打敗暗黑精靈後，就往前<span style='color: #ff0000;' data-mce-mark='1'>取得「土之水晶」</span>！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 走出水晶之間後，就可以用「傳送」離開磁力洞窟</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 再騎上黑陸行鳥，會自動往左返回陸行鳥村</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 在陸行鳥村可以再找一隻黃陸行鳥，往南騎回特羅亞城 ( 一樣要在森林下來 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/07-the_magnetic_cave-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='返回特羅亞城'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>返回特羅亞城</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-001.png' width='486' height='326' /><br /> <a name='返回特羅亞城 2F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞城 2F</span></p>
<p>回到特羅亞城後，先前往最裡面 2F 去找神官大人們交還水晶<br /> ( 然後會出現凱因的聲音，先別理他XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span></p>
<p>接著到之前遇到吉爾伯特的醫務室 ( 特羅亞城左側 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-003.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 吉爾伯特會交出一個傳繼能力道具「<span style='color: #800000;' data-mce-mark='1'>吟唱</span>」( 或加上<span style='color: #800000;' data-mce-mark='1'>隱藏</span>及<span style='color: #800000;' data-mce-mark='1'>醫藥</span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-004.png' width='486' height='326' /><br /> <a name='特羅亞城本次取得條件說明'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>本次取得條件說明：</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>1. 吟唱：</span>可以使用吟唱技能</strong>
<br /> 取得條件：擊破磁力洞窟的暗黑精靈後，返回特羅亞城醫務室找吉爾伯特取得<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>2. 隱藏：</span>在戰鬥中躲到畫面外不受攻擊，一定時間後會返回</strong><br /> 取得條件：在法
布爾城事件結束前 ( 上船前 )，對吉爾伯特已使用了一個傳繼道具。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>3. 醫藥：</span>使用回復道具效果為全體化</strong><br /> 取得條件：在法布爾城事件結束前 ( 上船前 )，對吉爾
伯特已使用了兩個傳繼道具。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>建議說明：</span><br /> 因為法布爾城事件結事前取得的傳繼道具，我們留給了雙胞胎，是為了取得後面的「連續詠唱」，如果你之前是選擇給吉爾伯特 1~2 個，本次所取得的道具就會不同，當然，等你通關之後會保留，第二輪開始玩的時候就能做不同選擇。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 所以這真是一個邪惡的遊戲啊XDDDDDD<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完傳繼道具後，回到 1F 大廳，往右側下去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 到之前拿過寶箱的房間，這次就可以往左側下樓</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-006.png' width='486' height='326' /><br /> <a name='返回特羅亞城 B1'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>特羅亞城 B1</span><br /> 下來後找 B1 的人對話，選「是」會開啟一個暗道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進入暗道往上後往右走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 繞過來另一邊的通道往下走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-009.png' width='486' height='326' /><br /> <a name='返回特羅亞城 B2'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span></p>
<p><span style='color: #0000ff;' data-mce-mark='1'>特羅亞城 B2</span></p>
<p>下面有 18 個寶箱啊XDDDD ( 真大方！)<br /> 取得寶箱：<span style='color: #800000;' data-mce-mark='1'>高級恢復藥 x2、萬能藥 x2、以太 x2、特級以太 x2、聖靈藥、銀蘋果</span><br /> <span style='color: #800000;' data-mce-mark='1'>山彥草 x2、強弓、寒冰箭、烈火箭、50000 元、5000 元、閃雷箭</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接下來離開特羅亞城，要上飛空艇之前，確認一下隊伍的狀態，或是到旁邊的特羅亞鎮上做一下道具補充，當然也別忘了儲存一下。等一下要去的佐特塔也是無法
以傳送離開的，只有一開始的 1F 有傳送點能離開，務必做好準備。( 建議不死鳥之尾多準備一些，裡面的雜兵蠻強大的XDDDDD )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>泰拉離隊前說明：</span><br /> 接著要前往的地方是佐特塔，不夠在這之前，要提醒一下大家，下一個離隊的人會是泰拉，在他離隊之前可以先確認好要給他吃什麼傳繼能力道具，要吃一個還是兩個，我給他吃了兩個：海嘯、合力詠唱，這樣後續可以取得三個不錯的傳繼能力道具。</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 說明：<br /> <strong><span style='color: #800000;' data-mce-mark='1'>1. 回憶：</span>效果為隨機發動黑魔法</strong><br /> 取得條件：在佐特塔頂劇情後取得。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>2. 誓死抵抗：</span>瀕死時防御力變為兩倍</strong><br /> 取得條件：對泰拉
使用過一個傳繼能力道具，在佐特塔頂劇情後取得。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>3. 快速詠唱：</span>詠唱時間縮短為二分之一</strong><br /> 取得條件：對泰拉使用過兩個傳繼能力道具，在佐特塔頂劇情後取得。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 決定好之後，就可以上飛空艇，凱因會出現，帶領著我們直接進入佐特塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/08-back_to_castle_troia-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='佐特塔'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔</span><br /> 可以開始行動後，已經出現在佐特塔的 1F ( 瞬間移動XDDDD )<br /> 這裡大部份的敵人有火屬性弱點，用自動攻擊時裝備或魔法建議可以調整一下，但是也有敵人是吸收火屬性，或是吸收冰屬性，有點麻煩就是了，就注意一下不要全程都自動攻擊，不然打不完的&#8230;.</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>重要提醒：</span></p>
<p>佐特塔屬於一次性的地圖，走過就沒了，<span style='color: #ff0000;'>所以請特別注意「地圖完成度 100%」及「怪物圖鑑收集」</span>，地圖完成度會關係著最後是否能取得重要的技能道具「<span style='color: #800000;'>寶物獵手</span>」。在塔中有一些寶箱的周圍地圖很容易被忽略掉，因為常常拿了寶箱人就走掉了，結果地圖沒繞完整。請確認你在每一個樓層都有拿到地圖獎勵再離開，否則後續若發現沒有拿到「寶物獵手」會很失望，要一個一個去各迷宮找，而佐特塔又不見的情況下&#8230;.只能下一輪繼續了。</p>
<p>( 而怪物圖鑑的收集後續會再整理，反正第一輪是無法完成怪物圖鑑 100% 的，就不用太擔心 )</p>
<p>( 怪物圖鑑請參考：<span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_enemies_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 怪物圖鑑收集</span></a></span></span> )<br /> <a name='佐特塔 1F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 1F</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 左側的 1 是傳送點，可以返回地圖 ( 再次乘上飛空艇會自動回到佐特塔 )<br /> 先往上角取得寶箱 ( <span style='color: #800000;' data-mce-mark='1'>烈焰甲</span> ) 後，就往右上的 2 進入 ( 調查後開門 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>宙斯之怒 x5</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-002.png' width='486' height='326' /><br /> <a name='佐特塔 2F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 2F</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 先往下取得寶箱 ( <span style='color: #800000;' data-mce-mark='1'>火焰劍</span> )，打開寶箱時會遇到強敵：<span style='color: #0000ff;' data-mce-mark='1'>烈火猛犬</span><br /> 若你有裝備火屬性武器，記得開寶箱前要先換掉，否則會有點麻煩</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 強敵：<span style='color: #0000ff;' data-mce-mark='1'>烈火猛犬</span><br /> HP：<span style='color: #0000ff;' data-mce-mark='1'>約 6000</span>，弱點：<span style='color: #ff0000;' data-mce-mark='1'>冰</span><br /> 攻擊：<span style='color: #ff0000;' data-mce-mark='1'>烈炎 ( 全體傷害 800~1000 )，會吸收火屬性</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 運氣不好的話，這傢伙會連續放烈炎，兩次很可能就會全滅，要注意<br /> 2. 楊裝備寒冰爪 + 妖精爪，直接攻擊效果很好！( 妖精爪會使他混亂 )<br /> 3. 泰拉用「冰封」一次傷害約 3000~4000<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著就繼續繞地圖，然後往 3 入口前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>眾神之怒 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-006.png' width='486' height='326' /><br /> <a name='佐特塔 3F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 3F</span><br /> 這一段地圖沒有寶箱，直接往 4 前進 ( 但是還是要繞完地圖&#8230;.Orz )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>藍色獠牙</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-008.png' width='486' height='326' /><br /> <a name='佐特塔 4F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 4F</span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p>這一段一樣沒有寶箱，但是共有 4 個出口，依序往 5、6、7 會取得 4 個寶箱，最後再進入 8</p>
<p>提醒一下，拿寶箱時要確認寶箱周圍的地圖迷霧都有開到，別拿了就跑，到時候又重走XDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 寶箱取得：<br /> 入口 5：<span style='color: #800000;' data-mce-mark='1'>大地之錘</span><br /> 入口 6：<span style='color: #800000;' data-mce-mark='1'>地獄爪、烈焰盾</span><br /> 入口 7：<span style='color: #800000;' data-mce-mark='1'>祭司法袍</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>聖靈藥</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-010.png' width='486' height='326' /><br /> <a name='佐特塔 5F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 5F</span><br /> 來到 5F 之後，先往 9 進去，裡面是一個<span style='color: #ff0000;' data-mce-mark='1'>儲存點 ( 終於&#8230;. )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 終於可以好好休息一下了 ( 汗 )，儲存一下就往入口 10 前進吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 地圖獎勵：<span style='color: #800000;' data-mce-mark='1'>銅沙漏 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 盡頭會遇到三個小嘍囉，進入戰鬥！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> BOSS 戰：<span style='color: #0000ff;' data-mce-mark='1'>梅加斯三姊妹 ( 多格、馬格、拉格 )</span><br /> 技能：<span style='color: #ff0000;' data-mce-mark='1'>反射魔法</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 主要先集中攻擊中間的馬格胖子 ( 塞西爾、楊、西德 )，兩側先不管<br /> 2. 泰拉先防御，一但他們開始使用反射魔法後，會有機會放到我們身上<br /> 3. <span style='color: #ff0000;' data-mce-mark='1'>利用我們身上的反射效果，就能反彈魔法到對方身上</span> ( 不會再被反彈 )<br /> 4. 例如西德中了反射 ( 變綠色 )，就讓泰拉對西德使用「暴雷」！<br /> 5. 彈回 BOSS 身上的暴雷會有 4000~4200 以上的傷害！<br /> 6. 中間的馬格解決掉之後，兩側的就隨便攻擊了&#8230;.很快就能搞定<br /> 7. 如果一開始攻擊兩側，打死後會被中間救活，所以才要先攻擊中間<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 打完後就進入最後的入口 10，再提醒一下，<span style='color: #ff0000;' data-mce-mark='1'>進入 6F 後，經過了劇情泰拉就會離隊</span>，如果還沒給他吃過傳繼能力道具，這時候還有最後機會</p>
<p>( 傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span> )</p>
<p><span style='color: #ff0000;'>( 另外，如果你是第二輪遊戲，有給泰拉穿精金鎧、洋蔥裝備的話，務必要卸下來啊！)</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-016.png' width='486' height='326' /><br /> <a name='佐特塔 6F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 6F</span><br /> 直接往上面最後的入口前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 盡頭會遇見高貝扎與凱因，隨後會交出土之水晶</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 超不爽的泰拉，向前攻擊高貝扎，最後使出了隕石魔法！</p>
<p>( 明明 MP 就不夠啊&#8230;&#8230;&#8230;.原來是用生命換 MP 啊&#8230;. )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 劇情：高貝扎撤退，凱因倒下，泰拉則犧牲了&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 這時候，地上出現了光點，取得傳繼能力道具：<span style='color: #800000;' data-mce-mark='1'>回憶</span> ( 或加上<span style='color: #800000;' data-mce-mark='1'>快速詠唱、誓死抵抗</span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-021.png' width='486' height='326' /><br /> <a name='佐特塔本次取得條件說明'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>本次取得條件說明：</span><br /> ( 前面有說明過了，取得項目在於你曾對泰拉用了幾個傳繼能力道具 )<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>1. 回憶：</span>效果為隨機發動黑魔法</strong><br /> 取得條件：劇情後在塔頂必定取得<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>2. 誓死抵抗：</span>瀕死時防御力變為兩倍</strong><br /> 取得條件：對泰拉使用過一個傳繼能力道具<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <strong><span style='color: #800000;' data-mce-mark='1'>3. 快速詠唱：</span>詠唱時間縮短為二分之一</strong><br /> 取得條件：對泰拉使用過兩個傳繼能力道具<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 接著去關心倒在一旁的凱因，會一起進去救羅莎</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-022.png' width='486' height='326' /><br /> <a name='佐特塔 7F'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>佐特塔 7F</span><br /> 唉&#8230;..擁抱的一幕，凱因的心裡做何感想&#8230;.太無奈了&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 談話完之後，<span style='color: #ff0000;' data-mce-mark='1'>凱因與羅莎一起加入了隊伍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 兩位伙伴加入隊伍後，下面是傳繼道具的使用建議：<br /> ( 當然你也可以自行決定&#8230;&#8230;. )<br /> 1. 羅莎：使用<span style='color: #800000;' data-mce-mark='1'>連續詠唱、快速詠唱</span><br /> 2. 塞西爾：使用<span style='color: #800000;' data-mce-mark='1'>誓死抵抗</span><br /> 3. 西德：使用<span style='color: #800000;' data-mce-mark='1'>合力詠唱、回憶</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ff0000;' data-mce-mark='1'>西德會是下一個離隊的人員</span>，現在給他 1~2 個傳繼能力道具，後續會取得的技能當然也不太一樣，我使用兩個的原因，是為了得到瀕死攻擊力加倍的技能，至於凱因與楊，目前暫時還不需要使用任何傳繼道具。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 塞西爾現在我用了<span style='color: #800000;' data-mce-mark='1'>反擊、誓死抵抗</span>兩個，能力裝備就看狀況選擇即可，而羅莎的能力就可以調整一下指令的欄位，連續詠唱很好用，只怕你 MP 不夠XDDDDD<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 最後就往下離開，馬上會再次進入 BOSS 戰</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> BOSS 戰：<span style='color: #0000ff;' data-mce-mark='1'>巴爾巴莉希亞</span><br /> 技能：<span style='color: #0000ff;' data-mce-mark='1'>龍捲風 ( 單體瀕死 )、徐徐石化 ( 需用金針解除 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 攻略：<br /> 1. 這場 BOSS 戰其實很簡單，只是時間會拖得有點久<br /> 2. 主力攻擊是楊與凱因，凱因每回合跳躍，傷害約 500 左右<br /> 3. 楊連續使用「凝氣」滿三次後就攻擊，傷害可達 2500~3000<br /> 4. 其餘人「完全不要攻擊」，否則被反擊就會很慘<br /> 5. 只有楊與凱因攻擊即可，這樣就不會被反擊，BOSS 也不太會持續攻擊<br /> 6. 等楊出手三次左右就能擊敗 BOSS<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 擊敗 BOSS 後，羅莎協助傳送大家出去 ( 為什麼她就能用傳送啊XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/09-the_tower_of_zot-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴隆城'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>巴隆城</span><br /> 接著會回到巴隆城內，凱因說了暗之水晶的事，<span style='color: #ff0000;' data-mce-mark='1'>並拿出了「岩漿石」</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/10-castle_baron-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 走出巴隆城，飛空艇已經被西德搖控回來，我們先返回之前的磁力洞窟<br /> ( 在西北方向，還記得那個討厭的洞窟嗎XDDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/10-castle_baron-002.png' width='486' height='326' /><br /> <a name='返回磁力洞窟'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>返回磁力洞窟</span><br /> 別忘了要去找黑色陸行鳥才能到達磁力洞窟 ( 現在金屬裝備已不受影響了 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/11-back_to_the_magnetic_cave-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 進來後要一路往最裡面的 B4，再進入水晶之間，好遠啊&#8230;&#8230;<br /> ( FF4 要拿個道具都要走這麼遠是怎樣&#8230;..好險現在實力已變強了XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/11-back_to_the_magnetic_cave-002.png' width='486' height='326' /><br /> <a name='返回磁力洞窟 水晶之間'></a><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>磁力洞窟 水晶之間</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 到了水晶之間就會發現光點，取得傳繼能力道具「<span style='color: #800000;' data-mce-mark='1'>龍捲風</span>」<br /> ( 效果為對敵全體風屬性攻擊，接著對敵人的火屬性傷害提升 1.5 倍 )<br /> ( 不太實用的能力，但是可以用來調整獲得其他技能道具時的備用品XDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_2-1/11-back_to_the_magnetic_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> 拿完之後，走出水晶之間就能用傳送離開 ( 水晶之間內不能用 )。</p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'> -</span><br /> <span style='color: #0000ff;' data-mce-mark='1'>FF4 Part 2-1 後記：</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 這一篇好像寫了有點久 ( 篇幅真的比較長 )，沒辦法這篇要說明的地方太多了，而且迷宮內也是挺麻煩的，畢竟我希望寫詳細一點，至少迷宮走完才能截到完整的迷宮地圖。說真的，看著攻略的地圖走與自己走完全是兩回事，所以這一篇稍微慢了點。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 關於傳繼能力道具只要有遇到我都會盡量做說明的，而且之後也會把完整的列表做出來，不過那是通關之後才會做的，現階段我會提供一些能力安排與使用的建議，如果你自有安排，當然也是可以的。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 我看大家在回覆區討論得很熱烈，大家的進度都很快，當然會遇到一些問題，我因為攻略需要很多的處理工作 ( 趕進度、練等級、查資料、截圖、修圖、上傳、編輯文章等等，每一篇大概要花<span style='color: #ff0000;' data-mce-mark='1'> 8~10 小時</span>以上才能完工 )，所以暫時無法回答太後期的問題 ( 我也是第一次玩啊XDDD )。不過這邊一定有很多高手會幫各位先解答的。<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> 非常謝謝你們大家對這個網站這麼捧場，我會繼續盡力寫出完整的攻略，讓每個玩 FF4 的朋友以後都能盡情的享受順暢的攻略！下篇待續~<br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p><span style='text-decoration: underline;' data-mce-mark='1'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'><a href='#top'><span style='color: #0000ff; text-decoration: underline;' data-mce-mark='1'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;' data-mce-mark='1'>-</span><br /> <span style='color: #ffffff;' data-mce-mark='1'>-</span></p>
<p>FF4 Part 2-1 佐特塔擊破 ( 完 )</p></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
