<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy IV ( FF4, iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 4 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 1-3 聖騎士的覺醒</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#密西迪亞'><span style='color: #000080; text-decoration: underline;'>密西迪亞</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#密西迪亞 祈福之館'>
<span style='color: #000080; text-decoration: underline;'>密西迪亞 祈福之館</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='color: #ff0000;'>帕羅姆、普羅姆加入隊伍</span><br /> (02) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#試煉之山'><span style='color: #000080; text-decoration: underline;'>試煉之山</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#試煉之山 入口'><span style='color: #000080; text-decoration: underline;'>試煉之山 入口</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>解毒藥 x5</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#試煉之山 第 3 階段'><span style='color: #000080; text-decoration: underline;'>試煉之山 第 3 階段</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>泰拉加入隊伍</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.3 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#試煉之山 第 7 階段'><span style='color: #000080; text-decoration: underline;'>試煉之山 第 7 階段</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>以太</span> )
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#試煉之山 山頂'><span style='color: #000080; text-decoration: underline;'>試煉之山 山頂</span></a></span>
</span> ( 地圖獎勵：<span style='color: #800000;'>紅色獠牙</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰 ( 第一階段 )：斯卡米留尼、骨魂 x4<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰 ( 第二階段 )：斯卡米留尼<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.5 &#8211; <span style='color: #ff0000;'>塞西爾成為聖騎士</span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.6 &#8211; <span style='color: #ff0000;'>泰拉憶起全部魔法，並學會「隕石」</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回試煉之山 第 7 階段'><span style='color: #000080; text-decoration: underline;'>返回試煉之山 第 7 階段</span>
</a></span></span>：取得傳繼能力道具「<span style='color: #800000;'>詛咒</span>」<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回密西迪亞'><span style='color: #000080; text-decoration: underline;'>返回密西迪亞</span></a></span></span> ( 魔鬼之路 > 巴隆鎮 )<br /> (03) 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆鎮'><span style='color: #000080; text-decoration: underline;'>巴隆鎮</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='color: #ff0000;'>楊加入隊伍</span> ( 遇敵：巴隆近衛軍 x2 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
3.2 &#8211; 取得「巴隆之匙」( 開啟武器防具店、古老水路的門鎖 )<br /> (04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古老水路'><span style='color: #000080; text-decoration: underline;'>古老水路</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古老水路 B4'><span style='color: #000080; text-decoration: underline;'>古老水路 B4</span></a></span></span> ( 地
圖獎勵：<span style='color: #800000;'>高級恢復藥 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古老水路 B3'><span style='color: #000080; text-decoration: underline;'>古老水路 B3</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>以太</span> )<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古老水路 B2'><span style='color: #000080; text-decoration: underline;'>古老水路 B2</span></a></span></span> ( 地圖獎勵：<span style='color: #800000;'>萬能藥 x3</span> )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.4 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古老水路 B1 - 1'><span style='color: #000080; text-decoration: underline;'>古老水路 B1 &#8211; 1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>4.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古老水路 B1 - 2'>
<span style='color: #000080; text-decoration: underline;'>古老水路 B1 &#8211; 2</span></a></span></span><br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城'><span style='color: #000080; text-decoration: underline;'>
巴隆城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城 1F'><span style='color: #000080; text-decoration: underline;'>巴隆城 1F</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：貝迦恩、左手、右手<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='text-decoration: underline; color: #000080;'><a href='#巴隆城 東塔 1F'><span style='color: #000080; text-decoration: underline;'>巴隆城 東塔 1F</span></a></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#巴隆城 東塔 B1'><span style='color: #000080; text-decoration: underline;'>巴隆城 東塔 B1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城 東塔 2F'><span style='color: #000080; text-decoration: underline;'>巴隆城 東塔 2F</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城 東塔 3F'><span style='color: #000080; text-decoration: underline;'>巴隆城 東塔 3F</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴隆城 2F'><span style='color: #000080; text-decoration: underline;'>巴隆城 2F</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：凱納槽<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.7 &#8211; <span style='color: #ff0000;'>雙胞胎石化犧牲 ( 離隊 )、西德加入隊伍、取得飛空艇</span><br /> (06) 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回古老水路 B3'><span style='color: #000080; text-decoration: underline;'>返回古老水路 B3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
6.1 &#8211; 取得傳繼能力道具「<span style='color: #800000;'>海嘯</span>」</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><a href='./ff4.php' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>返回 FF4 攻略總目錄</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='密西迪亞'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>密西迪亞</span><br /> <span style='color: #ffffff;'>-</span><br /> 醒來後發現只剩自己一人的塞西爾，延路往右來到了密西迪亞</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 也許是命運的安排吧！讓自己又來到這個曾經痛下殺手的地方，這裡的黑白魔法師幾乎每個都仍懷恨在心，如果你跟門口的黑魔對話，會被變成青蛙&#8230;.XDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 逛到了酒館 ( 旅店 1F )，左邊櫃檯會賞你一杯「
毒藥」讓你中毒，右邊的舞女跳完舞之後會讓你變成豬&#8230;..所以沒事還是別亂對話XDDDD ( 豬變要用<span style='color: #800000;'>減肥食品</span>解除 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 連武器店、防具店的黑魔法師講話都很嗆是怎樣XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器店的裝備果然都用不上，還是算了吧</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-005.png' width='486' height='326' /><br /> <a name='密西迪亞 祈福之館'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>密西迪亞 祈福之館</span><br /> <span style='color: #ffffff;'>-</span><br /> 逛完之後就往中間的大房子進去，找密西迪亞的長老對話</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 對話中長老看出了塞西爾的迷惘，並要塞西爾到試煉之山去接受考驗，以找到全新的自己，並且派出了雙胞胎<span style='color: #ff0000;'>「帕羅姆、普羅姆」協助，兩人加入隊伍！</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/01-mysidia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 建議事項：<br /> 目前帕羅姆、普羅姆兩人的等級也都不高，建議先在密西迪亞週邊提升一下等級，這附近除了一般雜兵外，也會出現一種名為「祖」的大鳥，經驗值很高，三人分下來還有 1000 多的經驗值，對於雙胞胎的等級提升有很大幫助，也能很快就學會許多的黑白魔法，花點時間練一下再前往吧！( 密西迪亞的旅店還是可以睡覺的，$200/次 )<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='試煉之山'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>試煉之山</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 從密西迪亞離開後，往東延著陸地走，經過長長的一段路來到了試煉之山</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-002.png' width='486' height='326' /><br /> <a name='試煉之山 入口'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>試煉之山 入口</span><br /> 取得寶箱：<span style='color: #800000;'>恢復藥 x2</span>，兩邊都只有一個出入口，直接往上前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 前進一小段路之後，發現被火焰擋住了，帕羅姆使出了冰結解除了阻礙<br /> ( 這兩個小傢伙真的很可愛XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 畫面跳到了另一邊，高貝扎派出了土之斯卡米留尼，將帶著一群不死系妖怪前來試煉之山阻擋塞西爾一行人，屆時會是什麼情況呢&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>解毒藥 x5</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-006.png' width='486' height='326' /><br /> <a name='試煉之山 第 3 階段'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>試煉之山 第 3 階段</span><br /> 這一段路沒有寶箱，直接繼續往上走即可</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 在這裡的半路上會遇到正在尋找隕石魔法的泰拉，對話過後<span style='color: #ff0000;'>泰拉加入隊伍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-009.png' width='486' height='326' /><br /> <a name='試煉之山 第 7 階段'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>試煉之山 第 7 階段</span><br /> 取得寶箱：<span style='color: #800000;'>以太 x2</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-011.png' width='486' height='326' /><br /> <a name='試煉之山 山頂'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>試煉之山 山頂</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 終於有一個儲存點，記得恢復 / 儲存</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 儲存點左側的階梯再上去就會遇到 BOSS 了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰 &#8211; 第一階段：<span style='color: #0000ff;'>斯卡米留尼、骨魂 x4</span><br /> 弱點：<span style='color: #ff0000;'>火 ( 恢復魔法、恢復道具皆可有效傷害，傷害值就是正常的恢復值 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. BOSS 與 4 個骨魂的弱點都是
火，讓帕羅姆和泰拉都用火魔法攻擊<br /> 2. 因為是對方都不死系，恢復用的魔法對他們是有傷害效果的，例如用救療來攻擊<br /> 3. 塞西爾物理攻擊，普羅姆用救療協助恢復我方全體<br /> 4. 因為火魔法效果很好，所以基本上 3 回合左右就能解決這場<br /> <span style='color: #ffffff;'>-</span><br /> <span style
='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>打敗後要繼續過橋前進時，先確認一下隊伍的狀態，並且建議：</span><br /> 1. 回去剛剛的儲存點再儲存一次，並恢復<br /> 2. 調整隊列，前後排交換 ( 過橋後會再發生一次 BOSS 戰，且為背後襲擊！)<br /> 3. 但其實如果你有信心的話，直接走過去也可以&#8230;..XDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰 &#8211; 第二階段：<span style='color: #0000ff;'>斯卡米留尼</span> ( 露出了真面目&#8230; )<br /> 弱點：<span style='color: #ff0000;'>火 ( 恢復魔法、恢復道具可有效傷害 )</span><br /> 特技：詛咒、毒氣攻擊 ( 中毒、失明、睡眠、沉默等各種狀態 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 1. 開戰後帕羅姆先放「逞強」提升智力，之後以「烈炎」攻擊，傷害達 1800 左右<br /> 2. 塞西爾的物理攻擊效果不佳，可幫忙回復<br /> 3. 普羅姆與泰拉建議用白魔法「救療」直接攻擊，傷害可達 800~900<br /> 4. 中了沉默的話因無法使用魔法，也可以丟高級恢復藥甚至特級恢復藥<br /> 5. 如果剛剛有記得切換隊列的話，BOSS 的物理攻擊基本上不算猛烈<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>紅色獠牙</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著往旁邊的石碑走去，就會觸發事件</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 劇情：眾人進入了一個奇怪的空間，聽見了疑似塞西爾父親的聲音！？</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 結果是兩個塞西爾必須進行戰鬥，敵人就是暗黑騎士身份的自己！塞西爾將以聖騎士的身份與過去的自己對戰&#8230;..<span style='color: #ff0000;'>( 此戰用「防御」就可以了，馬上就會自動結束 )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>結束後塞西爾接受了聖光，成為了「聖騎士」！</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>在一旁的泰拉受到聖光的啟示，也想起了全部的魔法，包括「隕石」</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 看了一下轉職後的塞西爾，雖然得到了傳說之劍，但 LV 竟然從 1 開始&#8230;.其實大家心裡還是比較喜歡原本的暗黑塞西爾吧XDDDDDDD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>備註：</span>有網友發現塞西爾轉職後出現無法升級的問題，後來重新安裝就恢復了，如果你有遇到此問題的話，記得用 iTunes 先備份好資料，然後再移除遊戲，重新安裝好之後再用 iTunes 從備份回復。</p>
<p><span style='color: #ffffff;'>-</span><br /> 再來是泰拉，雖然記起了所有魔法，也學會了隕石，但是這老頭的 MP 也太悲劇了吧，一直保持在 90 是怎樣？連兩個小鬼的 MP 都超過他的兩倍！( 不過劇情原本的設定就是如此 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 不過雖然塞西爾的等級從 1 開始，但以現在雜兵的經驗值，要提升也是很快的，在路上打個幾場就知道了，有時間的話也好好練一下吧！<br /> <a name='返回試煉之山 第 7 階段'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>返回試煉之山 第 7 階段</span><br /> 離開試煉之山前，往回走到「第 7 階段」下圖的<span style='color: #ff0000;'>紅圈處</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地上有發光的光點，調查後可取得第四個傳繼能力道具「<span style='color: #800000;'>詛咒</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/02-mt_ordeals-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 之前在離開法布爾城時取得的「<span style='color: #800000;'>反擊</span>」，如果你有照我的建議給塞西爾用的話，這時候你應該還有三個傳繼能力道具：<span style='color: #800000;'>自動恢復藥、道具
知識、詛咒</span><br /> <span style='color: #ffffff;'>-</span><br /> 這時候建議可以照下面的給法：<br /> <strong>帕羅姆 ( 小黑魔 )</strong>：<span style='color: #800000;'>詛咒</span><br /> <strong>普羅姆 ( 小白魔 )</strong>：<span style='color: #800000;'>自動恢復藥、道具知識</span><br /> <span style='color: #ffffff;'>-</span><br /> 這樣建議的原因是之後可以取得更好的傳繼能力道具。</p>
<p>傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到攻略，離開試煉之山後，就回去密西迪亞找長老對話。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='返回密西迪亞'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>返回密西迪亞</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/03-back_to_mysidia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到密西迪亞後，長老提到了必須通過密西迪亞內的魔鬼之路，前往巴隆，去取得飛空艇</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/03-back_to_mysidia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 前往魔鬼之路前，可以先到這裡的武器、防具店，幫塞西爾換個裝備，另外要檢查一下泰拉的裝備，如果之前在達姆希安城有卸掉的話，現在的狀況可能不太好，也是要處理一下 ( 錢不夠就賣掉暗黑裝備，或再去賺賺錢XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/03-back_to_mysidia-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 準備好之後就可以來到最右上角的房子，裡面就是魔鬼之路的傳送點，沒有迷宮，不用擔心XD</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/03-back_to_mysidia-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 直接往傳送點進去吧！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/03-back_to_mysidia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴隆鎮'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆鎮</span><br /> <span style='color: #ffffff;'>-</span><br /> 經過傳送便回到了巴隆鎮，就是之前無法傳送的地方</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在鎮上繞一繞沒發現什麼，來到了旅店 2F 竟然看到了楊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 結果在旁邊的士兵竟然開戰 ( <span style='color: #0000ff;'>遇敵：巴隆近衛軍 x2</span>，小心會被豬變 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著連楊也對我們開打，但打了兩回合之後楊就恢復了記憶&#8230;.( 哪招XD )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 結束後<span style='color: #ff0000;'>楊也加入了隊伍</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 眾人在旅店討論了一番，楊拿出了「<span style='color: #800000;'>巴隆之匙</span>」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿到巴隆之匙後，鎮上之前有一間屋子，還有一間武器防具店上著鎖，現在都可以開啟了，調查上鎖的門後，會跳出道具選懌，用巴隆之匙打開即可。<br /> <span style='color: #ffffff;'>-</span><br /> 現在先前往之前上鎖的武器防具店，打開它進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左邊是武器店，右邊是防具店，但裝備其實還好而已，看自己需求是否購買</p>";
echo "<p><span style='color: #ff0000;'>但是你有注意到兩個櫃檯裡面各有一個寶箱了嗎？</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 從右下角的箱子旁邊是有暗道的，延著牆壁就能繞上來到櫃檯後方</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這樣就能進來取得兩個寶箱：<span style='color: #800000;'>2000 元、宙斯之怒</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就可以到鎮上的西側，之前遇過的另一道上鎖的門，開啟它進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後先別下樓梯，右側有一個暗道可以進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭是一個寶箱：<span style='color: #800000;'>1000 元</span>，拿完就繼續下樓，進入「古老水路」</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/04-baron-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='古老水路'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #0000ff;'>古老水路</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>提醒事項：</p>
<p>1. 從進去古老水路 B4 開始，一直要到最後的 B1 才會有儲存點可以恢復與儲存，中間又有許多的暗道，請務必確認好角色的狀態，且準備好足夠的恢復道具，<span style='color: #ff0000;'>而且在古老水路中是不能使用「緊急出口」或是「傳送」魔法來離開迷宮的，要特別注意</span>。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>2. 等到出了古老水路後，會到巴隆城，裡面當然也是沒有儲存點，要一直等到打完兩場 BOSS 戰才能有機會出去儲存，務必要準備好。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>3. 這個區域的敵人大部份怕火屬性，如果你習慣用自動的話，記得把泰拉和帕羅姆的自動指令設為火屬性魔法</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-001.png' width='486' height='326' /><br /> <a name='古老水路 B4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古老水路 B4</span><br /> <span style='color: #ffffff;'>-</span><br /> 取得寶箱：<span style='color: #800000;'>高級恢復藥、以太、宙斯之怒</span><br /> 第一段路取得寶箱、繞完地圖後，就直接往出口 2 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>高級恢復藥 x3</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-003.png' width='486' height='326' /><br /> <a name='古老水路 B3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古老水路 B3</span><br /> <span style='color: #ffffff;'>-</span><br /> 取得寶箱：<span style='color: #800000;'>赫耳墨斯之靴、銅沙漏、蜘蛛絲</span><br /> 這一段路有非常多暗道，可以參考下面的地圖來走，3 是出口</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 地圖獎勵：<span style='color: #800000;'>以太</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-005.png' width='486' height='326' /><br /> <a name='古老水路 B2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古老水路 B2</span><br /> <span style='color: #ffffff;'>-</span><br /> 取得寶箱：<span style='color: #800000;'>以太</span> ( 地圖獎勵：<span style='color: #800000;'>萬能藥 x3</span>，沒截到圖XD )<br /> 出口 4 左側有個暗道，拿完寶箱繼續往 4 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-006.png' width='486' height='326' /><br /> <a name='古老水路 B1 - 1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古老水路 B1 &#8211; 1</span><br /> <span style='color: #ffffff;'>-</span><br /> 這個區域有兩個出口，先往出口 5 前進</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-007.png' width='486' height='326' /><br /> <a name='古老水路 B1 - 2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古老水路 B1 -2</span><br /> <span style='color: #ffffff;'>-</span><br /> 取得寶箱：<span style='color: #800000;'>古代劍</span><br /> 這裡有儲存點，右側還有一個暗道，過去盡頭可取得寶箱</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到這裡 MP 快不夠了吧！終於可以儲存與恢復了&#8230;.( 以太捨不得用XD )<br /> ( 用了帳篷如果發現無法完全回滿 HP/MP，是正常的，要用小屋才能完全回滿 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回來後就繼續往出口 6 前進，就會離開這裡，進入巴隆城的外圍水道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/05-the_old_waterway-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴隆城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 到了巴隆城後是出現在外圍水道的左上角，直接往下走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往下走到底後，就在城的左下角有個入口可以進入</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左下角的入口</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上來後直接往右側的門進入</p>
<p><span style='color: #ff0000;'>1/5 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>Cheng</span> 補充 )</p>
<p><span style='color: #ff0000;'>來到巴隆城後，可以先回到西塔樓上的塞西爾房間床舖休息恢復</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一段階梯，往下繼續走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-005.png' width='486' height='326' /><br /> <a name='巴隆城 1F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 1F</span><br /> 繼續往右走就會遇到貝迦恩</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 對話後貝迦恩居然成為同伴？事情沒那麼簡單，馬上進入了戰鬥！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>貝迦恩、左手、右手</span><br /> HP：( 後續補上 )，弱點：<span style='color: #ff0000;'>冰</span><br /> 技能：<span style='color: #0000ff;'>反射魔法</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 大約一回合後，貝迦恩會在本體放反射魔法，此時不要用魔法攻擊本體<br /> 2. 讓帕羅姆與泰拉用「冰結、冰封」等魔法攻擊左右手的「單體」，勿用全體<br /> 3. 左右手擊破後會再生，繼續用冰魔法攻擊即可<br /> 4. 塞西爾與楊持續用物理攻擊貝迦恩的本體<br /> 5. 一發現貝迦恩的反射效果失效後 ( 恢復原本顏色 )，馬上以冰屬性魔法攻擊全體<br /> 6. 貝迦恩本體擊破後，如果左右手還在也不用擔心，這時候就輕鬆多了<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打完後先別往前，先往右走</p>
<p><span style='color: #ff0000;'>1/5 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>Cheng</span> 補充 )</p>
<p><span style='color: #ff0000;'>打完貝迦恩後，一樣可以先回到西塔樓上的塞西爾房間床舖休息恢復</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走地圖上右側的樓梯過去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會再經過一小段階梯，繼續往下走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後這個房間左上角有一個暗道，往上走，接著持續往左走到底，再往下走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 取得寶箱：<span style='color: #800000;'>以太 x2、獨角獸之角 x2、不死鳥之尾 x2</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完寶箱後，返回往下面出口走出去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出來後從左邊大入口進去直走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底直接進入東塔</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-016.png' width='486' height='326' /><br /> <a name='巴隆城 東塔 1F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 東塔 1F</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 在 1F 就有 4 個寶箱：<span style='color: #800000;'>赫耳墨斯之靴 x2、酒神之酒 x2</span><br /> 接著繼續往左邊下去 B1</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-017.png' width='486' height='326' /><br /> <a name='巴隆城 東塔 B1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 東塔 B1</span><br /> <span style='color: #ffffff;'>-</span><br /> 下來後在第一個蠟燭與石像的中間，可以找到一個「<span style='color: #800000;'>聖靈藥</span>」<br /> ( 往右繼續走還有路，但是目前過不去，會被封印的力量擋住 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到 1F 右側往上繼續走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-019.png' width='486' height='326' /><br /> <a name='巴隆城 東塔 2F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 東塔 2F</span><br /> <span style='color: #ffffff;'>-</span><br /> 2F 有兩個寶箱：<span style='color: #800000;'>高級恢復藥 x2</span>，左邊繼續上樓</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-020.png' width='486' height='326' /><br /> <a name='巴隆城 東塔 3F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 東塔 3F</span><br /> <span style='color: #ffffff;'>-</span><br /> 3F 有三個寶箱：<span style='color: #800000;'>以太、帳篷 x2</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後在房間的右上角落，還可以找到另一個「<span style='color: #800000;'>以太</span>」，都拿完之後就可以原路回去</p>
<p>回到 1F 剛剛與貝迦恩對戰的地方</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到大廳後就一路往上直走</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-023.png' width='486' height='326' /><br /> <a name='巴隆城 2F'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴隆城 2F</span><br /> <span style='color: #ffffff;'>-</span><br /> 經過兩個房間，來到之前巴隆王的王座間門口，確認一下角色狀態就進去吧！</p>
<p><span style='color: #ff0000;'>提醒：</span>進入發生 BOSS 戰，劇情結束後<span style='color: #ff0000;'>帕羅姆與普羅姆就會離隊！</span>，如果還沒對這兩位使用過傳繼能力道具的話，現在還有最後機會，詳情可以參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後見到巴隆王，不，原來這傢伙是個冒牌貨！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 原來是高貝扎四天王之一的「<span style='color: #0000ff;'>水之凱納槽</span>」( 好難聽的名字= = )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>凱納槽</span><br /> HP：( 後續補上 )，<span style='color: #ff0000;'>弱點：集中水源時 &#8211; 雷、躲進殼裡時 &#8211; 雷/冰</span><br /> 技能：催眠 ( 全體 )、減速 ( 全體 )、海嘯 ( 全體傷害約 450~600 )<br /> 備註1：BOSS「開始集中水源」時，冰屬性會被吸收，要注意勿用<br /> 備註2：BOSS「開始躲進殼裡」的狀態時，會有「冰屬性弱點」，且物理攻擊會反擊</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. <span style='color: #ff0000;'>BOSS 集中水源後就會放海嘯，全體傷害較高，務必馬上回復</span><br /> 2. 帕羅姆放逞強後以震雷攻擊 ( 集中水源狀態 )，泰拉用暴雷</p>
<p>3. 兩位的魔法傷害很有效，帕羅姆最高甚至可達到 2000 左右 ( 看等級 )<br /> 4. 普羅姆主要作回復、放魔盾或護盾協助<br /> 5. 如果太多人中異常狀態 ( 催眠、麻痹等 )，可丟一個「獨角獸之角」解除<br /> 6. 幾回合後 BOSS 會開始躲進殼裡，這時候可轉用「冰屬性魔法」攻擊弱點！<br /> 7. 如果時間拖得較久，可能會再遇到 1~2 次的海嘯攻擊，要注意<br /> 8. 若怕運氣不好冰魔法剛好被吸收的話，全程都使用雷魔法也可以<br /> 9. 如果 MP 不夠用，除了吃以太之外，也可以讓帕羅姆或泰拉丟「宙斯之怒」<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗凱納槽後，西德就會出現，後續就會加入隊伍</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在前往飛空艇的路上，竟遭到了莫名的襲擊，兩側的牆壁不斷向中間擠壓！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 就在最危急的時刻，小小的帕羅姆與普羅姆勇敢地挺身而出，對自己放出了石化魔法，擋住兩側的石牆，解救了所有人！就連泰拉也無法以康復來解除他們的石化&#8230;.. <span style='color: #ff0000;'>( 帕羅姆與普羅姆離隊 )</span><br /> <span style='color: #0000ff;'>( 看到這一幕我真的是噴淚了&#8230;.太感人&#8230;.. )</span></p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上了飛空艇後，凱因又出現，要求眾人必須取得水晶來交換羅莎的安全</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在出發之前，還有個物品要拿，先停下飛空艇，回到巴隆城</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='返回古老水路 B3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>返回古老水路 B3</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到巴隆城的 1F 大廳往最左邊走上去</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出來後往左下角前進，回到外圍的水道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就一路從左下方，延著左側水道往上，走回古老水路</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這時候是否開始想念雙胞胎的黑白魔法了呢？換了一個西德感覺差好多啊&#8230;..不過還是要痛定思痛，西德身上的裝備有點悲劇，記得幫他調整一下。<br /> <span style='color: #ffffff;'>-</span><br /> 古老水路的 B1、B2 地圖都很簡單，直接一路往下走，前往 B3</p>
<p>來到 B3 後，前往地圖的中間靠上位置 <span style='color: #ff0000;'>( 紅圈處 )</span>，可以走下圖中的暗道</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡可以取得一個傳繼能力道具：「<span style='color: #800000;'>海嘯</span>」( 水中會出現發光點 )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 拿完之後，就可原路回去巴隆城，這裡無法使用道具「緊急出口」或是魔法「傳送」，必須要用走的回去&#8230;..好麻煩XDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>12/25 Update:</span> ( 感謝網友 <span style='color: #0000ff;'>alen</span> 補充，東塔 B2 打完 BOSS 後即可進入 )</p>
<p>接著回到巴隆城的東塔去，走到 B1 往右繼續走，之前被擋住的地方，現在已經可以下去了</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-038-1.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>在 B2 可以見到真正的巴隆王，但是講了關於幻獸的事情就又消失了&#8230;..</p>
<p>在後期<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff4_part_2_3.php#幻獸圖書館' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>取得召喚魔法：阿修羅、利維亞桑</span></a>
</span></span>之後，再回來這裡找巴隆王對話，會進入 <span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_part_3_1.php#巴隆城' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>BOSS 戰</span></a></span></span>，對手是奧丁，在奧丁身上可以偷到傳繼能力道具：<span style='color: #800000;'>暗黑 </span></p>
<p>( 傳繼能力道具取得及流程請參考：<span style='text-decoration: underline;'><span style='color: #0000ff;'><a href='./ff4_ability_items_list.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF4 傳繼能力道具一覽表</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-038-2.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 離開巴隆城後，可以先到旁邊的巴隆鎮上補充需要的恢復道具，在道具店的櫃檯內會多了一個老頭，有賣不一樣的道具，可以視需求買一下</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-038.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 不夠好像有點貴XDDD，買不起的話就多準備一些恢復道具即可</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後記得在旅店睡一覺恢復體力 ( 這裡的旅店睡覺只要 50 元，非睡不可&#8230;XDDDD )，然後就可以上飛空艇，往西北方向前進，到下一個地點：特羅亞城！</p>
<p><img class='alignnone' alt='' src='./ff4_images/ff4_part_1-3/06-castle_baron-040.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<p>FF4 Part 1-3 聖騎士的覺醒 ( 完 )</p></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
