<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "</head><body>";
echo "<style type='text/css'>
#liu table{background-color:#eeeeee; font-size:14px; text-align:center; border-collapse:collapse; border:1px black solid; width:600px;}
#liu th{background-color:#555555; border:1px black solid; color:#FFFFFF;}
#liu td{border:1px black solid;}</style>
<div id='liu' align='center'>
<br><font size=6>DQ7咒文一览</font><br><br>
<table>
    <tbody>
        <tr>
            <th colspan='5'>攻击咒文</th>
        </tr>
        <tr>
            <th width='100'>名称</th>
            <th width='75'>消耗MP</th>
            <th width='100'>使用范围</th>
            <th width='50'>属性</th>
            <th width='200'>效果</th>
        </tr>
        <tr>
            <td>
            Blaze</td>
            <td>2</td>
            <td>敌单体</td>
            <td>火 </td>
            <td>7～12伤害</td>
        </tr>
        <tr>
            <td>
            Blazemore</td>
            <td>4</td>
            <td>敌单体</td>
            <td>火</td>
            <td>80左右伤害</td>
        </tr>
        <tr>
            <td>
            Blazemost</td>
            <td>10</td>
            <td>敌单体</td>
            <td>火</td>
            <td>180左右伤害</td>
        </tr>
        <tr>
            <td>
            Firebal</td>
            <td>4</td>
            <td>敌一组</td>
            <td>火</td>
            <td>15～25伤害</td>
        </tr>
        <tr>
            <td>
            Firebane</td>
            <td>6</td>
            <td>敌一组</td>
            <td>火</td>
            <td>30～40伤害</td>
        </tr>
        <tr>
            <td>
            Firebolt</td>
            <td>10</td>
            <td>敌一组</td>
            <td>火</td>
            <td>90～100伤害</td>
        </tr>
        <tr>
            <td>
            Bang</td>
            <td>5</td>
            <td>敌全体</td>
            <td>爆炸</td>
            <td>15～25伤害</td>
        </tr>
        <tr>
            <td>
            Boom</td>
            <td>8</td>
            <td>敌全体</td>
            <td>爆炸</td>
            <td>55～60伤害</td>
        </tr>
        <tr>
            <td>
            Explodet</td>
            <td>15</td>
            <td>敌全体</td>
            <td>爆炸</td>
            <td>120～140伤害</td>
        </tr>
        <tr>
            <td>
            Iceblot</td>
            <td>3</td>
            <td>敌单体</td>
            <td>冰</td>
            <td>10～20伤害</td>
        </tr>
        <tr>
            <td>
            SnowStorm</td>
            <td>5</td>
            <td>敌一组</td>
            <td>冰</td>
            <td>40～50伤害</td>
        </tr>
        <tr>
            <td>
            Blizzard</td>
            <td>12</td>
            <td>敌全体</td>
            <td>冰</td>
            <td>90～100伤害</td>
        </tr>
        <tr>
            <td>
            Infernos </td>
            <td>2</td>
            <td>敌一组</td>
            <td>风</td>
            <td>8～25伤害</td>
        </tr>
        <tr>
            <td>
            Infermore</td>
            <td>4</td>
            <td>敌一组</td>
            <td>风</td>
            <td>25～55伤害</td>
        </tr>
        <tr>
            <td>
            Infermost</td>
            <td>8</td>
            <td>敌一组</td>
            <td>风</td>
            <td>60～120伤害</td>
        </tr>
        <tr>
            <td>
            Beat</td>
            <td>4</td>
            <td>敌单体</td>
            <td>即死</td>
            <td>即死</td>
        </tr>
        <tr>
            <td>
            Defeat</td>
            <td>7</td>
            <td>敌一组</td>
            <td>即死</td>
            <td>即死</td>
        </tr>
        <tr>
            <td>
            DefeatMax</td>
            <td>15</td>
            <td>敌全体</td>
            <td>即死</td>
            <td>即死</td>
        </tr>
        <tr>
            <td>
            Zap</td>
            <td>6</td>
            <td>敌全体</td>
            <td>雷</td>
            <td>80～90伤害</td>
        </tr>
        <tr>
            <td>
            Thordain</td>
            <td>15</td>
            <td>敌一组</td>
            <td>雷</td>
            <td>180～220伤害</td>
        </tr>
        <tr>
            <td>
            Alldain</td>
            <td>10&times;4</td>
            <td>敌单体</td>
            <td>雷</td>
            <td>四人合体攻击500～600伤害</td>
        </tr>
        <tr>
            <td>
            CoralRain</td>
            <td>8</td>
            <td>敌全体</td>
            <td>水</td>
            <td>50～100伤害</td>
        </tr>
        <tr>
            <td>
            WhirlPool</td>
            <td>12</td>
            <td>敌一组</td>
            <td>水</td>
            <td>120～150伤害</td>
        </tr>
        <tr>
            <td>
            Sacrifice</td>
            <td>1</td>
            <td>敌全体</td>
            <td>即死</td>
            <td>牺牲自己造成敌方巨大伤害</td>
        </tr>
        <tr>
            <th colspan='5'>回复咒文</th>
        </tr>
        <tr>
            <th>名称</th>
            <th>消耗MP</th>
            <th>使用范围</th>
            <th>属性</th>
            <th>效果</th>
        </tr>
        <tr>
            <td>
            Heal<br />
            </td>
            <td>2</td>
            <td>己单体</td>
            <td>回复</td>
            <td>30～40HP回复</td>
        </tr>
        <tr>
            <td>
            Healmore</td>
            <td>4</td>
            <td>己单体</td>
            <td>回复</td>
            <td>80左右HP回复</td>
        </tr>
        <tr>
            <td>
            HealAll</td>
            <td>6</td>
            <td>己单体</td>
            <td>回复</td>
            <td>HP全回复</td>
        </tr>
        <tr>
            <td>
            HealUs</td>
            <td>10</td>
            <td>己全体</td>
            <td>回复</td>
            <td>80左右HP回复</td>
        </tr>
        <tr>
            <td>
            HealUsALL</td>
            <td>20</td>
            <td>己全体</td>
            <td>回复</td>
            <td>全员HP全回复</td>
        </tr>
        <tr>
            <td>
            Antidote</td>
            <td>2</td>
            <td>己单体</td>
            <td>治疗</td>
            <td>解毒</td>
        </tr>
        <tr>
            <td>
            NumbOff</td>
            <td>2</td>
            <td>己全体</td>
            <td>治疗</td>
            <td>治疗麻痹</td>
        </tr>
        <tr>
            <td>
            Vivify</td>
            <td>8</td>
            <td>己单体</td>
            <td>苏生</td>
            <td>救活死亡同伴，成功率50％，HP50％回复</td>
        </tr>
        <tr>
            <td>
            Revive</td>
            <td>15</td>
            <td>己单体</td>
            <td>苏生</td>
            <td>救活死亡同伴，成功率100％，HP100％回复</td>
        </tr>
        <tr>
            <td>
            Farewell</td>
            <td>全部</td>
            <td>己全体</td>
            <td>苏生</td>
            <td>牺牲自己令全体同伴复活</td>
        </tr>
        <tr>
            <th colspan='5'>辅助咒文</th>
        </tr>
        <tr>
            <th>名称</th>
            <th>消耗MP</th>
            <th>使用范围</th>
            <th>属性</th>
            <th>效果</th>
        </tr>
        <tr>
            <td>
            Outside</td>
            <td>8</td>
            <td>己全体</td>
            <td>地图</td>
            <td>迷宫脱出</td>
        </tr>
        <tr>
            <td>
            Return</td>
            <td>1</td>
            <td>己全体</td>
            <td>地图</td>
            <td>飞行，立刻到达去过的城市</td>
        </tr>
        <tr>
            <td>
            X-Ray</td>
            <td>2</td>
            <td>宝箱等</td>
            <td>地图</td>
            <td>侦察宝箱，红色是怪物，蓝色是道具，黄色是金钱</td>
        </tr>
        <tr>
            <td>
            StepGuard</td>
            <td>2</td>
            <td>己全体</td>
            <td>地图</td>
            <td>安全穿越障碍和毒沼</td>
        </tr>
        <tr>
            <td>
            Repel</td>
            <td>4</td>
            <td>己全体</td>
            <td>地图</td>
            <td>一定步数内弱小敌人不出现</td>
        </tr>
        <tr>
            <td>
            Location</td>
            <td>2</td>
            <td>迷宫</td>
            <td>地图</td>
            <td>判断当前所在迷宫层数</td>
        </tr>
        <tr>
            <td>
            MapMagic</td>
            <td>2</td>
            <td>宝物</td>
            <td>地图</td>
            <td>侦察当前地图上的宝物</td>
        </tr>
        <tr>
            <td>
            Expel</td>
            <td>1</td>
            <td>敌全体</td>
            <td>即死</td>
            <td>以光之力赶走弱小怪物，丧尸系特效</td>
        </tr>
        <tr>
            <td>
            RobMagic</td>
            <td>0</td>
            <td>敌单体</td>
            <td>吸收</td>
            <td>吸收MP</td>
        </tr>
        <tr>
            <td>
            TakeMagic</td>
            <td>2</td>
            <td>己单体</td>
            <td>吸收</td>
            <td>受到魔法攻击时吸收相应MP</td>
        </tr>
        <tr>
            <td>
            StopSepell</td>
            <td>3</td>
            <td>敌一组</td>
            <td>封印</td>
            <td>封印敌人咒文</td>
        </tr>
        <tr>
            <td>
            MagicBack</td>
            <td>4</td>
            <td>自单体</td>
            <td>防御</td>
            <td>反弹敌人一次魔法攻击</td>
        </tr>
        <tr>
            <td>
            Bounce</td>
            <td>4</td>
            <td>自单体</td>
            <td>防御</td>
            <td>一定回合内反弹所有咒文</td>
        </tr>
        <tr>
            <td>
            MagicWall</td>
            <td>3</td>
            <td>己全体</td>
            <td>防御</td>
            <td>提高队伍魔法防御</td>
        </tr>
        <tr>
            <td>
            Surround</td>
            <td>5</td>
            <td>敌一组</td>
            <td>辅攻 </td>
            <td>起雾，降低敌命中率</td>
        </tr>
        <tr>
            <td>
            Sap</td>
            <td>3</td>
            <td>敌单体</td>
            <td>辅攻 </td>
            <td>降低敌物理防御</td>
        </tr>
        <tr>
            <td>
            Defense</td>
            <td>4</td>
            <td>敌一组</td>
            <td>辅攻 </td>
            <td>降低敌物理防御</td>
        </tr>
        <tr>
            <td>
            Upper</td>
            <td>2</td>
            <td>己单体</td>
            <td>防御</td>
            <td>提高单体物理防御</td>
        </tr>
        <tr>
            <td>
            Increase</td>
            <td>3</td>
            <td>己全体</td>
            <td>防御</td>
            <td>提高全体物理防御</td>
        </tr>
        <tr>
            <td>
            Sleep</td>
            <td>3</td>
            <td>敌一组</td>
            <td>辅攻 </td>
            <td>催眠敌人</td>
        </tr>
        <tr>
            <td>
            SleepAll</td>
            <td>5</td>
            <td>敌一组</td>
            <td>辅攻 </td>
            <td>强力催眠</td>
        </tr>
        <tr>
            <td>
            PanicAll</td>
            <td>5</td>
            <td>敌一组</td>
            <td>辅攻 </td>
            <td>令敌人混乱</td>
        </tr>
        <tr>
            <td>
            Barrier</td>
            <td>3</td>
            <td>己全体</td>
            <td>防御</td>
            <td>提高对炎系、冻气系特技的防御</td>
        </tr>
        <tr>
            <td>
            Disperse</td>
            <td>8</td>
            <td>敌单体</td>
            <td>即死</td>
            <td>吹跑敌人</td>
        </tr>
        <tr>
            <td>
            BeDragon</td>
            <td>18</td>
            <td>自单体</td>
            <td>变身</td>
            <td>幻化成龙，不受控制</td>
        </tr>
        <tr>
            <td>
            TwinHits</td>
            <td>6</td>
            <td>己单体</td>
            <td>变身</td>
            <td>对敌物理攻击伤害&times;2</td>
        </tr>
        <tr>
            <td>
            Chance</td>
            <td>20</td>
            <td>？</td>
            <td>？</td>
            <td>历代的谜之咒文，多种效果随机出现</td>
        </tr>
        <tr>
            <td>
            Ironize</td>
            <td>2</td>
            <td>己全体</td>
            <td>变身</td>
            <td>全体钢铁化，敌攻击无效</td>
        </tr>
    </tbody>
</table>
</div>";
echo "</body></html>";
?>

<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
