<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "</head><body>";
echo "<style type='text/css'>
#liu table{background-color:#eeeeee; font-size:14px; text-align:center; border-collapse:collapse; border:1px black solid; width:600px;}
#liu th{background-color:#555555; border:1px black solid; color:#FFFFFF;}
#liu td{border:1px black solid;}</style>
<div id='liu' align='center'>
<br><font size=6>DQ7特技一览</font><br><br>
<table>
    <tbody>
        <tr>
            <th colspan='4' wdith='509'>攻击系特技</th>
        </tr>
        <tr>
            <th width='123'>日文名称</th>
            <th width='63'>消耗MP</th>
            <th width='73'>使用范围</th>
            <th width='247'>效果</th>
        </tr>
        <tr>
            <td>
            UltraHit</td>
            <td>20</td>
            <td>敌单体</td>
            <td>雷属性，伤害600+1～100</td>
        </tr>
        <tr>
            <td>
            CragThrow</td>
            <td>0</td>
            <td>敌一组</td>
            <td>扔石头，15～20伤害</td>
        </tr>
        <tr>
            <td>
            Lightning</td>
            <td>0</td>
            <td>敌全体</td>
            <td>雷电攻击，40左右伤害</td>
        </tr>
        <tr>
            <td>
            BoltSlash</td>
            <td width='63'>
            <p align='center'>0</p>
            </td>
            <td width='73'>敌单体</td>
            <td>雷光斩，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>
            FireSlash</td>
            <td>0</td>
            <td>敌单体</td>
            <td>火焰斩，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>
            BlazeAir</td>
            <td>0</td>
            <td>敌全体</td>
            <td>炎之息，35左右伤害</td>
        </tr>
        <tr>
            <td>
            WhiteAir</td>
            <td>0</td>
            <td>敌全体</td>
            <td>辉之息，冻气系220左右伤害</td>
        </tr>
        <tr>
            <td>
            WindBeast</td>
            <td>0</td>
            <td>敌单体</td>
            <td>镰鼬，风属性Lv&times;3＋10左右</td>
        </tr>
        <tr>
            <td>
            Bite</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通攻击&times;1.1～1.2</td>
        </tr>
        <tr>
            <td>
            BirdSlash</td>
            <td>0</td>
            <td>敌单体</td>
            <td>空中敌人&times;1.25倍伤害</td>
        </tr>
        <tr>
            <td>
            RockThrow</td>
            <td>0</td>
            <td>敌全体</td>
            <td>投巨石，110左右伤害</td>
        </tr>
        <tr>
            <td>
            GigaSlash</td>
            <td>15</td>
            <td>敌一组</td>
            <td>雷属性，350～400伤害</td>
        </tr>
        <tr>
            <td>
            K.O. Punch</td>
            <td>0</td>
            <td>敌单体</td>
            <td>即死，失败的话普通攻击&times;0.5</td>
        </tr>
        <tr>
            <td>
            MultiCut</td>
            <td>20</td>
            <td>敌一组</td>
            <td>巨十字，风系180～220，丧尸系&times;1.3</td>
        </tr>
        <tr>
            <td>
            CallArmy</td>
            <td>0</td>
            <td>乱数4</td>
            <td>召唤军队Lv&times;2＋25左右，耗钱Lv&times;50</td>
        </tr>
        <tr>
            <td>
            IceAir</td>
            <td>0</td>
            <td>敌全体</td>
            <td>冰之息，50～60伤害</td>
        </tr>
        <tr>
            <td>
            IceStorm</td>
            <td>0</td>
            <td>敌全体</td>
            <td>冻吹雪，120～140伤害</td>
        </tr>
        <tr>
            <td>
            RainSlash</td>
            <td>0</td>
            <td>敌全体</td>
            <td>五月雨剑，伤害逐次递减</td>
        </tr>
        <tr>
            <td>
            HellBlast</td>
            <td>25</td>
            <td>敌全体</td>
            <td>地狱雷霆，220～290伤害</td>
        </tr>
        <tr>
            <td>
            SquallHit</td>
            <td>0</td>
            <td>敌单体</td>
            <td>优先攻击，普通攻击&times;0.8</td>
        </tr>
        <tr>
            <td>
            K.O. Dance</td>
            <td>0</td>
            <td>敌全体</td>
            <td>即死，概率低</td>
        </tr>
        <tr>
            <td>
            Quake</td>
            <td>0</td>
            <td>敌全体</td>
            <td>岩系，50～65伤害</td>
        </tr>
        <tr>
            <td>
            WhiteFire</td>
            <td>0</td>
            <td>敌全体</td>
            <td>炎系，150～160伤害</td>
        </tr>
        <tr>
            <td>
            Tremor</td>
            <td>0</td>
            <td>敌全体</td>
            <td>掉入深渊，空中敌人无效，有失误概率</td>
        </tr>
        <tr>
            <td>
            VacuSlash</td>
            <td>0</td>
            <td>敌单体</td>
            <td>风系，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>
            Vacuum</td>
            <td>0</td>
            <td>敌全体</td>
            <td>风系80～90左右伤害，丧尸系&times;1.3</td>
        </tr>
        <tr>
            <td>
            Berserker</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通攻击&times;2，己伤害（含特技）&times;2</td>
        </tr>
        <tr>
            <td>
            Punch</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通攻击&times;1.5，有失误概率</td>
        </tr>
        <tr>
            <td>
            ZombieCut
            </td>
            <td>0</td>
            <td>敌单体</td>
            <td>丧尸系&times;1.5伤害</td>
        </tr>
        <tr>
            <td>
            Ramming</td>
            <td>0</td>
            <td>敌单体</td>
            <td>敌HP&times;0.8，己HP&times;0.8，有失误概率</td>
        </tr>
        <tr>
            <td>
            Tsunami</td>
            <td>0</td>
            <td>敌全体</td>
            <td>水系30～40伤害，失误概率与地形有关</td>
        </tr>
        <tr>
            <td>
            FrigidAir</td>
            <td>0</td>
            <td>敌全体</td>
            <td>冻气系，10～16伤害</td>
        </tr>
        <tr>
            <td>
            SwordDanc</td>
            <td>0</td>
            <td>乱数4</td>
            <td>普通攻击&times;0.75&times;4</td>
        </tr>
        <tr>
            <td>
            Howl</td>
            <td>0</td>
            <td>乱数4</td>
            <td>普通攻击&times;4，有失误概率</td>
        </tr>
        <tr>
            <td>
            Stampede</td>
            <td>0</td>
            <td>乱数4</td>
            <td>普通攻击&times;4，有失误概率</td>
        </tr>
        <tr>
            <td>
            JumpKick</td>
            <td>0</td>
            <td>敌单体</td>
            <td>空中敌人&times;1.5伤害</td>
        </tr>
        <tr>
            <td>
            DrakSlash</td>
            <td>0</td>
            <td>敌单体</td>
            <td>龙系敌人&times;1.5伤害</td>
        </tr>
        <tr>
            <td>
            ThiefHit</td>
            <td>0</td>
            <td>敌单体</td>
            <td>攻击附加偷取道具</td>
        </tr>
        <tr>
            <td>
            QuadHits</td>
            <td>0</td>
            <td>乱数4</td>
            <td>普通攻击&times;0.5&times;4</td>
        </tr>
        <tr>
            <td>
            Scorching</td>
            <td>0</td>
            <td>敌全体</td>
            <td>炎系65～80伤害</td>
        </tr>
        <tr>
            <td>
            FalconCut</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通攻击&times;0.7&times;2</td>
        </tr>
        <tr>
            <td>
            Hurricane</td>
            <td>0</td>
            <td>敌一组</td>
            <td>风系＋水系70左右伤害，有失误概率</td>
        </tr>
        <tr>
            <td>
            Rip</td>
            <td>0</td>
            <td>敌一组</td>
            <td>普通攻击，伤害逐次递减</td>
        </tr>
        <tr>
            <td>
            BigBang</td>
            <td>30</td>
            <td>敌全体</td>
            <td>炎系爆炸，300～400伤害</td>
        </tr>
        <tr>
            <td>
            FireAir</td>
            <td>0</td>
            <td>敌全体</td>
            <td>炎系6～10伤害</td>
        </tr>
        <tr>
            <td>
            FireTower</td>
            <td>0</td>
            <td>敌单体</td>
            <td>炎系180左右伤害，有失误概率</td>
        </tr>
        <tr>
            <td>
            Tackle</td>
            <td>0</td>
            <td>敌单体</td>
            <td>敌HP&times;0.8，己HP&times;0.8</td>
        </tr>
        <tr>
            <td>
            ConfuHit</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通攻击，追加混乱效果</td>
        </tr>
        <tr>
            <td>
            Magma</td>
            <td>0</td>
            <td>敌全体</td>
            <td>炎系＋岩系80左右伤害，有失误概率</td>
        </tr>
        <tr>
            <td>
            EvilSlash</td>
            <td>0</td>
            <td>敌单体</td>
            <td>Miss或会心一击，成功概率为3/8</td>
        </tr>
        <tr>
            <td>
            MegaMagic</td>
            <td>所有</td>
            <td>敌全体</td>
            <td>当前MP&times;3伤害</td>
        </tr>
        <tr>
            <td>
            RamAttack</td>
            <td>0</td>
            <td>敌单体</td>
            <td>冲撞敌人，让对方和自己的HP都剩下1/5</td>
        </tr>
        <tr>
            <td>
            IceSlash</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>
            Roundhous</td>
            <td>0</td>
            <td>敌一组</td>
            <td>普通攻击，伤害逐次递减</td>
        </tr>
        <tr>
            <td>
            Massacre</td>
            <td>0</td>
            <td>任一</td>
            <td>会心一击，对象不可指定</td>
        </tr>
        <tr>
            <td>
            BackFlip</td>
            <td>0</td>
            <td>敌全体</td>
            <td>普通攻击&times;[3/（敌人数＋1）]倍</td>
        </tr>
        <tr>
            <td>
            Tremor</td>
            <td>15</td>
            <td>敌全体</td>
            <td>大地龟裂，100％成功，空中敌人无效</td>
        </tr>
        <tr>
            <td>
            MetalCut</td>
            <td>0</td>
            <td>敌单体</td>
            <td>金属系&times;1.5＋1伤害，命中率99％</td>
        </tr>
        <tr>
            <td>
            2EdgeHit</td>
            <td>0</td>
            <td>敌单体</td>
            <td>普通伤害&times;1.5，1/4伤害反弹</td>
        </tr>
        <tr>
            <td>
            HellFlame</td>
            <td>20</td>
            <td>敌全体</td>
            <td>炎系250～300伤害</td>
        </tr>
        <tr>
            <th width='509' colspan='4'>回复系特技</th>
        </tr>
        <tr>
            <th width='123'>日文名称</th>
            <th width='63'>消耗MP</th>
            <th width='73'>使用范围</th>
            <th width='247'>效果</th>
        </tr>
        <tr>
            <td>
            LifeSong</td>
            <td>10</td>
            <td>己全体</td>
            <td>全体复活，100％HP回复，50％成功，效果维持2回合</td>
        </tr>
        <tr>
            <td>
            AngelSong</td>
            <td>0</td>
            <td>己单体</td>
            <td>单体复活，50％成功，50％HP回复</td>
        </tr>
        <tr>
            <td>
            Hustle</td>
            <td>0</td>
            <td>己全体</td>
            <td>全体80左右HP回复</td>
        </tr>
        <tr>
            <td>
            Meditate</td>
            <td>0</td>
            <td>自单体</td>
            <td>使用者HP回复500</td>
        </tr>
        <tr>
            <td>
            WakeSong</td>
            <td>0</td>
            <td>己全体</td>
            <td>全体睡眠状态解除</td>
        </tr>
        <tr>
            <td>
            HealSong</td>
            <td>0</td>
            <td>己全体</td>
            <td>全体HP回复20～30</td>
        </tr>
        <tr>
            <td>
            Mineuchi</td>
            <td>0</td>
            <td>己单体</td>
            <td>解除睡眠和混乱状态</td>
        </tr>
        <tr>
            <td>
            LifeDance</td>
            <td>0</td>
            <td>己全体</td>
            <td>牺牲自己使我方其他同伴完全复活（复活时HP全恢复），1/2几率失败，失败时使用者还是死亡。</td>
        </tr>
        <tr>
            <th bgcolor='#555555' colspan='4' height='24'>
            <p align='center'><font color='#ffffff' size='2'>辅助系特技</font></p>
            </th>
        </tr>
        <tr>
            <th width='123'>日文名称</th>
            <th width='63'>消耗MP</th>
            <th width='73'>使用范围</th>
            <th width='247'>效果</th>
        </tr>
        <tr>
            <td>
            LegSweep</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一回合内无法行动</td>
        </tr>
        <tr>
            <td>
            SleepAir</td>
            <td>0</td>
            <td>敌一组</td>
            <td>睡眠</td>
        </tr>
        <tr>
            <td>
            FishNet</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            EerieFog</td>
            <td>0</td>
            <td>敌我全体</td>
            <td>无法使用魔法</td>
        </tr>
        <tr>
            <td>
            QuickJoke</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            DeMagic</td>
            <td>0</td>
            <td>敌全体</td>
            <td>去除有利附加状态</td>
        </tr>
        <tr>
            <td>
            WoolGuard</td>
            <td>0</td>
            <td>己全体</td>
            <td>冻气系特技伤害减半</td>
        </tr>
        <tr>
            <td>
            ParryPass</td>
            <td>0</td>
            <td>自单体</td>
            <td>伤害反弹到其他同伴or怪物身上</td>
        </tr>
        <tr>
            <td>
            BirdEye</td>
            <td>0</td>
            <td>地图</td>
            <td>侦察最近的城镇、山洞坐标</td>
        </tr>
        <tr>
            <td>
            FairWind</td>
            <td>0</td>
            <td>自单体</td>
            <td>反弹炎系和冻气系特技</td>
        </tr>
        <tr>
            <td>
            WarCry</td>
            <td>0</td>
            <td>敌全体</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            DanceShut</td>
            <td>0</td>
            <td>敌一组</td>
            <td>封住舞蹈系特技</td>
        </tr>
        <tr>
            <td>
            PsycheUp</td>
            <td>0</td>
            <td>自单体</td>
            <td>下回合物理攻击伤害2倍</td>
        </tr>
        <tr>
            <td>
            Tickle</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一定几率最多三回合无法动弹</td>
        </tr>
        <tr>
            <td>
            Whistle</td>
            <td>0</td>
            <td>地图</td>
            <td>招来敌人进入战斗</td>
        </tr>
        <tr>
            <td>
            Summon</td>
            <td>0</td>
            <td>己方</td>
            <td>召唤4种幻魔之一作为仲间参战</td>
        </tr>
        <tr>
            <td>
            WaveSong</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一定几率强力睡眠</td>
        </tr>
        <tr>
            <td>
            LureDance</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            Retaliate</td>
            <td>0</td>
            <td>自单体</td>
            <td>模仿自己所受到的攻击进行反击</td>
        </tr>
        <tr>
            <td>
            TipToe</td>
            <td>0</td>
            <td>己方</td>
            <td>减少遇敌概率</td>
        </tr>
        <tr>
            <td>
            Giggle</td>
            <td>0</td>
            <td>己方</td>
            <td>似乎无效果</td>
        </tr>
        <tr>
            <td>
            Summoner</td>
            <td>20</td>
            <td>己方</td>
            <td>召唤4种大地精灵之一作为仲间参战</td>
        </tr>
        <tr>
            <td>
            BigTrip</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            BoxerDanc</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            SandStorm</td>
            <td>0</td>
            <td>敌全体</td>
            <td>一定几率物理攻击命中减半</td>
        </tr>
        <tr>
            <td>
            StrongD</td>
            <td>0</td>
            <td>自单体</td>
            <td>所有伤害降至1/10</td>
        </tr>
        <tr>
            <td>
            WarSong</td>
            <td>0</td>
            <td>己全体</td>
            <td>增加50%物理防御</td>
        </tr>
        <tr>
            <td>
            EagleEye</td>
            <td>0</td>
            <td>地图</td>
            <td>侦察最近的城镇、山洞坐标</td>
        </tr>
        <tr>
            <td>
            ChargeUp</td>
            <td>0</td>
            <td>自单体</td>
            <td>下回合物理攻击伤害2倍</td>
        </tr>
        <tr>
            <td>
            KnockDown</td>
            <td>0</td>
            <td>敌单体</td>
            <td>踢飞敌人</td>
        </tr>
        <tr>
            <td>
            PointOut</td>
            <td>0</td>
            <td>自单体</td>
            <td>反击敌人攻击</td>
        </tr>
        <tr>
            <td>
            Smell</td>
            <td>0</td>
            <td>地图</td>
            <td>侦察本层宝物数量</td>
        </tr>
        <tr>
            <td>
            PoisonGas</td>
            <td>0</td>
            <td>敌一组</td>
            <td>令敌人中毒</td>
        </tr>
        <tr>
            <td>
            Suplex</td>
            <td>0</td>
            <td>敌单体</td>
            <td>轰飞敌人</td>
        </tr>
        <tr>
            <td>
            LushLicks</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            Guardian</td>
            <td>0</td>
            <td>自单体</td>
            <td>承受一回合内所有攻击</td>
        </tr>
        <tr>
            <td>
            Slumber</td>
            <td>0</td>
            <td>自单体</td>
            <td>行走1步回复1HP和1MP</td>
        </tr>
        <tr>
            <td>
            HolyAura</td>
            <td>0</td>
            <td>己全体</td>
            <td>诺亚之舟，我方全体不受任何攻击一回合</td>
        </tr>
        <tr>
            <td>
            CurseSong</td>
            <td>0</td>
            <td>敌一组</td>
            <td>降低敌防御</td>
        </tr>
        <tr>
            <td>
            PuffPuff</td>
            <td>0</td>
            <td>敌单体</td>
            <td>男性使用为攻击，女性为让敌人不能行动</td>
        </tr>
        <tr>
            <td>
            RamSong</td>
            <td>0</td>
            <td>敌全体</td>
            <td>睡眠</td>
        </tr>
        <tr>
            <td>
            RamDance</td>
            <td>0</td>
            <td>？</td>
            <td>？</td>
        </tr>
        <tr>
            <td>
            SickLick</td>
            <td>0</td>
            <td>敌单体</td>
            <td>封住行动＋防御降为0</td>
        </tr>
        <tr>
            <td>
            EerieLite</td>
            <td>0</td>
            <td>敌一组</td>
            <td>降低敌人魔法耐性</td>
        </tr>
        <tr>
            <td>
            OddDance</td>
            <td>0</td>
            <td>敌单体</td>
            <td>削减敌MP</td>
        </tr>
        <tr>
            <td>
            ShipDance</td>
            <td>0</td>
            <td>敌单体</td>
            <td>一回合无法行动，成功率高</td>
        </tr>
        <tr>
            <td>
            Change</td>
            <td>0</td>
            <td>自单体</td>
            <td>变身为怪物，不可控制</td>
        </tr>
        <tr>
            <td>
            Bark</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一回合内一定几率无法行动</td>
        </tr>
        <tr>
            <td>
            Silliness</td>
            <td>0</td>
            <td>自单体</td>
            <td>躲开敌人攻击，有失败概率</td>
        </tr>
        <tr>
            <td>
            MistSong</td>
            <td>0</td>
            <td>敌一组</td>
            <td>封印魔法</td>
        </tr>
        <tr>
            <td>
            Flash</td>
            <td>0</td>
            <td>敌全体</td>
            <td>一定几率物理攻击命中率减半</td>
        </tr>
        <tr>
            <td>
            RobDance</td>
            <td>0</td>
            <td>敌单体</td>
            <td>吸收MP</td>
        </tr>
        <tr>
            <td>
            Tamer</td>
            <td>0</td>
            <td>敌单体</td>
            <td>提高魔物仲间率，可重复使用，效果叠加</td>
        </tr>
        <tr>
            <td>
            SideStep</td>
            <td>0</td>
            <td>自单体</td>
            <td>物理攻击回避率50%，效果持续2回合</td>
        </tr>
        <tr>
            <td>
            ScapeGoat</td>
            <td>0</td>
            <td>自单体</td>
            <td>
            <p>替指定的伙伴承受攻击</p>
            </td>
        </tr>
        <tr>
            <td>
            PaniDance</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一定几率混乱</td>
        </tr>
        <tr>
            <td>
            PoisonFog</td>
            <td>0</td>
            <td>敌一组</td>
            <td>中剧毒，每回合扣1/8HP</td>
        </tr>
        <tr>
            <td>
            PalsyAir</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一定几率麻痹</td>
        </tr>
        <tr>
            <td>
            SleepSong</td>
            <td>0</td>
            <td>敌一组</td>
            <td>一定几率睡眠</td>
        </tr>
    </tbody>
</table>
</div>";
echo "</body></html>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
