<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "<link href='./ff9.css' rel='stylesheet' type='text/css' media='all'/>";
echo "</head><body>";
echo "<center><font size=6>勇者斗恶龙7石板指南</font><br><font color=red>红色石板</font><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_taizuo_red1.gif' /></td>";
echo "<td align=center><font color=red>左上方台座(1)Engow(炎豪)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Rexwood(伍德帕尔纳)東の塔1F右边的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>ColorstoneMine(采掘所)採掘所最底层B7上方地上调查获得</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Estard(王城)城背面地下宝物库中的宝箱</td>";
echo "</tr></table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=5><img src='./pic2/dq7shiban_taizuo_red5.gif' /></td>";
echo "<td align=center><font color=red>右下方台座(5)Ruins_of_Verdham(记忆之叶废墟)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Falrish(佛利修)西侧仓库内的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝过去－</font>Mech_base(机关兵据点)最下层的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Zebbot(机关研究所)中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>Falrish(佛利修)镇右下角民家中与アルマン的孙女对话获得</td>";
echo "</tr></table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_taizuo_red2.gif' /></td>";
echo "<td align=center><font color=red>右上方台座(2)Loomin(鲁梅恩)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Palace-Dune(沙漠之城)隐藏阶梯地下宝物库中的宝箱<br>Hamelia(哈梅里亚)剧情完成后回到Palace-Dune(沙漠之城)与女王对话</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Mountain_Tower(深山之塔)1F的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Mountain_Tower(深山之塔)最上层boss掉落</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_taizuo_red3.gif' /></td>";
echo "<td align=center><font color=red>中间的台座(3)Litorud(利特鲁德)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Krage(克雷久)井中事件完成后与农夫对话后获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Krage(克雷久)豪宅地下的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Krage(克雷久)北方世界树下发现</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_taizuo_red4.gif' /></td>";
echo "<td align=center><font color=red>左下方台座(4)Mardra(玛迪拉斯)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>世界一高い塔最上层10F事件后获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Hamelia(哈梅里亚)地下宝物库的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>海底都市1F的宝箱</td></tr>";
echo "</table><br><br><font color=green>绿色石板</font><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=5><img src='./pic2/dq7shiban_green_green1.gif' /></td>";
echo "<td align=center><font color=green>左上方台座(1)－Orph(奥尔菲)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>打倒Rexwood(伍德帕尔纳)東の塔门前的ゴーレム获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Rexwood(伍德帕尔纳)村子左下方屋子内的桌子</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Engow(炎豪)村炎の山进入后遇分岔，走右边到最下层的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>移民の町石碑右方调查获得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=6><img src='./pic2/dq7shiban_green_green3.gif' /></td>";
echo "<td align=center><font color=green>左下方台座(3)－DejaCamp(尤巴尔族休息地)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>－Orph(奥尔菲)武器店中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Falrod_Castle(佛罗德城)城地下牢房中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Ruins_of_Verdham(记忆之叶废墟)西の洞窟b2f宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>4＝过去－</font>Ruins_of_Verdham(记忆之叶废墟)西の洞窟b4f宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>5＝现在－</font>过去Ruins_of_Verdham(记忆之叶废墟)的位置处的废墟中发现</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=5><img src='./pic2/dq7shiban_green_green2.gif' /></td>";
echo "<td align=center><font color=green>右上方台座(2)－Probina(普罗比纳)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>Litorud(利特鲁德)镇中南方民家中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Balock_Tower(巴洛克之塔)最上层的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Hamelia(哈梅里亚)Mountain_Tower(深山之塔)5F老乐者给予</td></tr>";
echo "<tr><td align=left><font color=blue>4＝过去－</font>Hamelia(哈梅里亚)宝物库内的宝箱</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=6><img src='./pic2/dq7shiban_green_green4.gif' /></td>";
echo "<td align=center><font color=green>右下方台座(4)－圣风之谷</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>乘坐魔法飞毯来到Mezar(梅萨雷)东边的Great_Hero_Shrine(神兵之祠)，调查宝箱获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Probina(普罗比纳)教会中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Loomin(鲁梅恩)井下洞穴最深处打败boss后获得</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>DejaCamp(尤巴尔族休息地)西の岩壁アイラ加入时获得</td></tr>";
echo "<tr><td align=left><font color=blue>5＝现在－</font>大神殿地下通道的宝箱</td></tr>";
echo "</table><br><br><font color=darkyellow>黄色石板</font><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_yellow_yellow1.gif' /></td>";
echo "<td align=center><font color=darkyellow>左上方台座(1)－Rexwood(伍德帕尔纳)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>Ruin_Temple(谜之神殿)大厅石碑前的地上调查获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>黄色台座的房间左上方调查获得</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Fishbel(鱼铃)村自己家里与父亲对话获得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=6><img src='./pic2/dq7shiban_yellow_yellow3.gif' /></td>";
echo "<td align=center><font color=darkyellow>中间的台座(3)－沙漠之城</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>移民镇(移民镇)镇右下方秘密基地中的木桶</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Mentare(记忆之叶)3F的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>DejaCamp(尤巴尔族休息地)湖の洞くつ最下层的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>Dharma(达玛神殿)神殿内宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>5＝现在－</font>(达玛神殿)神殿西南方山贼藏身处打败最深处的山贼老大后获得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=6><img src='./pic2/dq7shiban_yellow_yellow5.gif' /></td>";
echo "<td align=center><font color=darkyellow>右下方台座(5)－Hamelia(哈梅里亚)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>达玛南废墟(达玛南废墟)町上方民家中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Mezar(梅萨雷)井中发现</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>化石の発掘現場的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>4＝过去－</font>Litorud(利特鲁德)谜之神殿异世界(时空洞穴)打败最深处的boss获得</td></tr>";
echo "<tr><td align=left><font color=blue>5＝现在－</font>Balock_Tower(巴洛克之塔)最上层的宝箱</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_yellow_yellow4.gif' /></td>";
echo "<td align=center><font color=darkyellow>左下方台座(4)－Krage(克雷久)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Dharma(达玛神殿)神殿内宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝过去－</font>砂漠の村地下宝物库中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>砂漠の村中央大罐子中发现</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=5><img src='./pic2/dq7shiban_yellow_yellow2.gif' /></td>";
echo "<td align=center><font color=darkyellow>右上方(2)台座－Labres(雷布雷萨克)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>Brugeo_House(布尔吉奥的家)敷厨房的地下室宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Probina(普罗比纳)山洞くつ的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Loomin(鲁梅恩)东面的山丘中发现</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>Lefa_Fane(利法族神殿)中神之石位置调查获得</td></tr>";
echo "</table><br><br><font color=blue>蓝色石板</font><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=2><img src='./pic2/dq7shiban_blue_blue1.gif' /></td>";
echo "<td align=center><font color=blue>左上方台座(1)－移民镇(移民镇)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Engow(炎豪)村炎の山黑烟时间结束后与占卜师对话获得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=5><img src='./pic2/dq7shiban_blue_blue2.gif' /></td>";
echo "<td align=center><font color=blue>右上方台座(2)－Falrish(佛利修)</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>Engow(炎豪)村炎の山内部打败炎の巨人后获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝过去－</font>Orph(奥尔菲)神の山2F的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Orph(奥尔菲)神の山5F的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>Orph(奥尔菲)神の山BOSS战处调查棺材事件后获得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_blue_blue3.gif' /></td>";
echo "<td align=center><font color=blue>左下方台座(3)－Dharma(达玛神殿)神殿</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>DejaCamp(尤巴尔族休息地)帐篷中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Estard(王城)城与Estard(王城)王对话后获得</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>化石の発掘現場井中的橱中发现</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_blue_blue4.gif' /></td>";
echo "<td align=center><font color=blue>右下方台座(4)－Coastal(克斯塔尔)城</font></td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>沙漠之城西南方的大地の精霊像5F调查获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Lefa_Fane(利法族神殿)中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Labres(雷布雷萨克)道具屋帐篷内的宝箱</td></tr>";
echo "</table><br><br>谜之石板<br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_wenhao_nazo1.gif' /></td>";
echo "<td align=center>天上の神殿上方的台座－聖なる湖</td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>Loomin(鲁梅恩)西边的塔最上层发现</td></tr>";
echo "<tr><td align=left><font color=blue>2＝过去－</font>Coastal(克斯塔尔)城下町右方民家调查书架后的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Halfling_cave(霍比特族洞穴)B3的宝箱</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=4><img src='./pic2/dq7shiban_wenhao_nazo2.gif' /></td>";
echo "<td align=center>化石の発掘現場最下层的台座－魔空间神殿（最终迷宫）</td></tr>";
echo "<tr><td align=left><font color=blue>1＝过去－</font>大灯台最上层事件后打败boss获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Coral_Cave(珊瑚洞窟)中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Hamelia(哈梅里亚)北方的祠堂与黑衣人对话获得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=5><img src='./pic2/dq7shiban_wenhao_nazo3.gif' /></td>";
echo "<td align=center>通关后来到Ruin_Temple(谜之神殿)大厅、打开上方铁门后的台座－Ruin_Temple(谜之神殿异世界)（隐藏迷宫1）</td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>海底都市打败bossグラコス5世后获得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>打败最终boss后周游世界最后到Estard(王城)城时在城下町的井中调查获得。之后可直接触发剧情完成通关。（对应3DS版）<br>
现在－打败最终boss后周游世界最后到Estard在城下町的井中调查获得石版,然后进入城下町右上方楼梯在下方深处发现一个宝箱，<br>调查宝箱把刚得到的石版放入宝箱中即可存档。欣赏完结局后读取进度再到原处调查宝箱获得（DISC2）</td></tr>";
echo "<tr><td align=left><font color=blue>3＝过去－</font>Coral_Cave(珊瑚洞窟)中与两个幽灵对话后获得（游戏后期）</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>徽章王城用100枚小徽章换得</td></tr>";
echo "</table><br>";
echo "<table width=80% border=1 cellspacing=0 cellpadding=1><tr><td align=center rowspan=7><img src='./pic2/dq7shiban_wenhao_nazo4.gif' /></td>";
echo "<td align=center>通关后来到Ruin_Temple(谜之神殿)、打开铁门后来到最下层的台座－Coral_Lake(圣湖)異世界（隐藏迷宫2）</td></tr>";
echo "<tr><td align=left><font color=blue>1＝现在－</font>Coastal(克斯塔尔)赌场2000代币换得</td></tr>";
echo "<tr><td align=left><font color=blue>2＝现在－</font>Coastal(克斯塔尔)神父事件后调查教堂桌子前获得</td></tr>";
echo "<tr><td align=left><font color=blue>3＝现在－</font>Coral_Cave(珊瑚洞窟)魔物给予</td></tr>";
echo "<tr><td align=left><font color=blue>4＝现在－</font>最终迷宫Dark_palace(黑暗宫)最下层使用水のアミュレット进入激流の洞くつ后的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>5＝现在－</font>移民之镇最终形态（14人以上）民家中的宝箱（对应3DS版）<br>移民之镇第八形态（35人以上）民家中的宝箱</td></tr>";
echo "<tr><td align=left><font color=blue>6-8＝－</font>Ruin_Temple(谜之神殿异世界)－19回合内击败隐藏boss神3次，得到三块石板</td></tr>";
echo "</table><br>";
echo "</center></body></html>";
?>
