<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='font-size: 22px; color: #800000;'>Final Fantasy 3 ( iOS )</span></p>
<p><span style='font-size: 22px; color: #800000;'>Walkthrough, Graphic Guide</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>最終幻想 3 ( iOS ) 圖文攻略</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>Part 2-2 取得飛空艇無敵號</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多加莊園'><span style='color: #000080; text-decoration: underline;'>多加莊園</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>1.1 &#8211; 多加加入隊伍<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#魔法陣洞窟'><span style='color: #000080; text-decoration: underline;'>魔法陣洞窟</span></a></span></span><br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#多加村'><span style='color: #000080; text-decoration: underline;'>多加村</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; 各級黑白魔法提供購買<br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#海底洞窟'><span style='color: #000080; text-decoration: underline;'>海底洞窟</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#海底洞窟 地圖1'><span style='color: #000080; text-decoration: underline;'>海底洞窟 地圖1</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#海底洞窟 地圖2'><span style='color: #000080; text-decoration: underline;'>海底洞窟 地圖2</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#海底洞窟 地圖3'><span style='color: #000080; text-decoration: underline;'>海底洞窟 地圖3</span></a></span></span></p>
<p>(04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞地下迷宮'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞地下迷宮</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>4.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞地下迷宮 地圖1'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞地下迷宮 地圖1</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞地下迷宮 地圖2'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞地下迷宮 地圖2</span>
</a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞地下迷宮 地圖3'><span style='color: #000080; text-decoration: underline;'>
薩羅尼亞地下迷宮 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞地下迷宮 地圖4'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞地下迷宮 地圖4</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
4.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞地下迷宮 地圖5'>
<span style='color: #000080; text-decoration: underline;'>薩羅尼亞地下迷宮 地圖5</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：奧丁 <span style='color: #ff0000;'>( 可偷到神槍昆古尼爾，建議後期再回來偷 )</span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>取得召喚魔法「災變」</span><br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#時之神殿'><span style='color: #000080; text-decoration: underline;'>時之神殿</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#時之神殿 地圖1'><span style='color: #000080; text-decoration: underline;'>時之神殿 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
5.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#時之神殿 地圖2'><span style='color: #000080; text-decoration: underline;'>時之神殿 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>5.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#時之神殿 地圖3'><span style='color: #000080; text-decoration: underline;'>時之神殿 地圖3</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#時之神殿 地圖4'><span style='color: #000080; text-decoration: underline;'>時之神殿 地圖4</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#時之神殿 地圖5'><span style='color: #000080; text-decoration: underline;'>時之神殿 地圖5</span>
</a></span></span> <span style='color: #ff0000;'>( 取得諾亞之琴 )</span><br /> (06) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#烏內之祠'><span style='color: #000080; text-decoration: underline;'>烏內之祠</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.1 &#8211; 烏內加入隊伍<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.2 &#8211; <span style='color: #ff0000;'>取得火之牙</span><br /> (07) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#古代遺跡'><span style='color: #000080; text-decoration: underline;'>古代遺跡
</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.1 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#古代遺跡 地圖1'><span style='color: #000080; text-decoration: underline;'>古代遺跡 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>7.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代遺跡 地圖2'>
<span style='color: #000080; text-decoration: underline;'>古代遺跡 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#古代遺跡 地圖3'><span style='color: #000080; text-decoration: underline;'>古代遺跡 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.4 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#古代遺跡 地圖4~7'><span style='color: #000080; text-decoration: underline;'>古代遺跡 地圖4~7</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>7.5 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代遺跡 地圖8'><span style='color: #000080; text-decoration: underline;'>古代遺跡 地圖8</span></a></span></span> <span style='color: #ff0000;'>( 取得飛空艇無敵號 )</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='多加莊園'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>多加莊園</span><br /> <span style='color: #ffffff;'>-</span><br /> 多加莊園位於南方的大陸上，先搭乘鸚鵡螺號前往南方的大陸的左下角</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 從山脈間的缺口飛進去 ( 飛行時也是會遇敵的 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 中途會有個叉路，走上面那一條</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭就會抵達多加莊園</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就會遇到兩隻莫古，多加也會馬上出現</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 多加說明了過去與烏內、贊德的事情後，便決定加入隊伍！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往前走，門口的莫古如果你有信還沒讀的話可以對話一下</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個房間兩側有商店，左邊是道具店，右邊是魔法店</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡有賣 LV 6 的黑白魔法，但是價格&#8230;..好想買啊！建議這些魔法還是盡量買齊比較保險，沒什麼錢的話就去賺&#8230;..或是賣裝備XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再往右邊走會有個小房間能召喚出胖陸行鳥，如果你需要的話</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下一個房間中，上方的罐子可以恢復 HP/MP，桌上的魔法書可以復活<br /> ( 其實莫古就會告訴你了XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著去調查右上角的蠟燭 ( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右邊會開啟通道，繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到一個房間，右上角有個小洞口，必須要<span style='color: #ff0000;'>全員「縮小」</span>後才能進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/01-dogas_manor-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='魔法陣洞窟'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>魔法陣洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來魔法陣洞窟後，就直接往右走 ( 暫時無法恢復狀態，遇敵時要小心 )<br /> ( 這時候風水師的「地形」就非常好用了XDDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/02-the_cave_of_the_circle-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後會經過三個傳送點切換通道，都持續往右走而已，沒什麼特別的</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/02-the_cave_of_the_circle-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後來到這個地點，往前走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/02-the_cave_of_the_circle-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著多加會施展魔法，將鸚鵡螺號增加了潛水的功能！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/02-the_cave_of_the_circle-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後多加會把我們直接傳送到外面，別忘了恢復狀態，並且儲存</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/02-the_cave_of_the_circle-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過剛剛多加的說明，我們現在應該要前往薩羅尼亞的南方，但是可以別急著去，我們可以先到同一塊大陸的東南方去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/02-the_cave_of_the_circle-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 飛到這裡會看到有個四面環山的小村落，看來是要從水下才能進入的</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在海面上點一下鸚鵡螺號，便會潛入海底，延著陸地往東北方走<br /> ( 海底的敵人也是挺強的，要小心一點 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著會發現一個叉路，往左前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了盡頭，再點一下鸚鵡螺號，就會浮上水面</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-004.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='多加村'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多加村</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 浮上水面後就能進入這個小村落：多加村</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 多加村裡面有賣幾乎所有的黑白魔法，連 LV 7 的都有，也有召喚魔法<br /> ( 外圍與中間圓形小島都各有一個黑魔法師在賣魔法 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> LV 7 的魔法價格當然是不便宜，而且現階段你也未必能使用XDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在這裡就看看是否有你需要的魔法，LV 7 的高級魔法購買與否就看你的財力了&#8230;.XD，現階段其實中、高級治療應該就很好用了，而且白魔的能力應該也還沒到能用 LV 7 魔法的時候。( 就算能用，次數也&#8230;.XD )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡也有一個莫古，剛好有西德的新信要讀 ( 標題：你們年幼的時候 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這邊也順便提醒一下，之前都忘了寫。找莫
古收信時，可以換一下隊列，把要收信的排在第一個，如果有該位角色的信就會出現。剛好現在可以休息一下，換一下人收信吧！<br /> <span style='color: #ffffff;'>-</span><br /> 以下也補充之前還沒寫到的信：<br /> <span style='color: #0000ff;'>因古斯</span> ( 莎拉公主 &#8211; 1 )：因古斯你可好？<br /> 
<span style='color: #0000ff;'>因古斯</span> ( 莎拉公主 &#8211; 2 )：每天都很無聊啊<br /> <span style='color: #0000ff;'>因古斯</span> ( 莎拉公主 &#8211; 3 )：最近的薩斯恩城<br /> <span style='color: #0000ff;'>蕾菲亞</span> ( 塔卡 &#8211; 1 )：蕾菲亞你還好嗎？<br /> 
<span style='color: #0000ff;'>蕾菲亞</span> ( 塔卡 &#8211; 2 )：卡茲斯回復平靜了<br /> <span style='color: #0000ff;'>蕾菲亞</span> ( 塔卡 &#8211; 3 )：歲月不饒人呀<br /> <span style='color: #0000ff;'>蕾菲亞</span> ( 塔卡 &#8211; 4 )：傳說的鐵匠<br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'> -</span><br /> 目前應該會有四個人寄來的信件：( 如果你是照我的攻略走的話 )<br /> 托帕帕 x4、塔卡 x4、莎拉公主 x3、西德 x3</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/03-dogas_village-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在多加村補充完需要的魔法後，就可以原路返回水面上的地圖。接下來我們還有一個地方值得先去探險：海底洞窟。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><a name='海底洞窟'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>海底洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 前往地圖的東南方，有一塊三角形的小島</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在小島的右側潛入海底</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來之後就會看到一個入口，直接控制鸚鵡螺號進入即可</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-003.png' width='486' height='326' /><br /> <a name='海底洞窟 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>海底洞窟 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 第一段路都是單線前進，直接走到下一個入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-004.png' width='486' height='326' /><br /> <a name='海底洞窟 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>海底洞窟 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 寶箱：<span style='color: #800000;'>猛虎爪、飛輪、雙印第安斧</span><br /> 叉路：右上 ( 寶箱 ) > 左上 ( 寶箱 ) > 左下 ( 寶箱 ) > 右下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-005.png' width='486' height='326' /><br /> <a name='海底洞窟 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>海底洞窟 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 第一個叉路先往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左邊先拿寶箱 ( <span style='color: #800000;'>古代劍</span> )，再往下繼續走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 過了橋還有 4 個寶箱：<span style='color: #800000;'>鑽石盾、金屬拳套、鑽石頭盔、知識之書</span><br /> ( 拿完就原路走回剛剛的叉路 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到這裡，繼續往左走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再經過 4 個寶箱：<span style='color: #800000;'>鑽石手鐲、洛基豎琴、鑽石甲、空氣匕首</span><br /> 拿完後繼續往下前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著又是 3 個寶箱：<span style='color: #800000;'>不死鳥之尾、聖靈藥、鑽石護手</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 沒了嗎？不！其實還有一個暗道在左邊，裡面還有最後 4 個寶箱。但是&#8230;..打開寶箱時會遇敵，而且敵人並不弱，建議先用傳送回入口處的海底，先儲存一下再重新進來，反正路並不難走，如果 MP 不太夠了，也建議可以找最近的村鎮去休息恢復。<br /> <span style='color: #ffffff;'>-</span><br /> 當然，如果你對目前的狀況很有信心，就直接前進吧！有怪物守著的寶箱肯定會是很不錯的物品的！<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在剛剛最後 4 個寶箱的中間，往左邊還有最後一個暗道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後的 4 個寶箱，以下分別說明寶箱內容與遇敵資訊，建議可以照以下的順序去開啟寶箱，這樣打起來會比較順手</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左上寶箱：<span style='color: #800000;'>三尖槍</span> ( 攻擊力 108 )<br /> 遇敵：<span style='color: #0000ff;'>佩利冬</span></p>";
echo "<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 備註：<br /> 我還來不及調查就被風水師的「漩渦」秒殺了…XDDD，正常這種飛在空中的應該
都會有風屬性的弱點，而且竟然可以被漩渦秒殺…真是讓我意外XD，如果你有龍騎士，打完就讓他裝備上三尖槍這把好物吧！<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左下寶箱：<span style='color: #800000;'>反射甲</span> ( 防御 30，防御部份異常狀態 )<br /> 遇敵：<span style='color: #0000ff;'>死亡之爪</span><br /> HP：<span style='color: #0000ff;'>3800</span>，弱點：無</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右下寶箱：
<span style='color: #800000;'>海王錘</span> ( 攻擊 110，附帶雷屬性效果 )<br /> 遇敵：<span style='color: #0000ff;'>吞食魔</span><br /> HP：<span style='color: #0000ff;'>2700</span>，弱點：<span style='color: #ff0000;'>暗黑劍</span><br /> 技能：增殖 ( 會自動增加一個 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右上寶箱：
<span style='color: #800000;'>聖盾</span> ( 防御 16，防御所有異常狀態 )<br /> 遇敵：<span style='color: #0000ff;'>殭屍龍</span><br /> HP：<span style='color: #0000ff;'>11000</span>，弱點：<span style='color: #ff0000;'>聖</span><br /> 技能：物理攻擊 x2 ( 傷害約 400~600，但<span style='color: #ff0000;'>暴擊可達 800~1000</span> 以上 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/04-the_sunken_cave-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 備註：<br /> 殭屍龍的物理攻擊很高，而且每回合攻擊兩次，一不小心就很容易有人被打趴。
除了一般的物理攻擊之外，龍騎士裝備剛剛的三尖槍，加上疾風槍共持雙槍，在跳躍攻擊時可達 4000 以上傷害。風水師的話就看運氣了，我是出了冰柱，傷害約 2200 左右。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這海底洞窟的寶箱真的很不錯吧XDDDD，一堆
攻擊力很高的武器，大大的增強了我們隊伍的實力，而且在這洞窟裡面的雜兵經驗值也不算低，我在這裡幾乎接近升了 2 級。<br /> <span style='color: #ffffff;'>-</span><br /> 接下來就可以先回到陸地上，前往下一個地點：薩羅尼亞地下迷宮</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='薩羅尼亞地下迷宮'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞地下迷宮</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到薩羅尼亞，要前往地下迷宮之前，可以先到鎮上恢復/補充/儲存一下</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 準備好之後就控制鸚鵡螺號，飛到薩羅尼亞東南方角落的海上，潛到海底</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 潛入海底後就會看到一個入口，直接進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-004.png' width='486' height='326' /><br /> <a name='薩羅尼亞地下迷宮 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞地下迷宮 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 第一段路單線往北前進，路上的敵人應該不需擔心，因為剛剛拿了一堆強力裝備，整個隊伍現在實力大增啊XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-005.png' width='486' height='326' /><br /> <a name='薩羅尼亞地下迷宮 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞地下迷宮 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 第二段路還是單線走到底，沒有任何叉路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-006.png' width='486' height='326' /><br /> <a name='薩羅尼亞地下迷宮 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞地下迷宮 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路1：右 ( 寶箱：<span style='color: #800000;'>巨像之杖、符文之鈴、聖盾</span> ) > 左 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路2：右 ( 寶箱：<span style='color: #800000;'>反射甲</span> ) > 左 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路3：右 ( 寶箱：<span style='color: #800000;'>重騎槍</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-009.png' width='486' height='326' /><br /> <a name='薩羅尼亞地下迷宮 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞地下迷宮 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 一進到這裡，右上角就有一個暗道可以往右前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到一個房間內有 8 個寶箱，上排是<span style='color: #800000;'>聖靈藥 x4</span>，下排是<span style='color: #800000;'>不死鳥之尾 x4</span><br /> 要注意的是打開分別都會遇敵，所以你要進行 8 次戰鬥才能拿完&#8230;.= =</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇敵 ( <span style='color: #800000;'>聖靈藥</span> )：<span style='color: #0000ff;'>銜尾蛇</span><br /> HP：<span style='color: #0000ff;'>2660</span>，弱點：<span style='color: #ff0000;'>雷</span><br /> 備註：攻擊會隨機附帶「石化」狀態</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇敵 ( <span style='color: #800000;'>不死鳥之尾</span> )：<span style='color: #0000ff;'>肯科斯</span><br /> HP：<span style='color: #0000ff;'>4000</span>，弱點：<span style='color: #ff0000;'>雷</span><br /> 備註：物理攻擊 x2</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到剛剛的房間後，繼續往上走就會遇到 BOSS：奧丁</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-014.png' width='486' height='326' /><br /> <a name='薩羅尼亞地下迷宮 地圖5'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ff0000;'>12/13 Update: ( 補充說明：奧丁身上有「神槍昆古尼爾」可以偷 )</span></p>
<p>1. 在進去打 BOSS 奧丁之前，有件事要提醒一下，就是在奧丁的身上有一把「神槍昆古尼爾」( 好槍一把，攻擊力 140 ) 可以被盜賊偷到，但是<span style='color: #0000ff;'>盜賊的熟練度需要 71 以上</span>，現階段如果沒有特地去提升熟練度的話，頂多大約在 30~40 左右而已，通常只能偷到「<span style='color: #800000;'>聖靈藥</span>」，所以為了偷神槍，建議把奧丁留到後期再回來一邊偷一邊打。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>2. 如果你不幸已經把奧丁打趴了，建議回到上一個儲存點，重新來過，把薩羅尼亞地下迷宮的寶箱都拿完後就傳送離開，到下一個地點「時之神殿」去，為了這把神槍重新打這一段是值得的啦XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>薩羅尼亞地下迷宮 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後就看到奧丁站在舞台 (?) 上，對話後進入戰鬥</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：
<span style='color: #0000ff;'>奧丁</span><br /> HP：<span style='color: #0000ff;'>32000</span><br /> 攻擊：物理攻擊 x2 ( 每次傷害約 400~600 )<br /> 技能：<span style='color: #ff0000;'>斬鐵劍 ( 全體攻擊，傷害約 1200~1400，有機會被全滅 )</span></p>
<p>偷盜：<span style='color: #800000;'>聖靈藥、神槍昆古尼爾</span> ( 低機率，盜賊熟練度需 71 以上，建議後期再來打 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：</p>
<p><span style='color: #800000;'>1. 奧丁身上有「神槍昆古尼爾」可以偷，建議後期再帶著熟練度 71 以上的盜賊回來偷</span></p>
<p>2. 奧丁的攻擊全是物理攻擊，包含知名技能「斬鐵劍」( 全體攻擊 )<br /> 3. 務必用「護盾」魔法或道具「龜甲殼」降低單體物理傷害<br /> 4. 白魔找機會對其他人放「護盾」，因為一次只能對單體，故要抓好機會<br /> 5. 其他人一開始先丟「龜甲殼」，接著便以物理攻擊 or 各項技能攻擊<br /> 6. 龍騎士裝備三尖槍
 + 重騎槍，以「跳躍」攻擊可有 4000~5000 傷害！<br /> 7. 中途的回復重要性大於進攻，多幫龍騎士爭取攻擊次數就能快速取勝<br /> 8. 不小心全滅了就&#8230;.放大絕吧XDDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗奧丁後，可以<span style='color: #ff0000;'>取得召喚魔法「災變」</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/05-saronia_catacombs-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來要前往的地點是時之神殿，那裡
有很多上了鎖的門，需要使用<span style='color: #ff0000;'>「魔法鑰匙」或是「盜賊」職業</span>才能開啟，如果你剛好有用盜賊就不用擔心，但若是沒有，那魔法鑰匙可能還是去多買一點比較方便，大概買個 10~15 把備用就夠了，不過&#8230;..我是覺得直接轉一個盜賊站第一位比較方便XDDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='時之神殿'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>時之神殿</span><br /> <span style='color: #ffffff;'>-</span><br /> 離開薩羅尼亞地下迷宮後，下一個地點也是在海底下，往西北大陸的南方前進，在一個由兩個半島圍起來的水域，就是時之神殿的所在地</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到圓形水域上方，控制鸚鵡螺號潛入海底</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後就會看到時之神殿 ( 在洞窟外面可以先儲存一下 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-003.png' width='486' height='326' /><br /> <a name='時之神殿 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>時之神殿 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 遇到的第一個叉路，先往左邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過第一個房間，要使用「魔法鑰匙」或「盜賊」職業來開啟</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 房間的盡頭是一個「<span style='color: #800000;'>鑽石頭盔</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到走道，繼續往左前進來到第二個房間 ( 中間叉路先不管 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭寶箱是「<span style='color: #800000;'>鑽石手鐲</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著往回走，從中間的叉路往下，到另一條並排的路上往左邊前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下了水路後，直接往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再走上階梯，往右邊繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-011.png' width='486' height='326' /><br /> <a name='時之神殿 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>時之神殿 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：右 ( 寶箱：<span style='color: #800000;'>守護者</span> ) > 下 ( 主線 )<br /> ( 守護者：攻擊 95，使用會引發護盾魔法，可以給騎士裝備上 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-012.png' width='486' height='326' /><br /> <a name='時之神殿 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>時之神殿 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 經過這裡先往右繼續走，有寶箱可以拿</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一樣是鎖住的房間，盡頭會有一個寶箱 ( <span style='color: #800000;'>鑽石甲</span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著回來走下台階後，先往左上方，走上台階</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 也是一道上鎖門，開啟後是兩個寶箱：<span style='color: #800000;'>巨獸匕首、鑽石護手</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到水路後往右繼續前進，一樣又是上鎖的門</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進入後都是單線，一路繼續往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-018.png' width='486' height='326' /><br /> <a name='時之神殿 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>時之神殿 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 來到一個大階梯處，先別往下，右邊的瀑布後方有暗道可以進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 暗道的盡頭是 3 個寶箱：<span style='color: #800000;'>嗜血槍、守護戒指、拉米亞豎琴</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著回到大階梯往下走，經過水路再到台階，先往左，再往右 ( 都有上鎖門 )<br /> 叉路：左 ( 寶箱：<span style='color: #800000;'>鑽石盾</span> ) > 右 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-021.png' width='486' height='326' /><br /> <a name='時之神殿 地圖5'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>時之神殿 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 來到最後一個房間，進來看到前方平台上放著一把琴</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往前調查後<span style='color: #ff0000;'>取得「諾亞之琴」</span>( 用來喚醒烏內的必要物品 )，寶箱物品都拿完之後，就可以傳送離開這裡，回到陸地上，我們該去叫醒烏內了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/06-temple_of_time-023.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='烏內之祠'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>烏內之祠</span><br /> <span style='color: #ffffff;'>-</span><br /> 烏內之祠位在時之神殿水域的正北方陸地上，是一個小洞窟</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 從時之神殿浮上水面後，往左邊延著海岸線北上</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 北上經過三條河流後，遇到的一個有森林的山脈間通道，往右飛進去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來就會到達烏內之祠</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後會看到烏內就沈睡在床上</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 「諾亞之琴」演奏起悠揚的音樂，把烏內從夢中世界喚醒了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 烏內醒來後，告訴我們需前往古代遺跡找巨型飛空艇，並加入了隊伍，離開前把「<span style='color: #ff0000;'>火之牙</span>」交給了我們</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/07-uneis_temple-007.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='古代遺跡'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代遺跡</span><br /> <span style='color: #ffffff;'>-</span><br /> 古代遺跡位於西北大陸的中間偏北的位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開烏內之祠後，繼續延著西海岸北上，看到有一塊都是森林的小島就往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 延著河道進來後，經過前面有一小塊沼澤地的洞窟，就是古代遺跡</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後會遇到 3 個考古學家 (?)，對話後得知下面的岩石擋住了去路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 調查後烏內便用了特殊能力催毀了岩石，得以繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-005.png' width='486' height='326' /><br /> <a name='古代遺跡 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代遺跡 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來之後第一個房間進去，盡頭是一個寶箱：<span style='color: #800000;'>反射甲</span>，拿完繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底是下一個入口，直接進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-007.png' width='486' height='326' /><br /> <a name='古代遺跡 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代遺跡 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 連來後右邊有個往下的叉路，先不要進去，我們先往上繼續走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 前面有三個房間都是商店，由左至右：旅館 + 道具店、武器店、防具店</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在旅館睡一覺，並整理好裝備後，就往回走剛剛的叉路下去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-010.png' width='486' height='326' /><br /> <a name='古代遺跡 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代遺跡 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路1：下 ( 寶箱：<span style='color: #800000;'>黑帶裝</span> ) > 右 ( 寶箱：<span style='color: #800000;'>脈輪頭帶</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路2：左 ( 寶箱：<span style='color: #800000;'>符文之鈴</span> ) > 右 ( 寶箱：<span style='color: #800000;'>妖精爪</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-012.png' width='486' height='326' /><br /> <a name='古代遺跡 地圖4~7'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代遺跡 地圖4~7</span><br /> <span style='color: #ffffff;'>-</span><br /> 接下來連續四個路段都是單線前進，沒有叉路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-013.png' width='486' height='326' /><br /> <a name='古代遺跡 地圖8'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代遺跡 地圖8</span><br /> <span style='color: #ffffff;'>-</span><br /> 走了好長的路終於來到這裡，從兩側往上走吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底便會進入一架巨大的飛空艇：<span style='color: #ff0000;'>無敵號</span>！( 烏內會先介紹用法 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著烏內告訴我們接下來的任務後，便離開了隊伍。終於取得了巨大的飛空艇無敵號，船上除了可以免費休息外，還有胖陸行鳥可以寄放道具，當然也有商店可以購買，其中有更強的武器，像是龍槍、符文之斧等等，真是太棒了XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> 桌上的物品由左至右是：魔法店、武器店、防具店、道具店</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 船上的莫古左邊可以收信，右邊可以查看遊戲的成就資訊與圖鑑等資料</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 先把信件收一收吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 如果你的進度跟我一樣的話，應該還有這些信件要收，記得換人讀信：<br /> 魯內斯：四位老爺爺 ( 好久不見啊、勇者的心得 )<br /> 阿爾克：阿魯斯 ( 阿爾克你好嗎？)<br /> 蕾菲亞：塔卡 ( 傳說的金屬奧利哈康 )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後就走到前面船舵位置，讓無敵號衝出水面出發！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到陸地後，先找個地方儲存一下吧！現在我們有了兩架飛空艇，原本的鸚鵡螺號目前還停在剛剛的古代遺跡入口處，有需要潛入海底再回去換即可</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-2/08-ancient_ruins-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 無敵號的取得代表著更多的任務即將到來，因為它可以翻過小山峰。現在可以先休息一下，到處繞繞提升一下職業的熟練度，或是玩玩不一樣的職業。如果你都準備好了，我們接下來就會進入攻略的 Part 3。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>FF3 Part 2-2 取得飛空艇無敵號 ( 完 )</div></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
