<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy 3 ( iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 3 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 1-3 德修的加入與離開</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<div><span style='color: #ffffff;'>-</span></div>
<div><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></div>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巨龍峰'><span style='color: #000080; text-decoration: underline;'>巨龍峰</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; 德修加入隊伍</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; 獲得「縮小」魔法<br /> (02) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#恢復之森'><span style='color: #000080; text-decoration: underline;'>恢復之森
</span></a></span></span><br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#托扎斯'><span style='color: #000080; text-decoration: underline;'>托扎斯 ( 小人村 )</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#托扎斯地道'><span style='color: #000080; text-decoration: underline;'>托扎斯地道</span></a></span></span><br /> 
(04) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#維京人據點 - 1'><span style='color: #000080; text-decoration: underline;'>維京人據點 &#8211; 1</span></a></span></span><br /> (05) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#涅普特神殿'><span style='color: #000080; text-decoration: underline;'>涅普特神殿</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; BOSS 戰：巨鼠<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; 取得水之牙<br /> (06) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#維京人據點 - 2'><span style='color: #000080; text-decoration: underline;'>維京人據點 
&#8211; 2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>6.1 &#8211; 取得企業號<br /> (07) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#托庫爾'>
<span style='color: #000080; text-decoration: underline;'>托庫爾</span></a></span></span><br /> (08) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#古代人之村'><span style='color: #000080; text-decoration: underline;'>古代人之村</span></a></span></span><br /> (09) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#陸行鳥之森'><span style='color: #000080; text-decoration: underline;'>陸行鳥之森</span></a></span></span><br /> (10) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#阿加斯城'>
<span style='color: #000080; text-decoration: underline;'>阿加斯城</span></a></span></span><br /> (11) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古爾岡山谷'><span style='color: #000080; text-decoration: underline;'>古爾岡山谷</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>11.1 &#8211; 獲得「蛙變」魔法<br /> (12) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#歐文塔'><span style='color: #000080; text-decoration: underline;'>歐文塔</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>12.1 &#8211; BOSS 戰：美杜莎</p>
<p>&nbsp;</p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p>&nbsp;</p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;</p>
<p><a name='巨龍峰'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>巨龍峰</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一開始進來都是單線前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：下 ( 寶箱：<span style='color: #800000;'>不死鳥之尾</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：右 ( 寶箱：<span style='color: #800000;'>疾風</span> ) > 左 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>金針</span> )，繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著傳說中的龍王巴哈姆特會突然出現</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 主角們被「吹」到一個&#8230;..鳥巢？( 還是龍巢XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 跟左上角的人對話，這傢伙就是德修</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著會進入戰鬥，對上巴哈姆特，當然是&#8230;..逃跑！<br /> ( 不要懷疑，就是逃跑&#8230;.跑太慢的話可能會被掛掉一個XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>然後德修會交給我們縮小魔法 ( 之後會用到 )，並加入了隊伍</span><br /> 然後帶著眾人 跳崖自殺 跳下巨龍峰</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/01-dragons_peak-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='恢復之森'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>恢復之森</span><br /> <span style='color: #ffffff;'>-</span><br /> 從巨龍峰跳下來之後，又回到了地圖上，左下角有個森林</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/02-restore_forest-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後有恢復泉 ( 但其實從巨龍峰下來後就已經補滿了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/02-restore_forest-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 裡面有一個小人，跟他對話還可以再拿到一個縮小魔法</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/02-restore_forest-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='托扎斯'></a><br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>托扎斯 ( 小人村 )</span><br /> <span style='color: #ffffff;'>-</span><br /> 在恢復之森的南方，有一片更大的森林，差不多走到這個位置，要先用縮小魔法變成小人，再往箭頭方向走就進去了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 魔法記得用「隊伍全員」，別一個一個變啊…XD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來之後草都比人高 ( 小人村嘛 )，往左邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 途中會遇到莫古，有托帕帕的信可以讀一下 ( 標題：最近的烏爾 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 村子裡的魔法可以買一下 ( 如果你有缺的話 )，另外就是如果你的 MP 不夠，就到旅館去睡一覺，不然等一下離開這裡沒有 MP 變回「大人」就&#8230;.傷腦筋XD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 跟村子裡的人對話搜集情報完了後，就到最北邊的房子去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 找臥病在床的謝爾科醫生，並給他「<span style='color: #ff0000;'>解毒藥</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 好人總是有好報的，又有寶物可以拿了XD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在謝爾科醫生的房子書櫃、桌子這邊三個寶物<br /> <span style='color: #800000;'>( 祕銀手鐲、烈火杖、烈炎 )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 謝爾科面前的罐子也有 ( <span style='color: #800000;'>中級治療</span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 剛剛右側有打開了通道，就馬上前進吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這邊又經過兩個寶箱 ( <span style='color: #800000;'>不死鳥之尾 x2</span> )，接著就是托扎斯地道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/03-tozus-012.png' width='486' height='326' /><br /> <a name='托扎斯地道'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>托扎斯地道</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/04-tozus_tunnel-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後是要往左邊走。這時候大家還是小人狀態，安全起見建議全員後排，物理攻擊當然很悲劇，但魔法還是很威的，當然你也可以暫時轉魔法職業。</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/04-tozus_tunnel-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後一路都是單線沒有叉路，過了兩段一樣的路就到出口了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/04-tozus_tunnel-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出來之後是在地圖的另一邊，想回去托扎斯的話，位置在森林的下方</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/04-tozus_tunnel-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='維京人據點 - 1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>維京人據點 &#8211; 1</span><br /> <span style='color: #ffffff;'>-</span><br /> 離開托扎斯後，西北方有個洞窟，是維京人據點 ( 別忘了變回大人XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一段小通道就會來到內部，可以去找每個人對話收集情報</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 就在入口處右側有個暗道，朝箭頭方向前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來會發現一個寶箱：<span style='color: #800000;'>火花短劍</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右側房間有旅館、道具及魔法店，需要的話可以買一下，然後走左邊繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇到一個叉路，先走左邊過去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到這裡也是一個暗道，往左下方前進 ( 箭頭方向 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走下來會有兩個寶箱：<span style='color: #800000;'>維京斧、3000 元</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右邊還有一個水池，但調查後什麼也沒發生 ( 因寫這個池是復活用的&#8230;完全復活那種XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-009.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後回到剛剛的長廊，往右邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在莫古左邊這個位置，還有一個暗道 ( 也太多了吧XD )，要摸黑往下方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再一路繞一個小圈，這裡有三個寶箱：<span style='color: #800000;'>震雷、烈炎、冰凍</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到主線繼續走會經過一個小砲台，調查會發射砲彈 = =，然後先往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ff0000;'>必要事件：</span>找維京人的老大對話 ( 截圖位置 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 他告訴我們如果願意幫他們的忙，就把企業號送我們用！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後就往北走離開這裡</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/05-vikings_cave-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='涅普特神殿'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>涅普特神殿</span><br /> <span style='color: #ffffff;'>-</span><br /> 從維京人據點出來到地圖上後，往北方走，前往「涅普特神殿」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭就是涅普特神殿</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就看到一個單眼龍的雕像</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 調查後決定要「<span style='color: #ff0000;'>縮小</span>」才能從雕像的口中進去一探究竟 ( 又要縮小了XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後單線往右邊走，如果遇敵的話，看是要魔法攻擊或是逃跑都可以<br /> ( 我大部份都是懶得打的，幾乎全程逃跑XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一路來到這裡，地上有兩個入口，先進去左邊有兩個寶箱：<span style='color: #800000;'>角貝鎧、角貝頭盔</span>，拿完之後就繼續走右邊的入口。( 兩個裝備我是給赤魔裝備上了…現在魔法職業比較重要XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>雷蛇劍</span> )，繼續往右就是最後一個入口了<br /> ( 這把劍&#8230;..以現在的小人狀態幾乎可以說無用武之地XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到盡頭看到了 BOSS，守著剛剛雕像缺少的眼睛：涅普特之眼</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>巨鼠</span><br /> HP：<span style='color: #0000ff;'>900</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 其實巨鼠的 HP 很低，但是因
為現在的小人狀態，物理攻擊完全無效，只能把希望放在魔法攻擊。我的隊伍只有一位赤魔&#8230;.XD，最後我是以三級的烈炎放一次，中途德修出來放了一次震雷 ( 運氣不錯XD )，後續加上四次的一級魔法「冰結」打敗他。<br /> <span style='color: #ffffff;'>-</span><br /> 其餘非魔法職業的，就每回合防禦或是幫魔法
師補血就好。巨鼠的攻擊就一般的物理攻擊、全體魔法 ( 每次傷害約 40 ~ 45 左右 )。<br /> <span style='color: #ffffff;'>-</span><br /> 如果中途快撐不住，就直接退出遊戲 ( 完全關閉 )，重開後選「Continue」繼續，會從剛剛看見 BOSS 的位置重來一次，多試幾次看看。( 這算大絕嗎XDDDDD )<br /> 
<span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗巨鼠後可取得「涅普特之眼」( HP/MP 會自動補滿，真好XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後&#8230;..往回走？沒錯，就是原路再走回去海龍雕像的入口處 ( 好遠&#8230;. )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到入口後，就把涅普特之眼放入原本空的位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 海龍為了報答我們，將「<span style='color: #ff0000;'>水之牙</span>」交給了我們</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開後，就原路回去維京人據點，找剛剛的老大對話</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/06-nepto_temple-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='維京人據點 - 2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>維京人據點 &#8211; 2</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到這裡找維京人老大對話</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/07-vikings_cave_2-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 老大很守信用，總算讓我們取得了「企業號」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/07-vikings_cave_2-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走出來地圖上，直接往左側海邊的企業號走過去，就可以直接上船了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/07-vikings_cave_2-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 先往上方延著水道出去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/07-vikings_cave_2-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在航行的時候也是會遇敵的，而且敵人還不弱</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/07-vikings_cave_2-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 出了水道後就往左下方前進，可以到一個小村落：托庫爾</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/07-vikings_cave_2-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='托庫爾'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>托庫爾</span><br /> <span style='color: #ffffff;'>-</span><br /> 在涅普特神殿西南方不遠處，靠岸後會來到托庫爾村</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡的人有點怪怪的，一講話就跑掉</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在第一間藍色房子內有個婦人說他的丈夫被抓了<br /> ( 和這婦人對話完後，村裡的人就會正常跟你講話了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 有人會告訴你西邊的古代人村落可以去看看</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左邊的廢棄房子旁邊可以找到「<span style='color: #800000;'>強弓</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/18 Update: ( 補上取得「酒神之酒、寒冰杖、拉米亞之鱗」)</span></p>
<p>另外在莫古左邊房子的左側，有個木桶上會發現「<span style='color: #800000;'>酒神之酒</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/06-tokkul_new_item-002.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>";
echo "<p><span style='color: #ffffff;'>-</span></p>
<p>接著到村內右邊靠中間的草地上，可以發現一把「<span style='color: #800000;'>寒冰杖</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/06-tokkul_new_item-003.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>然後在北邊村長家 ( 藍色屋頂的 ) 左側，有一顆樹下面會發現一個「<span style='color: #800000;'>拉米亞之鱗</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/06-tokkul_new_item-001.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 都拿完之後就進去村長家中</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右邊隔間的人會告訴你壁爐那裡有隱藏的樓梯 ( 其實好像不算是隱藏的XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 就從壁爐的入口進去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 兩個寶箱：<span style='color: #800000;'>雷蛇劍、功夫裝</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左邊的罈子裡 ( 拉近看 ) 還有一個「<span style='color: #800000;'>音速拳套</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 寶物都拿完後就可以離開這裡，往地圖的西南方位置：古代人之村</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/08-tokkul-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='古代人之村'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古代人之村</span><br /> <span style='color: #ffffff;'>-</span><br /> 古代人之村在地圖上的西南方 ( 越過沙漠 )，離托庫爾有點遠，路上要小心</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/09-ancients-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/18 Update: ( 補上取得「雷蛇劍」)</span></p>
<p>這邊可以先繞到旅館的右後方，然後往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/07-ancients_village_new_item-002.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>在後面的小白花上可以發現一把「<span style='color: #800000;'>雷蛇劍</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/07-ancients_village_new_item-003.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 這裡的魔法店有賣「傳送」魔法 ( $1500 )，還蠻必要的，建議一定要買</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/09-ancients-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器和防具&#8230;.有點貴，看自己的需求吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/09-ancients-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡有個小鬼說如果騎著陸行鳥繞大陸周圍一圈的話，會有好東西<br /> ( 等一下我們就去繞一下XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/09-ancients-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> 這裡沒有什麼特別之處，主要就是購買你需要的道具、武器、防具或魔法，可以休息一下，調整裝備，或在附近練練級、提升熟練度。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='陸行鳥之森'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>陸行鳥之森</span><br /> <span style='color: #ffffff;'>-</span><br /> 在古代人之村的右側，有一小塊森林是陸行鳥之森</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/10-chocobo_forest-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 抓一隻陸行鳥，我們去環繞世界地圖一周吧XD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/10-chocobo_forest-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就沿著東南方的邊界，開始順時針方向繞一整圈</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/10-chocobo_forest-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後直接走回到古代人之村</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/10-chocobo_forest-004.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>找剛剛的小鬼，結果得到&#8230;.<span style='color: #800000;'>小人麵包</span>XDDDD ( 還以為是什麼好東西咧XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/10-chocobo_forest-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再坐一次陸行鳥回到你停放企業號的位置，要坐船出發</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/10-chocobo_forest-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='阿加斯城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>阿加斯城</span><br /> <span style='color: #ffffff;'>-</span><br /> 阿加斯城在托庫爾的北方，海洋中間一個半島的位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 看起來黑黑的一座城堡&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p>阿加斯城內沒有半個人影，這裡主要就是拿一大堆寶箱，真的是一大堆XDDDDD，雖然有一部份寶箱只是裝著錢，但在連不死鳥之尾都買不到的狀況下，就算只能多拿一點錢放著也是好事，而且可拿到一堆寶箱有種說不出來的快感對吧XDDDDDD</p>
<p><span style='color: #ffffff;'>-</span><br /> 一路往前走到第二個房間 ( 牆上有四座蠟燭的 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 調查最右邊的蠟燭 ( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右邊牆壁會開啟一個暗道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到這裡先往右邊「穿牆而過」，可以拿到三個寶箱：<span style='color: #800000;'>1000 元 x3</span><br /> 拿完之後再回來繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著又是六個寶箱 ( 一樣都是錢XD )，共有：<span style='color: #800000;'>1500 元 x1、1000元 x3、100 元 x2</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續走會來到外部，先往左邊走好了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左邊走到底有個小門，調查會發現門鎖住了，跳出道具選項卻不知道要選什麼XD，正確的方式是<span style='color: #ff0000;'>將「盜賊」調整為隊伍第一個人，調查時就可以直接開門了</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後調查右前方的櫃子 ( 拉近看 )，可以開啟右側通道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡有三個寶箱：<span style='color: #800000;'>閃光箭 (x20)、殺手弓、美杜莎之箭 (x20)</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開小房間後繼續往右走，到另一邊也有一個小房間</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡還有六個寶箱 ( FF3 給寶箱還真大方XDDDD )<br /> 寶箱：<span style='color: #800000;'>烈火箭 (x20)、閃光之書、寒冰之書、烈火之書、學者服、寒冰箭 (x20)</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 原路回到剛剛四座蠟燭的房間，繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會來到一個大廳，在圓桌的右邊這裡是可以往下進入的 ( 如圖 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後會先經過兩個寶箱：<span style='color: #800000;'>爆彈碎片、南極之風</span>，然後右邊還有暗道，繼續走！<br /> ( 這裡的寶箱會不會太多XDDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後是最後一個寶箱：<span style='color: #800000;'>北極之風</span> ( 應該是最後一個了吧？)，這是後續打 BOSS 很有用的道具！<br /> ( 如果還有我沒發現的，請告訴我一下XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/11-castle_argus-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回來後如果從圓桌下方走出來，會發現外部的右邊水池可以恢復 HP/MP。寶箱終於都拿完了之後 ( 拿得好爽XD )，這裡就沒有其他特別的地方了。接下來可以離開阿加斯城，往西邊的下一個地點前進：古爾岡山谷。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='古爾岡山谷'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>古爾岡山谷</span><br /> <span style='color: #ffffff;'>-</span><br /> 離開阿加斯城後，一路往西邊前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/12-gulgan_gulch-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 延著湖泊的上緣向西走到底就會到達古爾岡山谷</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/12-gulgan_gulch-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡的人都是失明的，可以找他們對話收集情報，然後進入地下室</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/12-gulgan_gulch-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到地下室後找中間的人對話，<span style='color: #ff0000;'>會交給你「蛙變」魔法</span>，後續在歐文塔會用到</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/12-gulgan_gulch-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著從下方的通道繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/12-gulgan_gulch-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 又是一個暗道，要摸黑照順時針方向繞一小圈到另一個小房間<br /> 這裡有三個寶箱：<span style='color: #800000;'>魔導師服、寒冰杖、烈火杖</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/12-gulgan_gulch-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就可以離開這裡，坐企業號或是走路，往北方的歐文塔前進。</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='歐文塔'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>歐文塔</span><br /> <span style='color: #ffffff;'>-</span></p>
<p>這裡的敵人算有稍強一些，重點是裡面依然沒有儲存點的設定，包含最後面的 BOSS 戰前都不會有，而且我們的<span style='color: #ff0000;'>不死鳥之尾數量相當少</span>，一定要小心謹慎一點，補血的時機要抓好，恢復藥也不能太浪費，免得辛辛苦苦走到 BOSS 戰結果因為補血能力不足而被打趴，就得重走一次。如果不放心的話，建議進去之前可以在周圍再提升一下角色的等級與熟練度。</p>
<p><span style='color: #ffffff;'>-</span><br /> 歐文塔的位置在阿加斯城的東北方向，如下面截圖</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 可以直接走路過來，也可以坐企業號走水路北上</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後先往左邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了第一個叉路右轉</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第二個叉路再右轉，然後<span style='color: #ff0000;'>需用「蛙變」魔法將全員變青蛙</span>才能前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 變成青蛙後繼續往前走就會到下一個位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了下一個地點後，<span style='color: #ff0000;'>馬上再用一次「蛙變」將全員恢復正常狀態</span></p>
<p>( 或是用少女之吻 x4 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個區域都是單線前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往下過了橋有個寶箱 ( <span style='color: #800000;'>山彥草</span> )，繼續往左邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 後續一樣都是單線，但要留意一下叉路，這裡還會經過一個寶箱：<span style='color: #800000;'>火花短劍</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到這個叉路，上方有隱藏開關 ( 拉近看 )，打開後往下走</p>";
echo "<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：左 ( 寶箱：<span style='color: #800000;'>山彥草</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：右 ( 寶箱 ：<span style='color: #800000;'>爆彈碎片、山彥草</span> ) > 左 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：右 ( <span style='color: #800000;'>音速拳套</span> ) > 左 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上來這裡後直接走左邊</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：右 ( 寶箱：<span style='color: #800000;'>火蠑劍</span> ) > 左上 ( 寶箱：<span style='color: #800000;'>烈焰甲</span> ) > 左下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再經過一個寶箱 ( <span style='color: #800000;'>宙斯之怒</span> )，繼續往上就是 BOSS 了！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 邪惡的 BOSS 就在前方</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>美杜莎</span><br /> HP：<span style='color: #0000ff;'>3300</span>，弱點：<span style='color: #ff0000;'>冰</span><br /> 攻擊：物理攻擊約 100~150、烈炎 ( 單體約 100 / 全體約 70~80 )<br /> 偷盜：高級恢復藥</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 美杜莎的攻擊以物理攻擊
與烈炎魔法為主，還蠻痛的&#8230;.<br /> 2. 以我的組合來打的話有點辛苦XDDDD<br /> 3. 一般的物理攻擊大約只能傷個 150~200 傷害<br /> 4. 戰士用「突擊」，傷害雖然不算太高，但至少算裡面較高的了XD<br /> 5. BOSS 弱點是冰，有機會就丟「北極之風」、「南極之風」、「宙斯之怒」，傷害會很可觀<br /> 6. 只要 
HP 低於 150 就一定要趕快回復，回復藥或是魔法均可，不要省<br /> 7. 大概需要撐個五六回合，加油吧XDDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗美杜莎後，德修要我們前往矮人島 ( 矮人洞窟 )，並犧牲自己跳入火坑&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 之後眾人出現在企業號上，海上原本擋路的漩渦消失，可以離開這個海域繼續冒險了！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_1-3/13-tower_of_owen-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>FF3 Part 1-3 德修的加入與離開 ( 完 )</div></font></center>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
