<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='font-size: 22px; color: #800000;'>Final Fantasy 3 ( iOS )</span></p>
<p><span style='font-size: 22px; color: #800000;'>Walkthrough, Graphic Guide</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>最終幻想 3 ( iOS ) 圖文攻略</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>Part 3-3 水晶塔最終決戰</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔'><span style='color: #000080; text-decoration: underline;'>水晶塔</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖1'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 
&#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖2'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
1.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖3'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>1.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖4'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖4</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;
&#8211;</span>1.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖5'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖5</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;
&#8212;&#8211;</span>1.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖6'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖6</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>1.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖7'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖7</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
1.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水晶塔 地圖8'><span style='color: #000080; text-decoration: underline;'>水晶塔 地圖8</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：魔王贊德</p>
<p>(02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗之世界'><span style='color: #000080; text-decoration: underline;'>暗之世界</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>2.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗之世界 左下'><span style='color: #000080; text-decoration: underline;'>暗之世界 左下</span></a></span></span> ( 水之水晶 )</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：艾奇德娜<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#暗之世界 右下'><span style='color: #000080; text-decoration: underline;'>暗之世界 右下</span></a></span></span> ( 土之水晶 )</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：阿里曼<br /> <span style='color: #ffffff;'>&#8212;&#8212;
&#8211;</span>2.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗之世界 右上'><span style='color: #000080; text-decoration: underline;'>暗之世界 右上</span></a></span></span> ( 火之水晶 )</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：雙頭巨龍<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#暗之世界 左上'><span style='color: #000080; text-decoration: underline;'>暗之世界 左上</span></a></span></span> ( 風之水晶 )</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：刻耳柏洛斯</p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗之世界 中央'><span style='color: #000080; text-decoration: underline;'>暗之世界 中央</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>最終戰：暗黑之雲 + 觸手 x2</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#後記'><span style='color: #000080; text-decoration: underline;'>後記</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='水晶塔'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>水晶塔</span><br /> <span style='color: #ffffff;'>-</span><br /> 忙完了先前的支線事件後，我們又來到了水晶塔。對於要進入水晶塔必須要先通過長長的古代人迷宮這一點是否有點感到厭煩了呢XDDDDDD ( 對了，進來前記得還是要在無敵號補充一下恢復道具，以防萬一 )<br /> 
<span style='color: #ffffff;'>-</span><br /> 通過了古代人迷宮後，要進去水晶塔前，千萬要記得存檔，因為水晶塔裡面一樣是沒有儲存點的 ( 其實整個 FF3 就只有大地圖可以儲存XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 水晶塔裡面的敵人個個身懷絕技，如果你沒有
一定的等級或是熟練度的話，打起來會異常辛苦，建議進來之前還是練練等級會比較安心。即使我自己是在寫攻略，也是升到 60 級左右才進來打，大家自己斟酌一下吧！<br /> <span style='color: #ffffff;'>-</span><br /> 最後要進入水晶塔前的隊伍狀態，我選了<span style='color: #800000;'>空手道家、戰士、風水師、賢者</span>的組合，除了賢者熟練度 60 之外，其餘三人皆為 99，主角的等級平均 62。</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 這邊稍微說明一下這樣選的原因，空手道家與
賢者應該是很多人會選的職業，空手道家物理攻擊強悍且防御力高 ( 體力 )，賢者則是能同時使用最高級的黑白魔法。而選擇戰士不選騎士的原因很簡單，戰士的力
量、速度都比騎士高，而且能同時裝備「<span style='color: #800000;'>究極神兵</span>」與「<span style='color: #800000;'>巨人之斧</span>」這兩把攻擊力都是 155 的強力武器！( 巨人之斧是戰士取得頂級之證後獲得的 )<br /> <span style='color: #ffffff;'>-</span><br /> 至於風水師&#8230;..純粹個人喜好XDDD
DDDD，其實風水師雖然「地形」的攻擊方式為隨機，但是傷害都不低，而且最重要的是，不用管 MP 的消耗！所以個人喜好及不用消耗 MP 是我最後選擇風水師的原因。<br /> <span style='color: #ffffff;'>-</span><br /> 這樣的組合與等級進去水晶塔基本上已無往不利了，絕大部份的雜兵應該都沒有機會出手，一回合內就能
全部解決掉，可能只有最後的幾個 BOSS 要花點時間而已。準備好了之後，我們就出發吧！<br /> <a name='水晶塔 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>水晶塔 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 一開始上來大大的階梯後，我們先往右邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：上 ( 寶箱：<span style='color: #800000;'>莉莉絲之吻</span> ) > 右下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 下樓梯前的叉路：上 ( 寶箱：<span style='color: #800000;'>精靈之弓</span> ) > 右下 ( 寶箱：<span style='color: #800000;'>陸行鳥之怒</span> ) > 下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 下來這個房間後，左下及右上各有一個寶箱：<span style='color: #800000;'>白之香、陸行鳥之怒</span>，拿完之後就可原路返回一開始的那座大階梯處</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 返回大階梯後就往左邊走，叉路：上 ( 寶箱：<span style='color: #800000;'>陸行鳥之怒</span> ) > 左下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 來到一個樓梯處，拿完左邊寶箱 ( <span style='color: #800000;'>白之香</span> ) 後，先下樓梯</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後走右下拿寶箱 ( <span style='color: #800000;'>風魔之衣</span> )，拿完就直接往回走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走回來後就一路往上走進入下一段路 ( 這個入口你之前應該開過了，是用希爾科斯之鍵打開的，如果還沒開的話，調查一下牆壁就會開了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-010.png' width='486' height='326' /><br /> <a name='水晶塔 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：上 ( 寶箱：<span style='color: #800000;'>聖靈藥</span> ) > 右 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 單線前進，途中經過一個寶箱 ( <span style='color: #800000;'>不死鳥之尾</span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：左上 ( 寶箱：<span style='color: #800000;'>聖靈藥</span> ) > 右下 ( 主線 )<br /> ( 左邊是一個環形區域，除了剛剛那一個寶箱外就沒什麼了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後單線走到底就會進到下一個區域</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-014.png' width='486' height='326' /><br /> <a name='水晶塔 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 一上來之後，左邊可以完全忽略它，直接往右繞進一條狹小的走道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繞過來後，先往上走拿寶箱 (<span style='color: #800000;'> 聖靈藥</span> )，然後注意看右邊，是有一個通道可以過去去的，也太不明顯了吧XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後入口前有一個寶箱 ( <span style='color: #800000;'>不死鳥之尾</span> )，繼續往左前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後發現是個黑黑的暗道，碰壁後<span style='color: #ff0000;'>往下 > 往左 > 往上 > 往左</span>，就能前往另一個區域 ( 各方向長度都不長，總之感覺沒在前進就可以換個方向了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 過來之後先取得一個寶箱 ( <span style='color: #800000;'>手裡劍</span> )，然後直接往上走樓梯</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上來後又是很眼熟的場景，繼續往左下樓梯</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-020.png' width='486' height='326' /><br /> <a name='水晶塔 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 經過一條長長的通道後，再經過兩個寶箱 ( <span style='color: #800000;'>不死鳥之尾、聖靈藥</span> )，繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著又是一個環形走道，直接往右繞下半圈過去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 圓環右側的角落有一個寶箱 ( <span style='color: #800000;'>聖靈藥</span> )，拿完後就直接往圓環的上方入口去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-023.png' width='486' height='326' /><br /> <a name='水晶塔 地圖5'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 一上來就直接往上面入口進去，兩邊是圓環沒有任何東西</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-024.png' width='486' height='326' /><br /> <a name='水晶塔 地圖6'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖6</span><br /> <span style='color: #ffffff;'>-</span><br /> 第 6 段路上來直接往右邊走 ( 左邊是死路 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走下來一小段後，注意右側會有個入口，直接進去後往下方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後又是好長好長、上下繞來繞去的蛇行走道，好煩XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繞過來後直接往左繼續走，上面沒路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 看到這一個往上的叉路後，就直接往上走，會進到下一段路<br /> <span style='color: #ff0000;'>( 不用往左了，還是騙人的死路XDDDD )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-029.png' width='486' height='326' /><br /> <a name='水晶塔 地圖7'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖7</span><br /> <span style='color: #ffffff;'>-</span><br /> 上來這裡後，左右兩側的盡頭各有一個寶箱，拿完後回來繼續往上前進<br /> ( 左：<span style='color: #800000;'>不死鳥之尾</span>，右：<span style='color: #800000;'>水晶甲</span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上來後再繼續往上前進，左右一樣都沒有東西</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-031.png' width='486' height='326' /><br /> <a name='水晶塔 地圖8'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水晶塔 地圖8</span><br /> <span style='color: #ffffff;'>-</span><br /> 接下來這個區域，左右各能取得兩個寶箱，拿完就直接往大樓梯上去<br /> 左 ( <span style='color: #800000;'>水晶護手、水晶盾</span> ) > 右 ( <span style='color: #800000;'>水晶盔、不死鳥之尾</span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 但是在這附近要小心一點，有機會遇到「<span style='color: #ff0000;'>紅龍</span>」，要做好全滅的準備XDDDD，不小心全滅的話千萬別點螢幕，直接按 Home 鍵離開遊戲，重開遊戲選 CONTINUE 繼續吧&#8230;&#8230;只好放大絕了XDDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一上來最後的房間，在一塊大鏡子前，突然無法動彈！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 此時傳出了多加的聲音，並到了各地把大家的好伙伴：莎拉公主、西德、德修、阿魯斯、老爺爺都帶來了，為的是能抑制魔龍的力量，讓我們繼續前進！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 可以行動之後，現在可以確認一下主角們的狀態，直接往前走吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭遇到了魔王贊德，準備應戰</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>魔王</span><span style='color: #0000ff;'>贊德</span><br /> HP：<span style='color: #0000ff;'>49999</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 500~900 )、<span style='color: #ff0000;'>隕石 ( 全體傷害 1200~1500 )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-038.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 贊德的物理攻擊不太需要擔心，基本上你等級熟練度夠了就像騷癢&#8230;.<br /> 2. 隕石攻擊要小心一些，注意回復<br /> 3. 用你最強的技能去盡量 K 吧！大約三回合就把他處理掉XDDDDD<br /> 4. 這傢伙只是個小魔頭而已，不足為懼<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打倒贊德後，暗黑之雲現身，迎來了可怕的戰鬥！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>暗黑之雲、觸手 x2</span><br /> 攻擊：<span style='color: #0000ff;'>閃電、臭氣、波動砲</span><br /> <span style='color: #ff0000;'>這一戰隨便攻擊就好，一回合後 BOSS 就會放「波動砲」，接著就會全滅XDDDD</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-040.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著便是眾人的呼喚，而多加與烏內便注入了他們的靈魂到主角身上<br /> ( 好像每一代都會有的梗，第一次都會被打趴然後 NPC 陸續出現這樣XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-041.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 帶著伙伴們的勇氣與希望，我們終於還是站了起來，繼續前進吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-042.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 可以行動之後，再往前走就會進入暗之世界 ( 其實也可以先往下走看看XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-043.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進去之前如果下樓梯，還可以跟大家聊個天XDDDDDD</p>
<p>( 阿爾克表示：好累喔，我們回家了，隨便他們想怎樣吧&#8230;..XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/01-crystal_tower-044.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='暗之世界'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗之世界</span><br /> <span style='color: #ffffff;'>-</span><br /> 來到暗之世界後，第一個場景中間有個傳送點，<span style='color: #ff0000;'>但是請不要傻傻的現在就走過去，不然會再一次被暗黑之雲的「波動砲」全滅&#8230;..</span>我們還需要其他的力量協助！周圍有四條路，先走左下角吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-001.png' width='486' height='326' /><br /> <a name='暗之世界 左下'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗之世界 左下</span> ( 水之水晶 )<br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 暗之世界的路有的清楚，有的覆蓋了黑霧，但是還是能辨識方向，不過基本上只有左下是比較複雜一點的，另外三條路都很簡單。<br /> <span style='color: #ffffff;'>-</span><br /> 第一個叉路先直接往左邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 中間經過的叉路都先不要管，往左到底後單線繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在黑霧中如果卡住了，就稍微往兩側移動一下就能繼續前進了<br /> <span style='color: #ff0000;'>( 後續有遇到同樣的路都是這樣走即可 )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 單線走到底會有一個寶箱：<span style='color: #800000;'>緞帶</span>，打開後會遇敵</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇敵：<span style='color: #0000ff;'>贊德克隆體</span><br /> HP：<span style='color: #0000ff;'>39000</span><br /> 攻略：這只是贊德的化身而已，簡單處理掉，後面還要打三次XDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打完就往回走，繞過轉角後的第一個叉路往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底是另一個傳送點，直接進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往前走便會看見第一顆水晶 ( 水之水晶 )，接著便會進入 BOSS 戰</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>艾奇德娜</span><br /> HP：<span style='color: #0000ff;'>99999</span><br /> 攻擊：<span style='color: #ff0000;'>龍捲風 ( 單體瀕死 )</span><br /> <span style='color: #0000ff;'>攻略：接下來的三個 BOSS 也一樣不多做說明了，全力 K 就可以了XDDDD</span><br /> 備註：打完 BOSS 後都會全員恢復 HP/MP</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後會出現第一位暗之戰士 ( 好耳熟XD )，將協助我們對抗暗黑之雲</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開水晶後就可以往回走，下一個叉路往下就能回到暗之世界的入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-013.png' width='486' height='326' /><br /> <a name='暗之世界 右下'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗之世界 右下</span> ( 土之水晶 )<br /> <span style='color: #ffffff;'>-</span><br /> 接著我們往右下前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一出來就會看見寶箱 ( <span style='color: #800000;'>緞帶</span> )，打開一樣會遇敵：贊德克隆體，打完之後往左或往右都可以，盡頭會是同一條路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到盡頭就會看到傳送點</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇到第二顆水晶 ( 土之水晶 )，繼續開戰</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>阿里曼</span><br /> HP：<span style='color: #0000ff;'>99999</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後出現第二位暗之戰士，接著就可以往回走，繼續回到暗之世界入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-019.png' width='486' height='326' /><br /> <a name='暗之世界 右上'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗之世界 右上</span> ( 火之水晶 )<br /> <span style='color: #ffffff;'>-</span><br /> 接著我們往右上方繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡全都是單線，路上一樣會經過一個寶箱 ( <span style='color: #800000;'>緞帶</span> )，要打第三個贊德克隆體</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 直接走到底就是傳送點了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第三個水晶，好紅的火之水晶&#8230;.第三戰！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>雙頭巨龍</span><br /> HP：<span style='color: #0000ff;'>99999</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後第三位暗之戰士出現，然後就原路回去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-025.png' width='486' height='326' /><br /> <a name='暗之世界 左上'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗之世界 左上</span> ( 風之水晶 )</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡也是有部份的路上有黑霧，不過一開始也是單線前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 唯一的一個叉路，往左下是寶箱 ( <span style='color: #800000;'>緞帶</span> )，往右上就是前往最後一個水晶<br /> <span style='color: #ff0000;'>( 現在應該所有人都能裝備緞帶了，建議都裝上吧 )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後一個水晶 ( 風之水晶 )，迎來第四戰</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>刻耳柏洛斯</span><br /> HP：<span style='color: #0000ff;'>99999</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後一位暗之戰士加入協助</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-031.png' width='486' height='326' /><br /> <a name='暗之世界 中央'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗之世界 中央</span><br /> <span style='color: #ffffff;'>-</span><br /> 四個角落的水晶都打完後，整裝一下，我們就可以進去中間最後一個地點了<br /> <span style='color: #ff0000;'>進去前再確認一下，別忘了所有人都要裝備上緞帶！</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡的路很簡單，一開始往前走，方塊上都會自動出現光束，照著光束走即可，沒看見光束就往四個角落站一下就會出現了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭來到了最後一個傳送點</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 直接往上走吧，我們終於來到了最終戰！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 死到臨頭還是那麼囂張啊&#8230;.XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 開戰前，四位暗之戰士勇猛地衝向前去，消除了暗黑之雲的暗之力！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最終戰：<span style='color: #0000ff;'>暗黑之雲、觸手 2</span><br /> HP：<span style='color: #0000ff;'>120000</span> ( 暗黑之雲 )<br /> 攻擊：閃電、臭氣、<span style='color: #ff0000;'>波動砲</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-038.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 有了暗之戰士的協助後，暗黑之雲的攻擊減弱了許多！<br /> 2. <span style='color: #ff0000;'>兩隻觸手先主攻左邊，打爆後再視情況用「魔法」攻擊右邊 ( 物理攻擊無效 )</span>
<br /> 3. 如果你也是用風水師，反正就每回合用「地形」攻擊即可<br /> 4. 賢者每回合「終極治療」，MP 沒了就吃聖靈藥<br /> 5. 觸手的「臭氣」會附加各種異常狀態，但我們都有裝備緞帶所以可無視<br /> 6. 暗黑之雲只有「波動砲」會造成全體較大傷害，注意回復<br /> 7. 戰士與空手道家就盡全力打爆他們吧！<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來便進入了歡喜大結局了，眾人回到了自己的故鄉</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> FF3 的大木頭角色，因古斯當之無愧XDDDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-040.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後跑字幕時會介紹所有的主要人物與全部職業造型</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-041.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 連日來的冒險，世界終於恢復了和平&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-042.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 熟悉的 FF 系列經典水晶，感動萬分</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-043.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後的通關存檔時，右下角會多了三顆星星，代表已通關，狀態道具都會保留</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-044.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 讀取通關存檔後的位置會在古代人迷宮外面</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-045.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 檢查了一下寶箱開啟率，<span style='color: #ff0000;'>竟然是 99%！</span>我無言了，到底還有哪裡沒拿到XDDDDD</p>
<p>( <span style='color: #ff0000;'>1/4 Update: </span>感謝網友 <span style='color: #0000ff;'>NoverseYu</span> 提醒 )</p>
<p>( 原因找到了，是在 <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3_part_2_1.php#薩羅尼亞 西南' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>薩羅尼亞 西南</span></a></span></span> 的阿魯斯王子加入後要先取得「<span style='color: #800000;'>龍甲</span>」，原文章已更新 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-046.png' width='486' height='326' /><br /> <a name='後記'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #0000ff;'>後記：</span><br /> 到此 FF3 的主線劇情攻略已經全部結束了，剩下最後一個隱藏迷宮，那裡有強大的 隱藏 BOSS：鐵巨人，也有各種顏色的龍會掉落洋蔥裝備，不過因為篇幅的關係，要另外開一篇來寫了，而且以現階段的等級來看，不要說是鐵巨人了，我看會連打龍都會有點辛苦，大家可能要再練一下XDDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>下一篇會簡單介紹鐵巨人與各種龍的攻略心得，不過預計應該不會太詳細，因為打洋蔥裝備的過程實在是&#8230;..很煎熬啊！</p>
<p>( <span style='color: #ff0000;'>1/19 Update:</span> 專題已完成，請參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3_iron_giant.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF3 洋蔥裝備收集與鐵巨人</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-047.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 感謝一路有跟著我的 FF3 攻略打到現在的大家，下一部 FF 攻略會是 FF4，屆時也會盡量收集完整的資料來進行攻略的撰寫，希望大家都能玩得開心！至於這次的寶箱收集率 99%，剩下的最後 1% 就要靠大家自行努力在我的攻略中找找看，到底還有哪個地方沒有拿齊呢？有發現的話記得跟我說一下，謝謝XDDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這次的 FF3 攻略只花了兩個多禮拜便寫完，比起 FFD 用了一整個月真是差很多啊！不知道接下來的 FF4 要花多久時間，FF4 可是出了名的變態難度，大家一起期待 12/20 晚上 FF4 在 iOS 平台的上架吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-3/02-the_forbidden_land-048.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>FF3 Part 3-3 水晶塔最終決戰 ( 完 )</div></font></center>
";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
