<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy 3 ( iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 3 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 2-1 取得飛空艇鸚鵡螺號</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#遇難船'><span style='color: #000080; text-decoration: underline;'>遇難船</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
1.1 &#8211; 艾麗婭加入隊伍<br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水之神殿'><span style='color: #000080; text-decoration: underline;'>水之神殿</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>2.1 &#8211; 取得水晶碎片<br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#水之洞窟'><span style='color: #000080; text-decoration: underline;'>水之洞窟</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; BOSS：克拉肯<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; <span style='color: #ff0000;'>獲得水之力稱號 ( 取得新職業 x5 )</span><br /> (04) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#阿穆爾'><span style='color: #000080; text-decoration: underline;'>阿穆爾</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#下水道'><span style='color: #000080; text-decoration: underline;'>下水道</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.2 &#8211; <span style='color: #ff0000;'>取得浮遊草鞋</span>
<br /> (05) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#金德爾莊園'><span style='color: #000080; text-decoration: underline;'>金德爾莊園</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
5.1 &#8211; BOSS：金德爾<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='color: #ff0000;'>取得鎖鏈鑰匙</span><br /> (06) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#達斯特'>
<span style='color: #000080; text-decoration: underline;'>達斯特</span></a></span></span><br /> (07) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#雷普利特'><span style='color: #000080; text-decoration: underline;'>雷普利特
</span></a></span></span><br /> (08) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>8.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞 東南'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞 東南</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巨龍塔'><span style='color: #000080; text-decoration: underline;'>巨龍塔</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞 東北'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞 東北</span></a></span></span>
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞 西北'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞 西北</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞 西南'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞 西南</span></a>
</span></span> <span style='color: #ff0000;'>( 阿魯斯王子加入隊伍 )</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞城'>
<span style='color: #000080; text-decoration: underline;'>薩羅尼亞城</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.7 &#8211; BOSS 戰：迦樓羅<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.8 &#8211; <span style='color: #ff0000;'>
取得鸚鵡螺號</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>8.9 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞大圖書館'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞大圖書館</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='遇難船'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>遇難船</span><br /> <span style='color: #ffffff;'>-</span><br /> 離開了浮遊大陸後，是一片充滿黑暗烏雲的世界</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 我們先前往最東北方的一個小島</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 別忘了企業號只能停在水面上，我們就在小島旁靠岸，有一艘船在那邊</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上了船後往左下方進入船艙內</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再進入下一層</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一下來就看到兩個寶箱 ( <span style='color: #800000;'>宙斯之怒、嗜血劍</span> )，拿了之後往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 與床邊的人對話，了解到躺在床上的是「艾麗婭」，需要幫助&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後對著艾麗婭對跳出道具清單，選擇「解毒藥」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 艾麗婭醒了之後，說明了情況，並要我們前往水之神殿 ( 艾麗婭加入隊伍 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/01-wrecked_ship-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='水之神殿'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水之神殿</span><br /> <span style='color: #ffffff;'>-</span><br /> 接下來往南方的一個大陸前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/02-temple_of_water-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 將企業號停在大陸的南方岸邊，水之神殿就在附近</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/02-temple_of_water-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在入口的不遠處往右走會有一個恢復池，可以恢復 HP / MP<br /> ( 不過目前好像還不需要，繼續前進吧 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/02-temple_of_water-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底會獲得「水晶碎片」，艾麗婭會告訴我們需前往北方的水之洞窟</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/02-temple_of_water-004.png' width='486' height='326' /><br /> <a name='水之洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>水之洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 水之洞窟就在水之神殿的北方</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後，單線前進到第一道門，艾麗婭會把封印之門打開</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來也是單線前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 中間遇到第一個叉路，但下去沒路，直接往左邊的橋繼續走就好了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：上 ( 寶箱：<span style='color: #800000;'>冰封</span> ) > 右 ( 主線 )<br /> ( 拿寶箱的路有點遠&#8230;.但是冰封是 LV 4 的黑魔法，值得&#8230;.XD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來到了一個滿地都是水的區域，要延著黃色地面才有路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個叉路直接往上走，左邊沒路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往前會看到水之水晶，並且迎來了 BOSS 戰</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>克拉肯</span><br /> HP：<span style='color: #0000ff;'>7500</span>，弱點：<span style='color: #ff0000;'>雷</span><br /> 攻擊：物理攻擊與魔法攻擊共兩次，傷害約 150~300，附加失明</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 克拉肯每回合攻擊兩次
，傷害不算高，但會附加失明狀態<br /> 2. 剛剛有拿到一個宙斯之怒，讓魔法職業的人丟，傷害約在 700~1000 左右<br /> 3. 風水師使用「地形」，「鐮鼬之風」傷害約 680，「冰柱」傷害達 1000 以上<br /> 4. 物理攻擊就看角色的攻擊力，效果算還好，騎士約可輸出 700~900 傷害<br /> 5. 學者雙手拿閃光之書 ( 附帶雷
屬性 )，物理攻擊效果也不錯！<br /> 6. 白魔每回合使用中級治療，再注意回復即可<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗 BOSS 後，艾麗婭犧牲&#8230;.但我們取得了水之力，<span style='color: #ff0000;'>獲得了 5 個新職業！</span><br /> 新職業：<span style='color: #0000ff;'>龍騎士、維京戰士、魔劍士、幻術師、吟遊詩人</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一口氣給了 5 個新職業，還真大方XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 之後出現劇烈震動，眾人睡夢中有個老太婆在說話：要去見多加&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/03-cave_of_tides-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='阿穆爾'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>阿穆爾</span><br /> <span style='color: #ffffff;'>-</span><br /> 眾人醒來後發現被救出，在一個稱為「阿穆爾」的鎮上</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 開始到處對話收集情報吧！旅館二樓酒吧也有不少人，鋼琴可以去彈一下XD<br /> ( 彈鋼琴的時候大家會起身跳舞喔XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 商店有賣新職業可用的武器與防具，但價格&#8230;.為什麼都這麼貴啊！！！<br /> ( 防具店的<span style='color: #800000;'>黑裝束、黑頭巾、盜賊護手</span>待會都可以在鎮上取得，不用買 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 目前雖然有了新職業，但我暫時還未轉職，如果你想使用新武器，當然可以考慮轉職，這邊建議可以先練<span style='color: #ff0000;'>龍騎士</span>，後續會有一個相當麻煩的 BOSS 需要「全員龍騎士」來打比較
保險，只是未必會有適合的武器就是了。但若你覺得當前的職業還沒修煉夠，那就繼續維持吧！反正錢也不太夠，還是在旅館的道具店補充足夠的恢復道具比較重要XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 鎮上的人都一一對話完後，就先找南邊入口處的人對話，會遇到「傳說中的四勇者」&#8230;.不過這勇者看起來&#8230;..XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後到武器店右邊的房子去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 找長老「基爾」對話，會帶我們去開啟鎮上水道的門</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 先繞到上面的菜園去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拉近看會有四個<span style='color: #800000;'>基薩爾野菜</span> ( 閃光處 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後延著水道往左邊走 ( 左邊叉路進去 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下一個叉路再往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 中間的小島右側可以走上去，在島上的左右兩邊共有三個寶物 ( 拉近看 )<br /> 取得物品：<span style='color: #800000;'>黑裝束、黑頭巾、盜賊護手</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就延著水道往最東南方走，就是下水道的入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/04-amur-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline; color: #0000ff;'><a href='#top'><span style='text-decoration: underline; color: #0000ff;'>( 返回頂部目錄 )</span></a></span><br /> <a name='下水道'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>下水道</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後直接往右邊入口下去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個區域都走台階上就好，水路都沒什麼特別的</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路1：右下 ( 寶箱：<span style='color: #800000;'>貓爪</span> ) > 左邊入口 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下一個區域會遇到「四勇者」被襲擊，自動進入戰鬥：<span style='color: #0000ff;'>巨蛙 x4</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後往右繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路2：右暗道 ( 寶箱：<span style='color: #800000;'>金剛石之鈴、大錘</span> ) > 左 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路3：左暗道 ( 寶箱：<span style='color: #800000;'>凱撒拳套、力量護臂、淬毒短劍</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到下一個場景會遇到德莉拉，一開始會給假的浮遊草鞋&#8230;..</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 後來「四勇者」出現幫忙說明後，德莉拉便把真正的「浮遊草鞋」交給了我們，然後「四勇者」會帶大家傳送回到阿穆爾的入口處</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開阿穆爾後，目前企業號是無法使用的 ( 被鎖住 )，但陸地上的河道可以使用現有的「折疊獨木舟」來穿越河道，只要直接往河裡面走就能使用</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/05-amur_sewers-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 目前建議可以在此地先練練級，並提升一下職業的熟練度，反正旁邊有阿穆爾的旅館可以睡覺恢復，順便繼續多賺點錢 ( 建議至少提升 1~2 級 )。當你全部準備好了之後，就往大陸的南方走，步行前往下一個目的地：「金德爾莊園」。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='金德爾莊園'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>金德爾莊園</span><br /> <span style='color: #ffffff;'>-</span><br /> 金德爾莊園的位置在大陸的南方，目前只能步行前往</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在一個三面環山的位置上，前面的沼澤因為有浮遊草鞋所以可以順利通過</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來這個金碧輝煌的屋子，直接往北邊走，路上叉路都先不管，晚點再回來</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一路到底進入最北邊的入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一條很長的走廊後往南走，右側的叉路也都不用進去，都是空的</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 直接往南走到底後右轉</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後你會看到一整排的寶箱&#8230;..一共有 12 個！<br /> 寶箱：<span style='color: #800000;'>輝煌劍 x11、飛龍爪</span> ( 但是輝煌劍的攻擊力&#8230;..只有 5 &#8230;.XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 順便一提，輝煌劍雖然攻擊力只有 ' 5 &#8220;，但是一把可以賣 $2500！如果全部賣掉可以進帳 $27500 &#8230;.XDDDDDD，不過如果你想盡量收集全道具的話，不妨留個 1~2 把，不一定要全部賣掉就是了。<br /> <span style='color: #ffffff;'>-</span><br /> 拿完就原路走回去一開始的大廳</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 大廳一共有四間房間，直接到最右上角這一間 ( 其他三間都是空的 )，當你發現門是鎖住的，可用魔法鑰匙打開 ( 會跳出道具選擇視窗 )。如果你不幸沒有魔法鑰匙&#8230;&#8230;唯一辦法就只能<span style='color: #ff0000;'>轉職為盜賊</span>，站隊伍第一人才能進入了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後在房間的左側有通道，直接進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 第一段路是單線，進入下一個入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來的區域叉路非常多，但有不少死路，如果不想走太多錯路浪費時間的話，別忘了照著下面的提示來走，會節省很多時間！<br /> <span style='color: #ffffff;'>-</span><br /> 一開始往左 > 接著往下 > 然後再往左<br /> ( 這個通道不太明顯 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 過來之後，繼續往左</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後還要連續往左穿過「兩次」類似剛剛牆壁上的通道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了這個位置後，走左邊的通道往上走到底，就可以去找 BOSS 了<br /> ( 第一次玩的時候這裡真是一個煎熬的迷宮啊&#8230;..XDDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>金德爾</span><br /> HP：<span style='color: #0000ff;'>8700</span><br /> 攻擊：物理攻擊約 250~380、失明、沈默</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 金德爾的攻擊每回合只有
一次，不用擔心，魔法也不足為懼<br /> ( 傳說中的金玉其外，敗絮其中XDDDDD )<br /> 2. 騎士、戰士或武僧用一般的物理攻擊即可<br /> 3. 我讓學者丟了一個之前撿到的「眾神之怒」，傷害高達 2000！<br /> 4. 白魔只要注意幫所有人做回復即可<br /> 5. 風水師使用「地形」：鐮鼬之風、吹雪都能有 1000 左右的傷害
<br /> ( 如果運氣好使出了「暗核爆」&#8230;..那傷害就是 4000~5000 了XDDDD )<br /> 6. 如果你是用黑魔，建議用 LV 3 以上的黑魔法攻擊才會有效果<br /> 7. 結論：這 BOSS 根本不強嘛&#8230;.麻煩的其實是迷宮而已 ( 若沒攻略會很困擾XD )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗金德爾後，這傢伙很狡滑地破壞了水晶，但留下了一把錀匙</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往前把「鎖鏈鑰匙」拿起來吧！這樣才能回去解開企業號的鎖</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 離開時用「傳送」就好了 ( 你應該不會想再走一次同樣的路XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走回阿穆爾旁的企業號旁邊，就能使用鎖鏈鑰匙解開企業號了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/06-goldor_manor-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 現在可以稍微休息一下，回阿穆爾補充相關的道具並睡一覺補滿 MP，如果你是練功狂的話也可以在這附近再練一下XDDDD，下一個地點我們就先去地圖正中央一個小島，上面有個小鎮：達斯特。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='達斯特'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>達斯特</span><br /> <span style='color: #ffffff;'>-</span><br /> 在地圖正中央有一個小島，達斯特鎮就在島上 ( 將企業號停在海邊即可 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來之後可以先去找莫古，有西德的信可以讀 ( 標題：與老太婆的初次約會 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著從武器 / 防具店的後方往北走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭有一個「<span style='color: #800000;'>大地之鼓</span>」( 可引發地震魔法 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著從莫古的右邊房子後面，一樣往北走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭還有另一個「<span style='color: #800000;'>大地之鼓</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器店沒什麼好買，但防具店也許你會想買個大地之衣與符文手鐲<br /> ( <span style='color: #800000;'>符文手鐲</span>可以防禦部份異常狀態，<span style='color: #800000;'>大地之衣</span>可以加強風水師的防禦 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/07-duster-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 與鎮上的人都一一對話完收集情報後，接著就可以先離開這裡，坐企業號往地圖的西北方向前進，到下一個地點：雷普利特。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='雷普利特'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>雷普利特</span><br /> <span style='color: #ffffff;'>-</span></p>";
echo "<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 雷普利特的位置在西北大陸的北部岸邊處</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡住著一些召喚士，也會提供一些關於召喚魔法的情報資訊</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/18 Update: ( 補上取得「龜甲殼」)</span></p>
<p>在莫古左邊的樹下，可以發現一個「<span style='color: #800000;'>龜甲殼</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/08-replito_new_item-002.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 魔法店已經有賣召喚魔法，如果你有需要的話，可以購買<br /> ( 錢不夠的話&#8230;..其實你可以賣輝煌劍，一把能賣 $2500 &#8230;.XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在鎮上左側的中間位置，可以發現一個「<span style='color: #800000;'>龜甲殼</span>」( 拉近看 )<br /> ( 使用會引發護盾魔法 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後往上走一點，在這個位置往左邊走到約紅圈的位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡會有一個「<span style='color: #800000;'>聖靈藥</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著到水池右邊樹木間有個通道，往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會遇到一個古爾岡族人，在他左邊有個「<span style='color: #800000;'>不死鳥之尾</span>」( 拉近看 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 最後到右上角房子後面，走到房子右上角，再往下會進到屋子內<br /> ( 不懂的話可以照截圖的箭頭方向走，就會進去了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後往右邊走，這裡也是一個暗道</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭是一個寶箱：<span style='color: #800000;'>聖靈藥</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到剛剛的房間其實還可以往下，然後往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡有個老頭會告訴你三角形小角下面海底有個洞窟，裡面有寶藏<br /> ( 不過我們現在還無法潛入海底&#8230;. )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來就可以往同一塊大陸的東北方，有一大片城鎮與一座城的地方</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/08-replito-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='薩羅尼亞'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞</span><br /> <span style='color: #ffffff;'>-</span><br /> 搭乘企業號朝著中間一座城堡的正面前進，企業號就會遇到襲擊而被迫降落了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 可以行動後，發現身在一群正在對峙的士兵中間，先往下離開吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡一共有四個小城鎮分別位於四個角落，我們先往東南方的城鎮去<br /> ( 地圖上有綠色森林的區域還是會遇敵，而城鎮之間的區域也是可以存檔的 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-003.png' width='486' height='326' /><br /> <a name='薩羅尼亞 東南'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞 東南</span><br /> <span style='color: #ffffff;'>-</span><br /> 這裡的房子都是沒有門的，但我們的目標不是這些房子。鎮上的人可以去對話收集資訊，然後就一路往北走，會看到的一座高塔：巨龍塔，就是我們來這裡的目標</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-004.png' width='486' height='326' /><br /> <a name='巨龍塔'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巨龍塔</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後就繞著這樣的樓梯一路往上走 ( 會遇敵，但是不難打 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 路上的瓶瓶罐罐都沒有藏東西，只要一直往上走就好</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 來到頂層後，左右兩邊的房間各有 6 個寶箱，加起來有 12 個寶箱！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 寶箱：<span style='color: #800000;'>龍盔 x4、閃雷槍 x3、龍甲 x3、不死鳥之尾 x2</span><br /> ( 當然，看名字就知道是龍騎士專屬裝備XDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完之後就離開，繼續到東北方的城鎮<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='薩羅尼亞 東北'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞 東北</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 入口右側的旅館是有開放的，可以休息，也可以購買道具</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 左右兩邊都各有一間魔法店與一間武器店，但目前只有左上角的武器店有開放</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 裡面賣的是閃雷槍 ( 剛剛有取得了 3 把 ) 和疾風槍，結果我又買了一把疾風槍&#8230;.</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/18 Update: ( 補上取得「聖靈藥」)</span></p>
<p>在中央水池的右上方，在一顆樹的樹下拉近看</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/09-saronia_east-north_new_item-002.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>這裡可以發現一個「<span style='color: #800000;'>聖靈藥</span>」，拿完之後就繼續往西北鎮去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/09-saronia_east-north_new_item-003.png' width='486' height='326' /></p>
<p><a name='薩羅尼亞 西北'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞 西北</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡的旅館和道具店也有開放</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 但這裡賣的物品和東北鎮上的不太一樣，不同的地方是西北鎮有賣<span style='color: #800000;'>少女之吻、萬寶槌</span>，而東北鎮有賣<span style='color: #800000;'>海獺頭蘑菇、小人麵包</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 你會發現這裡的北方有一座大圖書館，但目前是進不去的</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 都逛完了之後，我們就前往最後一個西南城鎮<br /> <a name='薩羅尼亞 西南'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞 西南</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 在右側這棟房子內的人可以幫你召喚「胖陸行鳥」出來，能寄放道具，<span style='color: #ff0000;'>先進去吧！</span><br /> ( 一般的陸行鳥森林中，對著中間樹木使用基薩爾野菜也可以 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>12/18 Update: ( 補上取得寶箱：基薩爾野菜 11 個 )</span></p>
<p>在屋子裡面這位學者的右邊，有個暗道可以進入，進去後往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/10-saronia_west-south_new_item-003.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>然後要繞著房間外圍路線往左邊前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/10-saronia_west-south_new_item-004.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>繞過來之後往下，接著往左就會進到一個隱藏房間</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/10-saronia_west-south_new_item-005.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>這裡竟然有 <span style='color: #ff0000;'>11 個寶箱</span>，都是「<span style='color: #800000;'>基薩爾野菜</span>」，果然是陸行鳥愛好者XDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_missed_items/10-saronia_west-south_new_item-006.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 接著就可以繼續往北方走到底，進入這一棟房子</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就會看到有人在欺負一個小王子 ( 阿魯斯 )，然後會進入戰鬥</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 金騎士 x3 ( 戰鬥很簡單，不用擔心 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 勝利後阿魯斯王子會加入隊伍，就可以帶著他前往薩羅尼亞的主城了<br /> <span style='color: #ff0000;'>( 進去之前建議一定先在門口存檔一下，因為 BOSS 戰有很大機會全滅&#8230;. )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='color: #ff0000;'>1/4 Update:</span></p>
<p>(1) 感謝網友 <span style='color: #0000ff;'>NoverseYu</span> 提醒：王子加入後務必先去取得龍甲、疾風槍</p>
<p>(2) 阿魯斯王子加入隊伍後，可以從鎮上的階梯下到水道中，去找水道中間一個小島上的老者對話，取得「<span style='color: #800000;'>龍甲</span>」；在到最左下角找另一個老者對話，取得「<span style='color: #800000;'>疾風槍</span>」。</p>
<p><span style='color: #ff0000;'>( 請注意一定要在王子還跟在隊伍後面的狀況下去才能取得這兩個裝備，抱歉疾風槍就沒有截圖了，請自己走到最左下角去找那老頭吧！ )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/img_8926.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>對話後可以取得一個「<span style='color: #800000;'>龍甲</span>」<span style='color: #ff0000;'>( 之後一旦與王子進入中間的薩羅尼亞城，就無法再取得 )</span></p>
<p><span style='color: #ff0000;'>( 此處若未取得會影響寶箱開啟率無法達成 100% )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/img_8927.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 準備事項及說明：<br /> 1. 等一下進城後，很快就會進入 BOSS 戰，是目前為止最難打的 BOSS！<br /> 2. 最保險的打法是<span style='color: #ff0000;'>全員都轉職為「龍騎士」</span>，並裝備好剛剛取得的專用武器<br /> 3. 轉職會有過渡期，建議一定要花點時間
在周圍附近的綠色森林區打雜兵渡過<br /> 4. 建議把等級提升到最少 30 級或以上，否則&#8230;.真的會比較難打<br /> 5. 龍騎士是為了能用跳躍攻擊，不過還是有機會全滅&#8230;..<br /> 6. FF3 的跳躍攻擊，仍會因角色站前排或後排影響攻擊力，所以我還是都站前排<br /> 7. 如果你有錢的話，也可以回去東北鎮上，再
多買幾把槍來雙手持會更好！<br /> 8. 若你硬要使用其他職業的話，只好建議你用強力一點的魔法了XDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 別忘了轉職完要裝備好武器和防具 ( 到 30 級其實不用花很久時間，建議還是提升一下 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='薩羅尼亞城'></a><br /> <span style='color: #ffffff;'>-
</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞城</span><br /> <span style='color: #ffffff;'>-</span><br /> 中間北方直走就會進城 ( 最後我還是都轉了龍騎士XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 直接穿過對峙的士兵們，進到入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 與門口的士兵對話後就可以進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後就被叫去睡覺，但晚上阿魯斯與阿爾克似乎睡不太著<br /> ( 龍騎士全幅武裝睡覺感覺好怪XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 睡夢中，突然戈恩王出現，而且竟然想要下手殺害阿魯斯！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 但是戈恩王發現自己還是下不了手，只好自我了斷&#8230;. ( 淚 )<br /> ( 緊接著便會進入 BOSS 戰 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>
迦樓羅</span><br /> HP：<span style='color: #0000ff;'>11000</span>，弱點：<span style='color: #0000ff;'>風</span><br /> 攻擊：物理攻擊 x2 或是 物理攻擊 + 閃電 <span style='color: #ff0000;'>( 閃電為全體 600~750 傷害 )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：</p>
<p>1. FF3 出了名難打的 BOSS 之一，不用龍騎士的話真的很難處理它</p>
<p>2. 迦樓羅的物理攻擊不高，大約 150 ~ 200 左右，可怕的是閃電&#8230;.<br /> 3. 如果一開始就被放閃電，那就有點凶多吉少XDDD<br /> 4. 所有人都用跳躍攻擊，每下大約 1000 ~ 1200 左右傷害<br /> <span style='color: #ff0000;'>5. 如果你是裝備雙槍，那攻擊更高達 2200 ~ 4000</span>！( 看是閃雷槍還是疾風槍 )<br /> 6. 正常兩回合就可以結束，除非你鐵齒不是用龍騎士…XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> 若不幸被全滅，都別碰螢幕，直
接按 Home 鍵退出，並在多工列完全退出遊戲，再重新開始遊戲時選擇「CONTINUE」，會從在門口和士兵對話那邊重來一次 ( 放大絕XDDD )。不過如果你有照我的指示進來前有先在外面存檔過的話，就不用擔心了，總之一次打不過去就多試幾次吧！<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後，戈恩王掛點，阿魯斯決定繼承薩羅尼亞的王位</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著在床邊可以行動後，先往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 右邊牆上有裂縫的位置有一條暗道可以進去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一個來到了一個寶箱庫，可以取得 12 個寶箱！<br /> 寶箱：<span style='color: #800000;'>寒冰棒、學者帽子、銹鎧、美杜莎之箭、巨龍錘、左手劍</span></p>
<p><span style='color: #800000;'>烈火之典、寒冰之典、閃光之典、巨像之杖、回旋鏢、賽勒涅之弓</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完繼續往右下角入口走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個空房間，繼續往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了另一個房間，右邊牆上的裂縫處還有一個暗道，再往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭還有 6 個寶箱！<br /> 寶箱：<span style='color: #800000;'>銹鎧、大地之鈴、大地之衣、維京頭盔、龍盔、維京甲</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-038.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 原路走回一開始有床的房間後，可以先往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一路往上會來到一個大廳，可以去找裡面的人及阿魯斯對話</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-040.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 對話完後再返回有床的房間，接著就往下方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-041.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了城外的區域，兩側都會有一個這樣的小房間，先到左邊房間</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-042.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 房間內右上角的牆上又有裂縫了，再次穿牆往右走吧XDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-043.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來一個小房間要往左邊裂縫再穿出去，繞到上面往右走 ( 照箭頭方向走 )<br /> ( 發現被擋住的時候就是方向不對，轉一下方向就好了 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-044.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繞過來會再到另一個小房間，繼續往下走 ( 好長的暗道…XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-045.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一路走到盡頭就會遇到一個人和兩個寶箱：<span style='color: #800000;'>不死鳥之尾 x2</span><br /> ( 有沒有突然明白「不死鳥之尾」在 FF3 裡面很珍貴了呢XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-046.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到外部後再換右邊的房間</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-047.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 裡面是飛空艇的技術人員，直接找他們對話</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-048.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 我們就能得到另一艘速度更快，功能更強大的飛空艇：<span style='color: #ff0000;'>鸚鵡螺號</span>！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-049.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就可以出城了，會看到鸚鵡螺號就停在旁邊</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-050.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 現在先不急著離開這裡，東北鎮上的兩間魔法店與右上角的武器店都開放了，你可以買到 LV4 ~ LV5 的黑白魔法，<span style='color: #ff0000;'>終於可以開始使用魔法來復活了&#8230;..</span>XDDDDDD，在不死鳥之尾如此珍貴的 FF3，復活魔法真是太重要了XD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-051.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 武器店裡也有新增武器，看自己需求吧！( 還是覺得好貴XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-052.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 而在西北鎮上的魔法店則是賣 LV3 的魔法，我們應該都有了，所以可以繞去西北鎮上的圖書館看看，之前還進不去的那棟大房子<br /> <a name='薩羅尼亞大圖書館'></a><br /> <span style='color: #ffffff;'> 
-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞大圖書館</span> ( 西北鎮上方 )<br /> <span style='color: #ffffff;'>-</span><br /> 進來之後是一排排的書櫃</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-053.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在書櫃前面拉近看，會有一個一個的光點，調查後可以看到一些遊戲中的資訊，有時間的話可以把每個書櫃都看一看，裡面也有一些是不錯的情報喔！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_2-1-1/09-saronia-054.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來不妨就休息一下，可以考慮要換什麼職業
繼續，我的組合是換回了原本的騎士、風水師、白魔，然後其中一名維持目前的龍騎士。或者你也可以依照目前所取得的武器裝備來選擇職業，自己用起來順手就好了。<br /> <span style='color: #ffffff;'>-</span><br /> 離開薩羅尼亞之前，別忘了裝備你的武器防具，去旅館睡一覺並且儲存一下吧！然後就可以搭上速度超快的鸚鵡螺號出發了，目標：南方大陸。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>FF3 Part 2-1 取得飛空艇鸚鵡螺號 ( 完 )</div></font></center>
";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
