<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='color: #800000; font-size: 22px;'>Final Fantasy 3 ( iOS )</span></p>
<p><span style='color: #800000; font-size: 22px;'>Walkthrough, Graphic Guide</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>最終幻想 3 ( iOS ) 圖文攻略</span></p>
<p><span style='color: #800000; font-size: 22px;'> </span></p>
<p><span style='color: #800000; font-size: 22px;'>Part 3-1 多加與烏內的犧牲</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法爾加巴德'><span style='color: #000080; text-decoration: underline;'>法爾加巴德</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
1.1 &#8211; 獲得「菊一文字」( 遇敵：忍兵 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法爾加巴德 洞窟'>
<span style='color: #000080; text-decoration: underline;'>法爾加巴德 洞窟</span></a></span></span><br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟'><span style='color: #000080; text-decoration: underline;'>
暗黑洞窟</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖1'><span style='color: #000080; text-decoration: underline;'>
暗黑洞窟 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖2'>
<span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'>
<a href='#暗黑洞窟 地圖3'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖4'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖4</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖5'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖5</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖6'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖6</span>
</a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖7'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖7</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.8 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖8'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖8</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.9 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#暗黑洞窟 地圖9'><span style='color: #000080; text-decoration: underline;'>暗黑洞窟 地圖9</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;
&#8212;</span>BOSS 戰：赫卡通凱伊爾<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>
取得「土之牙」</span><br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴哈姆特洞窟'><span style='color: #000080; text-decoration: underline;'>巴哈姆特洞窟</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴哈姆特洞窟 地圖1'><span style='color: #000080; text-decoration: underline;'>巴哈姆特洞窟 地圖1</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴哈姆特洞窟 地圖2'><span style='color: #000080; text-decoration: underline;'>巴哈姆特洞窟 地圖2</span></a>
</span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#巴哈姆特洞窟 地圖3'><span style='color: #000080; text-decoration: underline;'>
巴哈姆特洞窟 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：巴哈姆特<br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>取得召喚魔法「巴哈姆特」</span><br /> (04) 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多爾湖'><span style='color: #000080; text-decoration: underline;'>多爾湖</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多爾湖 地圖1'><span style='color: #000080; text-decoration: underline;'>多爾湖 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
4.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多爾湖 地圖2'><span style='color: #000080; text-decoration: underline;'>多爾湖 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>4.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多爾湖 地圖3'><span style='color: #000080; text-decoration: underline;'>多爾湖 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>4.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多爾湖 地圖4'><span style='color: #000080; text-decoration: underline;'>多爾湖 地圖4</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：利維亞桑<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span><span style='color: #ff0000;'>取得召喚魔法「利維亞」</span><br /> (05) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#多加莊園'><span style='color: #000080; text-decoration: underline;'>多加莊園
</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.1 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#多加洞窟'><span style='color: #000080; text-decoration: underline;'>多加洞窟</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多加洞窟 地圖1'><span style='color: #000080; text-decoration: underline;'>多加洞窟 地圖1</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多加洞窟 地圖2'><span style='color: #000080; text-decoration: underline;'>多加洞窟 地圖2</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多加洞窟 地圖3'><span style='color: #000080; text-decoration: underline;'>多加洞窟 地圖3</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多加洞窟 地圖4'><span style='color: #000080; text-decoration: underline;'>多加洞窟 地圖4</span></a></span></span></p>
<p><span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#多加洞窟 地圖5'><span style='color: #000080; text-decoration: underline;'>多加洞窟 地圖5</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：多加<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：烏內<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>5.7 &#8211; <span style='color: #ff0000;'>取得優雷卡之鍵、希爾科斯之鍵</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3.php' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='法爾加巴德'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>法爾加巴德</span><br /> <span style='color: #ffffff;'>-</span><br /> 取得了無敵號之後，我們就先前往下一個地點：法爾加巴德。它位在西北大陸山脈之間，需要無敵號的翻越能力才能到達</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 我們先前往薩羅尼亞的西南方位置，左側有個山脈入口，往左前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 剛進來一小段後在下方會有一塊較矮的山峰，將無敵號轉向它會出現「！」，再點擊一下螢幕就可以越過小山峰繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往左飛，到盡頭還有另一塊小山峰，用一樣的方式越過去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 法爾加巴德就在左側的位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 除了與所有人對話收集情報之外，這裡也有旅館和各種商店，不過武器防具這些應該沒幾種是你會想買的，而且當然也是不便宜XDDDD ( 防具店的<span style='color: #800000;'>惡魔之甲、惡魔之盾</span>等一下會都會拿到，不用浪費錢買&#8230;.. )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 題外話，之前沒有提到的，像這種在村鎮裡面會出現的小水池，功能是「復活」，而且是「<span style='color: #ff0000;'>完全復活</span>」，會補滿 HP / MP 的那一種，如果你有人掛掉了，在旅館睡覺是不會復活的，要在水池才會有效。如果隊伍中沒有人陣亡，那就會「什麼事也沒發生」。</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在村內的東北方瀑布旁邊，有暗道可以往右進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後有個階梯等一下再走，先繼續往前走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭有個老頭，跟他對話後會發生戰鬥</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 遇敵：<span style='color: #0000ff;'>忍兵</span><br /> HP：<span style='color: #0000ff;'>11000</span><br /> 攻擊：物理攻擊約 1000~1200 ( 單體，附加中毒、失明效果 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後可以得到「<span style='color: #800000;'>菊一文字</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就往回走下階梯，往下繼續走水路出去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭會來到一個池中小島可以上去，在島上兩側共有四個物品可拿 ( 拉近看 )<br /> 取得物品：<span style='color: #800000;'>高級恢復藥、惡魔之甲、惡魔之盾、祝福錘</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 拿完就可以原路走回這裡離開</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-015.png' width='486' height='326' /><br /> <a name='法爾加巴德 洞窟'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>法爾加巴德 洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 接下來可以到村子北方的洞窟進去。但要注意的是裡面的怪物如果不是以「暗黑系列」的武器來攻擊，就容易會造成增殖或分裂，這有點麻煩，包含之後會去的暗黑洞窟也是。不過這些怪物要殺掉也不是難事，現在隊伍實力堅強啊XDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進來就有一個寶箱 ( <span style='color: #800000;'>祝福錘</span> )，然後往右走，通道之間很黑，正確的方向是往右、往下、再往右就可以過去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 單線前進會再經過一個寶箱 ( <span style='color: #800000;'>惡魔之甲</span> )，往右繼續走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個通道就會跑到全黑畫面，看不出來到底有沒有在前進XDDDD，正確走法是先往右之後，再往上、往左就會進到下一個區域</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到下一個位置有 3 個寶箱：<span style='color: #800000;'>虎徹、阿修羅</span>，拿完後就可以往回走了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/01-falgabard-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著就能離開這裡，前往下一個很討厭的地點：暗黑洞窟<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='暗黑洞窟'></a><br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗黑洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 暗黑洞窟在東部大陸的中間位置，需要無敵號穿越一塊又一塊的小山峰才能到達</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 到了東部大陸後，山脈群的左側與沙漠交界處，有一個「入口」可以進去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後就是不斷地翻山越嶺，就看到無敵號一直跳一直跳&#8230;..中途還會有叉路，這邊就不多說了，因為要跳太多次，如果發現走錯了無法前進就換一邊走，一路要繞好大一圈才會到盡頭&#8230;.. ( 擦汗</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭就會看到暗黑洞窟的入口，記得先存檔一下吧！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-004.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗黑洞窟 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：右 ( 寶箱：<span style='color: #800000;'>黑之香</span> ) > 下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 中途會經過一個寶箱：<span style='color: #800000;'>暗黑爪</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 往下繼續走之前，會遇到一個垂死的人，對話後可獲得「<span style='color: #800000;'>虎徹</span>」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-007.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗黑洞窟 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 繼續走一小段，繞上來左邊有個暗道，內有寶箱 ( <span style='color: #800000;'>麻醉針</span> )，拿完繼續走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 走到底通道不是很明顯，往左繼續走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-009-1.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>莉莉絲之吻</span> )，再來是往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-009-2.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗黑洞窟 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 這一段路是單線，中間左側雖然有經過一個暗道，但過去是空的，繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-009-3.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span>
<br /> <span style='color: #0000ff;'>暗黑洞窟 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 從這裡開始的路有點小複雜，加上通道幾乎都是黑漆漆的看不見路的方向，若你是第一次玩 FF3，這裡建議走慢一點，仔細照我寫的流程一小段一小段地走，才不會把路都搞混了。如果你具備冒險的精神，當
然也可以自己慢慢地探索，這樣才能完全體會 RPG 的樂趣啊！( 只是寶箱可能會拿不齊XDDDD )<br /> <span style='color: #ffffff;'>-</span><br /> 直接往右走 ( 往下的兩個通道是會繞一圈走不出去 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著直接往下走，黑暗中會延著牆壁路線一路往右下方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>源氏之護手</span> )，繼續往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-012.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖5'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span>
<br /> <span style='color: #0000ff;'>暗黑洞窟 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 第 5 段路這裡往下碰壁後，往左繼續延著牆壁走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著在黑暗中會順著往左上方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再來是往下，再順著牆壁往右下方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後再往下 > 往左，黑暗中順著路往左上方繼續走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著是往下 > 往右，然後就會看到往下一段路的階梯了 ( 呼… )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-017.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖6'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>暗黑洞窟 地圖6</span><br /> <span style='color: #ffffff;'>-</span><br /> 第 6 段路一樣直接往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 單線走到快底部的時候，往左邊暗道繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>菊一文字</span> )，繼續往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-020.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖7'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span>
<br /> <span style='color: #0000ff;'>暗黑洞窟 地圖7</span><br /> <span style='color: #ffffff;'>-</span><br /> 下來後左邊有個寶箱 ( <span style='color: #800000;'>源氏之盾</span> )，拿了之後往右走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後你會覺得似曾相識&#8230;.沒錯，往下走到底再往左走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繼續往下到下一段路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-023.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖8'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span>
<br /> <span style='color: #0000ff;'>暗黑洞窟 地圖8</span><br /> <span style='color: #ffffff;'>-</span><br /> 終於有點不一樣的路了，往右繼續走吧 ( 擦汗</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>源氏之盔</span> )，往上繼續走</p>";
echo "<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-025.png' width='486' height='326' /><br /> <a name='暗黑洞窟 地圖9'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span>
<br /> <span style='color: #0000ff;'>暗黑洞窟 地圖9</span><br /> <span style='color: #ffffff;'>-</span><br /> 這是最後一段，右邊有暗道先去拿寶箱 ( <span style='color: #800000;'>源氏之鎧</span> )，再繼續往上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭終於看到了桌上的「土之牙」，但是有那麼簡單得到嗎？</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-027.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>赫卡通凱伊爾</span><br /> HP：<span style='color: #0000ff;'>30000</span>，弱點：無<br /> 技能：物理攻擊 x2 ( 傷害約 400~450 )，地震 ( 全體 400~500 傷害 )<br /> 偷盜：黑洞<br /> ( FFD 也有出現這個名字的 BOSS，但是造型、麻煩度都差好多XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> <span style='color: #ff0000;'>1. 這傢伙弱爆了&#8230;.根本不用什麼攻略</span><br /> 2. BOSS 的攻擊毫無殺傷力，就連地震也是，是因為我們走了這麼一大段烏漆麻黑的路，所以
特別給的獎勵嗎XDDDDDD<br /> 3. 隨便用物理攻擊砍他都能有 3000 左右的傷害，龍騎士跳躍還高達 6000….<br /> 4. 沒了，就這樣，整個樂勝XD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後總算<span style='color: #ff0000;'>取得了「土之牙」</span>！</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 難道你還想慢慢走出去嗎？當然是傳送&#8230;.XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在暗黑洞窟獲得土之牙後，可以先回到無敵號裡面找莫古收信，記得換人收</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會收到以下信件：<br /> 收信人：因古斯 > 莎拉公主 ( 第 2 封 / 標題：不好了！)，告訴你她的首飾壞了<br /> 收信人：阿爾克 > 阿魯斯 ( 第 2 封 / 標題：那之後的薩羅尼亞 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-032.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 收了信之後雖然可以先回去浮遊大陸
的薩斯恩城找莎拉公主，但是對於我們現階段的攻略是沒什麼幫助的，因為我們的劇情發展還有幾段要進行，就算現在去觸發事件也不會取得什麼好東西，不如就先繼續吧！後續會再說明關於信件內容的子事件。<br /> <span style='color: #ffffff;'>-</span><br /> 另外要建議的是，目前我們的鸚鵡螺號還停在古代遺跡附近，
為了之後交換飛空艇比較方便，建議去把兩架飛空艇都一起放在薩羅尼亞城前面的空位，以後要換乘比較快。方法就是先把無敵號停在薩羅尼亞城前面，然後往左「走路」延著河道繞去古代遺跡，再把鸚鵡螺號開過來放。</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來我們要飛回去浮遊大陸 ( 地圖左下角 ) 的巴哈姆特洞窟，請使用無敵號前往，雖然飛得有點慢&#8230;.XDDDDD</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/02-the_cave_of_shadows-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='巴哈姆特洞窟'></a><br /> <span style='color: #ffffff;'>-
</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴哈姆特洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> 巴哈姆特洞窟位於浮遊大陸的東南方，就在托扎斯小人村的左側</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在托扎斯小人村的那片森林左邊山脈，使用無敵號靠近後會出現「！」</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後就會看到洞窟的入口</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這個洞窟的雜兵經驗值與金幣都很高，算是
後期一個很適合練等級和賺錢的地點，但如果你只是要單純提升熟練度的話，就不一定要在這裡了，一般要提升熟練度通常建議會去遊戲一開始的烏爾那附近找哥布林，利用「防禦」的次數來提升，之後有機會再來談這個部份。( 補充：熟練度的提升在 <span style='text-decoration: underline;'>
<span style='color: #0000ff; text-decoration: underline;'><a href='./ff3_part_3_2.php#支線事件：頂級之證與最終裝備' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>Part 3-2</span></a></span></span> 我已有簡單的說明 )<br /> <span style='color: #ffffff;'>-</span><br /> 進去之前，建議使用的職業中，最好準備一下龍騎士，然後裝備無敵號上有賣的「龍槍」，當然錢夠的話就買兩把都裝備上，這樣一
來使用跳躍攻擊將很快就能打趴 BOSS。傷害肯定突破 9999。<span style='color: #ff0000;'>( 數字的顯示最多只到 9999，但是實際是不止的！)</span><br /> 
<a name='巴哈姆特洞窟 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴哈姆特洞窟 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 一開始直接往下就會遇到叉路<br /> 叉路：左 ( 寶箱：<span style='color: #800000;'>眾神之怒、大地之鼓</span> ) > 右 ( <span style='color: #800000;'>不死鳥之尾、北極之風</span> ) > 下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-004.png' width='486' height='326' /><br /> <a name='巴哈姆特洞窟 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴哈姆特洞窟 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 第二段路直接往左邊走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>巨像之杖</span> )，繼續往下</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著一樣都是單線，路上會再取得<span style='color: #800000;'>白之香、酒神之酒、陸行鳥之怒、龜甲殼</span>，然後就繼續往下走，到下一個區域</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-007.png' width='486' height='326' /><br /> <a name='巴哈姆特洞窟 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>巴哈姆特洞窟 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 第三段路一出來就有一個寶箱 ( <span style='color: #800000;'>歐律托斯之弓</span> )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接著又是三個寶箱 ( <span style='color: #800000;'>不死鳥之尾、聖靈藥、虎徹</span> )，再往上走出去就是 BOSS 了</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>巴哈姆特</span><br /> HP：<span style='color: #0000ff;'>34000</span>，弱點：<span style='color: #ff0000;'>風</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 750~850 )</p>
<p>技能：( 來不及看到他就掛了XDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 巴哈姆特飛在空中具備風
屬性弱點，又屬於龍類，對付他最適合的就是龍槍&#8230;.<br /> 2. 龍騎士裝備兩把龍槍，用跳躍攻擊，傷害會突破 9999 ( 但只會顯示 9999 )<br /> 3. 我的龍騎士跳躍了一次，盜賊與騎士各砍了 1~2 次，他就掛了&#8230;..這表示龍騎士那一次的傷害肯定高達 25000 以上XDDDDD ( 我猜的，否則不可能那麼快… )<br /> 4.
白魔有空的話就幫忙加速、放護盾之類的就可以了<br /> 5. 盜賊速度最快，要丟恢復藥或聖靈藥找他最適合，一定可以先出手<br /> 6. 總之主攻就是龍騎士的跳躍，一定可以快速解決！<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗後<span style='color: #ff0000;'>取得召喚魔法「巴哈姆特」</span>( 巴哈姆爾？！ )，因為戰鬥完之在地圖上的另一個出口，所以無法用傳送離開，必須原路一直走回去才能離開</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/03-bahamuts_lair-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來我們可以前往浮遊大陸的左側，一個你曾經見過的湖泊。<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='多爾湖'></a><br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多爾湖</span><br /> <span style='color: #ffffff;'>-</span><br /> 在浮遊大陸的左側有個湖泊，位於阿加斯城左邊偏南的位置</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 控制無敵號飛到湖泊的下方，可以越過小山峰進入</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 你會看到湖泊中有一隻怪魚在游來游去，也許你之前就見過了，但是不得其門而入，現在我們就可以直接往湖裡面走，使用獨木舟，往湖泊的中間上方前進就能進入多爾湖</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 職業的選擇上我還是習慣用龍騎士的跳躍，可搭
配閃雷槍或是龍槍皆可 ( 我還是用龍槍XD )，最後我進去時的組合是龍騎士 x2、白魔、黑魔，至於黑魔的用處就是針對 BOSS 的弱點來放 LV 5 的暴雷，傷害值約 2500~2700 ( 視你黑魔的熟練度 )，但主要還是龍騎士進攻。<br /> <span style='color: #ffffff;'>-</span><br /> 如果轉職後發現黑魔沒有 MP，吃個聖靈藥就好
了，身上應該不少XDDDD<br /> <a name='多爾湖 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多爾湖 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：下 ( 寶箱：<span style='color: #800000;'>不死鳥之尾、眾神之怒、大地之鼓、北極之風</span> ) > 上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再經過 4 個寶箱 ( <span style='color: #800000;'>高級恢復藥 x3、聖靈藥</span> )，繼續往下走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-005.png' width='486' height='326' /><br /> <a name='多爾湖 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多爾湖 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：上 ( 寶箱：<span style='color: #800000;'>聖盾、白金錘、酒神之酒、龜甲殼</span> ) > 下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再經過一個寶箱 ( <span style='color: #800000;'>白之香</span> )，繼續往下前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-007.png' width='486' height='326' /><br /> <a name='多爾湖 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多爾湖 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 來到這個大叉路，先往右上走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會經過 3 個寶箱 ( <span style='color: #800000;'>黑洞、白金錘、反射甲</span> )，繼續往左還有一個寶箱 ( <span style='color: #800000;'>黑之香</span> )</p>
<p>拿完之後返回剛剛的大叉路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：左下 ( 寶箱：<span style='color: #800000;'>莉莉絲之吻、天狗的哈欠</span> ) > 左上 ( 主線 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-010.png' width='486' height='326' /><br /> <a name='多爾湖 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多爾湖 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 最後一段路都單線，走到底就會遇到 BOSS</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>利維亞桑</span><br /> HP：<span style='color: #0000ff;'>36000</span>，弱點：<span style='color: #ff0000;'>雷</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 300~400，隨機附帶石化狀態 )<br /> <span style='color: #800000;'>技能：海嘯 ( 全體傷害約 1000~1500 )</span></p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：<br /> 1. 龍騎士主攻 ( 跳躍 )，一開始
BOSS 只會用物理攻擊，傷害不高<br /> 2. 兩到三回合後，BOSS 會使出「海嘯」，如果 HP 不夠的話可能會掛 1~2 人<br /> 3. 白魔如果還在就趕緊回復、救人，如果不在就凶多吉少，看龍騎士的造化了<br /> 4. 龍騎士每次攻擊應該可以造成 5000~6000 的傷害，為攻擊主力<br /> 5. 黑魔除了放「暴雷」之外，也可以丟「眾神之怒」，效果差不多</p>
<p>6. 結論：感覺沒有特別有效的攻擊方式，龍騎士真的很好用XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗 BOSS 後，取得召喚魔法「利維亞」，接著就傳送離開</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/04-lake_dohr-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 再來我們就可以再回去找多加與烏內了，離開浮遊大陸回到世界地圖吧！<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='多加莊園'></a><br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多加莊園</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到世界地圖後，先去把飛空艇換成鸚鵡螺號，還記得多加莊園嗎？那是一個山脈間通道有強風的地方，無敵號是進不去的，所以要換成鸚鵡螺號</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/05-dogas_manor-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 多加莊園的入口在南方大陸的左下角</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/05-dogas_manor-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 一進到多加莊園就會受到多加的邀請</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/05-dogas_manor-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 眼前會出現一個傳送點，直接走進去</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/05-dogas_manor-004.png' width='486' height='326' /><br /> <a name='多加洞窟'></a><br /> <a name='多加洞窟 地圖1'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>多加洞窟</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>多加洞窟 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 第一段路都是單線，一路前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-001.png' width='486' height='326' /><br /> <a name='多加洞窟 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>多加洞窟 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 第二段路一共會經過兩個寶箱 ( <span style='color: #800000;'>10000 元 x2</span> )，繼續前進到下一段路</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-002.png' width='486' height='326' /><br /> <a name='多加洞窟 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多加洞窟 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 一開始的叉路先往左下方走</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 叉路：往上可拿 3 個寶箱 ( <span style='color: #800000;'>旭日、色欲短劍、白之香</span> )，往下走只會有一個空房間</p>
<p>( 房間內也會遇敵 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到開始的叉路往右下繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-005.png' width='486' height='326' /><br /> <a name='多加洞窟 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>多加洞窟 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 出來經過一個寶箱 ( <span style='color: #800000;'>陸行鳥之怒</span> )，繼續前進</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-006.png' width='486' height='326' /><br /> <a name='多加洞窟 地圖5'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>多加洞窟 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 這段路總共會經過兩個寶箱 ( <span style='color: #800000;'>不死鳥之尾 x2</span> )，再往前就會遇到多加與烏內</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭遇到了多加與烏內兩個人一起出現，說明
了優雷卡之鍵與禁斷之地的事，並且要我們與他們兩人戰鬥&#8230;..雖然很不願意，但是懷著滿腔的熱血，為了取得優雷卡之鍵，只好忍痛上了！( 說真的，這一段劇情是我最喜歡也最感動的，是不是覺得我很愛演XDDDDD )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>
多加</span><br /> HP：<span style='color: #0000ff;'>23500</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 700~950 )、爆炎/暴雷 ( 單/全體，傷害 700~1000 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：</p>
<p>1. 多加可能因為是自己人，所以出手都不太重，不管魔法或是物理攻擊都是</p>
<p>2. 這場戰鬥並不難，隨心所欲地去打吧，大約三回合後就能取勝<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗了多加，繼續上演感人的劇情，配上動聽的音樂，多加已經奄奄一息，接下來換到烏內了，這些對白是否讓你感到於心不忍了呢？( 偷偷掉淚&#8230;. )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> BOSS 戰：<span style='color: #0000ff;'>烏內</span><br /> HP：<span style='color: #0000ff;'>24000</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 500~600 )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 攻略：</p>
<p>1. 烏內感覺人更好，也是一樣出手都不重</p>
<p>2. 一樣不難打的一場 BOSS 戰， 忍著悲傷結束戰鬥吧&#8230;. ( 繼續演XD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗烏內後，<span style='color: #ff0000;'>取得優雷卡之鍵、希爾科斯之鍵</span> ( 好感人的音樂啊&#8230;.. )</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 傳送離開後，應該會有新的信件，可以先回去無敵號找莫古，讓阿爾克收信</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 阿魯斯 &#8211; 標題：鸚鵡螺號狀態如何？</p>
<p><img class='alignnone' alt='' src='./ff3_images/ff3_part_3-1/06-dogas_grotto-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來的主線劇情已所剩不多，但我們的最終職業也尚未取得。而信件的支線也有一部份必須要通過古代人迷宮、水晶塔與禁斷之地才會陸續觸發。另外在禁斷之地裡面還有許多高階武器等著我們去拿，所以接下來還是會建議先前往古代人迷宮，至於莎拉公主的首飾&#8230;&#8230;就讓她再等一下吧XDDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>對了，奧丁的神槍還記得嗎？如果你的盜賊熟練度已經達 71 以上，就可以回去 <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='./ff3_part_2_2.php#薩羅尼亞地下迷宮 地圖5' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>薩羅尼亞地下迷宮</span></a></span></span> 找奧丁偷神槍了，現在去打奧丁會覺得異常輕鬆，不過重點還是偷槍啦&#8230;..</p>
<p><span style='color: #ffffff;'>-</span></p>
<p>PS. 題外話：寫到這裡突然覺得 FF3 的劇情比 FFD 短好多，支線的數量也是差很多，FFD 劇情實在有夠長，而且支線跟可收集的要素更是相當多啊XDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>
<div>FF3 Part 3-1 多加與烏內的犧牲 ( 完 )</div></font></center>
";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
