<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo "<center><font size=4><p><span style='font-size: 22px; color: #800000;'>Final Fantasy 3 ( iOS )</span></p>
<p><span style='font-size: 22px; color: #800000;'>Walkthrough, Graphic Guide</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>最終幻想 3 ( iOS ) 圖文攻略</span></p>
<p><span style='font-size: 22px; color: #800000;'> </span></p>
<p><span style='font-size: 22px; color: #800000;'>Part 3-2 禁地武器與支線事件</span></p>
<p><a name='top'></a></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>本篇流程順序及重點摘要</p>
<p>點選連結可以跳轉</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='http://www.hdlulu.com/ff3_walkthrough_main_menu/' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>(01) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮'><span style='color: #000080; text-decoration: underline;'>古代人迷宮</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
1.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮 土之水晶'>
<span style='color: #000080; text-decoration: underline;'>古代人迷宮 土之水晶</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>BOSS 戰：泰坦<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>
<span style='color: #ff0000;'>獲得最終職業</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮 地圖1'><span style='color: #000080; text-decoration: underline;'>古代人迷宮 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.3 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮 地圖2'><span style='color: #000080; text-decoration: underline;'>古代人迷宮 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>1.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮 地圖3'><span style='color: #000080; text-decoration: underline;'>古代人迷宮 地圖3</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>1.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮 地圖4'><span style='color: #000080; text-decoration: underline;'>古代人迷宮 地圖4</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>1.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#古代人迷宮 地圖5'><span style='color: #000080; text-decoration: underline;'>古代人迷宮 地圖5</span></a></span>
</span><br /> (02) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡</span></a></span></span> <span style='color: #ff0000;'>
( 水晶塔內，開啟優雷卡之門 )</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖1'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖1</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>
2.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖2'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖2</span></a></span></span><br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>2.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖3'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖3</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖4'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖4</span></a></span>
</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得<span style='color: #800000;'>圓月輪</span> ( BOSS 戰：亞蒙 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.5 &#8211; <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖5'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖5</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得
<span style='color: #800000;'>萬全棒、正宗</span> ( BOSS 戰：女忍者 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖6'>
<span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖6</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得<span style='color: #800000;'>王者之劍</span> ( BOSS 戰：將軍 )<br /> <span style='color: #ffffff;'>
&#8212;&#8212;&#8211;</span>2.7 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖7'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖7</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得<span style='color: #800000;'>長老之杖</span> ( BOSS 戰：六獸妖 )<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>取得<span style='color: #800000;'>諸神之黃昏</span> ( BOSS 戰：守護者 )
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>2.8 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#禁地優雷卡 地圖8'><span style='color: #000080; text-decoration: underline;'>禁地優雷卡 地圖8</span></a>
</span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>禁地商人：可購得黑白魔法 LV 8<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8212;&#8212;&#8212;</span>暗道內禁地商人：可購得手裡劍及水晶裝備<br /> <span style='color: #ffffff;'>&#8212;&#8212;
&#8211;</span>2.9 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#返回水晶塔'><span style='color: #000080; text-decoration: underline;'>返回水晶塔</span></a></span></span> <span style='color: #ff0000;'>( 開啟封印之門 )
</span><br /> (03) <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#支線事件：莎拉公主的首飾'><span style='color: #000080; text-decoration: underline;'>支線事件：莎拉公主的首飾</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.1 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩斯恩城'><span style='color: #000080; text-decoration: underline;'>薩斯恩城</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#卡茲斯'><span style='color: #000080; text-decoration: underline;'>卡茲斯</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#薩羅尼亞 西北'><span style='color: #000080; text-decoration: underline;'>薩羅尼亞 西北</span></a></span></span>
<br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.4 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#迦南'><span style='color: #000080; text-decoration: underline;'>迦南</span></a></span></span><br /> 
<span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.5 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#法爾加巴德'><span style='color: #000080; text-decoration: underline;'>法爾加巴德</span></a></span></span> 
<span style='color: #ff0000;'>( 取得「究極神兵」)</span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>3.6 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#支線事件補充說明'><span style='color: #000080; text-decoration: underline;'>支線事件補充說明</span></a></span></span><br /> (04) <span style='text-decoration: underline;'>
<span style='color: #000080; text-decoration: underline;'><a href='#支線事件：頂級之證與最終裝備'><span style='color: #000080; text-decoration: underline;'>支線事件：頂級之證與最終裝備</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;</span>4.1 &#8211; 
<span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#熟練度與等級的提升'><span style='color: #000080; text-decoration: underline;'>熟練度與等級的提升</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;&#8212;&#8211;
</span>4.2 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#女鐵匠的出現地點'><span style='color: #000080; text-decoration: underline;'>女鐵匠的出現地點</span></a></span></span><br /> <span style='color: #ffffff;'>&#8212;
&#8212;&#8211;</span>4.3 &#8211; <span style='text-decoration: underline;'><span style='color: #000080; text-decoration: underline;'><a href='#最後的信件'><span style='color: #000080; text-decoration: underline;'>最後的信件</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='http://www.hdlulu.com/ff3_walkthrough_main_menu/' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>返回 FF3 攻略總目錄</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;<br /> <a name='古代人迷宮'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>- </span></p>
<p><span style='color: #0000ff;'>古代人迷宮</span><br /> <span style='color: #ffffff;'>-</span><br /> 古代人迷宮與水晶塔的位置在東北大陸右側 ( 需使用無敵號 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 在東北大陸的南方有一個山脈間的入口</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後飛空艇無法繼續往前，會被彈回，只好下船步行，一路往前走，石像會一一消失</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 走到底發現無法通過，所以需走回來以無敵號翻越過去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 一路往東走便會到達長方形的古代人迷宮，中心部份則是水晶塔<br /> ( 進去之前別忘了儲存，以及在無敵號睡一覺、補充好所需的道具 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-005.png' width='486' height='326' /><br /> <a name='古代人迷宮 土之水晶'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>古代人迷宮 土之水晶</span><br /> <span style='color: #ffffff;'>-</span><br /> 一進來先直接往上走，進入正上方的房間</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 盡頭會見到土之水晶，並進入 BOSS 戰</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>泰坦</span><br /> HP：<span style='color: #0000ff;'>29000</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 800~1200 )<br /> 技能：地震 ( 全體約 600~800 傷害 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 泰坦的攻擊傷害還能接受，
物理攻擊較多<br /> 2. 建議可以放龜甲殼或護盾魔法加強防禦<br /> 3. 龍騎士跳躍攻擊 ( 裝備雙龍槍 ) 可有 6000 左右傷害<br /> 4. 其餘人員熟練度高的話，雙武器通常都有 3000~4000 的傷害<br /> 5. 注意回復，如需聖靈藥一樣建議讓盜賊來丟，最有效率，不會浪費<br /> <span style='color: #ffffff;'>-</span>
<br /> <span style='color: #ffffff;'>-</span><br /> 打敗泰坦後，取得土之水晶的稱號，獲得了最終的職業：<br /> <span style='color: #ff0000;'>空手道家、導師、巫師、魔界幻士、賢者、忍者</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 終於獲得了更進階的職業，建議大家各項職業
都去試一試，看自己最喜歡哪一個職業，我的攻略裡面的職業也都只是建議，打 BOSS 的時候主要也是依我自己的職業來說明，既然取得了這麼多新職業，不換說不過去吧XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> 當然，如果你想先把目前的職業先練滿再說，也是可以。<br /> <a name='古代人迷宮 地圖1'>
</a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>古代人迷宮 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 返回一開始的入口，直接往右走，接著單線往上走</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 會經過一個寶箱 ( <span style='color: #800000;'>聖靈藥</span> )，繼續往左前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 直接往上走，進入下一段路 ( 左邊會繞回入口，不用走 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-012.png' width='486' height='326' /><br /> <a name='古代人迷宮 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>古代人迷宮 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：左 ( 寶箱：<span style='color: #800000;'>水晶盾、莉莉絲之吻</span> ) > 右 ( 主線 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 經過一個寶箱 ( <span style='color: #800000;'>水晶甲</span> )，往上繼續走</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著都是單線前進，延路會再取得兩個寶箱 ( <span style='color: #800000;'>白之香、水晶護手</span> )，然後就往右邊黑色的區域進去下一段路</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-015.png' width='486' height='326' /><br /> <a name='古代人迷宮 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>古代人迷宮 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 過來後右側先拿寶箱 ( <span style='color: #800000;'>水晶盔</span> )，接著往下走</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：下 ( 寶箱：<span style='color: #800000;'>石化劍、不死鳥之尾、陸行鳥之怒</span> ) > 右 ( 主線 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 盡頭左側還有一個寶箱 ( <span style='color: #800000;'>雙釘</span> )，拿完往右邊入口繼續前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-018.png' width='486' height='326' /><br /> <a name='古代人迷宮 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>古代人迷宮 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著是一條長長的走道，上下單線一直前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 再經過一個寶箱 ( <span style='color: #800000;'>不死鳥之尾</span> )，往下繼續走</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 盡頭入口處也有寶箱 ( <span style='color: #800000;'>守護戒指</span> )，往上繼續會到下一段路</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-021.png' width='486' height='326' /><br /> <a name='古代人迷宮 地圖5'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>古代人迷宮 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 到了第五段路，眼前的兩條路都一樣，走其中一條上去即可</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 走上來有一個寶箱 ( <span style='color: #800000;'>聖槍</span> )，繼續往左或往右皆可，會接回同一條路</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 繞上來後取得另一個寶箱 ( <span style='color: #800000;'>地獄爪</span> )，繼續往上走就會離開迷宮</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/01-ancients_maze-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='禁地優雷卡'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡</span> ( 水晶塔內 )<br /> <span style='color: #ffffff;'>-</span><br /> 出來後是在古代人迷宮範圍內部地圖的水晶塔前，建議先儲存一下再進去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 水晶塔內部的敵人都很硬，如果覺得太難打可能要回古代人迷宮練練級再進去，不過我們現在還沒有要進攻水晶塔，是要先到裡面的「禁地優雷卡」。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 進來後先一路往上直走，前往下一個位置</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-002.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 走到底在一個圓形圖騰前調查</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著優雷卡之鍵會發生效果，眾人會被傳送到禁地優雷卡</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-004.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖1'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖1</span><br /> <span style='color: #ffffff;'>-</span><br /> 下來後兩邊各有一條路，我們先從左邊開始</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：右 ( 寶箱：<span style='color: #800000;'>風魔之衣、陸行鳥之怒</span> ) > 下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 繞到下面入口時，先往右繞回去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 這邊還有兩個寶箱 ( <span style='color: #800000;'>白之香、聖靈藥</span> )，拿完再往剛剛的入口下去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-008.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖2'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖2</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著一樣是個叉路，這次我們先走右邊</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 先往上面入口進去拿寶箱</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 裡面是 3 個寶箱 ( <span style='color: #800000;'>白之香、陸行鳥之怒、不死鳥之尾</span> )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 繼續往下走，中途在左側有一條不是很明顯的叉路，先進去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 盡頭是一個寶箱 ( <span style='color: #800000;'>緞帶</span> )，但是打開後會遇敵！<br /> ( 在 FF3 的緞帶是頭盔類的裝備&#8230;.好怪XDDD )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-013.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 遇敵：<span style='color: #0000ff;'>忍者</span><br /> HP：<span style='color: #0000ff;'>24000</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 1000~1100，附加中毒、失明狀態 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 繼續往下走，來到下面叉路後，先往左側繞回去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-015.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 這邊一樣有一個入口，進面是一個寶箱 ( <span style='color: #800000;'>白之香</span> )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 拿完再往下回到這個叉路：左 ( 寶箱：<span style='color: #800000;'>手裡劍</span> ) > 右 ( 主線 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-017.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖3'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖3</span><br /> <span style='color: #ffffff;'>-</span><br /> 叉路：左 ( 寶箱：<span style='color: #800000;'>聖靈藥</span> ) > 下 ( 主線 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 路上再經過一個寶箱 ( <span style='color: #800000;'>手裡劍</span> )，繼續前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 下去之前旁邊還有一個寶箱 ( <span style='color: #800000;'>不死鳥之尾</span> )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-020.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖4'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖4</span><br /> <span style='color: #ffffff;'>-</span><br /> 接著就是一連串的高階武器與守護武器的 BOSS 戰，每場 BOSS 戰結束後都會取得該武器，且 HP / MP 會回滿。<br /> <span style='color: #ffffff;'>-</span><br /> 第一站：<span style='color: #800000;'>圓月輪</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>亞蒙</span><br /> HP：<span style='color: #0000ff;'>33500</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 700~900 )、魔法攻擊<br /> 技能：護罩切換 ( 弱點會變化 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 亞蒙長得很像之前打過的魔法師海
因，連技能也一樣，會切換弱點<br /> 2. 打法就看你用的是何種職業，盡量以最強技能去應付即可<br /> 3. 使用學者或是白魔法的偵測可以確定當前的 BOSS 弱點為何<br /> 4. 打完取得圓月輪後就繼續往下走<br /> <a name='禁地優雷卡 地圖5'></a><br /> <span style='color: #ffffff;'>-</span><br /> 
<span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖5</span><br /> <span style='color: #ffffff;'>-</span><br /> 在第五段路的叉路上，先往左拿寶箱 ( <span style='color: #800000;'>萬全棒</span> )，接著再往右走</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 第二站：<span style='color: #800000;'>正宗</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>女忍者</span><br /> HP：<span style='color: #0000ff;'>29000</span><br /> 攻擊：物理攻擊 x3 ( 傷害約 700~900，附加中毒、失明狀態 )、魔法攻擊</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 這個 BOSS 有點麻煩，因為她每回
合行動三次！( 這算啥&#8230;.. )<br /> 2. 如果三次都砍在同一個人身上，那應該是掛定了<br /> 3. 建議還是要放護盾或是龜甲殼來降低物理傷害<br /> 4. 找個人裝備緞帶，可以減少一些中毒、失明狀態的麻煩<br /> 5. 龍騎士的跳躍一樣簡單好用<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到叉路繼續往下走</p>";
echo "<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-026.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 到下一段路之前會經過一個寶箱 ( <span style='color: #800000;'>不死鳥之尾</span> )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-027.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖6'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖6</span><br /> <span style='color: #ffffff;'>-</span><br /> 第 6 段路一開始單線前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 要進去下一個入口之前，先往右走</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 第三站：<span style='color: #800000;'>王者之劍</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>將軍</span><br /> HP：<span style='color: #0000ff;'>35000</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 800~1000 )、吸血 ( 傷害約 900 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-031.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 沒什麼特別的，這傢伙感覺中看不中用XDDDD<br /> 2. 可以的話還是放個護盾，BOSS 手上的斧頭有點硬&#8230;.<br /> 3. 一般攻擊下大約三回合就能解決<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 拿到王者之劍後，如果你的職業能裝備，就趕快裝上吧，功力大增啊XDDDD</p>
<p>接下來就繼續往下一段路前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-032.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖7'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖7</span><br /> <span style='color: #ffffff;'>-</span><br /> 接下來眼前會有一個傳送點，左右兩邊則各有一把武器</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-033.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 第四站 ( 左 )：<span style='color: #800000;'>長老之杖</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-034.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>六獸妖</span><br /> HP：<span style='color: #0000ff;'>35000</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 700 )、神聖 ( 單體傷害約 1700~1800 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-035.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 六獸妖也沒什麼弱點，用你最拿手的攻擊進攻即可<br /> 2. 神聖魔法的攻擊，傷害高達 1700~1800，雖然是單體但仍要注意回復<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 第五站 ( 右 )：<span style='color: #800000;'>諸神之黃昏</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-036.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> BOSS 戰：<span style='color: #0000ff;'>守護者</span><br /> HP：<span style='color: #0000ff;'>33700</span><br /> 攻擊：物理攻擊 x2 ( 傷害約 800~1000 )、反射魔法</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-037.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 攻略：<br /> 1. 沒有什麼特別的，注意 BOSS 放反射時不要用魔法攻擊就好<br /> 2. 一般物理攻擊就能打爆他XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 拿到了諸神之黃昏和王者之劍後的騎士，這兩把一起拿在手上的感覺真不錯，帶著愉快的心情 (?) 往傳送點繼續前進吧XDDDDD</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-038.png' width='486' height='326' /><br /> <a name='禁地優雷卡 地圖8'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #0000ff;'>禁地優雷卡 地圖8</span><br /> <span style='color: #ffffff;'>-</span><br /> 最後的盡頭有 4 個寶箱 ( <span style='color: #800000;'>聖靈藥 x2、手裡劍 x2</span> ) 與兩個禁地商人</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-039.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 面前的兩個是禁地商人，左邊有賣最終 LV 8 的黑白魔法，右邊則是賣三個召喚魔法，但是之前你應該都有取得各一次了 ( 如果你為了偷奧丁的神槍還沒去打的話，後續還是要記得去打 )，所以可以買 LV 8 的魔法就好</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-040.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 買完之後先別走，右邊還有個暗道，延著牆壁往右繞一個半圓形路徑</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-041.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 盡頭還有一個商人，他賣的是&#8230;..</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-042.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 手裡劍、阿波羅豎琴和幾種水晶裝備，一樣全部 50000 起跳 ( 好貴&#8230; )，剛剛一路走來賺了幾十萬元，保證現在應該已經瞬間乾掉XDDDDDD</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-043.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就先傳送離開這裡，回到水晶塔與古代人迷宮之間的地圖上<br /> <a name='返回水晶塔'></a><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #0000ff;'>返回水晶塔</span><br /> <span style='color: #ffffff;'>-</span><br /> 接下來我們只剩最後一個迷宮，就是水晶塔。之前還有一些支線事件還未完成，且我們還有一個希爾科斯之鍵還沒用掉，所以現在我們先再次進入水晶塔</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-044.png' width='486' height='326' /></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span><br /> 走上大大的階梯後，先往左邊通道前進</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-045.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 繞過來後先往上前進 ( 經過的寶箱等水晶塔攻略再說，當然你也可以先拿 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-046.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 上面盡頭有著另一個畫了圖騰的牆壁</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-047.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 調查後會打開最後一道封印之門</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-048.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進入到水晶塔內部後，先別急著往前走，這部份的攻略會留待下一篇一起說明，我們可以先再次傳送離開水晶塔 ( 對&#8230;沒錯，就是離開XDDDD )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-049.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 又回到水晶塔與古代人迷宮之間這裡</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/02-eureka-050.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 還記得莎拉公主來信說他的首飾壞了嗎？在逛完禁地
優雷卡，也開啟了最後的封印之門後，關於首飾的事件才比較能夠順利進行，否則你跑來跑去最後卡住還是得回來水晶塔開啟這兩個門，在攻略上感覺會比較不順暢。<br /> <span style='color: #ffffff;'>-</span><br /> 現在就讓我們先去完成這些事件吧！是的，你必須往下走回古代人迷宮，並且經過之前在迷宮走過的一大段路，然後回到無敵號去吧！<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='支線事件：莎拉公主的首飾'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>支線事件：莎拉公主的首飾</span><br /> 
<span style='color: #ffffff;'>-</span><br /> FF3 的信件是一項蠻有趣的要素，在遊戲中主角們冒險的過程會遇到各地的朋友，在後續的劇情中會發信給特定的主角，當然信件有些只是噓寒問暖，但有一些是需要我們去觸發事件並取得相關物品才會進行的，例如莎拉公主的首飾事件。<br /> <span style='color: #ffffff;'>-</span><br /> 現在階段你應該有收到<span style='color: #800000;'>莎拉公主的第四封信 ( 標題：不好了！)</span>，提到她的首飾壞了，要我們想想辦法，
所以我們現在就回到浮遊大陸的薩斯恩城去找她吧！</p>
<p><span style='color: #ffffff;'>-</span><br /> 目前還不需要翻山越嶺，所以建議去換成鸚鵡螺號，飛行速度較快</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-001.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後就往地圖西南方的浮遊大陸出發</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-002.png' width='486' height='326' /><br /> <a name='薩斯恩城'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩斯恩城</span><br /> <span style='color: #ffffff;'>-</span><br /> 到了浮遊大陸，直接前往薩斯恩城</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-003.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 進來後直接前往薩斯恩東塔的頂層</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-004.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在頂層找到莎拉公主，便會取得<span style='color: #ff0000;'>「莎拉的墜飾」</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-005.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來該找誰幫忙修理墜飾呢？還記得卡茲斯的鐵匠塔
卡嗎？卡茲斯剛好也就在附近而已，所以就回到飛空艇，往右邊附近的卡茲斯去。<br /> <a name='卡茲斯'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>卡茲斯</span><br /> <span style='color: #ffffff;'>-</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-006.png' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 到最裡面鐵匠塔卡的家中，將墜飾交給了他，但塔卡表示這是他沒有看過的材料，所以恐怕無能為力啊&#8230;..</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-007.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 塔卡修不好，那還能找誰？還記得塔卡曾經在信件中提到有「傳說的鐵匠」與「傳說的金屬奧利哈康」，應該與事件有關，但是這傳說的鐵匠在哪裡呢？</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-008.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到飛空艇，我們先回到原本的世界地圖去吧！</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-009.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這邊順便說明一下，其實遊戲中的事件發展順序，我也
可以很簡單的指出該去哪裡、去找誰即可，但是絕大部份的事件都有著前因後果，如果就很簡單地把地點、人物幾行字就交待清楚，會少了很多玩遊戲的樂趣，也較難體會故事的情節發展。<br /> <span style='color: #ffffff;'>-</span><br /> 所以我還是決定照我的方式 ( Lu 式攻略？XD )，詳細地寫出事件的前因後果，讓大
家在玩 FF 系列遊戲時，更能融入故事的劇情中，很懶得看我廢話的朋友就請多多包涵了。( 說穿了只是我廢話太多嗎？這是風格，風格啊XDDDD )<br /> <a name='薩羅尼亞 西北'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>薩羅尼亞 西北</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到世界地圖後，我們到薩羅尼亞的西北城鎮去</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-010.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在西北鎮上的右上方，站著一個看來有點神祕的女子&#8230;.</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-011.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 她竟然就是傳說中的鐵匠，而且一下子就修好了！( 大概三秒鐘這樣XDDD )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-012.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 然後女鐵匠也提到了奧利哈康金屬的事，希望我們如果遇到的話，能帶來讓她試試，並且會將做成的東西送給我們，那當然沒問題啊！( 挺胸 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-013.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 當你一走出薩羅尼亞西北鎮時，再次進入的話女鐵匠就
會消失了，果然是熱愛旅行的鐵匠啊！不過這消失的速度也太快了點，其實她會瞬間移動 ( 無誤 )。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #800000;'>補充說明：</span><br /> 其實我自己一直不太清楚，為什麼女鐵匠一開始是出現在這裡？遊戲中有哪一個城鎮或是迷宮中，有相關的人
提供過情報嗎？印象中好像沒有，這也是我覺得有點奇怪的地方。如果你在遊戲中有發現哪一個地方曾經提到「女鐵匠與薩羅尼亞」這方面的關聯，請回覆告訴我一下XDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來找莫古收個信吧！可以去無敵號上，或是薩羅尼亞的東南鎮上 ( 如果你曾經有照我的說明做，現在無敵號應該也在旁邊而已 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-014.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 會收到<span style='color: #800000;'>西德的第四封信 ( 標題：在家裡的地下！)</span>，提到家裡的地下室有巨大的黑影出現，可能是怪物之類的，看來我們接下來應該去找西德了</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-015.png' width='486' height='326' /><br /> <a name='迦南'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>迦南</span><br /> <span style='color: #ffffff;'>-</span><br /> 搭上鸚鵡螺號，我們前往浮遊大陸上的迦南 ( 在薩斯恩城的東南方 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-016.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 西德的家在鎮上最北邊，找到西德後他確認應該是怪物，請我們協助擊退，然後就往床舖左側的通道下去 ( 如果你沒看見通道，代表你之前沒救過他老婆&#8230;. )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-017.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 下來後果然看到一個怪物在那邊，靠近後二話不說就上了吧！( 遇敵：阿伊翁 )<br /> ( 以現在隊伍的實力應該是不需要攻略了吧XDDDD )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-018.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 打敗怪物後，發現怪物掉了一個神祕的物品，取得了<span style='color: #ff0000;'>「神祕金屬」</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-019.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 回到樓上<span style='color: #ff0000;'>一定要記得找西德對話一次( 很重要 )</span>，才能觸發後續的關聯事件</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-020.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 而西德也看出了這金屬的來歷，果然就是傳說中的奧利哈康金屬</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-021.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 接下來該去找女鐵匠了，她在哪呢？我們先回去世界地圖吧！( 這個事件的跑法還真是累人啊，一下浮遊大陸，一下世界地圖的XDDDDD )<br /> <a name='法爾加巴德'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>法爾加巴德</span><br /> <span style='color: #ffffff;'>-</span><br /> 回到世界地圖後，先回去薩羅尼亞換成無敵號</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-022.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 用無敵號翻過薩羅尼亞左側的山脈，我們來到了法爾加巴德</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-023.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在鎮上東側的河邊 ( 武器店右側 )，我們又找到了旅行中、傳說的女鐵匠<br /> ( 我還是不知道為什麼她會來這裡&#8230;.XDDDD )<br /> ( 女鐵匠表示：陰魂不散啊你們&#8230;. )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-024.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 如果你來到這裡沒有看到女鐵匠，這有兩種可能，一是你剛剛在西德家裡打完怪物，上樓之後沒去找西德對話；二是你還沒有把水晶塔的兩道門打開進入過 ( 禁地優雷卡、封印之門 )。當然，若你一直是照我的攻略流程在走，現在應該是很順利就能遇到女鐵匠了。( 老師有教一定要聽XDDDDD )<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 女鐵匠拿到奧利哈康之後整個就高潮了，立刻做出了一把<span style='color: #ff0000;'>「究極神兵」</span>送給我們！<br /> 這次只花了大概五秒&#8230;.XDDDDD ( 究極神兵，攻擊力 155 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-025.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 臨走前女鐵匠還告訴我們，她將會在其他地方旅行，也許還會遇到喔！說完果然人就立刻消失了 ( 就說過她會瞬間移動吧XDDDDD )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-026.png' width='486' height='326' /><br /> <a name='支線事件補充說明'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>支線事件補充說明：</span><br /> 1. 在拿到了「究極神兵」之後，也別忘了把莎拉的墜飾拿去薩斯恩城還給她吧！畢竟能得到究極神兵的事件源頭都是因為這個首飾啊！( 但是還給她好像就沒下文了XDDD )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-027.png' width='486' height='326' />
<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 2. 如果你之前有照我的建議，為了能偷到神槍昆古尼
爾而留下了奧丁的活口，別忘了記得帶著熟練度 71 以上的盜賊回去偷槍 ( 奧丁就在 <span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='http://www.hdlulu.com/2012/12/13/ff3_part_2_2/#薩羅尼亞地下迷宮 地圖5' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>薩羅尼亞地下迷宮</span></a></span></span> 的盡頭 )，然後順便一起把奧丁解決掉，這樣我們三個召喚獸就全部打完了。</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-028.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 3. 如果你完全是照我的攻略走，現階段你應該已經完
成了以下事件：<br /> <span style='color: #ffffff;'>&#8212;-</span>(1) 打敗三大召喚獸 ( 奧丁、巴哈姆特、利維亞桑 )<br /> <span style='color: #ffffff;'>&#8212;-</span>(2) 取得洋蔥劍士職業<br /> <span style='color: #ffffff;'>&#8212;-</span>(3) 完成莎拉的首飾事件<br /> <span style='color: #ffffff;'>&#8212;-</span>(4) 取得究極神兵<br /> <span style='color: #ffffff;'>&#8212;-</span>(5) 寶箱收集率 80% 以上 ( 目前應該是 88% 左右，水晶塔內部的還沒拿完 )<br /> <span style='color: #ffffff;'>-</span><br /> 現在你可以試著再去找莫古收信，應該會接連收到「四位老爺爺」的第二封與第三封信</p>
<p>標題分別是：<span style='color: #800000;'> 勇者的心得、年輕時的冒險譚</span> ( 兩封信會先後出現 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-029.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 收完信莫古還會提醒你：頂級之證收集到多少了？哈哈哈，知道現在一個也沒有所以來刺激我們的嗎？好，那我們就看看怎麼來取得頂級之證吧！</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/03-sara-030.png' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span><br /> <a name='支線事件：頂級之證與最終裝備'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>支線事件：頂級之證與最終裝備</span><br /> 
<span style='color: #ffffff;'>-</span><br /> 如果你跟我一樣，有一兩個職業從開始到現在都幾乎沒換過的話，熟練度應該會有個 80~85 吧！距離職業攻頂的熟練度 99 也快了。<br /> <span style='color: #ffffff;'>-</span><br /> <strong><span style='color: #800000;'>頂級之證</span></strong> &#8211; 顧名思
義就是職業熟練度達到最高的 99，而給予的一張證書，至於證書要找誰發給你呢？剛剛我們有遇到一位特別的人士，就是傳說的女鐵匠 ( 對，就是會瞬間移動的那一位&#8230;.XDDD )。<br /> <a name='熟練度與等級的提升'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -
</span><br /> <span style='color: #0000ff;'>熟練度與等級的提升</span><br /> <span style='color: #ffffff;'>-</span><br /> 職業的熟練度與等級的提升，這邊只建議後期的「<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='http://www.hdlulu.com/2012/12/15/ff3_part_3_1/#巴哈姆特洞窟' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>巴哈姆特洞窟</span></a>
</span></span>」，其他前期、中期的地點就隨便了，大家自己覺得哪裡好練就去哪裡吧！<br /> <span style='color: #ffffff;'>-</span><br /> 為了寫攻略要舉例子，我只有先將盜賊提升到熟練度 99，其他慢慢再補充</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-001.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #ffffff;'> -</span><br /> 各職業在熟練度的提升方式上不盡相同，
因為戰鬥時的指令不太一樣，使用各項指令可以提升的數值也不同，看了一般資料，主要是說熟練度有一個數值 ( 姑且稱為 JP 好了 )，這在遊戲中的角色狀態是看不到的，JP 為 0~100，每次戰鬥使用各項指令分別會提升不等的 JP，若該次戰鬥後 JP 已滿 100，則戰鬥結束後熟練度會提升 1 級。<br /> <span style='color: #ffffff;'>-</span><br /> 通常提升 JP 最多的都是該職業的專屬技能，普通的物理攻擊則次之，例如盜賊的「偷盜」，龍騎士的「跳躍」，空手道家的「凝氣」，
魔法系職業的「魔法」等等都是，查到的資料中各指令最高都是使用一次提升 12 JP，也就是要 9 次才會破 100，每次戰鬥會累計，但該次戰鬥若已有提升 1 級熟練度，則下次戰鬥會<span style='color: #800000;'>歸零重算。</span><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> 
-</span><br /> 雖然查到很多資料是這樣寫，但自己測試下來，有些指令的 JP 數值應該提升不只 12 點，所以整理歸納了以上說明後，<span style='color: #800000;'>我對於提升熟練度的建議如下：</span><br /> <span style='color: #ffffff;'>-</span><br /> 1. 如果要同時提升熟練度與等級，建議去巴哈姆特洞窟
<br /> 2. 每次戰鬥盡量使用不會攻擊敵人的指令，且每場使用指令 5 次或以上<br /> 3. 例如騎士的「守護」、盜賊的「偷盜」、龍騎士的「跳躍」( 攻擊較慢 )<br /> 4. 或是白魔用恢復魔法，黑魔用低階魔法，只要能在戰鬥中用多次即可<br /> 5. 通常這樣做每 2 場戰鬥下來都能至少提升 1 級熟練度的<br /> 6. 洋蔥劍士各指令所能提升的 JP 數值都是最低的，所以會較慢</p>
<p>7. 戰鬥中每回合都使用「防御」也是我蠻常用的方式，網路上大部份也都建議這樣<br /> <span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span><br /> 至於各職業所有指令所提升的 JP 值這邊就先不列出，因為似乎不太正確，後續對於各職業技能指令與熟練度的關聯會再另外發一篇專題來說明心得，大家可以先照我上面的建議來提升熟練度。<br /> <a name='女鐵匠的出現地點'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> <span style='color: #0000ff;'>女鐵匠的出現地點</span><br /> 
<span style='color: #ffffff;'>-</span><br /> 女鐵匠說會去世界各地旅行耶？而且話一說完就會跟屁一樣消失了，如果我已經有職業熟練度達到 99 了，要到哪去找她呢？不用擔心，經過了數千萬人次 (?) 的測試確認後，歸納出了女鐵匠會出現的 10 個地點，但是，我這邊<span style='color: #ff0000;'>只列出四個
</span> ( 一般都提供 10 個地點，但我覺得真的不需要XDDD )：<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #800000;'>01. 烏爾村內右側的井內</span><br /> <span style='color: #800000;'> 02. 薩斯恩城東塔的三樓</span><br /> <span style='color: #800000;'> 03. 基薩爾的陸行鳥小屋</span><br /> <span style='color: #800000;'> 04. 回復森林 ( 托扎斯附近的北方 )</span><br /> <span style='color: #ffffff;'>-</span><br /> 為什
麼只列出四個呢？因為這四個地點都在浮遊大陸上，且距離都不遠，就算把 10 個地點都列出來你也不會 10 個地點跑來跑去吧XDDDDDD，一般都是建議在基薩爾與回復森林兩邊飛來飛去找就好了，心情好的話就再跑跑烏爾的井內和薩斯恩東塔看看。<br /> <span style='color: #ffffff;'>-</span><br /> 一直沒發現就在其中一個地點外存檔，然後中斷後再次讀取存檔，繼續跑這幾個地點，很快就會發現女鐵匠的。<br /> <span style='color: #ffffff;'>-</span></p>
<p>關於所有職業的頂級之證及最終裝備，請參考：</p>
<p><a href='http://www.hdlulu.com/2013/01/24/ff3_job_cards/' target='_blank'><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF3 各職業最終裝備一覽表</span></span></a></p>
<p>&nbsp;</p>
<p><span style='color: #ffffff;'>-</span><br /> 當你找到女鐵匠後，與他對話就會先發給你一張頂級之證<br /> ( 截圖地點是在恢復森林遇到的，發給了<span style='color: #800000;'>「盜賊之證」</span>)</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-002.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 並且會送給你一個該職業的終極武器或防具，例如盜賊的是<span style='color: #800000;'>「古羅馬短劍」</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-003.jpg' width='486' height='326' /><br /> <a name='最後的信件'></a><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 
<span style='color: #0000ff;'>最後的信件</span><br /> <span style='color: #ffffff;'>-</span><br /> 從你取得了第一張頂級之證後，再回去找莫古讀信 ( 讓魯內斯與阿爾克讀信即可 )，就會分別收到四位老爺爺與阿魯斯王子的第四封信。<br /> <span style='color: #ffffff;'>-</span><br /> 當然，前提是你完全照
我的攻略進度在進行，到現在如果沒收到這兩封信，請再檢查一下哪幾個點你還沒去，比較容易忽略掉的像是三大召喚獸打完了沒？海底洞窟最後隱藏通道的四個會遇敵的寶箱都拿完了沒？禁地優雷卡、水晶塔進去過了沒？或重新看一次我的攻略，找找有沒有漏掉的地方。<br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 四位老爺爺 &#8211; 標題：<span style='color: #800000;'>何謂真正的勇者</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-005.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 阿魯斯 &#8211; 標題：<span style='color: #800000;'>薩羅尼亞的傳說</span></p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-006.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 收到這兩封信後，就會開啟了最後隱藏地點，以及隱藏的最終 BOSS：鐵巨人。他的位置在世界地圖的海上，浮遊大陸的右側海域</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-007.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 需搭乘鸚鵡螺號，從浮遊大陸的位置往右飛，會發現海上有個「黑影」( 如圖 )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-008.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 在黑影下方潛入海底，前方會看到一堆珊瑚，直接往前走就會進入隱藏地點</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-009.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 這裡就先不介紹這個地點的資訊了，我們還有水晶塔要打呢！而且現階段你跑去打鐵巨人也是肯定全滅收場的，不信邪的話可以試試XDDDDD</p>
<p>( 詳情可參考：<span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='http://www.hdlulu.com/2013/01/19/ff3_iron_giant/' target='_blank'><span style='color: #0000ff; text-decoration: underline;'>[專題] FF3 洋蔥裝備收集與鐵巨人</span></a></span></span> )</p>
<p><img class='alignnone' alt='' src='http://pic.hdlulu.com/wordpress/wp-content/gallery/ff3_part_3-2/04-top_certificate-010.jpg' width='486' height='326' /><br /> <span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'> -</span><br /> 與信件相關的支線事件就先介紹到這裡了
，接下來的主線攻略就只剩最後的水晶塔內部，下一篇可能需要一點時間，因為我為了寫攻略的進度，怕大家等太久，所以幾乎都沒什麼練級和熟練度，進去水晶塔之
後整個好悲劇啊，請再給我一點時間XDDDDDD<br /> <span style='color: #ffffff;'>-</span><br /> 如果你覺得我的攻略還不錯，也可以留言回應一下，給我一點
鼓勵，也許我就會充滿鬥志，越寫越快，我相信我的攻略寫法與風格應該和網路上查得到的都不太一樣吧！雖然 FF3 的攻略網路上很多，但我自己是覺得應該要更詳細一點，而且應該要規劃出一個較合理的攻略進度，比較不會讓玩家們漏了一些要素，希望大家會喜歡我的攻略，下一篇就再稍等一下囉，先練練級去吧XDDDDD</p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='color: #ffffff;'>-</span></p>
<p><span style='text-decoration: underline;'><span style='color: #0000ff; text-decoration: underline;'><a href='#top'><span style='color: #0000ff; text-decoration: underline;'>( 返回頂部目錄 )</span></a></span></span></p>
<p><span style='color: #ffffff;'>-</span><br /> <span style='color: #ffffff;'>-</span></p>
<div>FF3 Part 3-2 禁地武器與支線事件 ( 完 )</div></font></center>
";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
