<?php
echo "<html><head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<link href='./main.css' rel='stylesheet' type='text/css' />";
echo "<style type='text/css'>
body{ text-align:center} 
#divcenter{margin:0 auto;width:800px}</style>
</head><body><div id='divcenter'>";
echo "<table cellspacing='1' cellpadding='1' align='center' border='1'>
    <tbody align='center'>
        <tr>
            <td bgcolor='#99ccff' colspan='6'>攻击系特技</td>
        </tr>
        <tr>
            <td bgcolor='#ccffcc'>属性</td>
            <td bgcolor='#ccffcc'>日文名</td>
            <td bgcolor='#ccffcc'>英文名</td>
            <td bgcolor='#ccffcc'>消耗MP</td>
            <td bgcolor='#ccffcc'>使用范围</td>
            <td bgcolor='#ccffcc'>效果</td>
        </tr>
        <tr>
            <td rowspan='11'>剑技</td>
            <td>いなずまぎり</td>
            <td>ElectricSlash</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>雷光斩，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>かえんぎり</td>
            <td>FlameSlash</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>火焰斩，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>しんくうぎり</td>
            <td>Discharge</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>真空斩，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>マヒャドぎり</td>
            <td>IceSlash</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>寒冰斩，普通攻击&times;1.3</td>
        </tr>
        <tr>
            <td>ゾンビぎり</td>
            <td>ZombieCut</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>丧尸斩，不死系普通攻击&times;1.5</td>
        </tr>
        <tr>
            <td>ドラゴンぎり</td>
            <td>DragonCut</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>屠龙斩，龙系普通攻击&times;1.5</td>
        </tr>
        <tr>
            <td>はやぶさぎり</td>
            <td>DoubleSlash</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>隼斩，普通攻击&times;0.75&times;2</td>
        </tr>
        <tr>
            <td>メタルぎり</td>
            <td>Metalcut</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>金属斩，金属系+1点伤害，其它&times;1.5</td>
        </tr>
        <tr>
            <td>まじんぎり</td>
            <td>Magiblade</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>魔神斩，会心一击，命中率3/8</td>
        </tr>
        <tr>
            <td>もろばぎり</td>
            <td>Lunge</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>诸刃斩，普通伤害&times;1.5，1/4伤害反弹</td>
        </tr>
        <tr>
            <td>さみだれけん</td>
            <td>Spinning</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>五月雨剑，伤害递减</td>
        </tr>
        <tr>
            <td rowspan='9'>体术</td>
            <td>とびひざげり</td>
            <td>Jumpkick</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>飞膝蹴，空中敌人&times;1.5伤害</td>
        </tr>
        <tr>
            <td>すてみ</td>
            <td>Berserk</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>舍身，先制，普通攻击&times;2，己伤害&times;2</td>
        </tr>
        <tr>
            <td>せいけんづき</td>
            <td>SpiritPunch</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>正拳突，普通攻击&times;2</td>
        </tr>
        <tr>
            <td>しっぷうづき</td>
            <td>First</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>疾风突，先制攻击，普通攻击&times;0.8</td>
        </tr>
        <tr>
            <td>ばくれつけん</td>
            <td>Swordlin</td>
            <td>0</td>
            <td>随机4体</td>
            <td>爆裂拳，普通攻击&times;0.5&times;4</td>
        </tr>
        <tr>
            <td>まわしげり</td>
            <td>SpinKick</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>回旋踢，伤害逐个递减</td>
        </tr>
        <tr>
            <td>たいあたり</td>
            <td>ThrowSelf</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>冲撞，敌伤害=敌HP&times;0.2，己伤害=己HP&times;0.8</td>
        </tr>
        <tr>
            <td>みなごろし</td>
            <td>Slowness</td>
            <td>0</td>
            <td>随机单体</td>
            <td>皆杀，无视防御会心一击</td>
        </tr>
        <tr>
            <td>ムーンサルト</td>
            <td>Moonsalt</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>月轮，普通攻击&times;[3/（敌人数＋1）]</td>
        </tr>
        <tr>
            <td rowspan='7'>炎系</td>
            <td>ひのいき</td>
            <td>FireBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>火之息，10左右HP伤害</td>
        </tr>
        <tr>
            <td>かえんのいき</td>
            <td>FlameBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>炎之息，30左右HP伤害</td>
        </tr>
        <tr>
            <td>はげしいほのお</td>
            <td>FierceBlaze</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>烈炎，75左右HP伤害</td>
        </tr>
        <tr>
            <td>マグマ</td>
            <td>Magma</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>熔岩，80左右HP伤害</td>
        </tr>
        <tr>
            <td>しゃくねつ</td>
            <td>ScorchingBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>灼热，150左右HP伤害</td>
        </tr>
        <tr>
            <td>ひばしら</td>
            <td>FlameOrb</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>火柱，180左右HP伤害</td>
        </tr>
        <tr>
            <td>ビッグバン</td>
            <td>BigBang</td>
            <td>30</td>
            <td>敌方全体</td>
            <td>大爆炸，300~400HP伤害</td>
        </tr>
        <tr>
            <td rowspan='4'>冰系</td>
            <td>つめたいいき</td>
            <td>ColdBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>冷之息，15左右HP伤害</td>
        </tr>
        <tr>
            <td>こおりのいき</td>
            <td>IceBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>冰之息，60左右HP伤害</td>
        </tr>
        <tr>
            <td>こごえるふぶき</td>
            <td>BlizzardBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>暴风雪，130左右HP伤害</td>
        </tr>
        <tr>
            <td>かがやくいき</td>
            <td>CrystalBreath</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>辉之息，220左右HP伤害</td>
        </tr>
        <tr>
            <td>水系</td>
            <td>つなみ</td>
            <td>Tsunami</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>海浪，30~40HP伤害，成功概率与地形有关</td>
        </tr>
        <tr>
            <td rowspan='3'>岩系</td>
            <td>いしつぶて</td>
            <td>RockThrow</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>扔石头，20左右HP伤害</td>
        </tr>
        <tr>
            <td>じひびき</td>
            <td>Quake</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>地震，60左右HP伤害</td>
        </tr>
        <tr>
            <td>がんせきおとし</td>
            <td>RockSlide</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>投巨石，110左右HP伤害</td>
        </tr>
        <tr>
            <td rowspan='3'>风系</td>
            <td>かまいたち</td>
            <td>WindSlash</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>镰鼬，Lv&times;3＋10左右HP伤害</td>
        </tr>
        <tr>
            <td>しんくうは</td>
            <td>VacuumBlade</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>真空波，90左右HP伤害，丧尸系&times;1.3</td>
        </tr>
        <tr>
            <td>グランドクロス</td>
            <td>GrandCross</td>
            <td>20</td>
            <td>敌方全体</td>
            <td>巨十字，180～220HP伤害，丧尸系&times;1.3</td>
        </tr>
        <tr>
            <td rowspan='3'>雷系</td>
            <td>いなずま</td>
            <td>Bolt</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>雷电，45左右HP伤害</td>
        </tr>
        <tr>
            <td>ギガスラッシュ</td>
            <td>GigaSlash</td>
            <td>20</td>
            <td>敌方一组</td>
            <td>强力斩，350~400HP伤害</td>
        </tr>
        <tr>
            <td>ジゴスパーク</td>
            <td>GigaSpar</td>
            <td>25</td>
            <td>敌方全体</td>
            <td>地狱雷霆，220~290HP伤害</td>
        </tr>
        <tr>
            <td rowspan='5'>即死</td>
            <td>きゅうしょづき</td>
            <td>StrikeWeakness</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>要害突，一定概率即死，失败的话普通攻击&times;0.5</td>
        </tr>
        <tr>
            <td>つきとばし</td>
            <td>Shove</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>突飞，将敌人踢飞，无法得到经验及金钱</td>
        </tr>
        <tr>
            <td>ともえなげ</td>
            <td>TossFiend</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>巴投，将敌人轰飞，可得到经验及金钱</td>
        </tr>
        <tr>
            <td>じわれ</td>
            <td>Tremor</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>地裂，一定概率使敌人即死，空中敌人无效</td>
        </tr>
        <tr>
            <td>しのおどり</td>
            <td>DeathDance</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>死亡之舞，一定概率即死，概率较低</td>
        </tr>
        <tr>
            <td rowspan='2'>召唤</td>
            <td>ぐんたいよび</td>
            <td>Recruit</td>
            <td>0</td>
            <td>随机4体</td>
            <td>召唤军队，Lv&times;2＋25左右HP伤害，耗钱Lv&times;50</td>
        </tr>
        <tr>
            <td>しょうかん</td>
            <td>Summon</td>
            <td>20</td>
            <td>我方</td>
            <td>召唤，召唤大地精灵</td>
        </tr>
        <tr>
            <td>变身</td>
            <td>へんしん</td>
            <td>Transform</td>
            <td>0</td>
            <td>自己</td>
            <td>变身，阿莫斯专有特技</td>
        </tr>
        <tr>
            <td>究极</td>
            <td>マダンテ</td>
            <td>Madante</td>
            <td>全部</td>
            <td>敌方全体</td>
            <td>玛丹特，伤害值=当前MP&times;2</td>
        </tr>
        <tr>
            <td bgcolor='#99ccff' colspan='6'>回复系特技</td>
        </tr>
        <tr>
            <td bgcolor='#ccffcc'>属性</td>
            <td bgcolor='#ccffcc'>日文名</td>
            <td bgcolor='#ccffcc'>英文名</td>
            <td bgcolor='#ccffcc'>消耗MP</td>
            <td bgcolor='#ccffcc'>使用范围</td>
            <td bgcolor='#ccffcc'>效果</td>
        </tr>
        <tr>
            <td>苏生</td>
            <td>せいれいのうた</td>
            <td>LifeSong</td>
            <td>20</td>
            <td>我方全体</td>
            <td>精灵之歌，全体复活，50％HP回复，50％成功</td>
        </tr>
        <tr>
            <td rowspan='2'>回复</td>
            <td>ハッスルダンス</td>
            <td>HustleDance</td>
            <td>0</td>
            <td>我方全体</td>
            <td>精神之舞，全体70以上HP回复</td>
        </tr>
        <tr>
            <td>めいそう</td>
            <td>Meditate</td>
            <td>0</td>
            <td>自己</td>
            <td>冥想，使用者500HP回复</td>
        </tr>
        <tr>
            <td bgcolor='#99ccff' colspan='6'>辅助系特技</td>
        </tr>
        <tr>
            <td bgcolor='#ccffcc'>属性</td>
            <td bgcolor='#ccffcc'>日文名</td>
            <td bgcolor='#ccffcc'>英文名</td>
            <td bgcolor='#ccffcc'>消耗MP</td>
            <td bgcolor='#ccffcc'>使用范围</td>
            <td bgcolor='#ccffcc'>效果</td>
        </tr>
        <tr>
            <td rowspan='11'>地图</td>
            <td>タカのめ</td>
            <td>Hawkeye</td>
            <td>0</td>
            <td>地图</td>
            <td>鹰眼，侦察城镇、山洞所在</td>
        </tr>
        <tr>
            <td>くちぶえ</td>
            <td>Whistle</td>
            <td>0</td>
            <td>地图</td>
            <td>口哨，招来敌人进入战斗</td>
        </tr>
        <tr>
            <td>とうぞくのはな</td>
            <td>GoldSniff</td>
            <td>0</td>
            <td>地图</td>
            <td>盗贼之鼻，侦察宝物数量</td>
        </tr>
        <tr>
            <td>ねる</td>
            <td>Rest</td>
            <td>0</td>
            <td>自己</td>
            <td>梦游，行走时处于睡眠状态，回复HP和MP</td>
        </tr>
        <tr>
            <td>おおごえ</td>
            <td>Caravan</td>
            <td>15</td>
            <td>地图</td>
            <td>随机召唤神父、旅馆老板、防具商之一</td>
        </tr>
        <tr>
            <td>しのびあし</td>
            <td>Sneak</td>
            <td>0</td>
            <td>地图</td>
            <td>忍足，减少遇敌</td>
        </tr>
        <tr>
            <td>あなほり</td>
            <td>Dig</td>
            <td>0</td>
            <td>地图</td>
            <td>挖掘</td>
        </tr>
        <tr>
            <td>おもいだす</td>
            <td>Recall</td>
            <td>0</td>
            <td>地图</td>
            <td>回忆，回忆起记住的5条消息</td>
        </tr>
        <tr>
            <td>もっとおもいだす</td>
            <td>Remember</td>
            <td>0</td>
            <td>地图</td>
            <td>更多回忆，回忆起记住的10条消息</td>
        </tr>
        <tr>
            <td>ふかくおもいだす</td>
            <td>Unforget</td>
            <td>0</td>
            <td>地图</td>
            <td>深层记忆，回忆起记住的15条消息</td>
        </tr>
        <tr>
            <td>わすれる</td>
            <td>Forget</td>
            <td>0</td>
            <td>地图</td>
            <td>遗忘，忘记记住的1条消息</td>
        </tr>
        <tr>
            <td rowspan='6'>麻痹</td>
            <td>さそうおどり</td>
            <td>EnticeDance</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>诱惑之舞，一回合内无法动弹</td>
        </tr>
        <tr>
            <td>あしばらい</td>
            <td>SweepKick</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>困足，一回合内无法动弹</td>
        </tr>
        <tr>
            <td>おたけび</td>
            <td>Scream</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>大声，惊吓使敌人一回合内无法动弹</td>
        </tr>
        <tr>
            <td>なめまわし</td>
            <td>SpinLick</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>舔舔，一回合内无法动弹</td>
        </tr>
        <tr>
            <td>やけつくいき</td>
            <td>Stun</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>麻痹之息，使敌人麻痹</td>
        </tr>
        <tr>
            <td>ぱふぱふ</td>
            <td>Flasher</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>一回合内无法动弹，使用者为男性时则是攻击</td>
        </tr>
        <tr>
            <td rowspan='4'>防御</td>
            <td>だいぼうぎょ</td>
            <td>Defenses</td>
            <td>0</td>
            <td>自己</td>
            <td>大防御，将伤害降至10%，对部分特技无效</td>
        </tr>
        <tr>
            <td>ぶきみなひかり</td>
            <td>EerieLight</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>诡异之光，降低敌人魔法耐性</td>
        </tr>
        <tr>
            <td>おいかぜ</td>
            <td>AirWall</td>
            <td>0</td>
            <td>自己</td>
            <td>追风，反弹炎系和冰系特技一次</td>
        </tr>
        <tr>
            <td>いてつくはどう</td>
            <td>Nullify</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>冻结波动，辅助效果解除</td>
        </tr>
        <tr>
            <td rowspan='3'>回避</td>
            <td>みかわしきゃく</td>
            <td>Deflect</td>
            <td>0</td>
            <td>自己</td>
            <td>见避脚，提高自身回避率</td>
        </tr>
        <tr>
            <td>すなけむり</td>
            <td>Sandstorm</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>砂烟，降低敌人命中率</td>
        </tr>
        <tr>
            <td>まぶしいひかり</td>
            <td>Dazzle</td>
            <td>0</td>
            <td>敌方全体</td>
            <td>眩目光，降低敌人命中率</td>
        </tr>
        <tr>
            <td rowspan='2'>吸收</td>
            <td>ふしぎなおどり</td>
            <td>StrangeJig</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>神奇舞蹈，削减敌人MP</td>
        </tr>
        <tr>
            <td>マホトラおどり</td>
            <td>RobMagicDance</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>吸收舞蹈，吸收敌人MP</td>
        </tr>
        <tr>
            <td rowspan='2'>封印</td>
            <td>おどりふうじ</td>
            <td>Stillnes</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>舞蹈封印，无法使用舞蹈特技</td>
        </tr>
        <tr>
            <td>ひゃくれつなめ</td>
            <td>DarkLick</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>百烈舔，封住敌人行动，同时防御降为0</td>
        </tr>
        <tr>
            <td rowspan='2'>蓄力</td>
            <td>きあいため</td>
            <td>PowerUp</td>
            <td>0</td>
            <td>自己</td>
            <td>气合，下回合伤害&times;2~2.5</td>
        </tr>
        <tr>
            <td>ちからため</td>
            <td>WindUp</td>
            <td>0</td>
            <td>自己</td>
            <td>蓄力，下回合伤害&times;2~2.5</td>
        </tr>
        <tr>
            <td rowspan='2'>反击</td>
            <td>まねまね</td>
            <td>Repeat</td>
            <td>0</td>
            <td>自己</td>
            <td>模仿，受到攻击后反击，反击攻击者</td>
        </tr>
        <tr>
            <td>うけながし</td>
            <td>Hide</td>
            <td>0</td>
            <td>自己</td>
            <td>攻击转移,受到攻击后反击，反击对象不定</td>
        </tr>
        <tr>
            <td rowspan='2'>毒</td>
            <td>どくのいき</td>
            <td>Poison</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>毒之息，使敌人中毒</td>
        </tr>
        <tr>
            <td>もうどくのきり</td>
            <td>Toxic</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>猛毒之雾，使敌人中毒，每回合扣HP</td>
        </tr>
        <tr>
            <td rowspan='2'>替身</td>
            <td>みがわり</td>
            <td>Defend</td>
            <td>0</td>
            <td>自己</td>
            <td>替身，代替某一同伴承受一回合攻击</td>
        </tr>
        <tr>
            <td>におうだち</td>
            <td>Protect</td>
            <td>0</td>
            <td>自己</td>
            <td>仁王立，承受一回合内所有攻击</td>
        </tr>
        <tr>
            <td>混乱</td>
            <td>メダパニダンス</td>
            <td>Chaos</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>混乱之舞，使敌人混乱</td>
        </tr>
        <tr>
            <td>睡眠</td>
            <td>あまいいき</td>
            <td>SweetBreath</td>
            <td>0</td>
            <td>敌方一组</td>
            <td>香甜气息，使敌人睡觉</td>
        </tr>
        <tr>
            <td rowspan='2'>其他</td>
            <td>メガザルダンス</td>
            <td>GiveLife</td>
            <td>0</td>
            <td>自己</td>
            <td>牺牲之舞，跳舞者死亡，其它角色全复活全恢复</td>
        </tr>
        <tr>
            <td>あそび</td>
            <td>Goof-off</td>
            <td>0</td>
            <td>？</td>
            <td>游玩，随机效果</td>
        </tr>
    </tbody>
</table>";
echo "</div></body></html>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
