<?php
echo "<html><head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<link href='./main.css' rel='stylesheet' type='text/css' />";
echo "<style type='text/css'>
body{ text-align:center} 
#divcenter{margin:0 auto;width:800px}</style>
</head><body><div id='divcenter'>";
echo "
<table cellspacing='1' cellpadding='1' border='1' align='center'>
    <tbody align='center'>
        <tr>
            <td bgcolor='#99ccff' colspan='5'>攻击咒文</td>
        </tr>
        <tr>
            <td bgcolor='#ccffcc'>日文名</td>
            <td bgcolor='#ccffcc'>英文名</td>
            <td bgcolor='#ccffcc'>消耗MP</td>
            <td bgcolor='#ccffcc'>使用范围</td>
            <td bgcolor='#ccffcc'>效果</td>
        </tr>
        <tr>
            <td>メラ</td>
            <td>Blaze</td>
            <td>2</td>
            <td>敌方单体</td>
            <td>7～12伤害</td>
        </tr>
        <tr>
            <td>メラミ</td>
            <td>Blazemore</td>
            <td>4</td>
            <td>敌方单体</td>
            <td>80左右伤害</td>
        </tr>
        <tr>
            <td>メラゾーマ</td>
            <td>Blazemost</td>
            <td>10</td>
            <td>敌方单体</td>
            <td>180左右伤害</td>
        </tr>
        <tr>
            <td>ギラ</td>
            <td>Firebal</td>
            <td>4</td>
            <td>敌方一组</td>
            <td>15～25伤害</td>
        </tr>
        <tr>
            <td>ベギラマ</td>
            <td>Firebane</td>
            <td>6</td>
            <td>敌方一组</td>
            <td>30～40伤害</td>
        </tr>
        <tr>
            <td>ベギラゴン</td>
            <td>Firevolt</td>
            <td>10</td>
            <td>敌方一组</td>
            <td>90～100伤害</td>
        </tr>
        <tr>
            <td>イオ</td>
            <td>Bang</td>
            <td>5</td>
            <td>敌方全体</td>
            <td>15～25伤害</td>
        </tr>
        <tr>
            <td>イオラ</td>
            <td>Boom</td>
            <td>8</td>
            <td>敌方全体</td>
            <td>55～60伤害</td>
        </tr>
        <tr>
            <td>イオナズン</td>
            <td>Explodet</td>
            <td>15</td>
            <td>敌方全体</td>
            <td>120～140伤害</td>
        </tr>
        <tr>
            <td>ヒャド</td>
            <td>Icebolt</td>
            <td>3</td>
            <td>敌方单体</td>
            <td>10～20伤害</td>
        </tr>
        <tr>
            <td>ヒャダルコ</td>
            <td>Snowblast</td>
            <td>5</td>
            <td>敌方一组</td>
            <td>40～50伤害</td>
        </tr>
        <tr>
            <td>マヒャド</td>
            <td>SnowStorm</td>
            <td>12</td>
            <td>敌方全体</td>
            <td>90～100伤害</td>
        </tr>
        <tr>
            <td>バギ</td>
            <td>Infernos</td>
            <td>2</td>
            <td>敌方一组</td>
            <td>8～25伤害</td>
        </tr>
        <tr>
            <td>バギマ</td>
            <td>Infermore</td>
            <td>4</td>
            <td>敌方一组</td>
            <td>25～55伤害</td>
        </tr>
        <tr>
            <td>バギクロス</td>
            <td>Infermost</td>
            <td>8</td>
            <td>敌方一组</td>
            <td>60～120伤害</td>
        </tr>
        <tr>
            <td>ザキ</td>
            <td>Beat</td>
            <td>4</td>
            <td>敌方单体</td>
            <td>即死（BOSS无效）</td>
        </tr>
        <tr>
            <td>ザラキ</td>
            <td>Defeat</td>
            <td>7</td>
            <td>敌方一组</td>
            <td>即死（BOSS无效）</td>
        </tr>
        <tr>
            <td>ザラキーマ</td>
            <td>Vanquish</td>
            <td>15</td>
            <td>敌方全体</td>
            <td>即死（BOSS无效）</td>
        </tr>
        <tr>
            <td>ライデイン</td>
            <td>Zap</td>
            <td>6</td>
            <td>敌方全体</td>
            <td>80～90伤害</td>
        </tr>
        <tr>
            <td>ギガデイン</td>
            <td>Lightning</td>
            <td>15</td>
            <td>敌方一组</td>
            <td>180～220伤害</td>
        </tr>
        <tr>
            <td>ミナデイン</td>
            <td>MegaZap</td>
            <td>10&times;4</td>
            <td>敌方单体</td>
            <td>四人合体攻击500～600伤害</td>
        </tr>
        <tr>
            <td>メガンテ</td>
            <td>Sacrifice</td>
            <td>1</td>
            <td>敌方全体</td>
            <td>牺牲自己，敌即死（BOSS无效）</td>
        </tr>
        <tr>
            <td bgcolor='#99ccff' colspan='5'>回复咒文</td>
        </tr>
        <tr>
            <td bgcolor='#ccffcc'>日文名</td>
            <td bgcolor='#ccffcc'>英文名</td>
            <td bgcolor='#ccffcc'>消耗MP</td>
            <td bgcolor='#ccffcc'>使用范围</td>
            <td bgcolor='#ccffcc'>效果</td>
        </tr>
        <tr>
            <td>ホイミ</td>
            <td>Heal</td>
            <td>2</td>
            <td>我方单体</td>
            <td>30左右HP回复</td>
        </tr>
        <tr>
            <td>べホイミ</td>
            <td>Healmore</td>
            <td>5</td>
            <td>我方单体</td>
            <td>80左右HP回复</td>
        </tr>
        <tr>
            <td>ベホマ</td>
            <td>Healall</td>
            <td>7</td>
            <td>我方单体</td>
            <td>HP完全回复</td>
        </tr>
        <tr>
            <td>ベホマラー</td>
            <td>Healus</td>
            <td>18</td>
            <td>我方全体</td>
            <td>80左右HP回复</td>
        </tr>
        <tr>
            <td>ベホマズン</td>
            <td>Healusall</td>
            <td>36</td>
            <td>我方全体</td>
            <td>HP完全回复</td>
        </tr>
        <tr>
            <td>キアリー</td>
            <td>Antidote</td>
            <td>2</td>
            <td>我方单体</td>
            <td>解毒</td>
        </tr>
        <tr>
            <td>キアリク</td>
            <td>Numboff</td>
            <td>2</td>
            <td>我方全体</td>
            <td>治疗麻痹，睡眠</td>
        </tr>
        <tr>
            <td>ザオラル</td>
            <td>Vivify</td>
            <td>10</td>
            <td>我方单体</td>
            <td>救活死亡同伴，成功率50％，HP50％回复</td>
        </tr>
        <tr>
            <td>ザオリク</td>
            <td>Revive</td>
            <td>20</td>
            <td>我方单体</td>
            <td>救活死亡同伴，成功率100％，HP100％回复</td>
        </tr>
        <tr>
            <td>メガザル</td>
            <td>GiveLife</td>
            <td>全部</td>
            <td>我方全体</td>
            <td>牺牲自己令全体同伴复活并回复</td>
        </tr>
        <tr>
            <td bgcolor='#99ccff' colspan='5'>辅助咒文</td>
        </tr>
        <tr>
            <td bgcolor='#ccffcc'>日文名</td>
            <td bgcolor='#ccffcc'>英文名</td>
            <td bgcolor='#ccffcc'>消耗MP</td>
            <td bgcolor='#ccffcc'>使用范围</td>
            <td bgcolor='#ccffcc'>效果</td>
        </tr>
        <tr>
            <td>リレミト</td>
            <td>Outside</td>
            <td>8</td>
            <td>我方全体</td>
            <td>迷宫脱出</td>
        </tr>
        <tr>
            <td>ルーラ</td>
            <td>Return</td>
            <td>1</td>
            <td>我方全体</td>
            <td>飞行，立刻到达去过的城市</td>
        </tr>
        <tr>
            <td>インパス</td>
            <td>Identify</td>
            <td>1</td>
            <td>宝箱等和自己物品</td>
            <td>侦察宝箱和查看自己的物品的用处<br>
            (在某塔可以用来开门)</td>
        </tr>
        <tr>
            <td>トラマナ</td>
            <td>Stepguard</td>
            <td>2</td>
            <td>我方全体</td>
            <td>穿越毒沼等不少HP</td>
        </tr>
        <tr>
            <td>トヘロス</td>
            <td>Repel</td>
            <td>4</td>
            <td>我方全体</td>
            <td>一定步数内弱小敌人不出现</td>
        </tr>
        <tr>
            <td>フローミ</td>
            <td>Mapreader</td>
            <td>2</td>
            <td>迷宫</td>
            <td>判断当前所在迷宫层数</td>
        </tr>
        <tr>
            <td>レミラーマ</td>
            <td>Locate</td>
            <td>2</td>
            <td>能显示的屏幕</td>
            <td>显示当前地图上的宝物</td>
        </tr>
        <tr>
            <td>ニフラム</td>
            <td>Expell</td>
            <td>1</td>
            <td>敌方全体</td>
            <td>以光之力赶走弱小怪物，丧尸系特效（BOSS无效）</td>
        </tr>
        <tr>
            <td>バシルーラ</td>
            <td>Limbo</td>
            <td>8</td>
            <td>敌方单体</td>
            <td>吹跑敌人（BOSS无效）</td>
        </tr>
        <tr>
            <td>マホトラ</td>
            <td>RobMagic</td>
            <td>0</td>
            <td>敌方单体</td>
            <td>吸收MP</td>
        </tr>
        <tr>
            <td>マホキテ</td>
            <td>Absorb</td>
            <td>2</td>
            <td>我方单体</td>
            <td>受到魔法攻击时吸收相应MP（包括回复）</td>
        </tr>
        <tr>
            <td>マホトーン</td>
            <td>StopSpell</td>
            <td>3</td>
            <td>敌方一组</td>
            <td>封印敌人咒文</td>
        </tr>
        <tr>
            <td>マヌーサ</td>
            <td>Surround</td>
            <td>5</td>
            <td>敌方一组</td>
            <td>起雾，降低敌命中率</td>
        </tr>
        <tr>
            <td>ルカニ</td>
            <td>Sap</td>
            <td>3</td>
            <td>敌方单体</td>
            <td>降低敌物理防御（50%）</td>
        </tr>
        <tr>
            <td>ルカナン</td>
            <td>Defense</td>
            <td>4</td>
            <td>敌方一组</td>
            <td>降低敌物理防御（25%）</td>
        </tr>
        <tr>
            <td>ラリホー</td>
            <td>Sleep</td>
            <td>3</td>
            <td>敌方一组</td>
            <td>催眠敌人</td>
        </tr>
        <tr>
            <td>ラリホーマ</td>
            <td>Sleepmore</td>
            <td>5</td>
            <td>敌方一组</td>
            <td>强力催眠</td>
        </tr>
        <tr>
            <td>メダパニ</td>
            <td>Chaos</td>
            <td>5</td>
            <td>敌方一组</td>
            <td>混乱</td>
        </tr>
        <tr>
            <td>バイキルト</td>
            <td>Bikill</td>
            <td>6</td>
            <td>我方单体</td>
            <td>对敌物理攻击伤害 X 2</td>
        </tr>
        <tr>
            <td>マホターン</td>
            <td>Reflect</td>
            <td>4</td>
            <td>自己</td>
            <td>反弹敌人一次魔法攻击</td>
        </tr>
        <tr>
            <td>マホカンタ</td>
            <td>Bounce</td>
            <td>4</td>
            <td>自己</td>
            <td>一定回合内反弹所有咒文</td>
        </tr>
        <tr>
            <td>スカラ</td>
            <td>Upper</td>
            <td>2</td>
            <td>我方单体</td>
            <td>提高单体物理防御（50%）</td>
        </tr>
        <tr>
            <td>スクルト</td>
            <td>Increase</td>
            <td>3</td>
            <td>我方全体</td>
            <td>提高全体物理防御（25%）</td>
        </tr>
        <tr>
            <td>フバーハ</td>
            <td>Barrier</td>
            <td>3</td>
            <td>我方全体</td>
            <td>提高对炎系、冻气系特技的防御</td>
        </tr>
        <tr>
            <td>マジックバリア</td>
            <td>MagiWard</td>
            <td>3</td>
            <td>我方全体</td>
            <td>提高队伍魔法防御</td>
        </tr>
        <tr>
            <td>ドラゴラム</td>
            <td>BeDragon</td>
            <td>18</td>
            <td>自己</td>
            <td>幻化成龙，不受控制</td>
        </tr>
        <tr>
            <td>アストロン</td>
            <td>Ironize</td>
            <td>2</td>
            <td>我方全体</td>
            <td>全体钢铁化3回合，敌攻击无效</td>
        </tr>
        <tr>
            <td>パルプンテ</td>
            <td>Chance</td>
            <td>20</td>
            <td>？</td>
            <td>历代的谜之咒文，多种效果随机出现*</td>
        </tr>
    </tbody>
</table>
<p>&nbsp;</p>
<table cellspacing='1' cellpadding='1' border='1' align='center'>
    <tbody align='center'>
        <tr>
            <td bgcolor='#99ccff' rowspan='16'>パルプンテ[Chance]的效果</td>
            <td>1.敌我双方全员命中睡眠</td>
        </tr>
        <tr>
            <td>2.我方HP回复，效果如ベホマズン[Healusall]</td>
        </tr>
        <tr>
            <td>3.敌我双方HP全部回复 </td>
        </tr>
        <tr>
            <td>4.敌我双方MP全部回复 </td>
        </tr>
        <tr>
            <td>5.敌我双方MP全部降为零 </td>
        </tr>
        <tr>
            <td>6.敌我双方死亡仲间复生</td>
        </tr>
        <tr>
            <td>7.我方全员攻击力增加，威力如同会心一击 </td>
        </tr>
        <tr>
            <td>8.放出奇怪的雾气，使咒文无效 </td>
        </tr>
        <tr>
            <td>9.时间倒流，回到战斗的第一回合</td>
        </tr>
        <tr>
            <td>10.出现魔人，攻击敌全体</td>
        </tr>
        <tr>
            <td>11.冻结敌人，使敌人不能动</td>
        </tr>
        <tr>
            <td>12.我方全员变成为龙</td>
        </tr>
        <tr>
            <td>13.敌方全体被炸得粉碎，没有经验和金钱</td>
        </tr>
        <tr>
            <td>14.敌我双方受到惊吓，战斗强制中止</td>
        </tr>
        <tr>
            <td>15.流星降落，敌我双方HP降为1</td>
        </tr>
        <tr>
            <td>16.发出机器损坏的声音，什么事都没发生</td>
        </tr>
    </tbody>
</table>
";
echo "</div></body></html>";
?>
<?php
include_once("/var/www/counter.php");
upcounter(__FILE__)
?>
